### ISSUE TITLE
Issue with highlighting of notebook name 

### ISSUE THREAD

**Issue by sneha-bharti** [att/rcloud#1029]
Steps:
1. Delete the currently loaded notebook. In the image below, it is notebook named <b>work1</b>
![initial_case](https://cloud.githubusercontent.com/assets/5227441/4848990/60558746-605e-11e4-94c9-2ff076eeb455.png)
2. Page will be re-directed to the last opened notebook. It is notebook named <b>Rnotebook</b>
![notebook _deleted](https://cloud.githubusercontent.com/assets/5227441/4849014/86409c16-605e-11e4-9b2f-2e7b62af87c2.png)
3. Load the deleted notebook using ID. It goes under the section <code>People I Starred</code>, which is correct but the notebook <b>Rnotebook</b> remains highlighted.
![difference_in_loaded_notebook](https://cloud.githubusercontent.com/assets/5227441/4849023/99c8b02a-605e-11e4-869a-61033ad406fb.png)
This behavior is not frequent but do occur sometimes. Mainly when <code>People I Starred</code> div is not open while loading the deleted notebook

**Comment by gordonwoodhull** [comment]
Unable to repro, probably was an error as described above.
