### ISSUE TITLE
list icons remain on closing notebook trees

### ISSUE THREAD

**Issue by sneha-bharti** [att/rcloud#1031]
Sometimes, on closing the All Notebooks section, the div gets closed but list icons still remain in the UI.
(Not a regular one but it does occur). The icons goes off when anything, except that window tab, is clicked.
![emptylist](https://cloud.githubusercontent.com/assets/5227441/4856149/39a86f54-60b4-11e4-8c10-7291b98c8d93.png)

**Comment by gordonwoodhull** [comment]
I haven't seen this.
