### ISSUE TITLE
Plot duplication in RCloud 1.2

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1046]
My notebook has 2 cells:

First cell:
  x=(1:10)
  y=(21:30)
  plot(x,y)

Second cell:
  plot((101:110),(201:210))

first time play the notebook from top to bottom, output looks fine.

second time, plot from the 2th cell shows up in the output for the 1st cell and again in the 2nd cell.

Link to notebook:
https://rcloud-2.research.att.com/edit.html?notebook=8feb8b9bef5e605b6961

happens in Chrome on Mac and Windows (I have not checked other browser/platform combos).

does not happen when running on RCloud 1.1

**Comment by gordonwoodhull** [comment]
fixed by direct input and not having knitr use a shared context
