### ISSUE TITLE
when RCloud is upgraded, browser caching of RCloud components might cause a problem for some users

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1051]
About 5-10 users this morning that have gotten stuck on the “Loading….” page when first logging into rcloud.reserach.att.com after the upgrade to RCloud 1.2.

After looking at the console and chatting with Prateek, it seems to be an issue with the cache, where some RCloud components are coming from the cache and some from the server, and (a guess here) the components from cache vs. server seem to be incompatible because of changes in the s/w.

The Chrome console says something about editor.js and shell_tab.js not found, and I believe referred to rcould_bundle.js or rcloud.js (not sure which).

I **wish** I had captured a screen shot of the Chrome console with the message..  When the next users reports this bug, I will get them to capture a screen shot. 

I had this problem on Saturday, and shift-Reload fixed it for me.

Given that more than a handful of users have reported this so far today, I figured I would open an issue to discuss if there was something we wanted to do about it.

Could we somehow enforce a “nocache” option for certain critical pieces, so that they always come from the server?

-------

How users get around the problem is below.

 - For some users, holding down shift and clicking Reload fixed the problem.

 - For some users, shift-Reload was not sufficient, so Prateek suggested they do this, which appears to work:
   Clear Chrome cache
   1. Click or tap on any open Chrome browser window to make it active.
   2. Press "Ctrl-Shift-Delete" together.
   3. Select the "Empty the cache" option together with any other types of data you wish to erase.
   4. Choose a period of time from the drop-down menu at the top. Select "the beginning of time" to erase all the selected data collected since Chrome was installed.
   5. Click or tap "Clear browsing data." The process may take some time to complete, depending on your selections
   6. Close Chrome and Open Again

**Comment by s-u** [comment]
Chrome is caching very aggressively anything that doesn't have an explicit `Cache-control:` header - to such a degree that it will happily serve stale content in that case without even checking with the server. The fix will be to enforce the presence of `Cache-contol: no-cache` in all results.

**Comment by gordonwoodhull** [comment]
This is now #1216
