### ISSUE TITLE
print all the code cells when looking at an un-executed notebook

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1086]
A user asked for this.  Some folks like to print out code.

Right now, you can print what is showing on the screen, but code in code cells that is not showing on the screen will not be included (say, there is a scroll bar, the code for which you need to scroll down to see will not print).  Also, if the notebook is longer than my browser's current window view of the notebook, only what is showing in the browser will be printed.

The scroll bars seem to be the obstacle, it's almost like the print function should expand all cells/frames such that the scroll bars are not needed.  Not sure how that works....

**Comment by gordonwoodhull** [comment]
Looks like the easiest way to support this is to add a special style sheet:

https://developer.mozilla.org/en-US/docs/Printing

**Comment by gordonwoodhull** [comment]
Related: export to PDF #1320, although it might be annoying to have your code print with a grey background when it's just code and no results.

**Comment by gordonwoodhull** [comment]
Sorry, this did not happen for 1.3 but I'll make sure to get to it for 1.4

**Comment by gordonwoodhull** [comment]
As a workaround, you can copy the entire code to the clip board using the mouse and print it out in another app. I could probably add ctrl/cmd-A to make this easier.

**Comment by gordonwoodhull** [comment]
#1321 select all is in place.  the workaround is: select a little bit of the notebook, then hit ctrl/cmd-A to select all, then copy and paste in another app to print.

**Comment by gordonwoodhull** [comment]
A user reports:
> I don’t have access to the source code, I removed all css via the chrome developer tools. Then add the following:
```
body, html, #wrapper {
  width: 100%;
}
```
 
> I decided it was possible after reading, http://stackoverflow.com/questions/10845621/window-print-is-not-printing-the-whole-page.

**Comment by gordonwoodhull** [comment]
Implemented in #1783

**Comment by gordonwoodhull** [comment]
Feedback on the formatting and page break behavior is welcome.
