### ISSUE TITLE
number formatting in workspace is lossy

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1099]
@prateek05 writes
> e <- 12345.956 shows as [e double 12300] That is because of signif()

**Comment by prateek05** [comment]
@gordonwoodhull  
This is closed we let R do it now 
e1 <- 123.456789012342332423421341343214234324
e1	double	123.45678901234233

**Comment by gordonwoodhull** [comment]
closed by #1245

**Comment by gordonwoodhull** [comment]
thanks!
