### ISSUE TITLE
Error: Invalid typed array length

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1133]
This error popped up with the current `master` version (on naraj) several times today when running a cell. It seems intermittent, i.e. re-loading the notebook and running the same cell later works. It has happened with different cells.

     Error: Invalid typed array length,
    From previous event:
        at Object.RCloud.UI.with_progress (https://rcloud.research.att.com/js/rcloud_bundle.js:4507:20)
        at HTMLButtonElement.result.run_notebook (https://rcloud.research.att.com/shell_tab.js:450:23)
        at HTMLButtonElement.jQuery.event.dispatch (https://rcloud.research.att.com/lib/js/jquery-1.10.2.js:5095:9)
        at HTMLButtonElement.elemData.handle (https://rcloud.research.att.com/lib/js/jquery-1.10.2.js:4766:46)

**Comment by gordonwoodhull** [comment]
It may or may not be the same thing, but I get this error consistently on Chrome in feature-compute-separation for plots on my local install (not from rcloud-5).  It is not intermittent, and I consistently get other errors in Firefox and Safari for plots.

Firefox:
```
Error: invalid arguments,
From previous event:
rcloud_handler/<@http://127.0.0.1:8080/js/rcloud_bundle.js:129:20
setup_authenticated_ocaps/rcloud.authenticated_cell_eval@http://127.0.0.1:8080/js/rcloud_bundle.js:539:20
Notebook.create_controller/result.execute_cell_version@http://127.0.0.1:8080/js/rcloud_bundle.js:2819:20
Notebook.Cell.create_controller/result.enqueue_execution_snapshot/<@http://127.0.0.1:8080/js/rcloud_bundle.js:2011:28
```

Safari:
```
Error: Byte offset and length out of range of buffer,
Promise$_settlePromiseFromHandler@http://127.0.0.1:8080/lib/js/bluebird.js:2358:53
Promise$_settlePromiseAt@http://127.0.0.1:8080/lib/js/bluebird.js:2521:39
Promise$_rejectPromises@http://127.0.0.1:8080/lib/js/bluebird.js:2658:30
Async$_consumeFunctionBuffer@http://127.0.0.1:8080/lib/js/bluebird.js:157:16
Async$consumeFunctionBuffer@http://127.0.0.1:8080/lib/js/bluebird.js:120:36
Promise$_Scheduler@http://127.0.0.1:8080/lib/js/bluebird.js:4287:19
```

**Comment by gordonwoodhull** [comment]
It seems to be the same root cause for the broken deferred results in #1150. It seems like the promise is "used up" (like it had already been called) in the deferred result case, so bluebird throws out the error. 

In both cases I'm getting the error on these lines in rserve.js:

                    return new ctor(this.buffer, 
                                    this.offset + new_offset, 
                                    n_els);

https://github.com/att/rcloud/blob/develop/htdocs/lib/js/rserve.js#L719

It seems like `n_els` is just too big for `this.buffer`, e.g. 11040 when `this.buffer.byteLength` is 8192.

Will dig deeper later, but posting this in case it sparks a memory for anyone.
