### ISSUE TITLE
R objects of type list not showing up in Workspace

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1144]
![thing](https://cloud.githubusercontent.com/assets/927657/5398244/c8288440-812e-11e4-9f63-cff22ad376da.png)

**Comment by prateek05** [comment]
@gordonwoodhull refer #1153 should I rebase and submit again ?

**Comment by gordonwoodhull** [comment]
thanks,  I know,  just backlogged. I'll get it.

**Comment by gordonwoodhull** [comment]
fixed by #1153
