### ISSUE TITLE
fork all notebooks in a folder/sub-tree

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1149]
Folks have asked for the ability to easily fork all notebooks in a folder/sub-tree.

**Comment by gordonwoodhull** [comment]
Thanks Marty, this is requested often. Will try to do this for 1.4. Duplicate of #1392

**Comment by gordonwoodhull** [comment]
this proved to be too buggy for 1.4, delaying to 1.4.1

**Comment by gordonwoodhull** [comment]
This wasn't as buggy as we thought, except that GitHub doesn't allow forking a gist a second time.
