### ISSUE TITLE
RCloud installation Issues.

### ISSUE THREAD

**Issue by mzhao577** [att/rcloud#1156]
Hello,

I am trying to install Rcloud at my EC2 Ubuntu 14.02 machines.  So I installed the R3.1.2 the instruction at the setup guide link:
   https://github.com/att/rcloud/blob/develop/doc/INSTALL.md

The RCloud I got using the following command is: RCloud 1.3:
   $git clone https://github.com/att/rcloud.git

Now when I ran the "sh scripts/fresh_start.sh", I got the following error message:
---------------------------------   Error Message:
Loading required package: rcloud.support
Loading required package: base64enc
Loading required package: rjson
Loading required package: parallel
Starting Rserve on ec2-54-174-16-168.compute-1.amazonaws.com
Loading RCloud configuration file...
Error in rcloud.support:::configure.rcloud() :
  *** ERROR: cookie.domain must be a FQDN! Please set your hostname correctly or add cookie.domain directive to rcloud.conf

***FATAL ERROR** aborting RCloud startup
Terminated

---------------------------------  Here is my rcloud.conf file with Client Secret hidden:
Host: ec2-54-174-16-168.compute-1.amazonaws.com
github.client.id: a8ea146640fa9f09f8e4
github.client.secret:  XXXXXXXXXXXXXXXXXXXXXXXXXXXX
github.base.url: https://github.com/
github.api.url: https://api.github.com/
github.gist.url: https://gist.github.com/
rcs.engine: redis
solr.host.port: 54.174.16.168:8983
solr.collection: collection1
solr.url: http://54.174.16.168:8983/solr/rcloudnotebooks
solr.page.size: 5
rcs.system.config.addons: rcloud.viewer, rcloud.enviewer
rcloud.languages: rcloud.r, rcloud.python
## smtp.server:xxxxxxxxxxxxx
email.from:donotreply
Cookie.Domain: 54.174.16.168

-----------------   
I got the same error message if I changed the Cookie.Domain: to "ec2-54-174-16-168.compute-1.amazonaws.com".

Any suggestions pinning down my problem will be greatly appreciated!

Max Zhao

**Comment by prateek05** [comment]
@mzhao577 Is this thread related to the same issue we discussed and fixed last week ? If so can we mark this issue to be closed now ?

**Comment by mzhao577** [comment]
Hi Prateek,

Yes. Please close it.
Max

**Comment by prateek05** [comment]
@gordonwoodhull  Please close this

**Comment by gordonwoodhull** [comment]
Great!

**Comment by Rnewbie** [comment]
Hi, 

Sorry for creating anything error in installing Rcloud, I got an error

Loading required package: rediscc
Error in redis.connect(host, port, 3, TRUE, TRUE, db = db, password = password) : 
  connect to redis failed: Connection refused

***FATAL ERROR** aborting RCloud startup

 after trying to start up the cloud with 
```
sh scripts/fresh_start.sh
```

**Comment by gordonwoodhull** [comment]
Do you have redis running on the server and port specified by the `rcs.redis.host` key in your rcloud.conf?

**Comment by Rnewbie** [comment]
Thanks for the prompt reply. It seems i didn't.
```
##------RCloud Configuration: copy into rcloud.conf and edit! ------
##: GitHub info below must be modified in order for RCloud to work!
## Only set Host: if it doesn't match the canonical name of your machine
##Host: 127.0.0.1
#--: gist back-end, pick either githubgist (default) or gitgist
github.client.id: a43e06c657c275976f30
github.client.secret: 7dd16b2611988267f75ced8a10edbcc629fc23a1
github.base.url: https://github.com/
github.api.url: https://api.github.com/
github.gist.url: https://gist.github.com/
#gist.backend: gitgist
#gist.git.root: ${ROOT}/data/gists
rcs.engine: redis
solr.url: http://127.0.0.1:8983/solr/rcloudnotebooks
rcs.system.config.addons: rcloud.viewer, rcloud.enviewer, rcloud.notebook.info
rcloud.languages: rcloud.r, rcloud.python, rcloud.rmarkdown
#--optional: set to enable for sending comment notificaion e-mails if desired
#smtp.server:xxxxxxxxxxxxx
#email.from:donotreply
```

**Comment by gordonwoodhull** [comment]
You need the host as well as port. E.g. since I run redis on the same machine, I have 

```
rcs.redis.host: 127.0.0.1:6379
```
More info on rcloud.conf settings here: https://github.com/att/rcloud/wiki/rcloud.conf

**Comment by Rnewbie** [comment]
Thank you, 

I can run the script and the output appear to be
```
Loading required package: rcloud.support
Loading required package: base64enc
Loading required package: rjson
Loading required package: parallel
Starting Rserve on chanin-nantasenamats-macbook-air.local 
Loading RCloud configuration file...
Loading required package: rediscc
Rserv started in daemon mode.
```
However, on here: http://127.0.0.1:8080/login.html 
I got a message of "ERROR: item at the specified URL not found".

**Comment by prateek05** [comment]
It is http://127.0.0.1:8080/login.R and .html. Can you point me to the place where its documented as login.html so that I can rectify it ? 
Thanks,
Prateek

**Comment by Rnewbie** [comment]
Thanks Gondor and Prateeks, I will close the issues now. Sorry for my ignorance. Thanks.
