### ISSUE TITLE
Python issue : problem while trying to generate plots

### ISSUE THREAD

**Issue by Arko2013** [att/rcloud#1159]
Hi,

When I try to create a simple graph in a new Python cell, the graph is not displayed on the first execution.No error messages are displayed. However on re-executing the cell, the graph is displayed.

**Comment by prateek05** [comment]
Is there anything specific you see in the console one your first execution ?

**Comment by prateek05** [comment]
@Arko2013 Any lead?

**Comment by gordonwoodhull** [comment]
Is this issue still open? I am not able to repro.

**Comment by gordonwoodhull** [comment]
Closing this - transient install issue?
