### ISSUE TITLE
Notebook info popover doesn't disappear if the notebook is deleted

### ISSUE THREAD

**Issue by Arko2013** [att/rcloud#1170]
Steps to replicate:
1) Click on the 'notebook info' option for any notebook, the popover will be displayed showing information about that notebook

![image](https://cloud.githubusercontent.com/assets/5258841/5612217/41f2cb88-94f7-11e4-810e-5b7065cea8ca.png)

2)Now delete that notebook. The popover will not disappear 

![image](https://cloud.githubusercontent.com/assets/5258841/5612228/86dc1e7a-94f7-11e4-8ad6-3df753ccdcfc.png)

**Comment by gordonwoodhull** [comment]
Thanks @Arko2013!

**Comment by gordonwoodhull** [comment]
There are still some obscure ways to end up with extra popovers, like clicking on a star/unstar button, which also rebuilds the notebook tree and invalidates the popover reference, but at least now when you click on anything that is not preventing propogation, all the darn info popovers will go away.
