### ISSUE TITLE
Installation issues with the rcloud.support R package

### ISSUE THREAD

**Issue by micrain** [att/rcloud#1171]
Hello,

I am using Ubuntu 14.04 and version 3.1.1 of R. As part of the RCloud installation process, when I try to install the rcloud.support package I get the following error. I am using the install.packages("rcloud.support", repos=c("http://RForge.net", "http://R.research.att.com"), type="source") command as mentioned in the instructions.

ERROR: dependency ‘gist’ is not available for package ‘rcloud.support’
* removing ‘/usr/local/lib/R/site-library/rcloud.support’

The downloaded source packages are in
	‘/tmp/RtmpBg2wmC/downloaded_packages’
Warning message:
In install.packages("rcloud.support", repos = c("http://RForge.net",  :
  installation of package ‘rcloud.support’ had non-zero exit status

Any ideas as to what is going wrong?

Thanks,
Caner

**Comment by gordonwoodhull** [comment]
Those instructions are out of date.  :-(

please try using `scripts/bootstrapR.sh`

**Comment by prateek05** [comment]
@micrain Is your installation problem resolved ?

**Comment by micrain** [comment]
Sorry forgot to reply back. Yes, running bootstrapR.sh helped a little. However, I ran into issues installing the guitar package. I kept on getting errors similar to,
boost/shared_ptr.hpp: No such file or directory.

I overcame it by installing libboost-dev before installing RCloud.

Thanks for your help.

**Comment by gordonwoodhull** [comment]
Great, glad to hear it. Yes we have a ton of dependencies and it is some feat to build it all. 

Congratulations!
