### ISSUE TITLE
shiny cells: occasional please wait of doom with big white background

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1172]
add screenshot here.

seems to happen more on windows.  almost certainly due to loading an aircraft carrier worth of headers, css, etc, into the cell where it does not belong.

**Comment by gordonwoodhull** [comment]
hopefully we can generate an html fragment in this case instead of trying to paste a whole html page into a cell.

**Comment by robert-a** [comment]
shiny was loading bootstrap.min (css & js). Removing these extra copies seems to clear up the problem.

**Comment by s-u** [comment]
User error to insert full HTML into a cell (and expect it to work).

**Comment by gordonwoodhull** [comment]
This issue was moved to att/rcloud.shiny#3
