### ISSUE TITLE
Bunch of functions in the environment viewer pane when running python

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1173]
Run a python cell say print("Hello World")
Enviewer Pane:
Functions
RC.auth.anonymous	function
RC.authenticate	function
authenticated.ocaps	function
make.oc	function
unauthenticated.ocaps	function

**Comment by gordonwoodhull** [comment]
Ever see this again @prateek05 ?

**Comment by gordonwoodhull** [comment]
Closing due to non-reproducibility.
