### ISSUE TITLE
Duplicate Language options for cells

### ISSUE THREAD

**Issue by Arko2013** [att/rcloud#1174]
Starting Rcloud and switching to a different notebook or creating a new notebook shows duplicate language options for a cell other than the prompt cell

Steps to replicate:
1) Start Rcloud
2) Switch to a different already existing notebook or create a new cell in a newly created notebook
![duplicate _langs_options](https://cloud.githubusercontent.com/assets/5258841/5661303/3fec617c-9750-11e4-9e34-87242d3e7973.PNG)

This exists for every cell in the notebook except the prompt cell.
The number of duplicates increase with the number of notebooks switched or created.
Reloading the page solves the problem.

**Comment by gordonwoodhull** [comment]
Thanks @Arko2013, this is new to me. Will check.
