### ISSUE TITLE
markdown should toggle code/results

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1175]
For R & Python cells, the behavior is now to always show both code and results.

This may not make as much sense for Markdown, which usually shows both code and results itself.

Maybe Markdown cells should go back to the either/or.

**Comment by martymcwizard** [comment]
Markdown is relatively simple, but if it were complex then you might want to see your markdown and your resulting construct side by side.  Think about a LaTeX editor which has the code and the result side by side.  BUT, I'm not really an expert on markdown functionality.  Perhaps it has more complexity than I have used but given the complexity I use, this seems like overkill.

**Comment by gordonwoodhull** [comment]
side-by-side would be a really cool option, especially on large monitors.  people might want that for code/results of other types of cells, too. but it's some work.

for 1.3, i think i will just revert the behavior for markdown cells, i.e. for markdown cells it will switch between code and results.

**Comment by gordonwoodhull** [comment]
implementing something in-between where the code does go away when the markdown runs, but when you edit, the result doesn't go away
