### ISSUE TITLE
cell commands get unresponsive after split/join

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1182]
As reported by @sneha-bharti:

> §  Some cell options get unresponsive after performing the ‘split cells’ and ‘join cells’ functions
Splitting and joining cells results in the of functionalities of the cells options like ‘run’, ‘toggle edit’, ‘remove’, ‘insert cell’ and ‘join cells’. Some of these options get unresponsive and failed to get clicked.
Any option may get unresponsive and there is no fixed pattern. This issue occurs for the cell immediately below the cell on the function is performed.

**Comment by gordonwoodhull** [comment]
I'm not able to repro this but I don't doubt it given #1181

**Comment by gordonwoodhull** [comment]
@sneha-bharti, please check - the fix for #1180 should also fix this, but i wasn't able to repro.

**Comment by Arko2013** [comment]
Tested the issues #1180 and #1182, both are working fine.

**Comment by gordonwoodhull** [comment]
Thanks @Arko2013!
