### ISSUE TITLE
run markdown cells (knitr) in fresh graphics context

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1185]
even with feature/direct-output, we are still getting double plots when running markdown after running R.

@s-u, am I correct in guessing that we are still using the broken "run in same context" feature of knitr?

**Comment by s-u** [comment]
yes, knitr has not changed, so it will have the same bugs. However, we decided to switch to non-shared device for markdown once direct output is enabled so we have to remove `global.device=TRUE` from `opts_knit$set()` since that's what's broken in `knitr`.

**Comment by gordonwoodhull** [comment]
Fixed in 9b19fca4fffcb58ab2e7749dd4045a35f7c2fd46
