### ISSUE TITLE
Independent command prompt

### ISSUE THREAD

**Issue by slobotai1** [att/rcloud#1188]
Hi,
Running a code (mostly a single line code) through the prompt cell, causes a new cell to be created in the open notebook.
Sometimes that is unnecessary and futile.
Command prompt can be independent of the notebooks directly showing the output in the session or in the workspace

**Comment by gordonwoodhull** [comment]
One of the objectives of RCloud is to make research reproducible.  Recording commands as cells is essential to this design.

We are working on making the cells more lightweight (this release) and making it easier to cull cells and retain the cells that worked (next release).

**Comment by slobotai1** [comment]
Thanks for the clarification. That helped.
Looking forward to it.
