### ISSUE TITLE
password() does not produce a pop up box

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1190]
## Error in self.oobMessage(list(s, ...)): argument "prompt" is missing, with no default

It would also be nice if we are revising this to support multiple password() declarations in a single cell. The previous implementation only renders the first pop up and goes into a never ending wait state. 

Prateek

**Comment by s-u** [comment]
This is a user error - `password()` has a mandatory argument `prompt`.

**Comment by prateek05** [comment]
@s-u "The previous implementation only renders the first pop up and goes into a never ending wait state"

Public Notebook: Cell2: notebook=6303ec8530ecae326417

**Comment by s-u** [comment]
But that's #371 - the error above is because you didn't put in the prompt
