### ISSUE TITLE
The 'notebook info' popover does't appear after 3rd consecutive click

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1193]
User can see the starrer list when clicked on the 'notebook info' icon. The list disappears when that icon is clicked again.  

To replicate the issue click on the 'notebook info' icon of the same notebook for three or more times  consecutively. 
- On first click on 'notebook info' icon, the popover will appear
- On second click on 'notebook info' icon for the same notebook, the popover will disappear
-  From third click onwards popover won't appear unless you click on 'notebook info' icon for any     other notebook and then again click on the 'notebook info' icon of the notebook which is previously clicked consecutively for two times

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11!

Possibly relevant: http://stackoverflow.com/questions/14285082/jquery-twitter-bootstrap-close-all-popovers-on-bodys-any-elements-focus

**Comment by sanketd11** [comment]
The behavior is slightly different in the current commits  on RCloud-2 (develop/eae0258) and RCloud-local (develop/071fc29) , after third consecutive click on the notebook info icon, the popover becomes visible for fraction of a second only and then disappears

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11!

This is a critical problem for the new release, because we are counting on being able to get at the protection groups through the info popover. (Previously it wasn't used all that much, which explains why users didn't complain much about this or odd disconnection errors that would occur after a notebook was loaded.)

**Comment by gordonwoodhull** [comment]
@anatoliyg, if you're not able to make click-away close in a stable way, maybe we should just have a close button. another developer and i already wasted a lot of time trying to make this work.

**Comment by anatoliyg** [comment]
ok, let me take a look

On Thu, Jun 11, 2015 at 10:56 AM, Gordon Woodhull <notifications@github.com>
wrote:

> @anatoliyg <https://github.com/anatoliyg>, if you're not able to make
> click-away close in a stable way, maybe we should just have a close button.
> another developer and i already wasted a lot of time trying to make this
> work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/att/rcloud/issues/1193#issuecomment-111162455>.
>



-- 
Anatoliy

**Comment by sanketd11** [comment]
We tested out for this issue. It seems to be working fine now. Hence closing it.
