### ISSUE TITLE
Code block for markdown cell disappears on changing the language

### ISSUE THREAD

**Issue by tejas1493** [att/rcloud#1200]
Steps to replicate: 
1) Create a markdown cell and run it
![markdown_cell](https://cloud.githubusercontent.com/assets/9250669/5870933/d9c31816-a2fb-11e4-8710-5a14dd72fbb5.PNG)

![run](https://cloud.githubusercontent.com/assets/9250669/5870934/d9f188ea-a2fb-11e4-9ef0-d006fc590e6a.PNG)

2) Only the output block is visible.
 Changing the language here will not bring back the code block after clicking toggle edit
![code disappear](https://cloud.githubusercontent.com/assets/9250669/5871004/e7981ca6-a2fc-11e4-9e52-2a30c2879309.PNG)

**Comment by gordonwoodhull** [comment]
Good point.  The code should be restored whenever the result is cleared.
