### ISSUE TITLE
update installation instructions

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1204]
The setup guide

https://github.com/att/rcloud/blob/develop/doc/INSTALL.md

is about two releases out of date.

Currently we recommend 
 1. installing some dependencies (like Boost and Python) through `apt-get` or `brew` or any other system-specific package installer
 2. `scripts/bootstrapR.sh`
 3. `scripts/build.sh`

**Comment by prateek05** [comment]
Would also integrating bootstrapR and build both in a single script for 1.3 be something we would want to do ?

**Comment by gordonwoodhull** [comment]
of course we would want to, but i doubt @s-u has time to

**Comment by gordonwoodhull** [comment]
https://github.com/att/rcloud/tree/develop/rcloud.packages

is also out of date in a trivial way

**Comment by gordonwoodhull** [comment]
The correct and up-to-date install document is [doc/INSTALL.md](https://github.com/att/rcloud/blob/develop/doc/INSTALL.md). 

Links corrected, obsolete INSTALL doc removed, warning corrected on wiki.  

Internal documentation is not relevant here.
