### ISSUE TITLE
Error in session pane while loading some notebooks

### ISSUE THREAD

**Issue by tejas1493** [att/rcloud#1206]
Noticed an error which is thrown in the session div while loading certain notebooks.
![ace_mode](https://cloud.githubusercontent.com/assets/9250669/5914195/8966fa4e-a617-11e4-9fb3-fa04fe55a68e.PNG)

The behavior is erratic in nature, that is, it is only happening while clicking some notebooks. For others, no such error message is thrown. The cells of the notebook are displayed but  if the notebook is opened in view mode, the previous notebook is displayed.

**Comment by sanketd11** [comment]
Observed similar error while performing file upload operation in the assets div
![ace_mode_error](https://cloud.githubusercontent.com/assets/9251570/5956085/9bb56c76-a7cf-11e4-96cb-66733a0b47af.PNG)

this error occurred at the time of uploading files of all the file extensions except '.R', '.py', '.md' files

**Comment by gordonwoodhull** [comment]
Thanks, that was a helpful clue. It does have to do with unrecognized languages then, just asset languages not cell languages.
