### ISSUE TITLE
Code is not editable on clicking it

### ISSUE THREAD

**Issue by tejas1493** [att/rcloud#1208]
Currently the user can click on the code or the 'toggle edit' button to edit the code

In some situations, the code block does not become editable when clicked on it.
This scenario can be replicated as follows:
1) Create a new notebook and create a new cell in it
2) Run any code in that cell
After the output is displayed, the code block will not become editable if the user clicks on it. The user can use the toggle edit button.
![cell_not_editable](https://cloud.githubusercontent.com/assets/9250669/5933110/fa7950a0-a6e0-11e4-8292-134887160c1c.PNG)

This problem exists only after running the cells. When an existing notebook is loaded, the cells can be clicked to edit them.
This issue occurs in some other cases also. In some notebooks, after running all cells, some cells showed the above behavior.

**Comment by gordonwoodhull** [comment]
Another way to repro this is simply to toggle edit mode on then off using the button.
