### ISSUE TITLE
option not to show cell numbers

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1213]
#1126 is great but a decluttering option would be nice.

**Comment by gordonwoodhull** [comment]
especially not in view mode

**Comment by martymcwizard** [comment]
agreed.  in the demo I did today I found myself wistful about the decluttered option, and I'm the guy who requested this!
another observation.  it would be nice to force renumber.  i was playing around and i had hoped that forking a notebook might number the cells anew but it didn't.  i'll raise a separate issue
