### ISSUE TITLE
defeat browser caching

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1216]
@s-u, I had to revert 7950d08 and 393c887 "enforce caching headers in http.R" because they were causing login.R to hang entirely on my setup.

if you don't see this, i will show you on my computer.

**Comment by s-u** [comment]
ok, one more try - can you test if this works for you, please?

**Comment by gordonwoodhull** [comment]
Will do!

**Comment by gordonwoodhull** [comment]
I did not notice it, therefore it seems to be working!
