### ISSUE TITLE
list of recent notebooks

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1217]
In addition to #698 browser "back" and "forward" buttons, it would be nice just to have a list of recent notebooks somewhere.

In fact, since I'm not great about remembering to name my notebooks, I keep expecting to find this list somewhere, and keep being surprised I can't find it.

We already keep a recently opened notebook list, it just has to be exposed in the UI somewhere.  Suggestions welcome where.

**Comment by gordonwoodhull** [comment]
API call: ` rcloud.config.get_recent_notebooks()`

**Comment by gordonwoodhull** [comment]
.. which returns a map of id -> date, which can be sorted as editor_tab does here:

https://github.com/att/rcloud/blob/develop/htdocs/editor_tab.js#L984-L989

**Comment by gordonwoodhull** [comment]
also #698

**Comment by holyguster** [comment]
Right now, the list of recent notebooks does not include the notebook owner.  Seems like that would be a helpful addition.

For example, when I look at someone else's notebook and then fork it, that notebook name will show up 2 times in the recent notebook list (see attached screen shot), one will be owned by the other user, and one by me.  I cannot necessarily assume that the more recent one is the one that I own, as the other user may be continuing to make changes to their copy of the notebook.

![screen shot 2015-08-17 at 10 54 11 am](https://cloud.githubusercontent.com/assets/927657/9307745/3447907c-44ce-11e5-873d-818a880e7fd9.png)

**Comment by anatoliyg** [comment]
Makes sense, will see how doable it is to do.

**Comment by anatoliyg** [comment]
@holyguster  are you testing this locally btw?


--
A

**Comment by holyguster** [comment]
I was looking at it on rcloud-2
