### ISSUE TITLE
workspace div doesn't show the status/value for variables of 'logical' data type

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1225]
steps to replicate :
1) Initialize any variable with value TRUE or FALSE ('logical data type')
2) Observe the workspace div
workspace div displays that variable and its data type but doesn't show whether it is 'TRUE' or 'FALSE'
![workspace](https://cloud.githubusercontent.com/assets/9251570/5972190/585bbde8-a87b-11e4-9857-a99046736f6c.PNG)

**Comment by gordonwoodhull** [comment]
Thanks! Good catch.

**Comment by gordonwoodhull** [comment]
fixed by #1153
