### ISSUE TITLE
Notebook options overlap with notebook title in the 'Notebooks div'

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1226]
Steps to replicate:
1) Create an notebook and rename it with long title
2) Hover the mouse over that notebook title in 'Notebooks div'
OR
1) Rename any existing notebook with long title and load that notebook
2) Hover the mouse over that notebook title in 'Notebooks div'

![notebook1](https://cloud.githubusercontent.com/assets/9251570/5975241/209d8cf0-a8a4-11e4-98f4-9b0e97cbd291.PNG)

![notebook](https://cloud.githubusercontent.com/assets/9251570/5975285/d6a9c748-a8a4-11e4-9b31-1df144ce5204.PNG)

The above overlapping occurs only in the case of currently loaded notebook with long title

**Comment by gordonwoodhull** [comment]
thank you @sanketd11, looks like some outdated css

**Comment by gordonwoodhull** [comment]
all the UI code was refactored, so there are many places where the DOM structure is just a little bit different, so i really appreciate your finding this
