### ISSUE TITLE
no line numbers in executed mode

### ISSUE THREAD

**Issue by T-BDCoE-Training** [att/rcloud#1230]
this is a comment on release 1.2 (checking on 1.3 but having different issues)

the cell line numbers don't show up when you are looking at the executed code

![screen shot 2015-02-01 at 4 10 22 pm](https://cloud.githubusercontent.com/assets/10699896/5994142/22bfe088-aa2e-11e4-9750-c593b1df89b6.png)

**Comment by gordonwoodhull** [comment]
Dupe of #1218 which is already fixed.

**Comment by gordonwoodhull** [comment]
I just noticed you were talking about 1.2 - the behavior is quite different in 1.3, but yeah, fixed there.

**Comment by T-BDCoE-Training** [comment]
thanks!
