### ISSUE TITLE
deferred results are being printed as values

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1233]
One consequence of direct-output is that the processing of deferred results was simplified.  But apparently the old replacement code was sneakily deleting the `[1] "` (and closing quote) from

![image](https://cloud.githubusercontent.com/assets/1366709/6007488/748fec54-aae8-11e4-916d-029c22147211.png)

I blame this opaque line from old cell_view.js:
```
                    var uuids = this.childNodes[0].childNodes[0].data.substr(8,65).split("|");
```
or rather, that it is only pulling part of the text out of the `code` element but replacing the whole thing.

It's not enough to just special-case deferred results and send them in a separate OOB or as HTML, although that might be a good idea.  When processing markdown, we still need to detect the rest of the printed value and remove it.

**Comment by s-u** [comment]
Create a  separate OOB send

**Comment by s-u** [comment]
@s-u look into an object that prints in Markdown but emits OOB in direct output

**Comment by s-u** [comment]
This is now fixed for R cells, but note that for markdown cells there is still `## ` -- I don't intend to fix that, though.

**Comment by gordonwoodhull** [comment]
I wonder how they do this kind of stuff in htmltools-land.  I bet there is a way to mark your type as something that should expand into html with out the value-hashes.
