### ISSUE TITLE
Missing packages (RCloud-5)

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#1235]
The following packages are not found on RCloud-5:
gridExtra 
googleVis
choroplethr

Should I go through the full package list from the old release?

**Comment by rhknag** [comment]
Example:
http://rcloud-5.research.att.com/edit.html?notebook=188a7d0cbe58790b7fc1

**Comment by gordonwoodhull** [comment]
This is not really an RCloud issue but a deployment issue; please take up any missing packages with Prateek.  I'm closing this.
