### ISSUE TITLE
wdcplot problem?

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#1236]
My large wdcplot no longer works on rcloud-5.  Example: 
http://rcloud-5.research.att.com/edit.html?notebook=366514e5bd12ffa4abee

**Comment by gordonwoodhull** [comment]
Works for me, or at least it looks like it's working.

Looks like it takes 20-30 seconds to display the charts after the markdown displays.

Could you describe the problem you were having?  Is it consistently reproduceable?

**Comment by rhknag** [comment]
Hmm – I walked away for 5 minutes and it didn’t display.  Now it seems to be working again.  I’ll test some more….
It always took a while to display.

ralph

**Comment by rhknag** [comment]
It’s working for me as well – perhaps I just got confused by a long delay….
Let’s close this

Ralph

**Comment by gordonwoodhull** [comment]
Okay.  Thanks for verifying, Ralph.
