### ISSUE TITLE
notebook.R notebooks are opening with null version

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#1237]
I don't understand this error.   I don't see a missing file anywhere - do you? 
http://rcloud-5.research.att.com/edit.html?notebook=fa5801f26e197c046c5b#
Works on RCloud (notebook.R call)

**Comment by gordonwoodhull** [comment]
Thanks for the report @rhknag.

This is an instance of #1244: all notebooks that don't use the RCloud GUI are generally broken.

**Comment by gordonwoodhull** [comment]
It looks like these notebooks are actually running fine, but the RCloud GUI doesn't understand that there is no version selected, and is appending `/null` to the URI.
