### ISSUE TITLE
Search feature is not working in RCloud-5

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1241]
The following error is thrown in session div when a keyword is searched through 'search div'

![capture](https://cloud.githubusercontent.com/assets/9251570/6040605/a628e434-ac99-11e4-973b-aa8d0b2de437.PNG)

**Comment by gordonwoodhull** [comment]
This is a deployment issue, not an RCloud issue. Github is For issues about the software itself.

But thanks for the report, will look into it. Closing.
