### ISSUE TITLE
shareable link to notebook.R fails to load

### ISSUE THREAD

**Issue by tejas1493** [att/rcloud#1243]
Opening the shareable link as notebook.R opens the link with '/null'
![null](https://cloud.githubusercontent.com/assets/9250669/6041293/05a14fa8-aca1-11e4-80fd-42bc100e29fb.PNG)
This causes failure to load the page
![error](https://cloud.githubusercontent.com/assets/9250669/6041295/0fecfcb4-aca1-11e4-9f80-c58f4c55ccb4.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @tejas1493.  duplicate of #1237
