### ISSUE TITLE
Difference in behavior in RCloud 5 and local instance of RCloud develop when shell script is executed through assets

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1250]
In local instance of RCloud develop, when any shell script is executed through assets div, the shell script returns the 'character (0)' output in to the R variable and the console output is displayed in sessions div. Also the R variable value is not displayed in workspace div. The workspace div displays only name and data type for that R variable and quotes are shown in the place of value

Refer the following screenshot:
![asset1](https://cloud.githubusercontent.com/assets/9251570/6058766/7597ed9e-ad50-11e4-8c19-71c3b5cca5b6.jpg)
 

But in case of RCloud-5, the behavior is different. In this case the shell script returns all the console outputs to the R variable in the form of list and nothing gets displayed in sessions div

Refer the following screenshot:
![asset2](https://cloud.githubusercontent.com/assets/9251570/6058771/86d95dcc-ad50-11e4-86c7-020336be3294.jpg)

Which is the expected behavior?

**Comment by gordonwoodhull** [comment]
I believe the correct behavior is to return an array of lines returned.  Certainly returning `character(0)` is not helpful.  

Have you managed to isolate the problem at all?  IIRC the only difference we determined between these deployments is CentOS versus Ubuntu.

**Comment by sanketd11** [comment]
I have tested this issue again on local. The behavior is as expected.

**Comment by gordonwoodhull** [comment]
Okay maybe this is transient. Please add an automated test case for this. Will close, comment if you see this again
