### ISSUE TITLE
view.html nondeterministically hangs

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#1256]
Seems like this notebook http://gist.github.com/cscheid/4fd45d564dd4ebcd94f6

only works on view.html once every 10 times or so. The other times, rcloud hangs mid-execution. This does not seem to happen in edit.html.

Unfortunately, the code in `cell_controller.js` is now completely foreign to me, so I can't really follow what's going on with the execution snapshots, resulters, contexts and what not.

Sorry I can't be of more help than this :(

**Comment by prattatx** [comment]
I'm seeing edit.html hanging intermittently as well. As a side note, none of the buttons work in the toolbar while RCloud is in this state. Logout should work always. 


![image](https://cloud.githubusercontent.com/assets/1541991/6087611/4f8b3598-ae13-11e4-952a-d8d7139d4569.png)

**Comment by cscheid** [comment]
I've seen that one as well, but much more rarely.

**Comment by gordonwoodhull** [comment]
@prattatx, thanks, but that is an entirely different bug, so I'm going to move it.

**Comment by gordonwoodhull** [comment]
@cscheid, are you running with compute separation?  I am able to reproduce this consistently with compute separation enabled (with current develop, rcloud.conf contains `compute.separation.modes: IDE`).

It also looks just like another instability we were seeing with load notebook messages just getting dropped, we don't know where.  We have decided not to support compute separation for this release, just too unstable.  :-(

**Comment by gordonwoodhull** [comment]
I am not able to repro this over many, many reloads with compute separation disabled, so I'm going to  mark it as such, but please lmk if you see this without compute separation.

**Comment by cscheid** [comment]
My rcloud.conf does *not* contain `compute.separation.modes: IDE`, but maybe the default is to use it?

**Comment by gordonwoodhull** [comment]
Perhaps if you pull latest develop this will go away, as we only recently decided to disable the feature.

**Comment by gordonwoodhull** [comment]
I'm putting this on 1.4 as I believe it is a compute separation bug.  Please comment if you see this without c-s.

**Comment by gordonwoodhull** [comment]
bug with early versions of c-u
