### ISSUE TITLE
Center column sizing 

### ISSUE THREAD

**Issue by prattatx** [att/rcloud#1257]
While sizing the center panel, increased right side one notch (to the right), and then sizing the left side of center panel one notch (to the left), resulted in a VERY skinny center panel. 

![image](https://cloud.githubusercontent.com/assets/1541991/6087231/a8530854-ae0e-11e4-850b-84d199cf839f.png)

**Comment by gordonwoodhull** [comment]
Thanks @prattatx.  The suggestion is to have a minimum width for the center column?  

I think we didn't want to interfere with being able to make the side panels as big as you want, so we allowed this.  Another possibility is to have the side panels overlap the center.

**Comment by prattatx** [comment]
The column is actually popping to a very skinny state as the picture shows. If the user changes the panel width on one side it should not make the other side of the panel to move. Also now that I am recreating the bug, I can no longer select the right side of the center panel in order to size it again.

**Comment by gordonwoodhull** [comment]
I agree about them being independent

And the disappearing right sizer is #1228.

I don't think I've seen the bug you are reporting here. I wonder what the particular circumstances are that cause it.  It sounds like you are saying you actually resized in the opposite direction and then it "pops" to something completely different. I'll keep trying to repro,  or lmk if you have more clues. 

I trust this is on Chrome, and I'll hazard to guess you are on a retina display?

**Comment by gordonwoodhull** [comment]
ah, i can repo this now
