### ISSUE TITLE
Cell sizes not increasing when adding lines in cell edit mode

### ISSUE THREAD

**Issue by prattatx** [att/rcloud#1260]
Code within the cell is falling above the fold when adding lines to a cell. As much code as possible should always be visible when a cell has focus and is having lines added to it. 

Given:
![image](https://cloud.githubusercontent.com/assets/1541991/6087735/bd2b7012-ae14-11e4-9c69-a8f56151a41e.png)

CRLF to add a line
![image](https://cloud.githubusercontent.com/assets/1541991/6087747/dddf9162-ae14-11e4-9528-fd6e051d1783.png)

CRLF to add another line, can't see first line of R
![image](https://cloud.githubusercontent.com/assets/1541991/6087752/ea9e68a6-ae14-11e4-9eda-e6611e330762.png)

**Comment by gordonwoodhull** [comment]
Thanks @prattatx.  Yes, this is #1222, which is fixed on develop but hasn't been deployed to rcloud-5 yet.
