### ISSUE TITLE
error in one cell prevents following cells from executing 

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#1262]
https://rcloud-2.research.att.com/edit.html?notebook=5e939dbaf93bff736d4a

gets the following error:

## Error in sample.int(length(x), size, replace, prob): cannot take a sample larger than the population when 'replace = FALSE'

On RCloud the following cells execute but on RCloud-2 they are cancelled.

**Comment by gordonwoodhull** [comment]
Thanks @rhknag.  Yes, this is a consequence of not reporting errors properly, and I was waiting on #1248 for a more helpful error class.

Errors from cell execution should be printed in the cell results and should not stop further execution.  

We might want a Stop On Errors option, though, in a later version.

**Comment by s-u** [comment]
Errors have to cancel subsequent cells. It was a bug in previous RCloud versions that errors were ignored. The cell where the error happened should not be cancelled, though and should show the error.

**Comment by s-u** [comment]
c.f. #214
