### ISSUE TITLE
indicate when a cell is enqueued or running

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#1264]
I was confused at first by the fact that the  "Computing" message has been moved to the end of cell. For a long while I didn't see it and it seemed like the cell execute didn't work.   A minor issue - it's ok once you understand what's happening, but perhaps there's an easy improvement?

**Comment by gordonwoodhull** [comment]
Hmm, any suggestions?  This is the feature of always showing code and results.  If you're expecting the code to go away on execution, you will be disappointed.

**Comment by rhknag** [comment]
The idea is to give some feedback that execution has started - otherwise there's a chance a user might hit cell execute more than once.    This only happens if its a large cell and the "computing" message is off screen.  The "computing" message used to be displayed right away at the top of the cell and always provided feedback.  Could you show "computing" on top as well as bottom?   Or change cell color or font  for example.   Again this only happens for long cells that go beyond the current display - but it actually happened to me....

**Comment by gordonwoodhull** [comment]
I see.  Yes, long cells are an issue here.

Maybe the button itself should change, as it does at the top?  I'm not sure what to: stop is not appropriate here, and I think enqueueing the same cell more than once is valid.  Maybe play with an ellipsis over it.

**Comment by holyguster** [comment]
IMHO changing the play button for the cell sounds good, as it gives feedback right where the user clicked; an ellipsis over play sounds like a fine idea. I assume it would change back to just play after execution completes.

**Comment by rhknag** [comment]
I think almost any indication would work

**Comment by prateek05** [comment]
With the upgrade I got a couple of emails today. People were mostly confused with cells that don't print any output.

**Comment by gordonwoodhull** [comment]
Thanks @prateek05, this is very good feedback.

**Comment by gordonwoodhull** [comment]
Actually, this enhancement won't help at all with that. That's more #1207 indication of empty result. I'll paste your comment there
