### ISSUE TITLE
signal causes incomprehensible errors

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1268]
I have a notebook for testing compute separation with a bunch of sleeps in it.

It seems that the error returned for interruption is not compatible with `.eval`, as the following line 

```
        o$traceback <- unlist(o$traceback)
```

dies with
```
Error: $ operator is invalid for atomic vectors
```

Commenting out that line doesn't help, because then the client dies with 
```
 Uncaught json() unsupported for type list
```

**Comment by s-u** [comment]
can you point to the notebook, please, so I can try to reproduce?

**Comment by s-u** [comment]
Ah, wait, that has nothing to do with the R objects  - that should be regular `ERR_xx` message from Rserve - how this is handled is up to rserve-js so will need to do something reasonable there I suppose (not sure what it did so far) - that's a whole different beast than the objects we generate (which as successful results as far as rserve-js goes).

**Comment by gordonwoodhull** [comment]
The notebook just has 

```
work <- function(x) {
   rcloud.out(x)
   Sys.sleep(5)
   x
} 
work(17) 
```

I can probably handle the client side but it looks like the wrong type on the server side as well.

**Comment by gordonwoodhull** [comment]
notebook is 3b4a8686146e5f5c91d2 on public github

**Comment by s-u** [comment]
Ok, thanks - the issue is that `Rserve.eval()` doesn't correctly signal abnormal abort. It's sort of too good for its own good - it tries hard to generate the error report even in case where it cannot be generated, so the error message is actually bogus.

**Comment by s-u** [comment]
I can't find an easy way to figure out if the condition is an interrupt as it doesn't seem to be passed through R as an actual condition so we may need to resort to something like `withCallingHandlers(expr, interrupt=function(...) stop("interrupt"))` - essentially creating our own condition for interrupt.

**Comment by gordonwoodhull** [comment]
fixed?
