### ISSUE TITLE
notebook forked from folder has the same title

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1277]
Currently while forking a notebook, the forked notebook is named with a post-fix number. But for notebooks present inside a sub folder, the forked notebooks get the same title without any post-fix number. This issue occurs only when forking one's own notebook.

![apture](https://cloud.githubusercontent.com/assets/9251570/6108208/2960e4b8-b097-11e4-94ac-e9c59b80eedf.PNG)

**Comment by gordonwoodhull** [comment]
Nice catch @sanketd11.  This is very odd.

**Comment by gordonwoodhull** [comment]
editor_tab.js `find_next_copy_name`

**Comment by gordonwoodhull** [comment]
This is necessary for #885 so I took it and fixed it.
