### ISSUE TITLE
Python cell execution throws error in RCloud-5

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1278]
This behavior is observed in RCloud-5 only. While executing a python cell the output is shown in output block for some time followed by an error in session div and then cell status changes to cancelled
  
![python_err](https://cloud.githubusercontent.com/assets/9251570/6108430/21e7bc3c-b099-11e4-825c-0d86f5cc8036.PNG)

**Comment by gordonwoodhull** [comment]
This was fixed in a61e16d26713a78b8135d7d8251d7778827062d9
