### ISSUE TITLE
Error in cell execution in RCloud-5

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1285]
Session div is showing the following error every time we execute any of the R, Markdown or Python cell in which any new code is  added. New changes in any cell are not getting saved.
 
![python_error](https://cloud.githubusercontent.com/assets/9251570/6125518/d7e20e90-b13c-11e4-83fb-3837a418ccb2.PNG)

**Comment by s-u** [comment]
rcloud-5 is not on any official branch, right now
