### ISSUE TITLE
Line numbers in executed mode are misaligned and overlap with adjacent cells

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1288]
Line numbers  of a cell are misaligned with the code lines when in executed mode
Due to this, line numbers overlap with the cell below or with the ouput block.

![number under](https://cloud.githubusercontent.com/assets/9251570/6143101/79078d26-b1e8-11e4-862d-c55ac3918a5e.PNG)
![number mislaigned](https://cloud.githubusercontent.com/assets/9251570/6143158/a08b1ace-b1e9-11e4-935e-c21d66f0dd58.PNG)

**Comment by gordonwoodhull** [comment]
I just tested this on 3 OS x 2 browsers, and didn't see it.  

I thought I had fixed this for Firefox in 586d01f98ad2e86b130a7df5ca4a60cc9072bc34. That was a week ago so it's unlikely this is just a version mismatch, but @sanketd11, please confirm you are still seeing this and lmk what OS and browser.

**Comment by sanketd11** [comment]
Yes , the issue still persists in firefox. I am working on ubuntu 12.04
This is also seen when we enable the source in view mode.

**Comment by gordonwoodhull** [comment]
I see it now.  It happens until any cell's edit mode is activated.

**Comment by gordonwoodhull** [comment]
there are still cases where this happens.  reopening
