### ISSUE TITLE
Overwrite cofirmation  message is missing while uploading same file multiple times

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1289]
While uploading any file through file upload div, if a file to be uploaded is already present then the overwrite confirmation message is expected that is currently missing 

![overwrite](https://cloud.githubusercontent.com/assets/9251570/6143310/8f62178e-b194-11e4-8389-e4ea3d9dbeff.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11!  Good catch.

Possibly due to change in error reporting.

**Comment by gordonwoodhull** [comment]
it was not seeing the error, due to changes in error handling, and thought it had succeeded
