### ISSUE TITLE
Find highlighting not working correctly

### ISSUE THREAD

**Issue by spenceatt** [att/rcloud#1292]
When I did a find or find/replace, I see inline HTML for highlights instead of highlights. See attached. Browser is Chrome 40.0.2214.111 m.
![find_highlight_not_working](https://cloud.githubusercontent.com/assets/6933057/6153451/9b2d9846-b1f2-11e4-9844-649356673dd2.PNG)

**Comment by spenceatt** [comment]
After a browser restart, this is working again.

**Comment by gordonwoodhull** [comment]
yes, this is a fixed bug
