### ISSUE TITLE
Cannot open find/replace with Ctrl-Alt-F

### ISSUE THREAD

**Issue by spenceatt** [att/rcloud#1293]
Earlier today, I saw find/replace with ctrl-alt-f, but now, it won't open. I see the find box only.

**Comment by gordonwoodhull** [comment]
it now uses the correct key on windows/linux, which is ctrl-H.  cf. #1212

**Comment by gordonwoodhull** [comment]
ctrl-F find, ctrl-H replace, that is

**Comment by gordonwoodhull** [comment]
@spenceatt, it's a very complicated little feature, please see if you can poke some holes in it!

**Comment by spenceatt** [comment]
Will do.
