### ISSUE TITLE
Running empty R cell asks run time inputs 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1298]
When an empty R cell is executed, it asks for run time input. The behavior of this input cell is as follows:
* This input cell execute the contents entered (only one R statement is executed)
* The code entered in this input window doesn't get saved in any cell 
*  Question mark is displayed at the place of line number

![empty1](https://cloud.githubusercontent.com/assets/9251570/6165307/e1837c7a-b274-11e4-8169-4b53bbf1b62a.PNG)

![empty2](https://cloud.githubusercontent.com/assets/9251570/6165309/e6fea5da-b274-11e4-98d2-d57a40f0bc7b.PNG)

This issue occurs only for the R cell. Execution of empty python and markdown cells throws error
* Python cell error
![empty3](https://cloud.githubusercontent.com/assets/9251570/6165488/59dee154-b276-11e4-8be8-24386aa07fc5.PNG)

* Markdown cell error
![empty4](https://cloud.githubusercontent.com/assets/9251570/6165498/78b02fde-b276-11e4-8e1e-8c51eb06b522.PNG)

**Comment by gordonwoodhull** [comment]
Odd.  @s-u, is there any way to avoid Rserve asking for input, or do we need to special case here?

**Comment by s-u** [comment]
The simple fix is to always append "\n" so that it is always a terminated expression.
