### ISSUE TITLE
Scroll bar should reset to top position when switched through page links in search div

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1300]
Steps to replicate:
* Search for any keyword that will show more than around 20 or more search results 
* Scroll down to the bottom for the first page of search results
* Switch to next or any other page link

for first page link

![scroll1](https://cloud.githubusercontent.com/assets/9251570/6167459/977ff026-b289-11e4-9b26-0b6bee1d942b.PNG)

for second page link

![scroll2](https://cloud.githubusercontent.com/assets/9251570/6167466/9e972258-b289-11e4-83a3-0fd34799dace.PNG)

It is observed that the scroll bar remains at the bottom 
I believe that the scroll bar should reset to top position when switched through the page links in search div

**Comment by gordonwoodhull** [comment]
I think this used to work.

**Comment by sanketd11** [comment]
The above issue is still unresolved for RCloud-2
