### ISSUE TITLE
Some errors are being reported twice

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1303]
Now that the cell is not getting improperly canceled, it is clear that some errors were already getting reported, and now they are reported twice.  As seen below, parse errors are okay but other errors are displayed twice because they are both output and error:

![image](https://cloud.githubusercontent.com/assets/1366709/6168517/0f0ad2b4-b294-11e4-89e3-e4732a50dbe8.png)

@s-u, what do we do here?  Not report the error as error-result, or not print it as a console.out?

**Comment by s-u** [comment]
Very good question. The problem is that we cannot easily eat up the error. So what I would do is to color all output in "console.err" red and only print the stack trace additionally if present (except for parse error messages which have to be printed since they are not evaluation errors).

**Comment by gordonwoodhull** [comment]
ah, console.err of course

**Comment by s-u** [comment]
awesome!
