### ISSUE TITLE
do not eat up the first newline in parse errors

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1306]
The first newline in parse errors is removed, resulting in incorrect indication of the error location.

![screen shot 2015-02-12 at 1 43 52 pm](https://cloud.githubusercontent.com/assets/2073427/6174538/5a09b752-b2bd-11e4-8d19-2c91f626d99e.png)

**Comment by gordonwoodhull** [comment]
ah, that's why!

**Comment by gordonwoodhull** [comment]
not removing newlines from parse errors

**Comment by gordonwoodhull** [comment]
![image](https://cloud.githubusercontent.com/assets/1366709/6175136/1dc18590-b2c2-11e4-977f-19622cd88a4e.png)
