### ISSUE TITLE
customization of navbar to include instance-specific links

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1313]
On our internal AT&T Research instance of RCloud, I would like the links to the RCloud Forum and a link to the RCloud documentation put back into the navbar on the right hand side (they used to be there).

These links are not appropriate for all instances of RCloud, so this should probably be a customize-able thing per RCloud instance.

The link to RCloud documentation was labeled “Help” before, but it would be better to change the label to something like “About” or “Doc” instead of “Help”, as this would prevent confusion with the existing R Help pane labeled "Help" on the left panel.

“Forum” would link to https://rcloud.research.att.com/forum

“About” or “Doc” would link to https://rcloud.research.att.com/rcloud_about.html
 
These are both internal AT&T web pages.

**Comment by prateek05** [comment]
This should be an internal package ?

**Comment by gordonwoodhull** [comment]
Most of the work is to create the extension point in the open-source RCloud, but I'll also create an internal package, or maybe just an internal configuration, for the links Gus mentions.

**Comment by gordonwoodhull** [comment]
Right now there is an extension point for the left "branding" area, and for the advanced menu, but not for the rest of the menu or for the main navbar buttons.  I'm not promising to get to the buttons for this release, but I'd like to.

**Comment by gordonwoodhull** [comment]
lucky issue - #1313 for release 1.3, filed on Friday the 13th.  

i am starting work on a feature branch, just in case the implementation is not so lucky...

**Comment by gordonwoodhull** [comment]
@s-u, do you have any objection to adding more rcloud.conf keys for this, in the style of `rcs.system.*` where actually a whole hierarchy is possible?

Straw man: 
```
rcs.menu.forum: 2000, link, Forum, https://rcloud.research.att.com/forum
rcs.menu.about: 3000, link, About, https://rcloud.research.att.com/rcloud_about.html
```

In the future, this could expand, where `link` could also be `menu` and then more sub-items could be added. But for now, just allowing customization through JavaScript and this way to add links in the tree.

**Comment by s-u** [comment]
Not at all, sounds good to me ... and yes, I'd love it, since I tend to blow away those unintentionally when they were patches ...

**Comment by gordonwoodhull** [comment]
Sorry Gus, there were too many bug fixes that had to happen this week; this will have to postponed.

**Comment by gordonwoodhull** [comment]
Updated comment above with new schema.

**Comment by gordonwoodhull** [comment]
This change may have ripple effects (for example, the logout link is now generated instead of hard-coded into the HTML, so it appears later) so I want this to get tested and go into 1.4 instead of a patch before then.

**Comment by gordonwoodhull** [comment]
https://github.com/att/rcloud/wiki/RCloud-UI-Extensions#navbar-menus
