### ISSUE TITLE
Resizing plots is constrained to one dimension

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1314]
Dragging any side of the plot performs a zoom-like resizing only, it is not possible to make a plot just wider or higher. E.g., dragging the right edge also changes the height instead of only increasing the width. As a side-effect all plots on the default device are always constrained to be square.

**Comment by gordonwoodhull** [comment]
Shift-drag. Should I reverse it so that shift-drag is constrained, and unmodified drag is unconstrained?

**Comment by s-u** [comment]
Yes, please

**Comment by s-u** [comment]
The constrained one does have an odd effect on the surrounding cells and is not very intuitive - in particular when you are dragging borders. When you use `<shift>` you know what you ask for so you know to expect such things.

**Comment by s-u** [comment]
BTW: the unconstrained resize is waaay cool :)

**Comment by gordonwoodhull** [comment]
Unfortunately it is only temporary and particular to that live device, but I think it's a great start.

**Comment by gordonwoodhull** [comment]
I had actually reversed the default here.  I guess I thought it was important not to mess up the aspect ratio, when in reality, the aspect ratio is usually wrong and you have to fix.

BTW, @s-u, you said
> The constrained one does have an odd effect on the surrounding cells and is not very intuitive - in particular when you are dragging borders

If you meant, "used to dragging borders", jQuery UI does support handles on all edges.  I just went with the default, which seems to be to only show the SE corner, but also allow dragging on the S and E edges.  

If you think more would be helpful/make the feature more obvious, there are styles and options for that.

**Comment by gordonwoodhull** [comment]
FIxed by e772b0583011330d0329893341da86c7f46958e0
