### ISSUE TITLE
use separate OOB for deferred results

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1318]
This is now trivial due to 6e1f196 - we use

```r
self.oobSend(list("html.out",unclass(x)))
```

in `rcloud.support/R/uuid.R:print.deferred_result` so it's as simple as changing the name of the OOB here and to add a handler on the JS side. All output is guaranteed to be flushed before the OOB so it can be inserted directly.

**Comment by gordonwoodhull** [comment]
+1
