### ISSUE TITLE
Testing in RCloud local: Change in position for 'upload to notebook' checkbox

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1328]
Previously the checkbox provided for option 'upload to notebook' was located right below the 'Choose Files' option. But now its position is changed as shown in screenshot

![file_upload](https://cloud.githubusercontent.com/assets/9251570/6203404/8b37eeb2-b546-11e4-8e0f-16838e2e34e3.PNG)

The above issue is not seen in RCloud-2

**Comment by gordonwoodhull** [comment]
Yes, I changed this purposely so that the dialog looks better at its minimum size, and takes up less space when expanded, as shown above.
