### ISSUE TITLE
Testing on RCloud local : 'plot()' function throws error in session div

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1329]
In RCloud local the plot function throws error in output div as well as in session div.

![plot](https://cloud.githubusercontent.com/assets/9251570/6203479/aa16018a-b54a-11e4-8206-7f9340274d69.PNG)

session div error

![plot_session_div](https://cloud.githubusercontent.com/assets/9251570/6203482/d0386e20-b54a-11e4-84ab-bdc8c721ec47.PNG)

**Comment by gordonwoodhull** [comment]
You need to update Cairo.  On the R command line, run

```{r}
install.packages('Cairo', repos=c("http://RForge.net"), type="source")
```
