### ISSUE TITLE
provide run time inputs in python code

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1334]
In python cell execution, if any of the statement in a code requires run time user inputs(e.g. raw_input()'), the execution remains stuck at that statement. The stop button remains enabled until the page reload

**Comment by gordonwoodhull** [comment]
@sisukapalli looked into this but it didn't make it into this release.

**Comment by gordonwoodhull** [comment]
@useless5771, as part of your Jupyter work, please look into how they do `input()`, `raw_input()`, etc. and see if you can hook it into the same UI handler we use for R stdin, e.g. `readline()`

**Comment by gordonwoodhull** [comment]
Implemented in RCloud 2.0
