### ISSUE TITLE
errors when resizing a plot too small

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1337]
The following error is thrown in session div, while resizing/rendering the plot

![error](https://cloud.githubusercontent.com/assets/9251570/6228787/2be294ee-b6d6-11e4-8bf4-c3f348c2c5fa.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11.

I can't reproduce this.  Do you always get this, or are there specific steps to follow? 

And I don't think this is it, but do you have the latest Cairo from rforge?

**Comment by sanketd11** [comment]
Following are the steps to replicate the issue:
1) Plot any graph 
![render1](https://cloud.githubusercontent.com/assets/9251570/6262889/e963754e-b832-11e4-84ce-1ec9a25fd6d1.PNG)

2) Try to minimize the graph to a smaller version in one step

![render2](https://cloud.githubusercontent.com/assets/9251570/6262891/ee3c73ae-b832-11e4-87c2-a44e3c3dfcdd.PNG)

after this step immediately the above error will be thrown in session div

I believe, I have latest Cairo from rforge. I have updated it from the link you provided in issue #1329

**Comment by gordonwoodhull** [comment]
Is it when you make the plot really, really small? I have seen some errors in that case.

Does it also happen on rcloud-5?

**Comment by sanketd11** [comment]
exact plot size cannot be measured but error is thrown in session div when plot size is reduced to slight less than 1/4th of the original plot size

In RCloud-5 I am getting the same errors as reported in issue #1329

**Comment by gordonwoodhull** [comment]
This error is harmless, so I'm disabling it but leaving the warning that goes with it, and restoring the previous div size.
