### ISSUE TITLE
should saving plots download them directly?

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1338]
Currently for pdf format, the plot images get downloaded on clicking save icon
While, for the rest of the formats ( namely png, svg and jpeg) it is opened in a new tab.

**Comment by gordonwoodhull** [comment]
Which browser are you using? Yes,  usually it should be saved, but there may be browser limitations.

**Comment by sanketd11** [comment]
I guess it is a problem with browser versions.
For chrome, the functionality is as expected. But there are issues with some versions of firefox.
For some firefox versions the images are getting downloaded and for some it is failing to do so.

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11. We don't support old firefox.  This is also a problem in Safari, but there is no known workaround.

Please [see FileSaver.js for detailed compatibility info](https://github.com/eligrey/FileSaver.js/).

If we ever fail to get an image at all, that's a bug.  Opening in another tab is not something we have control over.
