### ISSUE TITLE
Update installation page

### ISSUE THREAD

**Issue by martymcwizard** [att/rcloud#1340]
Please update (or optionally delete and reorganize github repo):
https://github.com/att/rcloud/wiki/Detailed-Installation-Overview

there is a link on how to raise on issue but it directs to cscheid
https://github.com/cscheid/rcloud/issues/new

whereas it should clearly link to /att/rcloud

then there is a comment

```This page is not kept up-to-date with current RCloud releases! ```

as well as at least one typo on the page.

We need to remove the statement and update the installation instructions and keep it current with releases OR just delete this if we want to use README for detailed instructions

```Please see the README in the soruces for the canonical installation instructions and refer to this file only for added detail to what is mentioned in the README. If you encounter conflicting information, README wins.```

**Comment by gordonwoodhull** [comment]
We made the warning less dramatic and it points to the correct installation instructions.  This page still contains some details which may be relevant, but the main install page should be used in most circumstances.
