### ISSUE TITLE
Please reconcile multiple INSTALL pages

### ISSUE THREAD

**Issue by martymcwizard** [att/rcloud#1342]
Please reconcile/reorganize among:

https://github.com/att/rcloud/blob/develop/INSTALL
https://github.com/att/rcloud/blob/develop/doc/INSTALL.md
https://github.com/att/rcloud/wiki/Detailed-Installation-Overview

**Comment by gordonwoodhull** [comment]
@s-u, @prateek05, what did we decide?  who is taking this on?

**Comment by gordonwoodhull** [comment]
(I am not qualified.  I avoid installing RCloud.)

**Comment by s-u** [comment]
Well, I have updated `doc/INSTALL.md`. I assume that is the canonical source. The Wiki was intended as a stopgap measure and it may make sense to include advanced setup tips there, but that is not the canonical documentation - we should have just one :). I didn't know about quite a few things that Marty is mentioning :)

**Comment by prateek05** [comment]
If you can tell me what structure should be like to address Marty's concern of duplication perhaps we can leverage help from Spence and his existing work of Install Documentation to put them in the right place

**Comment by gordonwoodhull** [comment]
IMO the important points are:
 - one set of install documents, not N
 - platform independent section, and whatever instructions are platform-specific should be separate and clearly marked.  Mostly it seems that we have prereqs that must be installed through `apt-get`, `brew`, or whatnot.

**Comment by gordonwoodhull** [comment]
Maybe it is just a matter of reconciling doc/INSTALL.md with the instructions that Spence came up with, and deleting (with a vengeance) all the random other install docs that keep proliferating.

**Comment by gordonwoodhull** [comment]
Alright, I gave up and fixed this myself.

**Comment by gordonwoodhull** [comment]
I hope.
