### ISSUE TITLE
comment notification not working on ATT Research instance

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1345]
On the Research intance of RCloud, I do not appear to receive notebook comment notifications on notebooks to which I have subscribed to comments.

I have verified that my email address in the Research GitHub is correct.

Not sure if this is related, but some possibly useful info:

For the GitHub v3 API, a this link works fine (as referenced in issue https://github.com/att/rcloud/issues/900):
      https://api.github.com/users/gordonwoodhull (note that this is the public GitHub).

I think we're running v2.1.1 GitHub on the Research instance.  A similar link to above for the Research GitHub instance does not work.  Is that a possible cause of the lack of notifications?

**Comment by s-u** [comment]
We don't have our internal instance setup to send mail. If you ask me it's a horrible idea. Please use internal channels for questions about internal deployment.

**Comment by gordonwoodhull** [comment]
There is a bug here: that the option was displayed when the feature was not enabled, #1347
