### ISSUE TITLE
Error while loading RCloud-2

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1348]
Observing this issue since 18 Feb 2015 11:30 am IST : 
When we tried to load RCloud-2 using the link 'https://rcloud-2.research.att.com/login.html' it asks for att research credentials. Even after adding the valid credentials it shows following error

![rcloud_2_err_1](https://cloud.githubusercontent.com/assets/9251570/6243532/3c726cd8-b769-11e4-9ad3-037682062dba.PNG)

console error for the same issue

![rcloud_2_err](https://cloud.githubusercontent.com/assets/9251570/6243534/4125bc1c-b769-11e4-8663-278fb9e9192b.PNG)

**Comment by gordonwoodhull** [comment]
Please don't report problems with particular instances in github unless it indicates a bug in the software. Email us about those instead. Thanks!
