### ISSUE TITLE
Plots are not displayed completely 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1353]
Testing on branch 'release/1.3.1'

Some plots like the following are not generated fully.
This is the plot which is generated
![1 before_resizing](https://cloud.githubusercontent.com/assets/9251570/6264515/ac341b48-b84a-11e4-84b1-f6dec3b5dd8b.PNG)

As we go on stretching it, the remaining plot becomes visible

![middle](https://cloud.githubusercontent.com/assets/9251570/6264524/bb858500-b84a-11e4-9bc1-014790a05569.PNG)
![1 after_resizing](https://cloud.githubusercontent.com/assets/9251570/6264526/bfa206fe-b84a-11e4-8bd0-7898a4a70e04.PNG)

The code we used which generates both the graph and legend with it:

cars <- c(1, 3, 6, 4, 9)
colors <- c("white","red","blue","yellow","black")
car_labels <- round(cars/sum(cars) * 100, 1)
car_labels <- paste(car_labels, "%", sep="")
pie(cars, main="Cars", col=colors, labels=car_labels,
   cex=0.8)
legend(1.5, 0.5, c("Mon","Tue","Wed","Thu","Fri"), cex=0.8, 
   fill=colors)

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11, good find.  This seems to be an issue with core R graphics, as I can reproduce this by pasting this on the R command line - the initial window that pops up is square and missing the legend, but I can resize it to find the legend.

@s-u, you told me that the aspect ratio is determined by the client, not by R.  There is nothing we can do here, right?

**Comment by s-u** [comment]
This is an user error - your'e placing the legend specifically outside of the plot region (the coordinates are [0,1] and you put it at 1.5)
