### ISSUE TITLE
Joining two cells in non-editable mode overlaps with cells below

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1354]
Testing on branch 'release/1.3.1'

Steps to replicate:
1) Have two cells which are in non-editable/executed mode
![non-editable](https://cloud.githubusercontent.com/assets/9251570/6264888/0b29403a-b84e-11e4-9a5f-80a51a75611e.PNG)

2) Join the two cells
![overlap](https://cloud.githubusercontent.com/assets/9251570/6264893/1d09e8ea-b84e-11e4-93ac-b3d370c71d74.PNG)

the resultant cells overlaps with the cell below. In this case, two lines of the code are hidden behind cell 3

This is the actual code seen when clicked on it
![actual](https://cloud.githubusercontent.com/assets/9251570/6264906/3fbc6e80-b84e-11e4-9d29-a4811acb1379.PNG)

This issue is worse in firefox

![firefox](https://cloud.githubusercontent.com/assets/9251570/6265067/ea4737a8-b84f-11e4-8377-00c503afe8a6.PNG)
Here the command prompt is overlapping the cell from between.

**Comment by gordonwoodhull** [comment]
Not able to reproduce this one either.  Tried on (Chrome, Firefox) x (OSX, Ubuntu, Windows) with notebooks up to thousands of lines.

**Comment by sanketd11** [comment]
This is tested on Ubuntu 12.04 on chrome as well as firefox.
Firefox is the worse of the two. 
This issue also exists on Rcloud-5.

**Comment by gordonwoodhull** [comment]
I was finally able to reproduce this, thanks to a live demo from @sanketd11 and @Arko2013.

The issue arises from cells that are longer than 30 lines, where the edit mode is shorter than the full code which is displayed when not in edit mode.  We were setting the height for the outer div which contains both the editor and the non-interactive text and ending up in that strange html behavior where the displayed size is larger than the layout size.

Moving the height adjustment to the ace div seems to have fixed this.

**Comment by gordonwoodhull** [comment]
Actually, to be clear, I could reproduce #1352, but I believe this is the same bug.

**Comment by gordonwoodhull** [comment]
Exact steps to reproduce:

 1. create notebook with one cell > 30 lines
 2. split the cell anywhere
 3. toggle the first cell out of edit mode
 4. join the cells
 5. the prompt appears after the 30th line of the new combined cell
