### ISSUE TITLE
clicking on the notebook that was open before a readonly one, edits the title

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1357]
Steps to replicate issue:
1) Load any read only notebook
2) Then click on any notebook name from 'My notebooks'  in 'Notebooks' div

It is expected that the clicked notebook should get loaded instead that notebook name becomes editable

**Comment by gordonwoodhull** [comment]
Not *any* notebook name, but the very last notebook you had open before clicking on the read-only notebook.  Please try to narrow in on these issues, because for a moment I thought I couldn't repro... but then I remembered #991 and figured it had to be a title that was previously editable.

**Comment by gordonwoodhull** [comment]
Looks like it wasn't making the last notebook uneditable because it wasn't making the readonly one editable. So it stayed editable, trapping the mouse click.
