### ISSUE TITLE
use line breaks in stack traces?

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1360]
I find the `<-` we are using to concatenate error traces very hard to read when the stack trace is long.

Furthermore, it is inaccurate, because there are often whole blocks of code split across a vector by line.  For example, the current stack trace I'm looking is this one (on the js side)

```
["strsplit(exttype, " *, *")", "tolower(strsplit(exttype, " *, *")[[1]])", 
"FUN(c("rcloud.viewer", "rcloud.enviewer", "rcloud.notebook.info", ", ""rcloud.logo", "rcloud.iip")[[1L]], ...)", 
"lapply(addons, function(x) {", "    exttype <- packageDescription(x, "RCloud-Extension")", 
"    exttype <- tolower(strsplit(exttype, " *, *")[[1]])", "    if (length(intersect(session.type, exttype))) ", 
"        suppressWarnings(suppressMessages(require(x, character.only = TRUE)))", "})", 
"rcloud.reset.session(session.type)", "fun(...)"]
```

Joining it with `<-` yields

```
strsplit(exttype, " *, *") <- tolower(strsplit(exttype, " *, *")[[1]]) <- FUN(c("rcloud.viewer", "rcloud.enviewer", "rcloud.notebook.info",  <- "rcloud.logo", "rcloud.iip")[[1L]], ...) <- lapply(addons, function(x) { <-     exttype <- packageDescription(x, "RCloud-Extension") <-     exttype <- tolower(strsplit(exttype, " *, *")[[1]]) <-     if (length(intersect(session.type, exttype)))  <-         suppressWarnings(suppressMessages(require(x, character.only = TRUE))) <- }) <- rcloud.reset.session(session.type) <- fun(...)
```

which is somewhat bogus, because R clearly meant to report

```
strsplit(exttype, " *, *")
tolower(strsplit(exttype, " *, *")[[1]])
FUN(c("rcloud.viewer", "rcloud.enviewer", "rcloud.notebook.info", 
"rcloud.logo", "rcloud.iip")[[1L]], ...)
lapply(addons, function(x) {
    exttype <- packageDescription(x, "RCloud-Extension")
    exttype <- tolower(strsplit(exttype, " *, *")[[1]])
    if (length(intersect(session.type, exttype))) 
        suppressWarnings(suppressMessages(require(x, character.only = TRUE)))
})
rcloud.reset.session(session.type)
fun(...)
```

**Comment by gordonwoodhull** [comment]
@s-u, I am guessing you might have done this because bluebird seems to be chopping the error at the first line break when it creates the stack trace.  maybe we should fix that instead.

**Comment by gordonwoodhull** [comment]
i am not sure if it's a good idea, but upgrading bluebird does fix this [apparent bug in their error handling](https://github.com/petkaantonov/bluebird/releases/tag/v2.2.1)

**Comment by s-u** [comment]
Agreed - the stack traces in the output should use \n. As you said, this was to work around the issue of BB only using the first line in the red area..

**Comment by gordonwoodhull** [comment]
cool, lucky guess then. 

upgrading bluebird did uncover one other promise bug, so i guess it is worthwhile.  (but not sure if it is a great idea right before this hotfix release.)
