### ISSUE TITLE
Join cells option present for the top most cell

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1363]
Testing on branch 'release/1.3.1'

When an existing notebook is loaded, the join cells option is present for the top most cell.
![join cell](https://cloud.githubusercontent.com/assets/9251570/6318567/9fafe6b4-babf-11e4-8180-ed6767a30933.PNG)
This issue is rectified when a new cell is created at the top or when a cell is moved to the top position.
The problem occurs only when an already existing notebook is loaded.

**Comment by shaneporter** [comment]
PR #2188.
