### ISSUE TITLE
Show source for Markdown cells in view.html

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1364]
Testing on branch 'release/1.3.1'

In view.html, Enabling 'Show Source' doesn't show the code for markdown cells
![no_source](https://cloud.githubusercontent.com/assets/9251570/6318962/0354f3b0-bad1-11e4-8102-e8a4792be01c.PNG)

**Comment by s-u** [comment]
I'd argue that this is expected - source refers to source code, but in Markdown the source code is embedded in the markdown and thus governed by options set in the Markdown itself instead (i.e., the above example doesn't actually have any source code that's why nothing is seen).

**Comment by gordonwoodhull** [comment]
I agree. Showing the source along with Markdown output is redundant.
