### ISSUE TITLE
infinite loop cannot be stopped

### ISSUE THREAD

**Issue by spenceatt** [att/rcloud#1367]
Hi --

This infinite loop cannot be stopped via the stop icon on the header when entered in a command prompt.

i=10
while(i==10){i=10;}

**Comment by gordonwoodhull** [comment]
That is correct. We do not yet support preemptive stopping of cells, as compute separation did not make it into this release. You still have to reload the page to get out of this.

**Comment by spenceatt** [comment]
Does the stop button serve any purpose currently?

**Comment by gordonwoodhull** [comment]
Yes, it will stop later cells but it cannot stop the current cell.  

> Non-preemptive stop. Although you still can't cancel a long-running cell, you can stop any later cells from running, by pressing the Stop button.

**Comment by spenceatt** [comment]
Oh, I see. If a cell hasn't run yet, the stop button will prevent it from running. Nevermind.

**Comment by gordonwoodhull** [comment]
It isn't all that useful but it is better than nothing.

**Comment by gordonwoodhull** [comment]
This is the purpose of compute separation, tagging for next release.

**Comment by gordonwoodhull** [comment]
this is what compute separation is all about
