### ISSUE TITLE
view.html does not work for tagged version for anonymous user

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1369]
The shareable links (view.html, Notebook.R, mini.html, shiny.html) for history versions of any published notebook, are not working for a user who is not logged into RCloud.

following is the console error:

![console](https://cloud.githubusercontent.com/assets/9251570/6349995/00a12f22-bc56-11e4-8738-cc6dc7eaa198.PNG)

**Comment by gordonwoodhull** [comment]
I'm not able to reproduce this with the current develop branch. @sanketd11, could you try again?

**Comment by sanketd11** [comment]
I am able to reproduce this issue on both RCloud-2 and RCloud-local instance only for tagged history version of any published notebook. If we load the shareable link for history version using version ID e.g.'http://127.0.0.1:8080/mini.html?notebook=9aeef731e366f052dfef&version=439b4cc7552065ce22e93df16e0f5f2cf23fe51b' then we are able to access the shareable link as anonymous user. However if we use tag name instead of version e.g. 'http://127.0.0.1:8080/mini.html?notebook=9aeef731e366f052dfef&tag=tagg', then we are unable to access that shareable link as anonymous user
following are the steps to replicate:
1 Tag any history version of any published notebook
2 Click on the shareable link option for that tagged history version and copy the url
3 Click on the Logout option
4 Try to load the copied url 

I also observed some strange behavior in RCloud-2. The shareable links are also accessible for anonymous user if we provide version= tagname e.g. 'https://rcloud-2.research.att.com/mini.html?notebook=f83a7a319bddfe7fa44f&version=tag1'

**Comment by gordonwoodhull** [comment]
Ah! A tagged version! That was the key information I was missing. I guess I could have deduced it from the error message, but it would help to include these details in the report/title as well. Retitling.

**Comment by gordonwoodhull** [comment]
I'm not sure what you mean here:

> I also observed some strange behavior in RCloud-2. The shareable links are also accessible for anonymous user if we provide version= tagname e.g. 'https://rcloud-2.research.att.com/mini.html?notebook=f83a7a319bddfe7fa44f&version=tag1'

Are you reporting a different issue, or just saying that it does work with version hashes? Could you open a separate issue if it's a different issue? 

Thanks @sanketd11!

**Comment by sanketd11** [comment]
* Apart from view.html, Issue #1369 is also replicable for shiny.html, mini.html, and notebook.R
* Will file separate issue for this. 
![capture](https://cloud.githubusercontent.com/assets/9251570/8109823/7e7d8142-1076-11e5-9c2f-e6fe6be50155.PNG)
