### ISSUE TITLE
coord_map() not found in shiny

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#1384]
I'm trying to do a coord_map in shiny, but I just get a "coord_map not found".   I'm using it with a ggplot map (actually through choroplethr).    Should this work?   It works fine in a regular notebook.
I have a library(mapproj) in both notebooks.

**Comment by gordonwoodhull** [comment]
Sorry for the slow response. I'm not able to repro this - if you're still having trouble, could you send an example notebook.
