### ISSUE TITLE
Python integration breaks with IPython 3.0

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1385]
@sisukapalli @martymcwizard  
If we use pip to install IPython now. It installs the newer 3.0

> > > from IPython.kernel.blocking.channels import BlockingShellChannel
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: cannot import name BlockingShellChannel
> > > from IPython.kernel.blocking.channels import ZMQSocketChannel

The python integration needs to update to use the new ZMQSocketChannel ofcourse with a fallback to BlockingShellChannel since RHEL and Ubuntu ship still the pre 3.0 release of ipython

**Comment by gordonwoodhull** [comment]
FWIW I was able to get past this on OSX by uninstalling ipython 3.* and then 

```
sudo pip install ipython==2.4.1
```

**Comment by gordonwoodhull** [comment]
I think we can skip IPython X.0 and go to Jupyter #1378

**Comment by gordonwoodhull** [comment]
This seems to be incorrect. Eugene has run IPython up to 5.9 or so. 

I don't know about the original problems with ZMQSocketChannel.
