### ISSUE TITLE
autosave causes long cells to scroll

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1386]
cells over 30 lines have internal scrolling.

whether or not they are already scrolled, autosave cause the scrolling to change. cursor is left in the same line but that line has been scrolled up a bunch

**Comment by anatoliyg** [comment]
what would be the expected behavior here? Should autosave not be triggering any scrolling?

**Comment by gordonwoodhull** [comment]
right, autosave should have no effect on the notebook or asset ui at all. 

i think cells are getting updated because of the classic MVC paradox of seeing your own updates, or something. there are probably a number of ways to fix this.

**Comment by anatoliyg** [comment]
ok. Could you point me in the general direction the code for this is in?
cellView.js?

On Thu, Apr 23, 2015 at 3:59 PM, Gordon Woodhull <notifications@github.com>
wrote:

> right, autosave should have no effect on the notebook or asset ui at all.
>
> i think cells are getting updated because of the classic MVC paradox of
> seeing your own updates, or something. there are probably a number of ways
> to fix this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/att/rcloud/issues/1386#issuecomment-95701821>.
>



-- 
Anatoliy

**Comment by gordonwoodhull** [comment]
Saving (accumulating changes and sending them over the wire) is implemented in the notebook controller. The direct bug here is in the cell view, yes. There is already some code to restore the cursor position there. That might be improved. Or there may be a more systemic way not to update the text when it hasn't changed. I am not 100% sure why this is happening.

**Comment by gordonwoodhull** [comment]
Taking this because it's an annoyance that users have complained about, and I want to be sure it gets in.
