### ISSUE TITLE
Notebook not deletible if user prevents confirmation dialog

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1388]
While deleting notebooks successively , it shows alert message with check box to prevent this alert message.When user checks it and goes on deleting the notebooks, the notebook is not getting deleted instead it is opening that particular notebook.Once user refreshes the tab and clicks on delete then that particular notebook is getting deleted
![deleting_notebook](https://cloud.githubusercontent.com/assets/10941328/6818857/b8ccab38-d2dd-11e4-80eb-966fea6c5852.PNG)

**Comment by gordonwoodhull** [comment]
Likely the browser throws an error in this case, and we don't stop propagation, so it percolates into a click on the parent element, the notebook entry.

**Comment by gordonwoodhull** [comment]
I guess we have no choice but to log an error to the session pane, since we don't want to disable the confirmation dialog. (As much as some of us would not like there to be a confirmation dialog at all.)

**Comment by gordonwoodhull** [comment]
It is not opening the notebooks for me, but it is also not showing the dialog or deleting the notebooks.

I don't think there is anything we can do about this (by browser design). The user will have to reload the page.

There is no way to detect this has happened:

http://stackoverflow.com/questions/11571015/how-to-detect-prevent-this-page-from-creating-additional-dialogs
