### ISSUE TITLE
line breaks lost when copying and pasting from non-edit mode cells

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1389]
Copy the contents from the cell which is in non editable mode, and paste it in any where (in new notebook cell  or in assets div) the way we copied, it is not getting pasted in the same manner

![copy-1](https://cloud.githubusercontent.com/assets/10941328/6818956/611f837c-d2df-11e4-93aa-69947b45ee71.PNG)

![paste-2](https://cloud.githubusercontent.com/assets/10941328/6818980/b968b666-d2df-11e4-9281-0d90a64df310.PNG)

**Comment by gordonwoodhull** [comment]
Has anyone seen this on OSX or Windows? I am only able to repro on Linux.

**Comment by gordonwoodhull** [comment]
On Firefox, it looks like it only copies the first line...

**Comment by prateek05** [comment]
I can confirm on OS X Chrome... I think even @holyguster was experiencing this
this issue is not with the asset pane. It happens when I paste copied content from a cell in 'edit mode' to some other applications itself.

**Comment by gordonwoodhull** [comment]
Aha, I finally narrowed in on it. This happens when selecting within a single cell. If multiple cells are selected, the line breaks are preserved (!)

**Comment by gordonwoodhull** [comment]
okay, i got this one. opening a separate issue for the firefox bug
