### ISSUE TITLE
Unable to drag and drop multiple files in asset div

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1400]
User is not able to drag multiple files and drop it, while file uploading in 'Asset div'. This issue can be replicated on both firefox and chrome browser.

**Comment by gordonwoodhull** [comment]
I'm unable to repro. @Prateek032, are you still seeing this? Is this on Windows?

**Comment by Prateek032** [comment]
This issue seems to be resolved on both RCloud-2 and RCloud-local instance.

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032!
