### ISSUE TITLE
left margin of inactive markdown is crazy huge 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1401]
When notebooks div and assets div are minimized the, the code lines in markdown cell don't get shifted as seen in the screen shot below
 
![markdown](https://cloud.githubusercontent.com/assets/9251570/6920026/e5c1b48e-d789-11e4-9b9c-ca4ecfdbc3ce.PNG)

**Comment by prateek05** [comment]
@sanketd11 @gordonwoodhull  Hi Sanket can you change the title and remove gitgist I could replicate the same in the github version. It's from the UI end. Gitgist is merely a notebook content backend. I would be surprised if any UI formatting issues would tie specifically to it.
