### ISSUE TITLE
empty Python cell hangs on error

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1403]
1. Create a new notebook or load python notebook which contains minimum 2 to 3 cells.
2. Click on Run all
3. after executing, now add/insert new blank python cell in between the present cells
4. Again click on Run all 
5. When empty cell starts to execute, immediately click on 'Stop'.
It keeps on executing that current cell, until and unless we reload the page

**Comment by gordonwoodhull** [comment]
I find that it's not necessary to press stop - RCloud displays the error ("None must be a string") and then seems to be hung processing the error. With compute separation, it is possible to terminate this processing, and then the error with stack trace displays to the session pane.
