### ISSUE TITLE
ERROR FROM R SERVER: 127 65538 127 16

### ISSUE THREAD

**Issue by Rutishauser** [att/rcloud#1407]
I am getting the error ERROR FROM R SERVER: 127 65538 127 16 (Aw, shucks)
when I install RCloud to Unumtu linux.  I tried the installation as described in INSTALL.md
on 2 different machines (under Ubuntu "saucy" and "utopic") with the same result.

The installation of R (r-base-dev) goes without errors. Then, when installing RCloud,
I get the error that "/usr/lib/R/site-library" is not writable, and I allow write access to
that directory.

My computer does not have a FQDN, and I am trying to use "127.0.0.1"
I tried it both, as "Host" and as "Cookie.Domain"

Any help will be appreciated.

**Comment by Rutishauser** [comment]
I have defined a host "rcloud.domain.com" as 127.0.0.1.  Nothing changed. 
The authentication seems fine. I am redirected to http://rcloud.domain.com:8080/edit.html
with the same error message.  My rcloud.conf is the following.

`Host: rcloud.domain.com`
`cookie.domain: rcloud.domain.com`
`github.client.id: a4f649cc63a1ecdbc9bd`
`github.client.secret: ...`
`github.base.url: https://github.com/`
`github.api.url: https://api.github.com/`
`github.gist.url: https://gist.github.com/`
`rcs.redis.host: 127.0.0.1:6379`
`#gist.backend: gitgist`
`#gist.git.root: ${ROOT}/data/gists`
`rcs.engine: redis`
`solr.url: http://127.0.0.1:8983/solr/rcloudnotebooks`
`rcs.system.config.addons: rcloud.viewer, rcloud.enviewer, rcloud.notebook.info`
`rcloud.languages: rcloud.r, rcloud.python, rcloud.rmarkdown`
`#smtp.server:xxxxxxxxxxxxx`
`#email.from:donotreply`

Do I need to run `sh scripts/fresh_start.sh` as "root" ?

**Comment by Rutishauser** [comment]
In the environment (Ubuntu + Chrome)  have the error (in JavaScript console) 
`Failed to load resource: the server responded with a status of 404 (Code 404)`
'http://rcloud.domain.com:8080/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
`edit.html:301 Uncaught ReferenceError: MathJax is not defined`

**Comment by Rutishauser** [comment]
Have downloaded MathJax manually. Now can see another error.
`pre-init post_error: ERROR FROM R SERVER: 127 65538 127 16 [object ArrayBuffer]Reconnect`
What does this mean?

**Comment by prateek05** [comment]
You should really go in the below order. 
scripts/bootstrapR.sh   -- This would have got you mathjax since you don't have it I am assuming you didnt run it. 
scripts/build.sh
And then finally scripts/fresh_start.sh

**Comment by s-u** [comment]
The problem is an old version of Rserve which lacks `Rserve.eval` so all R evaluations fail (127=eval error). RForge.net had a build of another Rserve branch in the the repo which was too old, but it should be back to the correct one now. If in doubt check that you have Rserve 1.8-2 or higher.

**Comment by gordonwoodhull** [comment]
Root problem is that bastard Detailed Installation Overview wiki page. I guess we should pull anything out that is not in INSTALL.md, and delete it.

**Comment by Rutishauser** [comment]
Just a couple of tailing questions.
Shall I stop RCloud as "scripts/shutdown.sh" being a user?
Shall I start RCloud as "scripts/fresh_start.sh" or "conf/start" ?
Should I start it as a user or the root?
Does it matter from what directory I start it?
Also, do I need to start /work/rcloud/services/SessionKeyServer/run & ?

**Comment by prateek05** [comment]
It really depends on the kind of deployment. 
I am going to make a big assumption that since you have a Session Key Server run your deployment intention is that of multiple users sharing the same environment. 
Below if the Assumption is True:
  1) You should do a graceful shutdown using scripts/shutdown.sh it keep s a track of the PPID in run
     1.1) If the PID is owned by root the script does check you have super cow powers and if you do it ll invoke them to shutdown using the privileged powers
  2) Yes root for starting rcloud
      2.1) fresh_start has some checks and chains to conf/start
      2.2) If your brave and understand the checks initiate from conf/start itself. 
  3) Multi-user environment start as user. Root is for multi-user sharing the same instance. 
 4) You can have it any directory but as of today it matters where you start it from. 
    4.1) As of today we keep track of "ROOT" variable as `pwd` and then build up our relative paths from "ROOT"
5) SessionKeyServer yes if multiple user or you plan to use any of SKS services. For multi-user yes for maintaining exec tokens.

**Comment by prateek05** [comment]
@s-u Shouldn't the package dependency move from -1 to -2 for  Rserve (>= 1.8-1) in rcloud.support. 
Honestly I have been bitten by version mismatch before that I have made it a practice to --mk-dist before installation.

**Comment by s-u** [comment]
Well, 1.8-2 didn't exist until today to flag this specifically, 1.8-1 is sufficient except that there may be different branches of 1.8-1 floating around while 1.8-2 is now only on CS, so you know that you won't get any other branch. Eventually, everything will merge into master and I do expect to require 1.8-2 for RCloud 1.4.

**Comment by Rutishauser** [comment]
Thank you.  I have fixed my other computer with the suggested command.
`install.packages('Rserve',,'http://www.rforge.net/')`
