### ISSUE TITLE
Display the view expression in 'Dataframe' panel

### ISSUE THREAD

**Issue by prateek032** [att/rcloud#1409]
Display the respective data frame names under 'Data frame' div. As we can see them under workspace div.
currently we have data frame's names under workspace div,
![workspace](https://cloud.githubusercontent.com/assets/10941328/7039419/8bf749e4-dddf-11e4-95c9-45b0147a8de7.PNG)

but when user opens the respective data frame, it is not displaying the respective data frame name.

![work](https://cloud.githubusercontent.com/assets/10941328/7039468/fdded4a0-dddf-11e4-863f-0c49cb2d5631.PNG)

**Comment by gordonwoodhull** [comment]
Note, in general it might not be a variable name, it could be an arbitrary expression. I'm sure R is fine with this, but we'll need to test it.

**Comment by gordonwoodhull** [comment]
Fixed with the new implementation of the data frame viewer in RCloud 1.9
