### ISSUE TITLE
suppress warnings when loading plugins that RCloud needs but my notebook does not

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1411]
Gotten complaints from a user about the session pane opening up and saying "loading required package: rmarkdown" every time they open a new Chrome window and edit a notebook.  (Side note: Interestingly, I do not see this on Chrome/Windows or Chrome/Mac.  I'll find out what OS this user is running.)

This annoys the user because their notebook doesn't have any rmarkdown cells, and they don't know why they see that message pertaining to rmarkdown.  Also, the message pops open the right-hand pane, which they immediately then minimize to get maximal screen real estate for the center pane.

Would it be possible to suppress warnings when RCloud is loading plugins that the user's notebook hasn't demanded?

**Comment by gordonwoodhull** [comment]
Yes, there should not be warning messages for extension our language packages.

**Comment by s-u** [comment]
Is this still actually an issue? I cannot replicate it on devel ...

**Comment by holyguster** [comment]
Looks like this is fixed to me, I cannot repro on develop.
