### ISSUE TITLE
Bokeh not functioning as expected

### ISSUE THREAD

**Issue by prattatx** [att/rcloud#1420]
http://ec2-54-172-12-188.compute-1.amazonaws.com/edit.html?notebook=082b5d9202eaffb22963

@prateek05 @gordonwoodhull

**Comment by prattatx** [comment]
The first cell runs and creates graph, but continuously "spins". Other two cells run but never produce viz.

**Comment by gordonwoodhull** [comment]
@prattatx, does this refer to rbokeh? I'm not sure when we will support python bokeh but rbokeh does now via the htmlwidgets support in RCloud 1.6.

**Comment by prattatx** [comment]
Awesome, thanks. I'll try it again!

**Comment by gordonwoodhull** [comment]
@prattatx, did you have a chance to try out rbokeh? As I said above, we don't have any current plans to support bokeh on Python, but rbokeh is now available in RCloud 1.6, which was deployed over the past couple weeks.

**Comment by prattatx** [comment]
@gordonwoodhull, hey, I did some minor testing of it. Looks good!
