### ISSUE TITLE
RCloud-2: Import External notebooks feature not working

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1422]
When we try to import any external notebook using "Import External Notebook" option present in Advance drop down menu, the corresponding notebook doesn't get imported. Following error message is thrown in session div 

![import](https://cloud.githubusercontent.com/assets/9251570/7343455/bcb5371c-ec8f-11e4-859f-97de6872f1a7.PNG)

The above issue is also replicated in proxified RCloud instance. However in local RCloud instance it's working as expected.

**Comment by gordonwoodhull** [comment]
I think we determined this was because of the different github instances. The notebook id should match the source repo specified at the top of the Import External Notebooks dialog.
