### ISSUE TITLE
Search functionality fails to search special characters

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1429]
When user enters special characters in comments/cells and tries to search that keyword. It is not displaying any results instaed it is displaying 'No results found'.

![search_special](https://cloud.githubusercontent.com/assets/10941328/7468671/01e9d87a-f329-11e4-896a-24e02d2db0dd.PNG)

**Comment by gordonwoodhull** [comment]
I think this is probably because you aren't following the lucene syntax for escaping special characters - could you please check?

http://lucene.apache.org/core/3_5_0/queryparsersyntax.html

**Comment by gordonwoodhull** [comment]
In particular, the last section specifies that a few of those characters must be preceded by a backslash, and the second section specifies that quotes are for grouping words together in a phrase (and probably don't help with special characters).

**Comment by gordonwoodhull** [comment]
I'll mark this as a duplicate #521 easier access to lucene documentation. Pity their syntax is so difficult, but I don't think we can fix that without tying ourselves in knots.
