### ISSUE TITLE
compute separation: all output from system() is eaten

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1430]
When we execute any shell script from assets div using 'rcloud.execute.asset' in R cell, all the console outputs from shell script are saved in R variable. But in this instance the "character(0)" is returned in R variable.

![assetshell](https://cloud.githubusercontent.com/assets/9251570/7489518/a02fcbf8-f3a5-11e4-85aa-c0400cad05ef.PNG)

**Comment by s-u** [comment]
More correctly `system(..., intern=TRUE)` doesn't yield any result:

```r
> system("echo foo", TRUE) 
character(0)
```

**Comment by gordonwoodhull** [comment]
@s-u, this seems rather serious. Any chance you can fix this for the release Tuesday?

**Comment by s-u** [comment]
Should be now fixed by combination of s-u/Rserve@1f505a0 and 8b45501. Forwarding will be enabled after forking and Rserve supports pass-through of the forwarding descriptor in OCAP iteration mode even if R input handlers are not active.

**Comment by s-u** [comment]
For the record, input was collected and sent to the trigger FD, but the compute process was only listening on the input (QAP) descriptor thus ignoring forwarding FD.

**Comment by gordonwoodhull** [comment]
Thanks @s-u!
