### ISSUE TITLE
keyboard shortcut for creating new cell and navigating between cells

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1439]
I was asked if this was something on the roadmap.  Figured I'd open an issue to discuss.

The specific ask was if there is a shortcut key combo for (1) creating a new cell, and (2) moving cursor focus to next/previous cell.

For (1), things to consider:
 - where would the new cell be created?  at the end of the notebook, below the current cell, above the current cell?  Maybe different key combo for each, or does that get to complicated?
 - what type of cell would be created?  use the type setting for the terminal cell, or use the type setting for the current cell?

For (2) and (3), I would imagine that the UI would treat the same as if the user clicked on the cell; if not already in edit mode, navigating to a cell would cause the cell to go into edit mode.

**Comment by shyamram** [comment]
I was looking for keyboard short cut to execute a cell. Is there one? If not, can that be added?

**Comment by gordonwoodhull** [comment]
To execute the current cell, press alt-enter. To create a new cell from the current selection or live, press ctrl-enter (or cmd-enter).

**Comment by shyamram** [comment]
thank you.

**Comment by gordonwoodhull** [comment]
I am in favor of this feature, because the keyboard is faster (and not having to switch between mouse and keyboard is even faster).

I want to avoid religious wars about what the keys should be, so if @s-u knows of equivalents in the R world, we should use them. But I think it's kind of wide open since the notebook/cell interface is pretty new.

IPython uses emacs-like ctrl-m prefixes, [so that's right out](http://ipython.org/ipython-doc/1/interactive/notebook.html#keyboard-shortcuts). But it's interesting to see what commands they have found useful.

I think there should be goto-last,goto-next, insert-after, insert-before, and goto-prompt (since that already inserts at end). I also think there should be delete-last, for folks using the command prompt and getting frustrated by all the cells being created. I don't yet have an opinion what the keys should be.

**Comment by gordonwoodhull** [comment]
Not getting to this feature for 1.4. It isn't hard but it needs to be spec'd out because there are potentially very many keys.

**Comment by shaneporter** [comment]
I was using IPython today, and noticed that:

- keydown on last row of current cell focuses on line 1 of next cell (or prompt);
- keyup on first row of current cell focuses on last line of previous cell.

**Comment by gordonwoodhull** [comment]
Hmm, that may work. Of course right now we use the same behavior on the prompt for command history, so it won't be symmetric. I wonder what others think of this idea.

Thanks for calling attention to this issue, it's a vital part of #300.

**Comment by shaneporter** [comment]
Ah yes - the inter-cell hopping should be restricted to cells in that case. The prompt is not invited to that functional party.

**Comment by s-u** [comment]
The special case of the prompt leads to a lot of idiosyncrasies. One example of how it breaks the mental model related to this issue is the following that I was running into more recently: you create a cell via prompt. You had a typo so you go back to the cell you just created and fix the typo and execute it. Then for the next cell you just want to do the same thing for another variable so you recall history in the prompt, but you get the wrong version with the bug. IMHO that illustrates why this model is broken. In the prompt world you wouldn't go back to the cell so history works just fine as you'd make a new entry. In the cell model you would use the previous cell as the history so it would work, too.

**Comment by gordonwoodhull** [comment]
@s-u, are there any constructive suggestions here?

**Comment by s-u** [comment]
BTW: by now, having used RCloud daily for a long enough time I'd argue for a cell-only model. The only convenience piece left is the ability to hit `<Enter>` in the prompt - everything else is just more intuitive and easier to work with if you have just cells.

**Comment by s-u** [comment]
Yes, get rid of the prompt :) That way Shane's proposal works just fine and solves the issue.

**Comment by gordonwoodhull** [comment]
So uncheck "Show Command Prompt".

**Comment by s-u** [comment]
... if you do that, you cannot add any cells - is that why we need the new cell shortcut?

**Comment by gordonwoodhull** [comment]
Use the new cell button.

**Comment by s-u** [comment]
I think we're on to something - if Shane's cell walking works then moving the cursor beyond the current cell would create a new cell which make sense while moving it up would enter the previous cell which acts like history. I like that. We just have to make sure we don't keep the last, empty cell when you do `<Cmd><Enter>`

**Comment by s-u** [comment]
@gordonwoodhull yeah, exactly, which is why it's unusable in the current version :)

**Comment by gordonwoodhull** [comment]
The new cell button is there, have you even looked?

I'm not sure I like arrow-down as the create new cell shortcut. Would continuing to arrow down create new cells? I won't stop you if this is what you really want, just seems messy to me.

**Comment by s-u** [comment]
The button is there, but that's obviously useless for interactive use since you'd have to click between every single execution.

**Comment by gordonwoodhull** [comment]
I see, so you sort of want a prompt but you want it to act more like a cell. Would a new notebook open with a blank cell instead?

**Comment by s-u** [comment]
Yes, exactly, and you would get a blank cell after execution of the last cell as well (since otherwise you're sort of stranded). If you couple that with the cell walking I think it's actually a very appealing concept!

**Comment by s-u** [comment]
Technically, there is no prompt just a blank cell tat the end of the notebook if you have edit rights - that's probably the best way to describe it.

**Comment by gordonwoodhull** [comment]
Makes sense. 

Okay, I'll suggest that this behavior be folded into the "hide command prompt" behavior and renamed, since that didn't really succeed on its own. It's a little late for feature requests but maybe @shaneporter will be able to fit this into the current release as well.

**Comment by shaneporter** [comment]
I've just thought of the page down/up scenario, where focus transfers across a cell boundary (or perhaps even multiple boundaries.)

**Comment by gordonwoodhull** [comment]
Interesting. I'm open to either paging or doing next-cell/last-cell for pageup/pagedown. Either way, I think we need keys that go directly to the next & last cells in addition to the arrow key behavior.

Neither here nor there, but Macs' pageup/pagedown keys are hidden behind the Fn-key so I doubt many people use them.

**Comment by gordonwoodhull** [comment]
For this issue, I suggest:
 - [ ] arrow past the end of a cell always goes to next / previous cell (if any)
 - [ ] alt-up and alt-down go to beginning of previous / next cell
 - [ ] ctrl-/ and ctrl-\ for adding a cell after or before the current cell

That last one is wacky, just a strawman. It doesn't seem to already be assigned, anyway.

I'll open a new issue summarizing the discussion about an "extra cell" replacing the command prompt.

**Comment by shaneporter** [comment]
ctrl-/ and ctrl-\ 

That would have to be done within a cell? ctrl-/ is currently assigned to comment/uncomment line.

**Comment by shaneporter** [comment]
Agreed that ctrl-/ is already assigned. Will use ctrl-( and ctrl-) for adding a cell before or after current cell.

**Comment by gordonwoodhull** [comment]
Heh. Oops I was unspecific, I meant "square brackets", ctrl-[, ctrl-]. If those aren't taken. 

One less modifier key.

**Comment by shaneporter** [comment]
I prefer square brackets. Modifying now :)

**Comment by shaneporter** [comment]
The arrow shortcut is a bit problematic. If I use ACE's addCommands to add a shortcut (that is already used), it overwrites the default shortcut.

**Comment by shaneporter** [comment]
Implemented in PR #1990, with some caveats.

**Comment by gordonwoodhull** [comment]
Mostly implemented in #1990, except for arrowing past end stuff.
