### ISSUE TITLE
unable to delete entry from "Disable Extensions" box and/or "Enable Extensions" box

### ISSUE THREAD

**Issue by martymcwizard** [att/rcloud#1440]
Having entered "rcloud.iip" into the disable extension box I am now not able to delete it.  Entering it into the enable extension box is allowed also but I can't figure out how to delete it there either.

![image](https://cloud.githubusercontent.com/assets/1158095/7597845/ed8767a6-f8bb-11e4-92f9-e78ad83c8e30.png)

**Comment by gordonwoodhull** [comment]
Delete the text and then press enter.

It's not ideal having these text entry boxes with no buttons. It's just that the other settings aren't modal (don't require an OK/Cancel step), so I did the same for the text entry.

**Comment by martymcwizard** [comment]
thanks
