### ISSUE TITLE
Support multiple read-only gist back-ends

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1443]
Supports reading notebooks from multiple gist contexts such as different GH back ends

**Comment by s-u** [comment]
- [ ] define configuration of multiple gist back-ends
- [ ] initialize multiple back-end, store multiple contexts
- [ ] implement copy from source into a new notebook when forking across sources
- [ ] support `&source=foo` in edit/view URLs

**Comment by gordonwoodhull** [comment]
@s-u, I think `notebook.R` will also need to be adapted - is it possible to add the source as a prefix before the gist id, or will that be ambiguous?

**Comment by s-u** [comment]
Well, it only needs to be adapted if we define that it triggers an automatic import. I would argue that its non-query form doesn't need to - it wouldn't break anything if we implement auto-import for the query form.

That said, I was thinking originally that only `edit.html` should trigger auto-import, but I don't have a strong opinion.

**Comment by s-u** [comment]
But to answer your question, I do think that something like `<source>/<user>/<notebook>` would conflict with named notebooks (unless we use special prefix for sources like `.<source>` but that may get too confusing).

**Comment by gordonwoodhull** [comment]
Ah, okay, so the idea is to import a notebook first, using edit or view mode. After import it will be possible to access the notebook without `&source`. That seem fine to me.

**Comment by gordonwoodhull** [comment]
Shoot, are we going with the multiple SOLR option, or the import-everything-at-night option? I thought we had decided on the latter.

**Comment by s-u** [comment]
I don't know - I thought there was some issue of having the content from other lakes in the same SOLR which is why Prateek was pushing for multiple SOLR instances, but I don't know if there was any actual decision made on this. What I was woking off is that search is by default only local with the option to query other lakes as well. The point here being that you don't necessarily have to import all notebooks from other lakes, but instead you rely on search to find what you want to import -- but I think we did mention both options, so I'm not sure if there is a preference either way.

**Comment by gordonwoodhull** [comment]
@s-u will do multiple parallel solr queries, aggregate and tag with source.

@gordonwoodhull will 
 - [ ] do the url stuff
 - [ ] add a checkbox to the search ui
 - [ ] maybe make notebooks another color in the tree
 - [ ] also they must be read-only for owner

**Comment by gordonwoodhull** [comment]
I suggest we do not support user/path URIs, or tagged versions, in combination with sources.

**Comment by gordonwoodhull** [comment]
(yet)

**Comment by gordonwoodhull** [comment]
I guarantee this is going to cause a lot of subtle bugs. It is rippling through all notebook code on the client.

**Comment by gordonwoodhull** [comment]
@s-u, I implemented this in a simpler way and it seems to work, although I still expect some subtle bugs down the line. Basically, if edit.html is asked to open a notebook with `&source=` **and** it doesn't already have metadata on this notebook, then it synchronously sets the notebook property before loading the notebook.

So it's a punt to the server. 

If the notebook is already known, then `&source` is ignored.

Also, I know you want the gist back-end to decide if a notebook is read-only, but I don't think that is realistic without massive rewrites on both the client and server side, because this means supporting multiple usernames for the logged-in user. So it's just checking if the `source` notebook property exists and making the notebook readonly in addition to the 3-4 other things it's checking.

Finally, I added the "All Lakes" (internally "all sources") checkbox to the search panel and another argument `all_sources` on `rcloud.search`. Any search results with a `source` tag will be displayed in green and add `&source=` to the url.

**Comment by s-u** [comment]
5b4e28c77 adds support for read-only GitHub contexts (e.g. use `sorurce=public-github` on chusuk), but there is an error in the UI "populate comments: Unexpected end of input"

**Comment by gordonwoodhull** [comment]
Thanks @s-u. That's interesting, the get comments api works fine without being logged in via the browser. I wonder if there is somehow a bug in rgithub in this area. It's not even reporting an error, just an empty vector where a JSON string is expected.

I guess we have to make comments read-only here anyway. One of those expected-unexpected case I don't really want to deal with.

**Comment by s-u** [comment]
Ok, all pieces should be in place, I have added support for `all_sources` in the SOLR search adn the results have an additional `source` tag.

I can't see the checkbox that corresponds to the "Search all" query (even though I do see the parameter in the API) and I think the URL construction happens on the UI side so AFAICS the remaining two pieces: add the checkbox and modify the URLs to add `&source=` when set need to be done on the UI end.

**Comment by gordonwoodhull** [comment]
Interesting, there seems to be a race condition between the UI initializing and the editor initializing, so when this runs on chusuk the editor doesn't know about the sources by the time the search panel looks whether to show the All Lakes checkbox.

**Comment by gordonwoodhull** [comment]
I can't remember why I didn't add the source to the URL, that's a good idea. It's technically not needed once the notebook is registered but it's a good hint to the user what's going on.

**Comment by s-u** [comment]
The notebooks in search are not registered, so it is really needed there.

**Comment by s-u** [comment]
RE; All Lakes - do we expose the API to query sources? AFAIR there is none on the R side at this point - if we need one it would have to check either `.session$gist.sources.conf`(whihc has the configured extra sources) or `.session$gist.contexts` (which has all source contexts).

A related question - how should we treat the main back-end? In `.session$gist.contexts` it is listed as `"default"` ...

**Comment by gordonwoodhull** [comment]
`?source=` works as an input but not an output - the front end basically registers the notebook and then throws the parameter out.

**Comment by gordonwoodhull** [comment]
I added the `get.gist.sources` api to source.R

If you want to test All Lakes, you can disable the code that hides the checkbox here:

https://github.com/att/rcloud/blob/develop/htdocs/js/ui/search.js#L57

I'll fix the race condition later.

**Comment by gordonwoodhull** [comment]
ripple, ripple, ripple, WAVE. 

the consequences continue to multiply.

**Comment by gordonwoodhull** [comment]
One of the essential problems here is that, while the server can load a notebook from a source it knows about, it doesn't tell the client it has done that. The client only knows the source of notebooks in All Notebooks.

So we get bugs like #1530 (notebooks stop being loadable) and #1531 client doesn't know notebook is foreign.

**Comment by gordonwoodhull** [comment]
Screw it, I'm just going to read the `source` notebook property if I don't know it...

**Comment by gordonwoodhull** [comment]
hmm, the populate_comments thing

**Comment by s-u** [comment]
I thought that the idea was to have `source` in the `notebook_info` so you'd always know it ...

**Comment by gordonwoodhull** [comment]
Yeah, I ended up going with just fetching the notebook info (or just this property) when I don't know the notebook.
