### ISSUE TITLE
view.html should not show cell headers

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1449]
Since `view.html` produces sequential output without controls that is primarily used in a reporting fashion, it should not show the cell headers since they are not meaningful in this context and are visually destructive.

**Comment by gordonwoodhull** [comment]
Yes. The only thing I'd like to keep is the status light, which can go in the margin and maybe disappear when all the cells have run.

**Comment by gordonwoodhull** [comment]
add to `?quiet=1`
