### ISSUE TITLE
Cell execution is getting cancelled in 'view.html' for all the notebooks

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1454]
When we open a notebook in view.html, it executes only first cell but cell status changes to 'cancelled status' automatically without executing further cells in that notebook.

![cellexecutioninview](https://cloud.githubusercontent.com/assets/10941328/7719815/38852e0a-fee3-11e4-9c19-b4bb2b4398f0.PNG)

**Comment by gordonwoodhull** [comment]
I'm not able to repro. @Prateek032, are you still seeing this? Sounds like perhaps a bad install.

**Comment by Prateek032** [comment]
This issue is not getting reproduced. The issue might be because of bad installation as you mentioned.

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032!
