### ISSUE TITLE
Stop button freezes while accepting user inputs in run time

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1455]
While executing a notebook which contains R cell and  which accepts user inputs in run time, we are unable to stop the  execution of that notebook. If we haven't provided the required input

![stop_freezes](https://cloud.githubusercontent.com/assets/10941328/7719913/589e978e-fee4-11e4-92ab-813c191073df.PNG)

**Comment by gordonwoodhull** [comment]
duplicate of #1196 ways to cancel input
