### ISSUE TITLE
confusion when changing cell language of enqueued cell

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1456]
When we execute a notebook using "run all" option, according to current behavior changes made in any cell while execution are not expected to reflected in current output, but if we change the 
language of any R cell to 'markdown' then the output reflects the language change as it shows R cell output in markdown format as seen in screen shot

![save](https://cloud.githubusercontent.com/assets/9251570/7720124/8e895fb6-fe97-11e4-96d7-8d620e453ffe.PNG)

**Comment by gordonwoodhull** [comment]
Solution to this is to also go to the Unknown state if the language is changed, just as if the code were edited

**Comment by sanketd11** [comment]
This issue can still be replicated as follows:
* Click on Run all
* Modify some code content in any of the queued cells and then change the cell language 
Or 
* Change the cell language for more than twice

Can you please open this issue.

**Comment by gordonwoodhull** [comment]
Or, change the cell twice :-p

Thanks for catching this, @sanketd11! This is almost useless if it reverts itself.
