### ISSUE TITLE
What should be the behavior of the save button in feature compute separation?

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1457]
According to the current scenario, 
1. Consider execution of a notebook( which consists of 3 to 4 cells) using run-all option
2. Modify any cell in that notebook before it starts getting executed
3. If we click on save button after making changes in the cell, still the output is displayed for older version of the code.
Anyhow the changes are getting saved irrespective of clicking on save button, what is the significance of 'saving' the code changes while execution?
Should the save button be disabled while execution or should the behavior of save button feature while execution be like, saving the cell changes and reflect the output in current execution itself?

**Comment by s-u** [comment]
The output has nothing to do with the saved version of the code, so I don't quite understand the issue. The results are always displayed for the code *submitted*, so it makes no difference if you changed it afterwards for the output. It should, however, be saved in the notebook/gist. And AFAICT that's what you're seeing - is that correct?

**Comment by gordonwoodhull** [comment]
I requested that QA open this ticket for discussion, although I don't regard it as a bug. It is the kind of confusion that I expect when this feature gets out in the real world.

It might be something to document, or there might be a warning tooltip we can display when clicking save on a running notebook.

**Comment by s-u** [comment]
I don't think the confusion is on the save end - it woudl seem odd to me if "save" meant saving previous sate.

I think the confusion is solely about results and that is handled by #1445

**Comment by gordonwoodhull** [comment]
The save button behavior is consistent: it always saves the content of the notebook as it is now, and does not modify any historical cells that are enqueued. Since we now explicitly show inconsistent state as "unknown" in the cells, I don't think there is an issue here. But it's important to have this "not an issue" issue, so thanks for filing it!
