### ISSUE TITLE
Files with '.R'  extension are not getting  uploaded to the notebook

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1460]
This was observed in RCloud local instance
When we upload any R file to the current notebook, in session div it is showing "(unexpected)"

![file_upload_is_not](https://cloud.githubusercontent.com/assets/10941328/7742158/f11b8156-ffa8-11e4-8c4b-ee6e7854c0cf.PNG)

**Comment by gordonwoodhull** [comment]
I'm not able to repro this. @Prateek032, are you still seeing this?

**Comment by Prateek032** [comment]
This issue seems to be resolved.

**Comment by gordonwoodhull** [comment]
Phew, this would be a very bad thing. Thanks @Prateek032!
