### ISSUE TITLE
Another RCloud installation Issue

### ISSUE THREAD

**Issue by mzhao577** [att/rcloud#1462]
Hi,

I am trying to install rcloud on my new EC2 Ubuntu 14.04 LTS instance with 4G memory (1G memeory runs out of virtual memeory every time I installed it)).  So I installed R, and then run the following accoring to the link: 
https://github.com/att/rcloud/blob/develop/doc/INSTALL.md

Here are the simple steps I used: 

Step 0.1
sudo apt-get update   
Step 0.2   
sudo apt-get install gcc g++ gfortran libcairo-dev libreadline-dev libxt-dev \   
libjpeg-dev libicu-dev libssl-dev libcurl4-openssl-dev subversion git automake \
make libtool libtiff-dev gettext redis-server rsync

Step 2.1  Clone the rcloud package.
	sudo mkdir /data
	sudo chown ubuntu:ubuntu /data
	cd /data
	git clone https://github.com/att/rcloud.git

Step 2.2 Build it.
	cd /data/rcloud
	sudo sh scripts/bootstrapR.sh

I got the following error messages while I was running the "sh scripts/bootstrapR.sh".  It's mainly about the Rserve and rcloud.support.  I would greatly appreciate if you could help!

* DONE (githubgist)
ERROR: dependencies ‘rjson’, ‘Rserve’ are not available for package ‘rcloud.support’
* removing ‘/usr/local/lib/R/site-library/rcloud.support’
ERROR: dependency ‘Rserve’ is not available for package ‘rcloud.web’
* removing ‘/usr/local/lib/R/site-library/rcloud.web’
ERROR: dependency ‘rcloud.support’ is not available for package ‘rcloud.enviewer’
* removing ‘/usr/local/lib/R/site-library/rcloud.enviewer’
ERROR: dependency ‘rcloud.support’ is not available for package ‘rcloud.lux’
* removing ‘/usr/local/lib/R/site-library/rcloud.lux’
ERROR: dependency ‘rcloud.support’ is not available for package ‘rcloud.notebook.info’
* removing ‘/usr/local/lib/R/site-library/rcloud.notebook.info’
ERROR: dependency ‘rcloud.support’ is not available for package ‘rcloud.viewer’
* removing ‘/usr/local/lib/R/site-library/rcloud.viewer’

Please let me know if you need more information.
Thanks,
Max Zhao

**Comment by mzhao577** [comment]
I was starting a new EC2 instance.  Could it be that I need to install something else in addition to the dependency packages as listed below?

sudo apt-get install gcc g++ gfortran libcairo-dev libreadline-dev libxt-dev \
libjpeg-dev libicu-dev libssl-dev libcurl4-openssl-dev subversion git automake \
make libtool libtiff-dev gettext redis-server rsync

The problem appears to be with Rserve installation.  I got the same error message if I want to install RServe within R (assuming the role of 'su') , like below:
install.packages("Rserve",,"http://rforge.net/",type="source")

Main error message listed below:
------------------------------------------------
make: *** [server] Error 1
ERROR: compilation failed for package ‘Rserve’
* removing ‘/usr/local/lib/R/site-library/Rserve’

The downloaded source packages are in
        ‘/tmp/RtmpLfZ9V6/downloaded_packages’
Warning message:
In install.packages("Rserve", , "http://rforge.net/", type = "source") :
  installation of package ‘Rserve’ had non-zero exit status

Thanks,
Max

**Comment by gordonwoodhull** [comment]
Do the messages list a compilation log file? Probably Rserve is missing a dependency.

**Comment by s-u** [comment]
Please re-try now. Since it installs Rserve from there devel site, it will fail if the current sources Rserve don't build which was the case for a day or so. Thanks, Simon

**Comment by mzhao577** [comment]
Hi Gordon and Simon,

I just tried to re-install rcloud on my Ubuntu 14.04 on EC2.  I am still getting the compilation error for Rserve.   Since I am using the "git clone https://github.com/att/rcloud.git" to get the package to my Linux.  Could you tell me which version is stable?  Maybe Rcloud1.3.1 is more stable?

Thanks,
Max

**Comment by s-u** [comment]
This is not about RCloud (so the version doesn't matter) - just run
```r
install.packages("Rserve",,"http://rforge.net")
```
in R to get a working version of Rserve. If you still get an error, please paste the actual error here.

**Comment by gordonwoodhull** [comment]
It is true that the `master` branch might be more stable (currently 1.3.4). But it won't help you here.

**Comment by mzhao577** [comment]
Hi Simon,

Attached at the end of this email is the error message when I tried to install Rserve winthin R using the command you provided:   -----  install.packages("Rserve",,"http://rforge.net")
 
I tried to run the command both as 'ubuntu' and as 'root'.   I got the same error message within R as well as when I run with the "sudo sh scripts/bootstrapR.sh" at Linux prompt.

I used to install RCloud using a Amazon Rcloud1.2 AMI and installed rhadoop and hmr upon that instance. Now I would like to install Rcloud from the very basic and tried to use it more.   Your help on this problem will be greatly appreciated!

Thanks,
Max

--------------- R version 3.02  at Ubuntu Server 14.04 LTS (HVM), SSD Volume Type ------
> install.packages("Rserve",,"http://rforge.net")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://rforge.net/src/contrib/Rserve_1.8-3.tar.gz'
Content type 'application/x-gzip' length 458184 bytes (447 Kb)
opened URL
==================================================
downloaded 447 Kb

* installing *source* package ‘Rserve’ ...
checking whether to compile the server... yes
checking whether to compile the client... no
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for sys/types.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... no
checking whether time.h and sys/time.h may both be included... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking return type of signal handlers... void
checking for memset... yes
checking for mkdir... yes
checking for rmdir... yes
checking for select... yes
checking for socket... yes
checking for srandomdev... no
checking for library containing crypt... -lcrypt
checking crypt.h usability... yes
checking crypt.h presence... yes
checking for crypt.h... yes
checking for socklen_t... yes
checking for connect... yes
checking whether to enable IPv6... no
checking for dlopen in -ldl... yes
checking openssl/rsa.h usability... yes
checking openssl/rsa.h presence... yes
checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key... -lcrypto
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for library containing SSL_CTX_load_verify_locations... -lssl
checking whether threads are desired... yes
checking for working threads support... checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
yes
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating src/client/cxx/Makefile
config.status: creating src/config.h
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c RSserver.c -o RSserver.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c Rserv.c -o Rserv.o
Rserv.c: In function ‘performConfig’:
Rserv.c:1038:10: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
    setgid(ruid);
          ^
Rserv.c:1039:9: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
   setuid(ruid);
         ^
Rserv.c:1042:28: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
   if (requested_gid) setgid(requested_gid);
                            ^
Rserv.c:1043:28: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
   if (requested_uid) setuid(requested_uid);
                            ^
Rserv.c: In function ‘auth_user’:
Rserv.c:2468:13: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
       setgid(u_gid ? u_gid : default_gid);
             ^
Rserv.c:2470:13: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
       setuid(u_uid ? u_uid : default_uid);
             ^
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c base64.c -o base64.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c http.c -o http.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c ioc.c -o ioc.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c md5.c -o md5.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c oc.c -o oc.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c qap_decode.c -o qap_decode.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c qap_encode.c -o qap_encode.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c rsio.c -o rsio.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c session.c -o session.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c sha1.c -o sha1.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c standalone.c -o standalone.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c tls.c -o tls.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c ulog.c -o ulog.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c utils.c -o utils.o
utils.c: In function ‘Rserve_eval_’:
utils.c:75:5: warning: implicit declaration of function ‘R_ExecWithCleanup’ [-Wimplicit-function-declaration]
     R_ExecWithCleanup(Rserve_eval_do, arg, Rserve_eval_cleanup, arg);
     ^
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c websockets.c -o websockets.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g  -c winembed.c -o winembed.o
gcc -std=gnu99 -shared -o Rserve.so RSserver.o Rserv.o base64.o http.o ioc.o md5.o oc.o qap_decode.o qap_encode.o rsio.o session.o sha1.o standalone.o tls.o ulog.o utils.o websockets.o winembed.o -lssl -lcrypto -ldl -lcrypt -L/usr/lib/R/lib -lR
gcc -std=gnu99 -DSTANDALONE_RSERVE -DDAEMON -I. -Iinclude -I/usr/share/R/include -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread     -fpic  -O3 -pipe  -g   -O3 -pipe  -g  -DRSERVE_PKG -I. -Iinclude   -pthread  -o Rserve standalone.c md5.c session.c qap_decode.c qap_encode.c sha1.c base64.c websockets.c RSserver.c tls.c http.c oc.c rsio.c ulog.c ioc.c utils.c -lssl -lcrypto -ldl -lcrypt    -L/usr/lib/R/lib -lR -lssl -lcrypto -ldl -lcrypt
In file included from standalone.c:6:0:
Rserv.c: In function ‘performConfig’:
Rserv.c:1038:10: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
    setgid(ruid);
          ^
Rserv.c:1039:9: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
   setuid(ruid);
         ^
Rserv.c:1042:28: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
   if (requested_gid) setgid(requested_gid);
                            ^
Rserv.c:1043:28: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
   if (requested_uid) setuid(requested_uid);
                            ^
Rserv.c: In function ‘auth_user’:
Rserv.c:2468:13: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
       setgid(u_gid ? u_gid : default_gid);
             ^
Rserv.c:2470:13: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
       setuid(u_uid ? u_uid : default_uid);
             ^
utils.c: In function ‘Rserve_eval_’:
utils.c:75:5: warning: implicit declaration of function ‘R_ExecWithCleanup’ [-Wimplicit-function-declaration]
     R_ExecWithCleanup(Rserve_eval_do, arg, Rserve_eval_cleanup, arg);
     ^
/tmp/ccQAlAeO.o: In function `Rserve_eval_':
/tmp/Rtmp3OglGN/R.INSTALLb1373e53316/Rserve/src/utils.c:75: undefined reference to `R_ExecWithCleanup'
collect2: error: ld returned 1 exit status
make: *** [server] Error 1
ERROR: compilation failed for package ‘Rserve’
* removing ‘/usr/local/lib/R/site-library/Rserve’

The downloaded source packages are in
        ‘/tmp/RtmpwYDJPF/downloaded_packages’
Warning message:
In install.packages("Rserve", , "http://rforge.net") :
  installation of package ‘Rserve’ had non-zero exit status
---------------  End of error message

**Comment by s-u** [comment]
Ah, got it, your R version is too old - you need R 3.1.0 or higher.

**Comment by mzhao577** [comment]
Hi Simon.

Thanks a lot! 

I will update my R. It's probably the mirror site I was using in my sources.list. My R was not updated even after I run 'sudo apt-get update'.

Thanks again for your timely response!

Max

--------------------------------
箴言9：10  敬畏耶和华是智慧的开端，认识至圣者便是聪明。

**Comment by mzhao577** [comment]
Hi Simon,

I got R installation fixed.  I successfully installed RCloud with a few
warnings.

Now I have a new issue. When I logon to rcloud, I could not see the R
prompt.

I am wondering if this is related to warning messages I got from Rserv.c:

Rserv.c: In function ‘performConfig’:

Here are the warning messages I got:

----------

Rserv.c: In function ‘performConfig’:

Rserv.c:1038:10: warning: ignoring return value of ‘setgid’, declared with
attribute warn_unused_result [-Wunused-result]

    setgid(ruid);

       ^

Rserv.c:1039:9: warning: ignoring return value of ‘setuid’, declared with
attribute warn_unused_result [-Wunused-result]

   setuid(ruid);

         ^

Rserv.c:1042:28: warning: ignoring return value of ‘setgid’, declared with
attribute warn_unused_result [-Wunused-result]

   if (requested_gid) setgid(requested_gid);

                            ^

Rserv.c:1043:28: warning: ignoring return value of ‘setuid’, declared with
attribute warn_unused_result [-Wunused-result]

   if (requested_uid) setuid(requested_uid);

                            ^

Rserv.c: In function ‘auth_user’:

Rserv.c:2468:13: warning: ignoring return value of ‘setgid’, declared with
attribute warn_unused_result [-Wunused-result]

       setgid(u_gid ? u_gid : default_gid);

             ^

Rserv.c:2470:13: warning: ignoring return value of ‘setuid’, declared with
attribute warn_unused_result [-Wunused-result]

       setuid(u_uid ? u_uid : default_uid);

             ^


Thanks,

Max

**Comment by gordonwoodhull** [comment]
@mzhao577, I doubt that warning has to do with it, that looks completely harmless.

Do you mean that the rest of the UI is okay but you don't have a command prompt at the bottom to type in?  There is an option in the Settings panel on the lower left that could be the culprit. 

Or do you mean that the page does not completely load?

Could you copy and paste a screenshot into a comment on this issue?

**Comment by gordonwoodhull** [comment]
@mzhao577, is this resolved?

**Comment by gordonwoodhull** [comment]
@mzhao577, closing this because the installation problem seems to be fixed. Please open another issue for the R prompt problem if you're still seeing it.

**Comment by mzhao577** [comment]
I had a trip to China and not have a chance to fix it yet. I will continue my journey with RCloud once I am back to US.

Thanks,
Max

--------------------------------
箴言9：10  敬畏耶和华是智慧的开端，认识至圣者便是聪明。
