### ISSUE TITLE
Error, While renaming the notebook with prefix.

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1467]
This issue was observed in RCLoud-loacal instance with reference to the following commit
Commit Number:'8af1f135780cb600f2c6ca1856d9831d449c126f'.
When we create a notebook and rename it with prefix (ex: Testing/Notebook name), it throws following error in session div.

![renaming_the_notebook_by adding_fwd_slash](https://cloud.githubusercontent.com/assets/10941328/7912118/3a4bde0c-0882-11e5-9014-02b9a99bd03b.PNG)

**Comment by gordonwoodhull** [comment]
This seems to be a more general problem because it also happens with self-forking. The error doesn't seem to have anything to do with either feature so I'm going to guess it has something to do with binary assets. 

@s-u, does a corrupt mime.rdb in `mime::guess_type` mean anything to you?

**Comment by s-u** [comment]
This means typically bad package version/R build mismatch - re-install packages (at least the one in question).

**Comment by gordonwoodhull** [comment]
I'm going to assume this was a bad install and close this. @Prateek032, please comment if you still see this.
