### ISSUE TITLE
Error, while forking our own notebook

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1469]
This issue was observed in RCLoud-loacal instance with reference to the following commit
Commit Number:'8af1f135780cb600f2c6ca1856d9831d449c126f'.

When we try to fork our own notebook, it displays the following error in session div

![fork](https://cloud.githubusercontent.com/assets/10941328/7912278/a9fff5b6-0883-11e5-8c5e-b83d0c51da4a.PNG)
 prefix)

**Comment by gordonwoodhull** [comment]
Duplicate of #1467 - seems to be a more general problem
