### ISSUE TITLE
prepend context to oobs

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1471]

**Comment by s-u** [comment]
closed by 6d2b0baa in s-u/Rserve -- requires
```
io.use.context yes
```
in `Rserve.conf`

**Comment by gordonwoodhull** [comment]
the other parts of this are prepending the context in oobs sent from rcloud itself, and passing the context in from session.R to the language extensions.

**Comment by s-u** [comment]
Note: requires lastest Rserve; it doesn't actually replace the context on the UI side but it should be a replacement thereof

**Comment by gordonwoodhull** [comment]
uhh, of course we need the context for images as well...

**Comment by gordonwoodhull** [comment]
i'm going to go ahead and convert the rest of the `self.oobSend` to `.rc.oobSend`, is there a reason not to?

**Comment by s-u** [comment]
You mean the ones in `device.R`? No - I thought you wanted to use the device ID instead.

BTW: I don't get any output at all since the last merge few mins ago ...

**Comment by gordonwoodhull** [comment]
yeah, i'm currently cleaning up the mess from removing the old bracket-with-oobs method. i can push a fix for that.

**Comment by gordonwoodhull** [comment]
it wasn't actually enabled on the client side.

**Comment by gordonwoodhull** [comment]
device IDs still have to be displayed in cells which are contexts. i'm replacing the rest of these

```
gordon$ grr self.oobSend
rcloud.packages/rcloud.python/R/main.R:          self.oobSend(list("html.out", msg))
rcloud.packages/rcloud.python/R/main.R:          self.oobSend(list("console.out", res[2]))
rcloud.packages/rcloud.python/R/main.R:          self.oobSend(list("html.out", res[2]))
rcloud.packages/rcloud.rmarkdown/R/main.R:    self.oobSend(list("html.out", val))
rcloud.packages/rcloud.web/R/inline.R:        self.oobSend(list("html.out",result$content$body))
rcloud.support/R/device.R:    self.oobSend(list("dev.new", did, type, c(width, height)))
rcloud.support/R/device.R:    self.oobSend(list(cmd, payload, rev(dim(img)), did, page))
rcloud.support/R/device.R:        self.oobSend(list("dev.close", did))
rcloud.support/R/ocaps.R:.rc.oobSend <- function(kind, ...) self.oobSend(list(kind, Rserve.context(), ...))
```

**Comment by s-u** [comment]
oh, the `rcloud.package` ones have no business being there in the first place ... they should all be `rcloud.html.out` - with the exception of `console.out` which makes me nervous ...

**Comment by gordonwoodhull** [comment]
hmm, how should Python be sending console-like output?

**Comment by gordonwoodhull** [comment]
oh, duh, `rcloud.out`
