### ISSUE TITLE
pdf assets not displayed

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1477]
When we upload any pdf file to the asset div, the pdf preview is not displayed
in Firefox it is displaying like below

![pdf_previewinff](https://cloud.githubusercontent.com/assets/10941328/8079919/949fd444-0f85-11e5-9282-644621f2dca2.PNG)

And in chrome browser it is displaying like below

![pdf_previewinchrome](https://cloud.githubusercontent.com/assets/10941328/8079933/b271e69c-0f85-11e5-9dab-31251f992af9.PNG)

**Comment by gordonwoodhull** [comment]
This is weird - I think the `<object>` tag is correct here. http://stackoverflow.com/a/5171817/676195
