### ISSUE TITLE
Help breaks with R 3.2.0

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1482]
@s-u 
tools::startDynamicHelp missing in tools with R 3.2.0

**Comment by s-u** [comment]
That's not the the actual error (`tools::startDynamicHelp` is in fact the official API even in 3.2.0), but I know what you mean (`tools:::httpdPort` is not longer available).

**Comment by prateek05** [comment]
Ah! I see so we don't need this section anymore? 
https://github.com/att/rcloud/blob/develop/rcloud.support/R/setup.R#L282
