### ISSUE TITLE
Notebook title gets prepended with <space> when New Notebook Prefix kept blank

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1490]
Following are the steps to replicate this issue:
* Remove all the text from 'New Notebook Prefix' field
* Create a new notebook 
* Observe the Notebook title.

The notebook title gets prepended with "space" as shown below

![pepend_space_title](https://cloud.githubusercontent.com/assets/9251570/8125020/4de29192-10ff-11e5-9f8a-e625b580916d.PNG)

**Comment by gordonwoodhull** [comment]
Okay, that seems kind of messy, but people might want their prefix to be "Notebooks/", which causes similar problems. Will fix both.

**Comment by gordonwoodhull** [comment]
@s-u, you're probably the only person who has set this option so far. You'll need to add a space to the end to get the previous behavior. This is to support "Notebooks/1", "Notebooks/2", etc.
