### ISSUE TITLE
Notebook Renaming accepts whitespace as folder/notebook name

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1491]
This issue occurs only if notebook being renamed is present in folder.
following are the steps to replicate:
* Load the notebook to be renamed
* Click on the notebook title
* Add '/' to notebook title if the notebook is present in any folder
* Add white space as notebook title after '/' e.g. 'folder_name/ <_space_>'

![empty_notebook_and_folder_name](https://cloud.githubusercontent.com/assets/9251570/8125390/ebb6eac8-1102-11e5-8d9a-412f1ea2f291.PNG)

The notebook title also accepts white space as folder name as shown in above screen shot in top left corner.
To replicate empty folder name and notebook name just give '<_space_> / <_space_>' as notebook title

**Comment by gordonwoodhull** [comment]
Good find, @sanketd11. For that matter, it accepts a blank notebook name as long as there is a folder, or both, i.e. " / / "
