### ISSUE TITLE
Fork option for folder overlaps with date and time stamp of notebook

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1492]
This issue is further case of #1491.
When folder name is just a white space, the fork option for that folder overlaps with the date and time stamp present adjacent to notebook name in Notebooks div.

![fork_folder](https://cloud.githubusercontent.com/assets/9251570/8125700/cb01a414-1105-11e5-8d68-9a5659e5426d.png)

**Comment by gordonwoodhull** [comment]
blank folder names should not be allowed!
