### ISSUE TITLE
disconnect on large file upload (again, still, but less often)

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1493]
When we try to upload any csv file to assets div via file upload div, the current RCloud session logs out.
This behavior is observed in both chrome and firefox browser. 'Reconnect' message appears immediately after uploading a csv file to asset however sometimes it appears after second consecutive csv file upload.

**Comment by gordonwoodhull** [comment]
This is an unpleasant item to wake up to. Of course we believe we have fixed all such issues, and I'm not able to repro.

Could you provide more specifics - which instance are you uploading to? Does file size matter?

**Comment by sanketd11** [comment]
I observed this issue on RCloud local instance. 
Yes.. I think file size matters here. I was able to replicate this issue while uploading the CSV files of size around 450 KB

**Comment by gordonwoodhull** [comment]
I am able to repro this intermittently with a 610K file (airports.csv copied three times). 

@s-u, could you diagnose this with the proxy?

**Comment by gordonwoodhull** [comment]
In addition, I saw this error once:
```
update_notebook: Error in toJSON(body) : 
  GC encountered a node (0x7fd473175200) with an unknown SEXP type: DOTSXP at memory.c:993
R trace:
.Call("toJSON", x, PACKAGE = "rjson")
toJSON(body)
method(url = url, config = config, body = body)
.api.request(ctx, req, .with.body(PATCH), expect.code, params, 
    config, body)
.api.patch.request(ctx, c("gists", id), body = content)
modify.gist.githubcontext(id, content, ctx = .rcloud.get.gist.context())
modify.gist(id, content, ctx = .rcloud.get.gist.context())
fun(...) Error: update_notebook: Error in toJSON(body) : 
  GC encountered a node (0x7fd473175200) with an unknown SEXP type: DOTSXP at memory.c:993
R trace:
.Call("toJSON", x, PACKAGE = "rjson")
toJSON(body)
method(url = url, config = config, body = body)
.api.request(ctx, req, .with.body(PATCH), expect.code, params, 
    config, body)
.api.patch.request(ctx, c("gists", id), body = content)
modify.gist.githubcontext(id, content, ctx = .rcloud.get.gist.context())
modify.gist(id, content, ctx = .rcloud.get.gist.context())
```

**Comment by gordonwoodhull** [comment]
Ugh, I am not able to repro on a remote server, only when running locally. So the proxy may not help us debug this.

**Comment by s-u** [comment]
The above is some bad memory corruption - the question is whether it's in rjson or somewhere in our code ..

**Comment by s-u** [comment]
This appears to be a memory corruption/protection bug in `rjson` used by `rgithub` and it goes away when using `jsonlite` instead of `rjson`.

**Comment by sanketd11** [comment]
I'm still able to replicate this issue on firefox browser

**Comment by gordonwoodhull** [comment]
Did you update rgithub?

**Comment by sanketd11** [comment]
Will do that. But I saw this issue on RCloud-2

**Comment by gordonwoodhull** [comment]
I'm not able to repro this with files around 600k and 730k. @sanketd11, could you email me the file which causes the crash?

**Comment by gordonwoodhull** [comment]
Locally, I was able to repro, installed the latest rgithub, and now it is okay. Anecdotal evidence that the bug I saw before is solved by the rgithub fix.

**Comment by s-u** [comment]
Sorry, I cannot reproduce it in Firefox, either.

**Comment by gordonwoodhull** [comment]
@Prateek032 reports they can no longer repro
