### ISSUE TITLE
Unable to open View.html

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1507]
This issue was observed in RCloud-Local instance on latest Commit:6eb027af59b2be78bce1f6c866cf797d604eace9.
When user opens a notebook in view.html, the following message is displayed. Even though the user is Logged in but still it is showing Log in to view it

![viewhtml_notopening](https://cloud.githubusercontent.com/assets/10941328/8200067/dd743a00-14dc-11e5-837f-23af19b8d6ab.PNG)

Following is the console error

![viewhtml_consoleerror](https://cloud.githubusercontent.com/assets/10941328/8200797/92534bc8-14e7-11e5-8516-cabd4e3a18ad.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032! 

Please file all the rest of the issues we discussed yesterday. There is no way I can remember everything from a brief phone call.

**Comment by Prateek032** [comment]
On latest commit ( f2f1e69fac6400ce8b0b017637b562cfcb3d5d86) still unable to load view.html and following error is dispalyed on the page
![viewhtml](https://cloud.githubusercontent.com/assets/10941328/8276932/2bd9d118-18da-11e5-9d78-ccd7633fd298.PNG)

And below is the error displayed under Console

![viewhtml_consoleerr](https://cloud.githubusercontent.com/assets/10941328/8276936/3b3f8aa8-18da-11e5-9751-bfd838e02460.PNG)

**Comment by gordonwoodhull** [comment]
okay, the root cause is completely different here, so it's a different bug, but reopening

**Comment by gordonwoodhull** [comment]
@Prateek032, chances are you have to update your Rserve package again.

**Comment by Prateek032** [comment]
After updating RServe package to 1.8.3, now it is working as expected.
