### ISSUE TITLE
star count drops to zero when forking another's notebook that you already forked

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1508]
This issue was observed in RCloud-Local instance on latest Commit:6eb027af59b2be78bce1f6c866cf797d604eace9.
Following is the scenario to replicate
1.Open RCloud 
2.Click on All notebook and select any user's notebook folder and click on Folder Fork option
3.Now click on any notebook/ Load any notebook of that user's from the Folder (from the All notebook). Respective Notebook will be opened in read only mode.
4.Now click on Fork option, the forked Notebook is visible under My notebook tree with 0 star count. Even though the notebook is starred, but still the count is showing 0

![starcount_zero](https://cloud.githubusercontent.com/assets/10941328/8200953/5f9bc4ba-14e9-11e5-97e2-dc8a701e1ab0.PNG)

**Comment by gordonwoodhull** [comment]
Just inappropriate, not aberrant?

**Comment by gordonwoodhull** [comment]
i wasn't able to follow the instructions on a first try. i think there is probably a simpler way to reproduce this that doesn't involve forking three times.

**Comment by gordonwoodhull** [comment]
probably related to #1514 in any case

**Comment by gordonwoodhull** [comment]
Okay, this is much simpler than the description above. 

GitHub will not let you fork a notebook you've already forked. If you try, RCloud properly opens that forked notebook again, but displays the star count zero.

It's just a temporary display problem, should be fixed the same way as #1522, by not trying to restar.

**Comment by gordonwoodhull** [comment]
Or rather, allow the star operation to just return the same star count.
