### ISSUE TITLE
Unable to close the notebook info popover

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1509]
Following are the steps to replicate the issue:
* Load any notebook 
* Click on the 'Notebook info' icon, the popover will be displayed 
* Rename the currently loaded notebook 
* Now try to close the popover( using close icon present on popover )

The popover won't close when clicked close button. It will freeze on the screen until we reload the page

**Comment by gordonwoodhull** [comment]
I think @anatoliyg has fixed this on his fork

**Comment by gordonwoodhull** [comment]
The popover now goes away on clicking the notebook title in the navbar or in the notebook tree; there is no need for the close button anymore.
