### ISSUE TITLE
Notebook info pop overs are getting piled up

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1511]
When user clicks on notebook info icon of 2-3 notebook's, the pop overs are getting piled up

![popoverpiledup](https://cloud.githubusercontent.com/assets/10941328/8201171/bdc515da-14eb-11e5-9be0-7c9d1eb02a68.PNG)

**Comment by gordonwoodhull** [comment]
I think @anatoliyg has fixed the popovers properly in his fork (yay!).

**Comment by gordonwoodhull** [comment]
Popover goes away in almost all cases now, except cases like #1546 where it becomes disconnected.
