### ISSUE TITLE
Notebook options becomes inaccessible when history versions are accessed

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1512]
Following are the steps to replicate the issue :
* Load any notebook having few history versions
* Click on the history icon for that notebook to see all the history versions for the notebook
* After clicking on the history icon, jqtree toggler icon will be displayed 

![history](https://cloud.githubusercontent.com/assets/9251570/8201405/49f3dcb0-14ee-11e5-863f-9fd623681e7a.PNG)

* Click on the jqtree toggler to collapse the history tree 
![history1](https://cloud.githubusercontent.com/assets/9251570/8201407/53d702ac-14ee-11e5-976f-6b03b7e13242.PNG)

* Hover mouse over the notebook options

The notebook options will not accessible until we close the history tree by click back the history icon for that notebook

**Comment by gordonwoodhull** [comment]
broken by doing the same thing for notebook folders, which i don't think was right. there is no harm in showing commands when either kind of folder is closed.
