### ISSUE TITLE
Time stamp for other user notebook changes after forking that notebook

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1516]
Steps to replicate this issue:
* Load any notebook from other user 

![before fork](https://cloud.githubusercontent.com/assets/9251570/8203438/7effa19e-14ff-11e5-8e58-542460180cf8.PNG)

* Fork that notebook 
* The time stamp for the forked notebook will show the current time (I forked at time on 6/17 14:43 )

![fork123](https://cloud.githubusercontent.com/assets/9251570/8203441/8572f738-14ff-11e5-9d5a-a1b0c650f195.PNG)

* Load back again the same notebook from other user

![after fork](https://cloud.githubusercontent.com/assets/9251570/8203450/8eeb3168-14ff-11e5-9b37-47378147e870.PNG)

The time stamp for other user's notebook will change and show current time

**Comment by gordonwoodhull** [comment]
thanks @sanketd11, this is good to know about, but it's really github behavior not rcloud behavior.

presumably github refreshes the `updated_at` field of the gist when it updates the `forks` list in the source gist.
