### ISSUE TITLE
Clicking on notebook title doesn't return to current version from history when history toggled

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1517]
Following are the steps to replicate the issue:
* Load any tagged history version of any notebook
* Click twice on jqtree toggler present besides the Notebook name in Notebook's div
* Try to load the current version of notebook 

If we click on the notebook name it becomes editable instead of switching back to current version of that notebook
![history_tag](https://cloud.githubusercontent.com/assets/9251570/8206124/5ccb3010-1514-11e5-92f8-a30c1f26c4ee.PNG)

**Comment by gordonwoodhull** [comment]
this doesn't actually have to do with tagged versions, just any history version. retitling

thanks @sanketd11!
