### ISSUE TITLE
toggle comment ACE shortcut 

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1519]
A user asked if there was a shortcut for doing this.

According to the ACE editor doco, the ACE editor has a shortcut of Cmd-/ on Mac (Ctrl-/ on Windows) to "toggle comment" for a block of highlighted lines.  It is listed on this page, near the bottom in a section labeled Other: https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts

That does not appear to be supported in RCloud, as the Cmd-/ (or Ctrl-/ on Windows) does nothing.

Opening this issue to discuss whether this would be a good thing to support.

One question that pops into my head:

 - R and Python use # for comments.  Markdown uses   (note 3 dashes on the first one, and just 2 dashes on the other).  So, depending on the cell language, the comment would need to do different things.  Or, maybe just support toggle comment shortcut in R and Python?

**Comment by gordonwoodhull** [comment]
Thanks for raising this @holyguster.

I have meant to look into this. As you mentioned, it is probably a function of Ace, along with all the sundry syntaxes for all the languages. 

Everything tends to be packaged into the language modes; this feature is probably just not enabled.
