### ISSUE TITLE
changes to Settings are not saved unless Enter is pressed

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1523]
The expected behavior is to commit changes as soon as you leave the text field (e.g. via Tab), but that doesn't trigger a save so the options revert back to previous values. It appears that the only way I could find to commit it was to press `<Enter>`. If such explicit submit is desired then there should be a corresponding "Submit"/"Save" button so it's obvious that an explicit save step via a default button is needed.

**Comment by gordonwoodhull** [comment]
Yeah. I followed the same interface as the notebook title, where I think the interface works. But somehow it being in a larger pane makes it confusing. I guess you are right that it should be onblur, with maybe just ESC to revert.

**Comment by gordonwoodhull** [comment]
Changing the blur action to commit, keeping Enter and ESC the same.
