### ISSUE TITLE
group assignment is empty when viewing permissions of notebook in group

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1528]
observed on rcloud-5 (not currently able to run notebook protections locally)

![image](https://cloud.githubusercontent.com/assets/1366709/8307662/d5e3d308-198d-11e5-9ea3-ea3b5e7288bd.png)

**Comment by anatoliyg** [comment]
This is all part of one issue that's caused by api results changing slightly once the keys were implemented.
