### ISSUE TITLE
editing the blank-group

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1538]
1. open the notebook permissions dialog on a notebook which you're just a member, not an admin, and then go to the Group tab.
 2. blank group is shown in the dropdown
 3. you can try to edit the members of the blank-group, but you get errors:

```
TypeError: Cannot read property 'id' of undefined
    at Scope.$scope.saveGroupTab (http://127.0.0.1:8080/js/ui/notebook_protection_controller.js:427:99)
    at Scope.$scope.save (http://127.0.0.1:8080/js/ui/notebook_protection_controller.js:470:24)
    at $parseFunctionCall (http://127.0.0.1:8080/lib/js/angular.js:12332:18)
```

Either a group you are an admin of should be displayed when you go to the group tab, or you should not be able to edit the blank-group.

**Comment by anatoliyg** [comment]
Ok. Blank group is the right behavior thou, right ? Since you're not the admin of that group, drop down wouldn't be populated with any groups .
 i agree you should not be able to add remove members of a blank group so I'll disable the selectize inputs in that case
