### ISSUE TITLE
Shareable link options are not working for anonymous user

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1541]
For anonymous user, the shareable links (view.html, shiny, mini and Notebook.R) option is not working. The following error is displayed on the page

![anonymoususer_viewhtml](https://cloud.githubusercontent.com/assets/10941328/8328491/c5744d8e-1a8e-11e5-8920-6d2221139f10.PNG)

And below is the console error for mini notebook

![anonymoususer_mini](https://cloud.githubusercontent.com/assets/10941328/8328612/d344b16e-1a8f-11e5-8d18-748bd4001c10.PNG)

**Comment by gordonwoodhull** [comment]
@s-u, we definitely still need anonymous login for view mode too...

**Comment by s-u** [comment]
Ack ... that error is really just to alert admins that forget to put in the github credentials ... so I guess we'll only check it in IDE mode ...
