### ISSUE TITLE
Error while execution, after changing cell language

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1542]
Change the cell language from R to Markdown and execute it, the following error message is displayed in Session div

![error after changing cell language](https://cloud.githubusercontent.com/assets/10941328/8330014/f32d5fd8-1a9b-11e5-977f-dbbd5552176f.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032

**Comment by gordonwoodhull** [comment]
specifically, for an empty cell - at least I wasn't able to reproduce it otherwise.
