### ISSUE TITLE
Notebook info pop over is not disappearing

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1546]
Notebook info pop over doesn't disappears for the following scenario:
* Click on any notebook info icon, pop over appears for the notebook
* Now click on other notebook's history icon ( the notebook which contains at-least one history version)
* And now click on notebook info icon to close the pop over

**Comment by gordonwoodhull** [comment]
Weird, it *almost* works in all cases. Thanks @Prateek032!

**Comment by gordonwoodhull** [comment]
Ditto for clicking on star/unstar button of another notebook. I think the common behavior is that these update the notebook tree, which may cause the popovers to become unhooked from the info buttons (which have been rebuilt from scratch).
