### ISSUE TITLE
Forking own notebook with 'Ctrl+Enter' creates notebook copy with same name

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1548]
When we fork our own notebook using 'ctrl+enter' the notebook gets forked with the same name and incremented postfix. But the postfix number disappears as soon as it is displayed in notebook div

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11. Very odd.

**Comment by gordonwoodhull** [comment]
Also present in 1.3

**Comment by gordonwoodhull** [comment]
There is still an odd delay when choosing a new name. It would be better to commit the name before doing any UI updates. But this is fixed. In a way it was what you asked for, but it's not helpful.
