### ISSUE TITLE
Group name for private notebook shows null

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1550]
Group name is appearing as null. Below is the scenario to replicate it
* Create a new group and add any notebook to that group.
* Now make the notebook "Private'
* Now click on Note info option, we see group name as 'null' instead of 'No groups' 

![group name null](https://cloud.githubusercontent.com/assets/10941328/8331560/b6a13142-1aa6-11e5-9f50-005896b24f13.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032!

**Comment by gordonwoodhull** [comment]
It should show as Private.

**Comment by anatoliyg** [comment]
I think the expected behaviur would be to show "private" on the tooltip

**Comment by Prateek032** [comment]
Current behavior after making notebook as private, it displays as below

![private](https://cloud.githubusercontent.com/assets/10941328/8348874/d083de36-1b35-11e5-9fc0-69455a7e8c65.PNG).

What if i create a group with its name as 'private'. It shows the same as above screen shot. It might mislead the user

**Comment by gordonwoodhull** [comment]
Okay, we can forbid the group name "private".
