### ISSUE TITLE
File upload feature breaking for notebook that belongs to any group

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1551]
File upload is feature is not working, when that notebook is assigned to any group. The following message is displayed in file upload div.

![fileupload_after_adding notebook to group1](https://cloud.githubusercontent.com/assets/10941328/8331756/9616c04e-1aa7-11e5-87c7-192169240a64.PNG)

And when we reload the tab, following error message is displayed under session div

![fileupload](https://cloud.githubusercontent.com/assets/10941328/8331845/15391318-1aa8-11e5-9aae-5d76fdb809a8.PNG)

**Comment by gordonwoodhull** [comment]
@s-u, we still rely on GitHub language identification but then override it when a language extension has registered the suffix. Is there an easy way to emulate this in the encrypted notebooks?

**Comment by gordonwoodhull** [comment]
Essentially, we use it because there are potentially many different asset languages (e.g. JavaScript, HTML) which are valid even if they are not valid cell languages. So this triggers the corresponding ace mode.

**Comment by s-u** [comment]
I guess we could create an extension-to-language mapping ... But it will be `null` for things like images anyway, right?

**Comment by gordonwoodhull** [comment]
Yeah, it doesn't matter what the language is for binary assets, only for text.
