### ISSUE TITLE
Error while assigning notebook to group

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1558]
Once we add any Notebook to any of the groups, the following error message is displayed

![errorwhileassigningtogroup](https://cloud.githubusercontent.com/assets/10941328/8348698/bea460f2-1b33-11e5-87e3-1f4fcf269623.PNG)

but the notebook is getting assigned to that particular group.
The same kind of error message displayed when we make it 'Public' from 'Group'.

**Comment by gordonwoodhull** [comment]
I'm only able to repro this on selected machines, which makes me think it's a configuration problem. 

Are you seeing this locally, and if so, have you updated your SKS?  I don't see it locally and I don't see it on rcloud-5. I'm currently not able to update rcloud-2 or rcloud-6 due to unrelated issues.

BTW, I've added better error logging, so if you see these abbreviated errors in the protection dialog, please look in the javascript log for the complete stack trace.

**Comment by Prateek032** [comment]
We are able to replicate it on RCloud-5 as well as on RCloud-Local instance only in Firefox browser

**Comment by gordonwoodhull** [comment]
I'm not able to repro on firefox running locally, and i'm not able to log in to rcloud-5 (or rcloud-2) using firefox due to a certificate problem on github.research. :(

**Comment by gordonwoodhull** [comment]
Just saw this on rcloud-2 with Chrome.

Looks like it's an error in error handling (love those):
```
Error: protection.set_notebook_cryptgroup: Error in if (nchar(key) < 64) stop("unable to use group key - likely access denied") : 
  argument is of length zero
R trace:
.encrypt.by.group(list(files = l), group$id)
rcloud.update.notebook(notebookid, list(files = list()))
fun(...)
  argument is of length zero
R trace:
.encrypt.by.group(list(files = l), group$id)
rcloud.update.notebook(notebookid, list(files = list()))
fun(...)
    at success (https://rcloud-2.research.att.com/js/rcloud_bundle.js:135:23)
From previous event:
    at Object.set_notebook_cryptgroupAsync (https://rcloud-2.research.att.com/js/rcloud_bundle.js:141:54)
    at Object.rcloud.protection.set_notebook_cryptgroup (https://rcloud-2.research.att.com/js/rcloud_bundle.js:644:44)
    at setNotebookGroup (https://rcloud-2.research.att.com/js/ui/notebook_protection_service.js:34:38)
    at https://rcloud-2.research.att.com/js/ui/notebook_protection_controller.js:183:43
    at Scope.$scope.saveNotebookTab (https://rcloud-2.research.att.com/js/ui/notebook_protection_controller.js:192:23)
    at Scope.$scope.save (https://rcloud-2.research.att.com/js/ui/notebook_protection_controller.js:480:24)
    at $parseFunctionCall (https://rcloud-2.research.att.com/lib/js/angular.js:12332:18)
    at callback (https://rcloud-2.research.att.com/lib/js/angular.js:22949:17)
    at Scope.$eval (https://rcloud-2.research.att.com/lib/js/angular.js:14383:28)
    at Scope.$apply (https://rcloud-2.research.att.com/lib/js/angular.js:14482:23)
    at HTMLSpanElement.<anonymous> (https://rcloud-2.research.att.com/lib/js/angular.js:22954:23)
    at HTMLSpanElement.jQuery.event.dispatch (https://rcloud-2.research.att.com/lib/js/jquery-2.1.1.js:4409:9)
    at HTMLSpanElement.elemData.handle (https://rcloud-2.research.att.com/lib/js/jquery-2.1.1.js:4095:28)
```

**Comment by gordonwoodhull** [comment]
I'm going to add an `is.null` to that - still undetermined if the encryption code is unstable or if this is a configuration problem.

**Comment by gordonwoodhull** [comment]
sigh, it's not `NULL`, doesn't seem like `is.na` works either ("missing value where TRUE/FALSE needed" either way. I give up. At least the error is on the right line if not descriptive.

**Comment by s-u** [comment]
just change `if(...)` to `if(!isTRUE(...))`

**Comment by gordonwoodhull** [comment]
@s-u, it's still your bug, or the session key servers are in a bad state.

```
Error: protection.set_notebook_cryptgroup: Error in .encrypt.by.group(list(files = l), group$id) : 
  unable to use group key - likely access denied
R trace:
stop("unable to use group key - likely access denied")
.encrypt.by.group(list(files = l), group$id)
rcloud.update.notebook(notebookid, list(files = list()))
fun(...)
  unable to use group key - likely access denied
R trace:
stop("unable to use group key - likely access denied")
.encrypt.by.group(list(files = l), group$id)
rcloud.update.notebook(notebookid, list(files = list()))
fun(...)
    at success (https://rcloud-2.research.att.com/js/rcloud_bundle.js:135:23)
```

The previous line is
```{r}
        key <- session.server.group.hash("rcloud", .session$token, groupid, salt)
```

**Comment by s-u** [comment]
Um - I guess I'm not understanding the bug - I thought it's just giving the wrong failure. Instead of saying "Access denied" it threw the internal error - so the above fixes it. Either case the notebook is not encrypted so the group state should not change.

**Comment by gordonwoodhull** [comment]
All I am doing is switching the notebook back and forth between private and group-protected. There should be no access denied. Maybe we just need to sync SKS with the RCS groups and/or restart both from scratch?

**Comment by gordonwoodhull** [comment]
I get this with a brand-new group as well.

**Comment by s-u** [comment]
The error says simply that the token supplied doesn't match any user registered with the group. One reason would be that your token expired or got replaced. So what exactly is this issue about? I thought it was about the missing `isTRUE` which I suggested a fix for (I can't even run `git pull` so I can't commit anything until next week - that's why I removed myself hoping you can commit that fix). I'm confused since is says "Firefox" only but then you also mention the error on Chrome - so what exactly is the bug here?

**Comment by gordonwoodhull** [comment]
There was an error in error handling, but there is still an error that shouldn't be. I'll just close this and start a new issue because this has gotten cloudy.
