### ISSUE TITLE
Unable to access tagged history version of notebooks from other lakes 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1563]
When we try to access a tagged history version(specifying tag name in url) of any notebook from other lake, it doesn't load that particular history version instead it loads current version of that notebook. However if we try to load history version specifying the version number in the url, it loads that particular history version of the notebook.

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11, this also is expected behavior. Tagged versions will not propagate across lakes.
