### ISSUE TITLE
Group feature error: Providing authorization for multiple users

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1564]
* Create a group with two admins ( obviously one admin will be author of the notebook and for other member add any one's name)
* Now Log in with other admins credentials, that notebook is visible under the All Notebook and will be accessible
* Now second admin has the rights to manage that group. Suppose now he removes the 1st admin( owner of the notebook)
* Now Log back in with 1st admin ( author of the notebook)  and try to load that notebook.
The notebook wont get loaded shows the encryption error.
And he no longer can manage that group ( the group which is created by him )

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032 for the in-depth test case. Yes, when a user is removed from a group, they will no longer be able to access any notebooks in that group - even if they are the author! This is the expected behavior.
