### ISSUE TITLE
"Open in Github" feature is breaking on RCloud-6

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1567]
"Open in Github" feature is breaking for the notebooks in default data lake i.e. public Github as well as for notebooks in different data lake

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11 

...more repercussions of the foreign notebooks feature...sigh...

**Comment by gordonwoodhull** [comment]
This was a configuration error.  `github.gist.url` needs to be specified in rcloud.conf for public github, otherwise the enterprise-like default of `github.base.url` + `gist/` is used
