### ISSUE TITLE
Group name is not visible under Select group drop down menu

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1569]
Steps to replicate the issue:
* Open the Notebook Permissions / Group Management prompt box.
* Now select a group from drop down menu and click on 'Group' tab

![1](https://cloud.githubusercontent.com/assets/10941328/8372042/edb947ee-1bfc-11e5-87dc-c3ec2aa71b95.PNG)

* The selected group name is not visible in drop down menu

![2](https://cloud.githubusercontent.com/assets/10941328/8372060/0d5bc496-1bfd-11e5-8a4f-47fd0b193ccf.PNG)

Once we click on select group drop down menu, the group name appears

**Comment by gordonwoodhull** [comment]
Is this a group you're a member of, but not an admin? We default the Group tab to the notebook group, but only administrable groups are shown, so there can be an "empty group" case there.

**Comment by Prateek032** [comment]
Yes, I am the admin of the group still it shows "empty group" case

**Comment by gordonwoodhull** [comment]
Okay, I see it. It's when you change the group of a notebook and then go to the Group tab.

**Comment by gordonwoodhull** [comment]
I think this is fixed now. The second tab should always show the group of the current notebook, unless you're not the admin of the group, in which case it should show blank (because you have to select something else).
