### ISSUE TITLE
Gist files are displayed in encrypted form, even for the admins/members of group

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1573]
For the notebooks belonging to any group, the notebook contents (the gist file) are displayed in encrypted form when opened in GitHub (even for the admin/ members of the group). Similar behavior observed for the private notebooks

**Comment by gordonwoodhull** [comment]
Of course this is expected behavior. This is the whole point.

**Comment by gordonwoodhull** [comment]
To be more specific: the encryption is an RCloud feature, not a GitHub feature. I think Gists are always readable on GitHub—in any case GitHub doesn't have a concept of encrypted notebooks, or access to our keys, so the notebooks should not be readable, whether the user is logged in or not.
