### ISSUE TITLE
private notebook is private to single server

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1574]
This may be expected behavior, but it's problematic since we have multiple servers sharing RCS/GitHub. 

 1. make a notebook private on, say rcloud-5
 2. try to load on rcloud-2

Error displayed in console:

```
Error: load_notebook: Error in rcloud.decrypt(ec, key) : 
  checksum mismatch - probably wrong key or ciper
R trace:
stop("checksum mismatch - probably wrong key or ciper")
rcloud.decrypt(ec, key)
.gist.binary.process.incoming(res$content)
rcloud.augment.notebook(res)
rcloud.get.notebook(id, version, source)
fun(...)
```

**Comment by s-u** [comment]
This is not a bug - this is by design - servers should never share RCS (unless they also share SKS).
