### ISSUE TITLE
access denied when assigning notebook to own group

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1575]
Observed on rcloud-2:

 1. create brand new group
 2. assign notebook to group

![image](https://cloud.githubusercontent.com/assets/1366709/8413157/83339e80-1e5c-11e5-8424-a1652a46515c.png)

```
Error: protection.set_notebook_cryptgroup: Error in .encrypt.by.group(list(files = l), group$id) : 
  unable to use group key - likely access denied
R trace:
stop("unable to use group key - likely access denied")
.encrypt.by.group(list(files = l), group$id)
rcloud.update.notebook(notebookid, list(files = list()))
fun(...)
  unable to use group key - likely access denied
```

**Comment by fourthark** [comment]
This seems to be univeral - also seeing this locally and on rcloud-5

**Comment by gordonwoodhull** [comment]
Note: the notebook appears to be successfully assigned to the group, but this is because the bookkeeping happens before the encryption operation. So it ends up in an inconsistent state. There may need to be better error handling here: 

https://github.com/att/rcloud/blob/develop/rcloud.support/R/notebook.protection.R#L22-L30

**Comment by s-u** [comment]
Found the problem - it got broken by 3f6e57da which had the logic backward (i.e. it raised an error when there was a valid key).
