### ISSUE TITLE
unable to create group

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1576]
I think this may be an error handling issue, or we need to disable notebook protection. Still I wanted to file the issue because the behavior is unfriendly.

This is rcloud-6, where perhaps SKS can't be expected to work properly, given that the primary lake is Public GitHub. (My public github id doesn't even match my research id).

Can't create a group. Get this error:

![image](https://cloud.githubusercontent.com/assets/1366709/8413319/aff3a6d0-1e5d-11e5-8118-60664413163d.png)

```
Error: protection.create_cryptgroup: Error in fun(...) : 
  unable to register a new group (possibly your authentication expired?)
R trace:
stop("unable to register a new group (possibly your authentication expired?)")
fun(...)
  unable to register a new group (possibly your authentication expired?)
R trace:
stop("unable to register a new group (possibly your authentication expired?)")
fun(...)
```

My authentication has not expired. I just logged in.

**Comment by s-u** [comment]
Works just fine - romo was simply running and old SKS.
