### ISSUE TITLE
Output div doesn't appear for execution of private notebook

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1579]
This issue is observed in RCloud-2 (develop/25e4c24) and RCloud-local (develop/fa6d125)
Steps to replicate:
* Create a notebook, add some code to it and execute (results will be displayed in output div)
* Make that notebook private
* Edit some code or change cell language for a cell
* Try to execute that notebook 

The results will not be displayed however the cell status will show 'green circle'

**Comment by gordonwoodhull** [comment]
Looks like it is fetching empty cell content somehow. Ugh.
