### ISSUE TITLE
Search feature is not working on RCloud-5

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1581]
Unable to search any keyword in search div. Following is the session div error

![search](https://cloud.githubusercontent.com/assets/9251570/8451842/4948b83c-1fb4-11e5-8928-697150a9b45e.PNG)

**Comment by gordonwoodhull** [comment]
Yeah, it looks like it is configured to use another SOLR on the same machine for searching public GitHub notebooks, but there is no server there. Not sure what @s-u intended here.

**Comment by gordonwoodhull** [comment]
In general, we shouldn't use GitHub for tracking configuration problems on the research servers, but we don't have an issue tracker for that, and this is something we need for testing the integration of all the features for the current release.

**Comment by s-u** [comment]
The idea was to test search across servers, but since there is no direct connection it required a local tunnel - which apparently went down. Thus I have removed the SOLR entry for the public github setup.

**Comment by gordonwoodhull** [comment]
okay, then rcloud-5 is not functioning as an integration server with all features active, because searching there is no searching of foreign notebooks.

**Comment by s-u** [comment]
Well, someone would have to configure a remote lake that provides SOLR as well - I don't know of any, but Prateek might ...
