### ISSUE TITLE
Error while forking Notebooks

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1584]
This issue is observed on RCloud-Local instance (387223897fcb4350f593cbbbe040cabc1a0d74cb)
When we click on fork icon, it is forking as expected but in session div we observe the following error

![forking notebook while forking with keyboard cntrl enter](https://cloud.githubusercontent.com/assets/10941328/8477304/a5a13c8e-20e6-11e5-8a5d-20b66702f499.PNG)

**Comment by gordonwoodhull** [comment]
Confirmed. Thanks @Prateek032!
