### ISSUE TITLE
Notebook folder name accepts whitespace while renaming

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1585]
Steps to replicate: 
* Click on any notebook folder to expand it 
* Again click on the folder name to make it editable
* Add only white space in the folder name and press enter

The folder will get renamed with white space.
The white space is not accepted if we rename the folder name by editing it from the notebook title or notebook name in 'Notebooks Div' as it is resolved in #1491

**Comment by gordonwoodhull** [comment]
For that matter, it even accepts an empty name. Thanks @sanketd11!

**Comment by gordonwoodhull** [comment]
Fixed. Now I just have to figure out how to fix all the empty folders I created testing this!
