### ISSUE TITLE
Asset content modification doesn't get reflected in output during cell execution

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1586]
This issue is observed on RCloud-5 (develop/3814944). Steps to replicate:
* Create an '.R' asset in a notebook and add some content to it 
* Execute that asset using 'rcloud.execute.asset' 
* Modify the asset content and click on save option
* Again execute that asset

the modified content will not get reflected in output during execution even though the changes were saved using 'save' option. The modified contents gets reflected in output only if the page is reloaded after making modifications or switching to other notebook and then switch back previous notebook

**Comment by gordonwoodhull** [comment]
Caching is failing. Even if other modifications happen to the notebook, `rcloud.get.asset('scratch.R', cached=TRUE) ` still returns the original version.

**Comment by gordonwoodhull** [comment]
`.session$current.notebook` is not getting updated, a regression from 1.3. 

We just don't notice it because we always explicitly load cells from a version. But this will definitely make running cells slower since it never hits cache.

**Comment by gordonwoodhull** [comment]
E.g. `names(rcloud.support:::.session$current.notebook$content$files)` always shows the assets from the first load, unaffected by added assets or cells.

**Comment by gordonwoodhull** [comment]
Ah, it's a compute-separation bug. Notebooks are cached in both processes. `rcloud.get.asset` runs in compute, but `rcloud.update.notebook` runs in control. 

@s-u wrote:
> CS has one nasty side-effect - since we're re-fetching the notebook for every cell, it gets painfully slow for big notebooks. People were already complaining about the snappiness - which got better with CS in that you can do UI things, but then the execution gets slow which offsets it. We may figure something out for 1.4.1 but not for 1.4.

This is a manifestation of the same problem.

**Comment by gordonwoodhull** [comment]
My kingdom for some control-compute OCAPS! 

(Well not really.)

**Comment by gordonwoodhull** [comment]
This is fairly serious. Do we temporarily disable caching for this method, or, since `cached` is already a parameter, do we tell people to use the workaround (and train them to do things inefficiently :-/).

**Comment by s-u** [comment]
Several possible solutions here - the most immediate fix is to inform compute when the UI changes the notebook. This can be done by simply adding an OCAP on the compute side and calling it from the UI along with the control OCAP - this was compute can update the cached contents accordingly.

Longer-term fix is to add the ability of compute to call control (not too hard - it's the sample piece of code in control that does forwarding for compute to WS which would inspect OOB and process some of them locally). That way compute would always ask control for any notebook content. This would also allow dis-immedation of compute so it never needs credentials.

I would argue to use the former now for 1.4 and latter for 1.4.1.

**Comment by gordonwoodhull** [comment]
Ugh, I don't like UI being the binding between compute and control, but I can add this temporarily for 1.4.

**Comment by s-u** [comment]
Yes, I agree but that's all we can do at this point AFAICS :/ It will be easy to remove once notebook management moves entirely to control.
