### ISSUE TITLE
Forked Notebook retains protection group of parent notebook

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1590]
If a notebook which is either private or assigned to any group, is forked, new copy of that notebook is created however that newly created notebook automatically gets assigned to the group or becomes privet similar to its parent notebook

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11.

Yes, this is the desired behavior, because we don't want notebooks to accidentally become public. Once protected, it should take a deliberate act to make them public again.
