### ISSUE TITLE
Unable to load shiny.html and mini.html links

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1591]
Following are the console errors:
For shiny.html
![shiny](https://cloud.githubusercontent.com/assets/9251570/8511414/5d19d28e-2332-11e5-9194-cfb8bfc5fd67.PNG)

for mini.html
![mini](https://cloud.githubusercontent.com/assets/9251570/8511419/7d0b89a2-2332-11e5-816a-99000c5dfbcd.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11

Looks like one of these is on you @anatoliyg, and one is on me. 

The protection UI stuff should go in require-edit.js not -common. 

And I probably broke mini trying to move the rest of the dcplot stuff out. (Which is still not done.)

**Comment by gordonwoodhull** [comment]
Ooops, the angular/selectize modules were not the cause of the shiny problem, shiny was simply not installed on the server. Still better to localize those requirements, though. @anatoliyg you're off the hook here.

**Comment by gordonwoodhull** [comment]
The mini.html error is also a configuration issue, rcloud.dcplot will need to be upgraded and simple mini.html notebooks work just peachy.

**Comment by gordonwoodhull** [comment]
resolved, and rcloud.dcplot is nicely modularized now
