### ISSUE TITLE
Long group names goes outside of the notebook info popover  

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1593]
Long group  names doesn't get wrapped as seen in below screen shot

![popover](https://cloud.githubusercontent.com/assets/9251570/8511607/de5cea74-233d-11e5-9010-4263f4032f9f.PNG)

**Comment by gordonwoodhull** [comment]
I think the popover would have to fit the text. I don't think it's a priority for this release.

**Comment by anatoliyg** [comment]
I agree the popover should fit the text. but should we put a limit on how long you can make the group's name as well?

**Comment by gordonwoodhull** [comment]
Okay, but it should be pretty long, like 80 characters, because the namespace is across all users. I'll do that part on the backend.

**Comment by anatoliyg** [comment]
e5e0e8e
