### ISSUE TITLE
Who are the members of this group?

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1595]
An user is able to assign his own notebooks to a group, of which the user is a member. This behavior might be insecure as the there is no way for a member of any group to know about all the other members in that same group

**Comment by gordonwoodhull** [comment]
If there is a problem, I think it's the latter rather than the former. One should be able to know the other members of a group, if one is a member. Not sure where to display that though.

**Comment by gordonwoodhull** [comment]
As discussed in #1589, the admins&members of groups should be public knowledge.

**Comment by gordonwoodhull** [comment]
I think the friendly way to handle this is to list the admins and users on the notebook page, so that you know what you're getting into when you click OK.
