### ISSUE TITLE
breaking API change in RClient.create

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1598]
@s-u, as discussed in email, we now require a new field `mode` in the options object passed to `RClient.create`. This was introduced by e8be7f406ef59ae41370cefc0179f700788229b4, and is a breaking change for notebooks which embedded their own "mini.js", which we *wanted* them to do instead of relying on mini.

I'm willing to make the change and chase down the consequences, but wanted to confirm with you that the fix is right: the field should not be required; it should default to the value ("client") which works for notebooks calling other notebooks. Right?

And the value "IDE" which the front-end needs should be specified everywhere that the front-end creates RClients, if it isn't already.

**Comment by gordonwoodhull** [comment]
FWIW, I searched the research instance for notebooks using `RClient.create` which are not forks of the one in question, and there is only one. It looks like it was just a test by Jyothi of loading html/js from the notebook instead of from mini.

This exhibits the same failure, and it's a simpler test. My fork here:
https://rcloud.research.att.com/notebook.R/3219bae4a2ec02447bf2/loadPage.html

**Comment by prateek05** [comment]
What about the project with "fishing" data... They would be using the same ???

**Comment by gordonwoodhull** [comment]
Could you send me a link? This will be encountered by notebooks which establish an RCloud session with `RClient.create` but which don't use mini.js/mini.html (or have copied those files into the notebook).

I propose leaving the notebooks unchanged and making the `RClient.create` API backward compatible. But we should test any that are out there.

**Comment by prateek05** [comment]
mailed it to you

**Comment by gordonwoodhull** [comment]
Closed by 92de3283fd1c7aaf1fca5f028e7b5d7fd9875a98
