### ISSUE TITLE
Open in GitHub constructs the wrong URL source for a notebook with a different source

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1599]
1) Open a notebook with a different gitsource
2) Click open in github

The url constructed is of having the hostname of the parents github source

**Comment by gordonwoodhull** [comment]
Yes, good point. This is one of many features not supported for alternate gist.source.

It doesn't look like the alternate gist.sources are exposed on the server API. Not a big deal to add them.

**Comment by gordonwoodhull** [comment]
Note, `github.gist.url` (for public-y) or `github.base.url` (for enterprise-y) must be specified for the gist source in order for this to work.
