### ISSUE TITLE
session.server.R uses RCurl lands up in SSL issues

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1600]
Get and Post for SKS and SOLR are through RCurl and httr. 
the verisign cert is set only for httr options.
We should make all of them use httr for consistency.

**Comment by s-u** [comment]
Did you try something like

```
options(RCurlOptions = list(cainfo="/data/rcloud/conf/verisign.crt"))
```
in `conf/local.R`? This should be really just a local deployment setting...

**Comment by prateek05** [comment]
Tried it just now... Still hits wit SSL Curl error. By the way it only happens when we go in compute seperation mode. 
Prateek

**Comment by s-u** [comment]
FWIW this is not a certificate issue so the options are a red herring.

**Comment by prateek05** [comment]
Evaluation error: Error in function (type, msg, asError = TRUE) : Peer certificate cannot be authenticated with known CA certificates

**Comment by s-u** [comment]
That error should be easy to fix as described above by providing the CA chain in `cainfo`.

**Comment by prateek05** [comment]
You were right! Its after the fork it gets into a bad state from the console:
[1] "Error in function (type, msg, asError = TRUE)  : SSL connect error\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<SSL_CONNECT_ERROR in function (type, msg, asError = TRUE) {    if (!is.character(type)) {        i = match(type, CURLcodeValues)        typeName = if (is.na(i))             character()        else names(CURLcodeValues)[i]    }    typeName = gsub("^CURLE_", "", typeName)    fun = (if (asError)         stop    else warning)    fun(structure(list(message = msg, call = sys.call()), class = c(typeName,         "GenericCurlError", "error", "condition")))}(35L, "SSL connect error", TRUE): SSL connect error>

**Comment by prateek05** [comment]
FYI underlying library openssl-1.0.1e-16.el6_5.15.x86_64

**Comment by s-u** [comment]
It's a know issue with CURL

http://stackoverflow.com/questions/15466809/libcurl-ssl-error-after-fork

attempted work-around in 0ea89b9
