### ISSUE TITLE
forking foreign notebook with binary asset fails

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1606]
`unable to convert R type 24 to JSON`

![image](https://cloud.githubusercontent.com/assets/1366709/8941181/270e3312-353c-11e5-8a3e-10737b87c7bd.png)

**Comment by s-u** [comment]
We should move all forking to the back-end code, otherwise we'll keep running into this mess of passing some internal objects to JS and back over again.

**Comment by gordonwoodhull** [comment]
agreed. will do for 1.5

**Comment by gordonwoodhull** [comment]
No, wait. This is already a back-end fork. 

And now `rcloud.fork.notebook` is returning base64-encoded text for the asset, instead of binary.

**Comment by gordonwoodhull** [comment]
Source notebook: https://rcloud-2.research.att.com/edit.html?notebook=e3e44d95d99faf4a15e2

Resulting gist: https://gist.github.com/gordonwoodhull/09ef3e30e55a651a2768

**Comment by s-u** [comment]
Ah, sorry, I misinterpreted "foreign" - this is as in from another gist source - yes, that is server-side, will have a look (FWIW the notebook above [`e3e..`] is empty so you probably changed it in the meantime)
