### ISSUE TITLE
recent notebooks: use ellipsis code from notebook_title.js

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1621]
It could be a bit wider (if not clipped by the panel, #1620), maybe fitting 40 characters or so.

Then since some people *do* tend to end up with really long notebook names and lots of folders, it should use the "smart ellipsis" code from ui/notebook_title.js, which calculates the size dynamically in pixels, and clips the folders before the notebook name.

**Comment by anatoliyg** [comment]
still need to perfect this and move to utils
