### ISSUE TITLE
clicking on cell code the first time causes horrible scrolling effects

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1624]
I think there are probably half a dozen bugs here. The window scrolls, the code scrolls, the cursor ends up in a different place from what was clicked. 

It is hard even to diagnose the problem there is so much wrongness here.

Users report this is worse as of 1.4, so perhaps the fix for #1358 exacerbated it somehow.. That commit was 48122f6aead5ac72434dcd042f9a41b798fea6f3

But we aren't sure, it might be that users just remember things working before RCloud 1.2 changed the cell implementation from Ace everywhere to static text that must be activated.

**Comment by martymcwizard** [comment]
in our 1/19 discussion we stopped discussion when we reached agreement on:
"where you click should be where your cursor ends up when you are switched to edit mode"

**Comment by holyguster** [comment]
Right, so if I scroll down and click on row 67 in between the 10th and 11th characters, when the cell changes over to edit mode, my cursor should be on row 67 in between the 10th and 11th characters.

**Comment by gordonwoodhull** [comment]
@shaneporter, sorry to throw one more at you, but this is the other major user annoyance besides the slow load. If you're up for some serious UI troubleshooting, we could definitely use your help here!

**Comment by gordonwoodhull** [comment]
@shaneporter fixed this by keeping the cells the same height when active, which I think is an elegant solution because it means no more scrolling at two levels. 

There are still slight differences in the fonts and word wrap behavior between active and inactive mode, but it is much much better than it was.
