### ISSUE TITLE
notebook scrolls on autosave

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1626]
create a notebook taller than the page. it seems to scroll to somewhere in the middle of the notebook content when the notebook autosaves.

this is particularly annoying if you're typing in the command prompt at the time

**Comment by anatoliyg** [comment]
I think my fix makes it better

**Comment by gordonwoodhull** [comment]
It's got the twitch, and I don't think it always returns to exactly the same spot. 

I generally don't like fixes that try to sweep stuff under the rug. I want to revert this. 

Hopefully we can put in a fix for the real issue in a patch release.

**Comment by gordonwoodhull** [comment]
I just narrowed down the cause of scrolling to this line:

https://github.com/att/rcloud/blob/develop/htdocs/js/ui_utils.js#L302

Setting the ace content causes it to rebuiild something in the DOM. But we are setting the content of the ace widget, even when the content hasn't changed, or when the content has changed to exactly what we already know it to be. This is due to our interpretation of the MVC paradigm and not necessary. 

I think we should figure out how not to reload the cells when they change in ways that we already know about. Hopefully without passing a flag through the entire chain of MVC, which would be a huge mess.

**Comment by gordonwoodhull** [comment]
This was reclosed by git merge fun, it's still open.
