### ISSUE TITLE
Code contents disappears after forking

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1631]
Steps to replicate:
1.Upload 2 or more binary assets to the notebook ( i tried with 277kb of pdf file  and 423kb of CSV file)
2. click on fork option
The notebook cell contents are disappearing.

**Comment by gordonwoodhull** [comment]
@s-u, appears there are still truncation issues here:
![image](https://cloud.githubusercontent.com/assets/1366709/9313688/4df1c3c0-44f2-11e5-824a-12315f1c0aba.png)

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032!

**Comment by gordonwoodhull** [comment]
This is the annoying self-fork special case on the front end. It uses `rcloud.create.notebook` - does that also need the second pass for truncated assets?

**Comment by s-u** [comment]
Ah, likley, I didn't realize `create.gist` can supply content - simply adding `.fix.truncated()` should fix it in that case.
