### ISSUE TITLE
Cell execution doesn't show output 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1632]
This is related to compute separation.
Steps to replicate:
* Execute any notebook using 'Run all'
* At the same time fork any folder in notebook div
* Now try to execute any cell from that notebook

The cell status will show 'executed' but the output will not be displayed. This behavior goes away after page reload

**Comment by gordonwoodhull** [comment]
Confirmed. Thanks @sanketd11 - like #1602, some calls must be resetting the current notebook, and then there is no error reported when cells fail to load #1633.

**Comment by gordonwoodhull** [comment]
Note: this is only an issue when forking one's own folders of notebooks, because it arises from the ever-feared self-fork hack and a client-side bug in `rcloud.create_notebook`

**Comment by gordonwoodhull** [comment]
It's potentially a problem with forking folders of foreign notebooks, though... 

:scream:

**Comment by gordonwoodhull** [comment]
putting that one off and fixing the others.
