### ISSUE TITLE
really long completions get truncated in menu

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1635]
![image](https://cloud.githubusercontent.com/assets/1366709/9313631/f235d5e4-44f1-11e5-9725-d101257bc933.png)

**Comment by shaneporter** [comment]
I was hopeful of an event (onShowAutocomplete or something) I could hook into so that the width could be set. No luck unfortunately.

Although not the most robust solution, I could increase the `width` property for the `.ace_autocomplete` selector. Its value is 280px.
