### ISSUE TITLE
Proper message should be displayed, while opening encrypted notebook

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1638]
Consider the following scenario:
1. Create One private notebook with user1 and note down the notebook ID
2. Log in with another user ( user2) and open the user1's notebook in view.html
3. It displays the following message on the screen

![shoulddisplaypropermsg](https://cloud.githubusercontent.com/assets/10941328/9348945/2053fc74-465c-11e5-9907-d7dabfa61ee3.PNG)

Although the user2 is logged in but still it displays 'You may need to login to see it', instaed it should display proper message

**Comment by gordonwoodhull** [comment]
this error message is really annoying, it's a catch-all, "if anything went wrong, it must be that you're not logged in."
