### ISSUE TITLE
Error while deleting comments

### ISSUE THREAD

**Issue by prateek032** [att/rcloud#1640]
While deleting the comments the following error message is displayed in session div.

![commenterrr](https://cloud.githubusercontent.com/assets/10941328/9349765/03fcb7a8-4668-11e5-97ef-66fe1897cb33.PNG)

![commenterr1](https://cloud.githubusercontent.com/assets/10941328/9349769/0cb1fc50-4668-11e5-833f-93b6f0a32a03.PNG)

Although  we are not able to reproduce it.

**Comment by gordonwoodhull** [comment]
looks like more search/solr bugs.

**Comment by gordonwoodhull** [comment]
can't reproduce with rcloud.solr
