### ISSUE TITLE
Still able to assign white space as sub folder names 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1644]
Steps to replicate:
* Create a notebook sub folder within any folder
* While creating the sub folder include some white space in the folder name
* Click on the sub folder name to rename it and remove the characters but keep white space from the name then press enter

The sub folder will be renamed with only white space  as folder name

![empty folder name](https://cloud.githubusercontent.com/assets/9251570/9351018/c44053d4-4623-11e5-9543-27337bc6b899.PNG)

**Comment by gordonwoodhull** [comment]
The folder rename logic was still just validating on a non-empty, non-whitespace string, not validating each part of the path as we do elsewhere.
