### ISSUE TITLE
space in password causes login to fail

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1651]
Hopefully I have captured this well enough to be understood here....

If a user has a space as part of their password, RCloud does not correctly encode and forward that on to AUTH/pam authentication, so the response from AUTH/pam is that the login FAILED.

We have come across this issue a couple of times with RCloud users, and just get them to change their password to eliminate the space.  Seems like this should be fixed.

**Comment by holyguster** [comment]
Data point:  In our environment here, one user with a space in their password gets Auth Failed on rcloud, but *successfully* gets in on rcloud-2 (including using the space in their password).

**Comment by prateek05** [comment]
`"https://host.sub.domain:4301/auth_token?realm=rcloud.exec&user=testpam&pwd=test%20test"`
works fine. Infact URIencode encodes `<space>` with `%20` just fine.

Tested this with a test account on the linux box. Wondering if its something to do with PAM on the network auth service. Any volunteers !? Changing their password and running the diagnostic to see what PAM says!? :)

**Comment by s-u** [comment]
The issue was that `URLdecode` in R does not decode `+` to space so it needs to be treated separately. This happened in the parsing piece of `script.R` where the raw query is converted to R objects so it only affected proxified setup.
