### ISSUE TITLE
Undefined Something went wrong in 'Recent' option list for deleted notebooks

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1656]
The deleted Notebook are displaying like below

![recent_option_after_deleting_nb](https://cloud.githubusercontent.com/assets/10941328/9682312/9c3f6db8-52d3-11e5-9065-0253b20755ba.PNG)

**Comment by gordonwoodhull** [comment]
As we discussed, please filter the list to remove these. These kinds of glitches are always possible in a system with concurrent users, and it would be difficult to remove the entries from all other users' recent lists when another user deletes one of their notebooks.
