### ISSUE TITLE
Unable to load foreign data lake Notebooks 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1657]
The search results display links to the notebooks from foreign data lake but when tried to access it throws session div error 

![fdn](https://cloud.githubusercontent.com/assets/9251570/9712955/56f088be-551c-11e5-811b-29c8c53c48f6.PNG)

**Comment by prateek05** [comment]
The GHE API Access point changed for internal lakes. Would suggest the system admin of the box this issue was found at to get a copy of the current GHE and SOLR from the Prod in research

**Comment by holyguster** [comment]
Fixed on the rcloud-2 and rcloud-5 test machines.
