### ISSUE TITLE
Asset contents are getting replaced with html content

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1658]
This issue is observed for CSV files with size large file size ( 512 Kb and above)  on RCloud Research instances
Steps to replicate:
* Upload any csv file of size 512kb or above to notebook
* Rename that csv file in asset div  

The Actual contents of csv file will be replaced by html contents showing github link for that csv assset

![asset](https://cloud.githubusercontent.com/assets/9251570/9713334/bea74f04-551e-11e5-8d98-b15bb7c444ad.PNG)

**Comment by s-u** [comment]
This seems like a new "feature" of GHE since the latest update - we may need to change the way we fetch the RAW links. Also this is likely the cause that made you re-open #1578.

**Comment by s-u** [comment]
@sanketd11  please test if this fixes the issue and also if this fixes #1578

**Comment by sanketd11** [comment]
Issues #1658 and #1578 seem to be resolved on RCloud-2 with the latest commit e92587b41383574036d9a0293e12eeb843495398

**Comment by s-u** [comment]
Thanks!
