### ISSUE TITLE
Image assets overlaps with other Divs 

### ISSUE THREAD

**Issue by iPrateek032** [att/rcloud#1660]
When any image is uploaded to notebook in asset div, that image overlaps with the other divs present below. In the below screenshot, "File upload' and 'Workspace' Divs got overlapped by the image 

![asset_image](https://cloud.githubusercontent.com/assets/12950376/9783488/34da1cd8-57c2-11e5-8dcd-6b77311bf802.PNG)

**Comment by gordonwoodhull** [comment]
@anatoliyg, could you take a look at this one as well?

**Comment by anatoliyg** [comment]
Ok

**Comment by anatoliyg** [comment]
@gordonwoodhull  If the image is larger than the panel it's in, should it scale to show fully within the panel or should we allow vertical scrolling? or is this a z-index issue and it just needs to be behind the panel, not scrollable

**Comment by gordonwoodhull** [comment]
I think it should scroll, but I also think it's a z index issue, as I have fixed similar problems with many of the other panels before, by changing the way they calculate their height. Hard to say if it's worse to have a visual glitch or part of the content that's inaccessible...

**Comment by anatoliyg** [comment]
got the binary asset to not spill outside. Scrolling coming up next

**Comment by anatoliyg** [comment]
for now, we decided to leave it so the large images are simply cropped, without having a scrollbar. We should be able to add scrollbar functionality in the future
