### ISSUE TITLE
Make system addons not RCS based

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1666]
rcs.system.config.addons currently creates or re assigns the RCS key. 

It becomes a problem when multiple instances use the same RCS backend but have different addon modules. Would it be a good idea to make it conf file based and not read/write to RCS key!? Just like deployment conf parameters

Thanks,
Prateek

**Comment by prateek05** [comment]
@gordonwoodhull  Would it be possible to vote up :+1: this issue for 1.5

**Comment by gordonwoodhull** [comment]
I'm fine with this. I can't remember why we did the system-level addons in RCS. Maybe it was just for consistency with user-level addons, which have to be stored there. @s-u, do you remember?

**Comment by s-u** [comment]
No Idea, I don't remember why the system settings are not config-based. It looked always odd to me that you could override RCS with a config file - it should either be RCS only or config-only IMHO.

**Comment by gordonwoodhull** [comment]
Probably some miscommunication, I remember us talking about it but not why this seemed like a good idea.

**Comment by gordonwoodhull** [comment]
I put a ton of work into implementing this the wrong way, with a lot of advice from @s-u, and a fair amount of cruft is going to be left behind - see 28000c422c91f921214685c3e3e3da5b08e0c584. See also the work @s-u put into cleaning up what I did, 9240a9d50b3ddb0a1ba79be8c495ec6b02b8a5c2

Oh well. Life is cruft.

**Comment by gordonwoodhull** [comment]
The new rcloud.conf key is `rcloud.alluser.addons` - @prateek05, please note.

**Comment by gordonwoodhull** [comment]
Note, the other feature that uses this misfeature is `rcs.system.config.featured_users`, which populates the RCloud Sample Notebooks tree. Again, I have no recollection why.

**Comment by s-u** [comment]
I think I recall now why we used RCS - that makes sure that the state is synchronized across all back-end servers.

However, that raises a more general issue - a lot of the config directives have to be synchronized across the back-end servers, while some of them are custom (e.g. the hostname).

**Comment by gordonwoodhull** [comment]
It doesn't really, though, since each server will likely have its own setting, so they'll just overwrite each other whenever they're restarted. 

I think this was the right change. But yeah, there is probably a better model...

**Comment by s-u** [comment]
No, that was before config overrides - the idea was that RCS will hold the setting, but later on the config override was put in place which defeated the original purpose. Now it all makes sense :). Going to config only is the right thing.
