### ISSUE TITLE
change File Upload to deposit files in RCloud home instead of UNIX home

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1671]
File Uploads that are not uploaded to the notebook currently get put into the users home directory.

This works fine for some environments, but does not work well for a few of the AT&T data lakes, where home directories are not cross-mounted, and the policy is that little data be stored there.

I propose that a prefix be added to rcloud.conf to control this.

For example, something like this might be good for most environments:

     rcloud.deployment.file.upload.prefix:~/ 

And,

     rcloud.deployment.file.upload.prefix:/opt/data/share01/${USER}

would work for a couple of the AT&T data lakes.

If the target directory does not exist, then they should get an error when trying to upload.

**Comment by gordonwoodhull** [comment]
Good idea. I did a quick test. 

```{r}
write('hello', "~/hello.txt")
```

works, but

```{r}
write('bye', "/Users/${USER}/hello.txt")
```

@s-u, is there a simple way to expand environment variables in a string?

**Comment by s-u** [comment]
`path.expand()`

**Comment by s-u** [comment]
No, not beyond `path.expand()` which does the `~` expansion. We do `gsub("${ROOT}", getConf("root"), ...)` but could probably generalize ...

**Comment by gordonwoodhull** [comment]
I guess something like that would be fine here, since we're only looking for the one environment variable.

**Comment by s-u** [comment]
But more generally - this is not about file upload but user's `$HOME`. We do assume that it exists and is usable. I think it's entirely wrong to think of this as a file-upload "feature". The current contract is that it is accessible in the home, so I'd say this is about having incorrect home location in the deployment rather than an RCloud issue ...

**Comment by s-u** [comment]
To clarify, I think `rcloud.deployment.file.upload.prefix` is a really bad idea, it's masking a problem in the deployment, it will affect many other things beyond the file upload.

**Comment by holyguster** [comment]
@s-u and I chatted a bit, and came up with:

(1) Make RCloud user home configurable, and add an API call to get the path.  tracking that under #1673

(2) Change the behavior of the File Upload to deposit files in the RCloud user home instead of their UNIX home.

**Comment by gordonwoodhull** [comment]
It's great when the code is already commented with FIXME. :wink:

upload.R 
```{r}
# FIXME we need a better place for this.
rcloud.upload.path <- function() Sys.getenv("HOME")
```

**Comment by s-u** [comment]
This should now probably just be

```r
rcloud.upload.path <- function() rcloud.home()
```

**Comment by gordonwoodhull** [comment]
Thanks, will apply and test.
