### ISSUE TITLE
make rcloud user home configurable and add an API call to get the path

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1673]
currently is under $ROOT/data/userfiles; should be configurable, and there should be an API call to get the path.

this could be set to /opt/data/share01 on the various data lakes.  RCloud would create a user directory there if it did not already exist, with permission 700.

**Comment by gordonwoodhull** [comment]
@s-u, is this something you want to address for 1.5? I'm willing to do the file upload path part.

**Comment by s-u** [comment]
Ok, done. I think

```r
rcloud.upload.path <- function() rcloud.home()
```

may be all we need form here.
