### ISSUE TITLE
Session Div error while renaming large CSV asset

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1675]
Similar to #1578  but different error message
Steps:
- Create new notebook
- Upload large csv asset 
- Make that notebook private
- Try to rename the asset 

Following error is thrown in session div :

![private_csv_rename](https://cloud.githubusercontent.com/assets/9251570/10133968/91135f3c-65ff-11e5-985c-f6ad61f3e835.PNG)

**Comment by gordonwoodhull** [comment]
I'm not able to repro this locally, on rcloud-2 or rcloud-5. Please clarify?

**Comment by gordonwoodhull** [comment]
@sanketd11, please verify. This passes the Moby Dick test for me.

**Comment by sanketd11** [comment]
Verified on RCloud-2 & 5 (release-1.5/ 906d5ee) and local (release-1.5/ edc6bb0) . Not reproducible

**Comment by s-u** [comment]
Thanks!
