### ISSUE TITLE
Unable to fork folder from other users notebook tree

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1688]
Steps to replicate:
1. Fork a folder from other users notebook tree
2. Now again click on the same icon (folder fork)
it gives us alert like below

![folderforkalert](https://cloud.githubusercontent.com/assets/10941328/10217715/4743153a-684f-11e5-9ce0-b2772fbf9592.PNG)

Now delete the forked folder from 'My Notebooks' and again click on 'fork folder' it gives us the same above alert instead of forking a  folder

**Comment by gordonwoodhull** [comment]
This is because notebooks are not truly deleted until you delete them from the GitHub interface.
