### ISSUE TITLE
Forking own notebook folder creates multiple copies of notebooks in the same folder

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1690]
Steps to replicate:
- For any notebook folder present in my notebooks click on the folder name to make it editable
- Press 'Ctrl+ Enter' to fork notebook folder

This will create multiple copies of notebooks in the same folder instead of creating new folder where as clicking on 'fork icon' besides folder name creates multiple folders

**Comment by gordonwoodhull** [comment]
This works as designed. While the default should be to create new folder names, the ctrl-enter "power user feature" should respect the name the user entered. It's the same case as if the user wanted to fork some other folder into an already existing folder.
