### ISSUE TITLE
Foreign data lake notebooks disappear from 'Recent' list

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1698]
- Load any notebook from foreign data lake 
- Switch back to other notebook from default data lake
- Reload the page 

The notebook belonging to foreign data lake will disappear from 'Recent' list

**Comment by gordonwoodhull** [comment]
The behavior is identical to the notebook tree: if the notebook is not owned or starred when the session is closed, it will disappear both from the tree and the recent notebooks list. The "catalog" is defined by the undeleted notebooks owned by current users, and the notebooks starred.

TL;DR: starring is the way to keep a foreign notebook around.
