### ISSUE TITLE
installation typo

### ISSUE THREAD

**Issue by salivian** [att/rcloud#1702]
typo: add-apt-repository -> apt-add-repository

**Comment by gordonwoodhull** [comment]
I'm not an expert in ubuntu admin but this SO answer says they are synonyms?

http://askubuntu.com/questions/83489/what-is-the-difference-between-add-apt-repository-apt-add-repository

**Comment by gordonwoodhull** [comment]
@salivian, did this actually cause trouble / are there Linuxes where these are not synonyms? I'm closing for now. The SO answer seems to indicate that we're using the actual one and not the symlink.
