### ISSUE TITLE
Toggle edit mode adds extra lines to code in non editable mode

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1703]
Steps to replicate:
- Create a new cell
- Copy any code content from assets or another cell
- Paste that code in newly created cell 
- click on toggle edit button

Extra lines will be added to code in non editable mode as seen in below screen shots
editable mode
![before_](https://cloud.githubusercontent.com/assets/9251570/10302703/7ba9adf8-6bdc-11e5-87e5-d321fb195be8.PNG)

non editable mode

![after](https://cloud.githubusercontent.com/assets/9251570/10302716/884c4ffc-6bdc-11e5-9c2f-00dbd0af1fb0.PNG)

Also the line numbers are misaligned in non editable mode. This issue is reproducible on RCloud-2, RCloud-5 instances only

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11.

Which platform and browser is this? Looks like a formatting issue.

**Comment by sanketd11** [comment]
I was able to reproduce this issue on RCloud-2 and RCloud-5 with chrome browser only

**Comment by gordonwoodhull** [comment]
Operating system?

**Comment by sanketd11** [comment]
Windows OS

**Comment by gordonwoodhull** [comment]
This looks like an extreme example of #1266. 

You may not believe us, but it's hard to see the difference between active and inactive mode on OSX, except for the line break issue #1375. We wish it that way everywhere.

**Comment by gordonwoodhull** [comment]
This bug probably goes back to 1.3, btw, just our users were too polite to complain.
