### ISSUE TITLE
JS timeout causes RCloud to apparently hang foerever

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1710]
JavaScript timeouts are not caught so RCloud seems to be hanging forever while loading - example trace below. RCloud should show an error message and provide a re-load button if that happens.

This may be one of causes for #1283 although that issue doesn't have enough details to tell.

```
Uncaught Error: Load timeout for modules: shell_tab
http://requirejs.org/docs/errors.html#timeout
https://rcloud.research.att.com/shell_tab.js Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
require.js:141 Uncaught Error: Script error for: shell_tab
http://requirejs.org/docs/errors.html#scripterror
```

**Comment by gordonwoodhull** [comment]
Yes, this is precisely #1283 - this issue should be about reporting the problem better, and that one about fixing the underlying problem in Rserve or our use of nginx.

**Comment by gordonwoodhull** [comment]
Moving this to 1.5.1 - should be easy to catch.
