### ISSUE TITLE
don't rewrite parts of url that don't concern rcloud

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1713]
currently when the notebook is loaded `ui_utils.make_url` creates a new URL to replace the current history item, without looking at the current url.

this interferes with notebook uses of query parameters. RCloud should, probably via the same little library rcloud.params will use, just replace the parameters it knows about.

**Comment by gordonwoodhull** [comment]
A couple of libraries in this space:

https://github.com/Mikhus/jsurl (just the parsing part, no history manipulation)

https://github.com/ryanburnette/Qurl (with history support)

(we might need tighter control over history than qurl offers; see https://github.com/att/rcloud.params/issues/1)

**Comment by gordonwoodhull** [comment]
Related: when a notebook is opened via `?user=...&path=...`, we shouldn't rewrite that with the hash, if possible.

**Comment by gordonwoodhull** [comment]
@bashlee, you can ignore the stuff about history. I think it will be sufficient just to manipulate the current url instead of rewriting it from scratch. There may be other good URL libraries too, these are just what I found in a quick search 2.5 years ago.

**Comment by gordonwoodhull** [comment]
@useless5771, thanks for the warning in `rcloud.params/README.md` 

Are you willing to look at this? 

I built a couple small but comprehensive JS libraries for round-tripping URL parameters. They are both more and less than what we need here - same model I think, but exclusively JS based, and here we need to do the validation on the R side.

https://github.com/dc-js/dc.graph.js/blob/develop/querystring.js
https://github.com/dc-js/dc.graph.js/blob/develop/sync-url-options.js

We probably can't use them directly, but some of their techniques may be relevant.

If for some reason you don't want to take this up, I can do it...

**Comment by useless5771** [comment]
Yes, this is actually the first item on my todo list :)
