### ISSUE TITLE
Notebook name in forked link doesn't get updated 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1716]
Steps:
- Fork any notebook from our own notebook tree. The link to the parent notebook will be displayed below notebook name

![forked](https://cloud.githubusercontent.com/assets/9251570/10573036/d8a81e98-766a-11e5-9133-c702c4c3c177.PNG)
- Go back to the parent notebook and rename it 
- Switch back again to forked notebook

The updated parent notebook name doesn't get reflected in the fork link

**Comment by gordonwoodhull** [comment]
The root cause is we are storing `fork_of` data for self-forked notebooks as a notebook property, with `owner`, `id`, and `description`. This is an incorrect way to imitate the GitHub API, which of course doesn't store this data statically.

I could fix the symptom for the 1.5.1 patch release easily, but I'd rather go deeper and not store the extra data. So I'm putting this off to 1.6.

**Comment by gordonwoodhull** [comment]
```{js}
            if(fork_of && fork_of.description) {
                var owner = fork_of.owner ? fork_of.owner : fork_of.user;
                var fork_desc = owner.login+ " / " + fork_of.description;
                var url = ui_utils.make_url(shell.is_view_mode() ? 'view.html' : 'edit.html',
                                            {notebook: fork_of.id});
                $("#forked-from-desc").html("forked from <a href='" + url + "'>" + fork_desc + "</a>");
            }
```
https://github.com/att/rcloud/blob/develop/htdocs/js/ui/notebook_title.js#L105-L111

```{r}
        rcloud.set.notebook.property(new.nb$content$id, "fork_of",
                                     new.nb$fork_of <-
                                     list(owner=owner,
                                          description=src.nb$content$description,
                                          id=src.nb$content$id))
```
https://github.com/att/rcloud/blob/develop/rcloud.support/R/rcloud.support.R#L594-L598

**Comment by gordonwoodhull** [comment]
Although this issue has to do with our self-fork workaround, we faced a related issue with our new gist backend, which doesn't have a central database from which to populate metadata.

So henceforth the only `fork_of` field we will use is `id`. I'm also removing the code which set the other fields for self-forks and cross-source forks. When a notebook is loaded which has `fork_of.id`, we just fetch the description and owner of that notebook from RCS.

I believe this is consistent with the way we use RCS to populate the notebook tree, and it normalizes RCS a tiny bit.

There is the possibility that the fork parent is not in RCS (e.g. if the notebook was created in another instance); in this case the link will simply display 

![image](https://cloud.githubusercontent.com/assets/1366709/25811072/06fc1572-33e0-11e7-9cfc-5c8a85df7351.png)
