### ISSUE TITLE
Enhancement: Find and Replace feature  should display count for search results

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1720]
Currently it highlight the results but it doesn't display the count for the search results. As shown below

![find_replace](https://cloud.githubusercontent.com/assets/10941328/10630429/67eaa172-77a4-11e5-8067-a2abd4398f92.PNG)

**Comment by shaneporter** [comment]
Chrome's search automatically highlights a matching string, which is only done in RCloud when the 'next' or 'previous' buttons are clicked.

The match index is also performed from the current selection (if any).

So, to do what Chrome does, we would need to:

1 - Perform the initial highlight when search text is modified.
2 - Calculate the match index based on the current selection (if any).

Seems as though they are desirable improvements that could be encapsulated by this enhancement.

**Comment by gordonwoodhull** [comment]
I am seeing it highlight immediately, but it doesn't highlight the "current" one in orange immediately, or scroll to it. IT

**Comment by shaneporter** [comment]
Suggested implementation opened with #2107.

**Comment by gordonwoodhull** [comment]
implemented in #2107

**Comment by Prateek032** [comment]
I couldn't find this enhancement on release-1.6/ 112bd78

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032, failed to merge this somehow, must have been juggling branches. 

Reopening to close with proper commit.
