### ISSUE TITLE
Prompt cell becomes inaccessible when Find & Replace is invoked

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1723]
This issue occurs for a notebook containing  two or more cells so that it covers whole page and scroll bar displayed. When we invoke 'Find & Replace', the prompt cell becomes inaccessible. The scroll bar can't be scrolled down to see the prompt cell. It becomes accessible again after closing ' Find & Replace'

![find replace](https://cloud.githubusercontent.com/assets/9251570/10631239/86f437ee-77aa-11e5-9bf7-cf1d23723b18.PNG)

**Comment by gordonwoodhull** [comment]
fixed by #1829
