### ISSUE TITLE
do pseudo-readline history in input field of context

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1729]
normally R uses the gnu readline library for command editing and history, which preserves history across calls and whatever you type into R.

this is helpful in debugging because you're always typing the same variable name to print it. but you can end up getting into history that has nothing to do with your debugging session, which you usually don't want.

rcloud should fire up a history instance with the minimal readline imitation we use for the command prompt. the history could be local to the output context, to the cell, share history with the prompt, or share history only with other readlines within the notebook, i'm not sure which.

**Comment by holyguster** [comment]
My gut response is that history should be local to the cell, regardless if prompt cell or code cell.

I'll chew on it some more.

**Comment by gordonwoodhull** [comment]
Thanks @holyguster, that was my first thought too. The fact that command-line R gets "universal" history is just an artifact of the way it uses Gnu readline. 

One reason it might be helpful to get more history is if you debug two cells in succession. Then you might arrow up to your debug commands on the last cell. But that's probably rare. Getting back your command prompt stuff is probably not useful (and I find it annoying when using command-line R).
