### ISSUE TITLE
Execution of python cell leads to session reconnect 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1732]
This issue can be reproduced only on RCloud-2

**Comment by prateek05** [comment]
looks like bad python install :) Most likely mismatched ipython. The python wiki has the right version.

**Comment by gordonwoodhull** [comment]
I think there is some customization of the scripts for Anaconda on that server which got lost recently - @s-u, do you know how to fix it?

**Comment by prateek05** [comment]
ecaz might have it.

**Comment by gordonwoodhull** [comment]
Thanks @prateek05, that's essentially what I put on rcloud-2 but it didn't help - now it just hangs. Still, I don't think this is an RCloud bug, just a system configuration problem, so I'm closing this.
