### ISSUE TITLE
Add a way to clear the Session pane

### ISSUE THREAD

**Issue by CourseraStudent58** [att/rcloud#1734]
The contents of the Session window is very helpful.
But as it gets long and you have to scroll a lot, it would be helpful if it could be cleared between runs.

**Comment by s-u** [comment]
You can always remove cells that you deem unnecessary. If you start new work, you just create a new notebook.

**Comment by CourseraStudent58** [comment]
Perhaps I am not using the correct terminology.  I don't mean a new RCloud Notebook session.  Rather, I am referring to the "Session" tab that appears in the lower right section of the RCloud UI.  When a user Rund their code, log info appears in this Session tab.  I normally have debugging sequences where I Edit-Run-Edit-Run...and all the while, the log info is appending inside the Session tab.  I'm suggesting that I'd like to "clear" that Session tab between each Edit-Run iteration.

**Comment by s-u** [comment]
Ah, ok, got it, yes, makes sense - feature request to clear the Session pane.

**Comment by gordonwoodhull** [comment]
I often want a Reset Session button - usually to clear JavaScripts but also to clear R variables. 

I wonder if we should combine these features, and further whether it would be nice to have an option to have the Run All button also reset the session. Because right now you aren't sure if your notebook really works if you press Run All. Simple ex: `library(X)` is in a cell after package `X` is used.

**Comment by prateek05** [comment]
+1 on clearing R for RunAll

**Comment by gordonwoodhull** [comment]
There are two requests here:

 - [ ] an option (default enabled) to reset the R session when pressing (or invoking with what's-that-hotkey) Run All. Resetting the session always clears the session pane.
 - [ ] a little button in the header of the session pane to clear the content like the new notebook button. (This would benefit from #463 but could be implemented independently.)

**Comment by gordonwoodhull** [comment]
The button could be 
![image](https://cloud.githubusercontent.com/assets/1366709/15562271/dd48fd2e-22cb-11e6-9ce3-79359a968412.jpeg)
only white on black

**Comment by CourseraStudent58** [comment]
I like first option [an option (default enabled) to reset the R session when pressing (or invoking with what's-that-hotkey) Run All.].  Reason: less clutter and user can override option for backwards compatibility behavior.  Plus, the proposed button for the second option is ginormous! ;-)

**Comment by shaneporter** [comment]
@gordonwoodhull I like the button; but I'm guessing you'd prefer it if it were a little smaller? :smile:

**Comment by gordonwoodhull** [comment]
sigh, ok, we can make it a little smaller 😉 

i think we should do both. there will be times when you can't reload your notebook yet the session pane is clogged up and you need to look at the first message that appears after running a cell.

**Comment by shaneporter** [comment]
@gordonwoodhull I'm running things and I don't see anything output to the session pane. What's the easiest/best way to generate a lot of output to the session pane? 

Also, can I suggest this icon (other sizes are available :wink:)

![image](https://cloud.githubusercontent.com/assets/2493614/16840496/eccb19b2-49cc-11e6-8883-3fae229d9282.png)

The [eraser](http://fontawesome.io/icon/eraser/) icon is more synonymous with clearing than a cross, evoking 'delete' or 'remove'.

**Comment by gordonwoodhull** [comment]
Huh, I hadn't seen that icon before, sure that makes sense.

You can generate session logs directly using e.g.

```r
rcloud.session.log(1:1000)
```

**Comment by gordonwoodhull** [comment]
Note, #1997 is related.

**Comment by shaneporter** [comment]
Thanks, I thought there'd be something like that :smile:

Noted about #1997.

**Comment by gordonwoodhull** [comment]
@shaneporter, please do the clear button and I'll see about resetting the session. 

Since #1997 requires using another library and possibly changing the output format to something with uniform height, I think we'd better put that off. 

But at least if we have a clear button then if the user notices the browser is in danger of crashing, they can clear the session pane.

**Comment by shaneporter** [comment]
@gordonwoodhull - looks like I missed something from this, namely the setting - that's in PR #2269. Let me know if there's anything else you need from 'my side'.

**Comment by gordonwoodhull** [comment]
I implemented this via `shell.load_notebook()`, which is kind of slow. Reset was not enough because the R session needs to know about the current notebook. 

We could revisit this in the future.
