### ISSUE TITLE
Forking from foreign lake retains fork_of without lake source

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1736]
So if you fork a foreign notebook you would have the fork_of attributes with hashid but clicking that on the title would generate a url without the source and end up looking for the notebook in the local backend 
Prateek

**Comment by gordonwoodhull** [comment]
Hi @prateek05! 

We do cache the source of any opened notebook, so yeah, this shouldn't happen. 

But somehow I doubt you tested this just now. :-D

**Comment by prateek05** [comment]
@gordonwoodhull  yeah this was an really old thing i forgot to close then. Updated the status recently  :)
