### ISSUE TITLE
debug thumb doesn't show the first time

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1737]
first time i run the discovery page, all the images are broken links:

![image](https://cloud.githubusercontent.com/assets/1366709/11005074/c3f13d5e-8489-11e5-91c1-5b39e024e3ab.png)

seems to be a race condition, as adding a breakpoint sometimes helps, as does increasing the delay at discovery_page.js:75

using all these delays is probably not a safe way to deal with this - we should be able to determine when the `img`s have actually been created and add the handler then.

**Comment by anatoliyg** [comment]
Strange. Shouldn't be any race conditions there. The delays are just to make sure the model has populated. I'll take a look

**Comment by gordonwoodhull** [comment]
and let me guess, you can't wait for that explicitly because that's not how angular works..

**Comment by anatoliyg** [comment]
Well, usually it's not needed if the whole app is in angular. But since the data comes as a result of non- native angular operation (rcloud sockets vs angulars own $http), there's some trickery to when the data actually appears available inside the controllers $scope.
