### ISSUE TITLE
discovery page should use logo/title plugin

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1740]
i'm not sure what other navbar buttons would be appropriate here, but it should at least say RCloud (with the option to customize)

**Comment by gordonwoodhull** [comment]
Sorry I wasn't specific about this - it should use the same mechanism that the other pages use, which allows customization and display of the instance (lake).

Although I do like the big logo displayed here better than what the rcloud.logo package does!

**Comment by anatoliyg** [comment]
Hehe cool

**Comment by gordonwoodhull** [comment]
making the logo bigger is att/rcloud.logo#1
