### ISSUE TITLE
notebooks with content error in view.html

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1741]
Open any notebook in view.html, following message is displayed

![python_view_html](https://cloud.githubusercontent.com/assets/10941328/11031959/2e01abe0-86fe-11e5-9091-d2e71e6f9ae0.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032! Must remember always to test view.html when changing the edit.html UI. This is the kind of thing that automated testing will find immediately.
