### ISSUE TITLE
switch from isotope to masonry

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1742]
RCloud is MIT licensed, and using the GPL-licensed isotope for the discovery page causes us to become GPL, which we don't want. 

Masonry should offer the same functionality, if somewhat less efficient/up to standards.

**Comment by gordonwoodhull** [comment]
http://stackoverflow.com/questions/8856893/difference-between-isotope-and-masonry-jquery-plugins

**Comment by anatoliyg** [comment]
Cool

**Comment by gordonwoodhull** [comment]
Looks great. You still need to remove the isotope library and references to it.
