### ISSUE TITLE
Posting and Deleting comments, session div displays error

### ISSUE THREAD

**Issue by prateek032** [att/rcloud#1743]
While Posting and deleting comments, session div displays following error

![11postingcomments](https://cloud.githubusercontent.com/assets/10941328/11110755/2b231ec0-8926-11e5-9efa-2982109b89b7.PNG)

**Comment by gordonwoodhull** [comment]
Not able to repro. Would be fixed by rcloud.solr if it was more than an intermittent bug in the first place.
