### ISSUE TITLE
Notebook title doesn't get wrapped in Discover page

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1745]
![titlespills](https://cloud.githubusercontent.com/assets/10941328/11112914/d0370932-893d-11e5-905b-577b4d6c4495.PNG)

**Comment by iPrateek032** [comment]
This issue is no longer reproducible in Chrome browser but still persists in Firefox browser

**Comment by Prateek032** [comment]
This issue is no longer reproducible in Chrome browser but still persists in Firefox browser

**Comment by shaneporter** [comment]
Submitted PR #1935 to tackle this issue.
