### ISSUE TITLE
discover page has long load time

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1746]
On Research RCloud, it takes about 10 seconds to just display "Loading notebooks".  Before it says "Loading notebooks", there is just a black title bar.  After it says "Loading notebooks", it takes only 2-3 seconds to finish. 

Might be good to give some indication that load/startup activity is happening even before displaying "Loading notebooks".

**Comment by gordonwoodhull** [comment]
Yes. I haven't looked deeply into the code but it seems to be fetching the notebook metadata before it shows "Loading Notebooks"  (actually right now it generates the notebook tree but doesn't use it), and when it says it's loading notebooks it's actually loading the images.

Optimizing the image loading is another option we've talked about, but as we know, loading the notebook tree is slow in itself.
