### ISSUE TITLE
discover page star icons are always shown full

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1759]
In discover page even for a notebook with zero star count it shows filled star icon as shown in below screenshot

![discoveremptystar](https://cloud.githubusercontent.com/assets/9251570/11626979/1f0759d0-9d0d-11e5-9aa9-68249b17fe0b.jpg)

Notebooks with zero star count in notebook tree

![emptystarnbtree](https://cloud.githubusercontent.com/assets/9251570/11626980/1f0e56b8-9d0d-11e5-9026-6b450ddde170.jpg)

**Comment by gordonwoodhull** [comment]
Clarification: notebooks *not starred by the current user* should have an empty star icon.

If running discover page while not logged in, no star should be filled (as well as no unpublished notebook shown).

**Comment by gordonwoodhull** [comment]
@paulinshek, @shaneporter, I'm going to assign you both the outstanding issues on the discover page - not sure who wants to take what. Most of this is client-side.

**Comment by shaneporter** [comment]
Have modified code so that 'empty' stars are shown for 0 stars, full completion of this issue dependent on #2061.

**Comment by gordonwoodhull** [comment]
@shaneporter, that doesn't sound quite right. The filled-ness is not about the total number of stars; it is about whether the current logged-in user starred those notebooks. Hopefully the notebook tree reflects this; it's easy to miss this in testing.

**Comment by shaneporter** [comment]
It was more your comment _If running discover page while not logged in_

Also, because the star counts are coming back from the server, I'm assuming there is no client side code to explicitly manage this. It's just a case of using a different icon if it's 0.
