### ISSUE TITLE
unwanted formatting in copied text on OSX

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1764]
(do they still call it rich text? i'm old)

Seems like copying anything from the notebook (including the welcome message) to e.g. an OSX Mail email, results in the text successfully pasted but with some formatting that makes it invisible.

Changing the email to plain text reveals it. Another workaround is to paste via a text editor.

**Comment by shaneporter** [comment]
Do you know of an Ubuntu app that exhibits the issue?

**Comment by gordonwoodhull** [comment]
Hmm, I'm not able to repro on Ubuntu and LibreOffice - it looks like they somewhere drop all formatting from text copied from the browser (?)

My description above was imprecise. The problem is that a lot of formatting does get copied. In the case of the welcome message, the pasted text is invisible. In the case of cells, I get blue and grey bars through the text (here pasted into Mail):

![image](https://cloud.githubusercontent.com/assets/1366709/14614540/a4f0b8a0-056f-11e6-8613-9bea51d99cbb.png)

I expect to see similar results on Windows, which definitely supports rich text copy and paste, but I don't have access today, so I'm labeling this an OSX bug for now.

**Comment by gordonwoodhull** [comment]
I am pretty sure the blue bars were not happening before, and the grey bars were omitted because they were entirely `.nonselectable` - but this is very tricky stuff and maybe there is a better way (for example, it might be easier to get it right if we didn't use the selection but only the selected cells, see #1879).

https://github.com/att/rcloud/blob/develop/htdocs/js/ui/init.js#L70-L87

**Comment by gordonwoodhull** [comment]
So, even worse, I pasted some stuff into a message. It was invisible. Then I pressed backspace and *everything else in the message* became invisible!

![image](https://cloud.githubusercontent.com/assets/1366709/14862615/4544d7a2-0c80-11e6-8ea3-386cf8958845.png)

**Comment by shaneporter** [comment]
I tried this in 'Outlook Mail' (I still call it Hotmail) and replicated the 'where's my text?' issue. Pasting as plain text into Hotmail works works. 

Tried in various editors and things seem to work ok.

**Comment by gordonwoodhull** [comment]
Glad you were able to replicate somewhere. Yes, it's exactly the paste as html or paste as rich text that fails. 

Since we are synthesizing the data that gets copied in an off-screen div, we're either adding formatting that makes it invisible, or we're copying it out of the notebook wrong. 

Probably some kind of clipboard inspector tool would point out the problem immediately. Last time I looked into it, all the possible formats got copied to the clipboard independently.

**Comment by shaneporter** [comment]
Good idea about the clipboard inspector. Here's 'CopyQ' for Ubuntu showing two copied items

![image](https://cloud.githubusercontent.com/assets/2493614/19592959/2407a57a-9776-11e6-9bcf-700f103a5df8.png)

The top item is a copied selection from RCloud.

**Comment by gordonwoodhull** [comment]
ah, that's a beaut 😏  - does it show the source as well?

**Comment by shaneporter** [comment]
Yeah, it's got the HTML (in this case for the two cells it has selected), and when I paste it into jsfiddle, I see the expected output.

**Comment by useless5771** [comment]
Tried reproducing this with no luck, tried various selections, including cells with plots; pasting into Outlook, Outlook webmail and gmail, none exposed issues mentioned in here. However I haven't tried OS X which is the environment in which this happens.

I noticed however that for some selections (when the last element in the selection is a new-line) chrome adds a 'BR' element with class: 'Apple-interchange-newline', e.g.:

```
<meta http-equiv="content-type" content="text/html; charset=utf-8"><pre class="response" style="box-sizing: border-box; font-family: Monaco, &quot;DejaVu Sans Mono&quot;, &quot;Droid Sans Mono&quot;, &quot;Lucida Console&quot;, Consolas, monospace; font-size: 13px; white-space: pre-wrap; display: block; padding: 16px; margin: 0px; line-height: 1.42857; color: rgb(51, 51, 51); word-break: break-all; word-wrap: break-word; background-color: rgb(245, 245, 245); border: 0px; border-radius: 0px; max-width: 100%;">RCloud 1.8-devel (features-issue-2401/d9b30c6), R version 3.2.3 (2015-12-10) <br style="box-sizing: border-box;">Welcome, useless5771</pre><div class="notebook-cell" id="part1.R" style="box-sizing: border-box; border-width: 0px; padding: 0px; margin-top: 0em; background-color: white; position: relative; width: 1127px; min-height: 25px;"><div style="box-sizing: border-box;"><div class="source-div" style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Verdana, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><div class="code-div" style="box-sizing: border-box; position: relative; tab-size: 4; display: block;"><div class="rcloud-gutter" style="box-sizing: border-box; background-color: rgb(245, 245, 245); position: absolute; width: 48px; height: 27px; cursor: pointer;"></div><pre class="edit-code inactive" style="box-sizing: border-box; font-family: Monaco, &quot;DejaVu Sans Mono&quot;, &quot;Droid Sans Mono&quot;, &quot;Lucida Console&quot;, Consolas, monospace; font-size: 13px; white-space: pre-wrap; display: block; padding: 0px 0px 2px; margin: 0px; line-height: 1.42857; color: rgb(51, 51, 51); word-break: break-all; word-wrap: break-word; background-color: rgb(238, 243, 247); border: 0px; border-radius: 0px; max-width: 100%; cursor: text;"><code class="r hljs " style="box-sizing: border-box; font-family: Monaco, &quot;DejaVu Sans Mono&quot;, &quot;Droid Sans Mono&quot;, &quot;Lucida Console&quot;, Consolas, monospace; font-size: 11px; padding: 1px 6px 0px 54px; color: inherit; white-space: pre-wrap; background-color: transparent; border-radius: 0px; border: 0px; display: block; max-width: inherit; margin-right: auto; margin-left: 0px; word-break: normal; line-height: 1.1;"><span class="hljs-number" style="box-sizing: border-box; color: mediumblue;">1</span>+<span class="hljs-number" style="box-sizing: border-box; color: mediumblue;">1</span> 

</code></pre></div></div><div class="r-result-div" style="box-sizing: border-box; padding: 16px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Verdana, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><pre style="box-sizing: border-box; font-family: Monaco, &quot;DejaVu Sans Mono&quot;, &quot;Droid Sans Mono&quot;, &quot;Lucida Console&quot;, Consolas, monospace; font-size: 12px; white-space: pre-wrap; display: block; padding: 0px; margin: 0px; line-height: 1.42857; color: rgb(51, 51, 51); word-break: break-all; word-wrap: break-word; background-color: white; border: 0px; border-radius: 0px; max-width: 100%; cursor: text;"><br class="Apple-interchange-newline"> 
```

This <br> element is added automatically by Chrome, Firefox doesn't do this.

Difficult to say without actually being able to reproduce that this might be the cause of the formatting issues.

Another thing that I noticed is that the 'offscreen' element created by the select_allowed_elements function in Firefox gets included in the copied HTML snippet but in Chrome it isn't.

I can have a look at select_allowed_elements and possibly delete the trailing br, but would be good to have a confirmation that this 'Apple-interchange-newlline' is what is causing the issue.

**Comment by gordonwoodhull** [comment]
Yeah, this is difficult to repro and I guess we need someone with a Mac to look at it. I thought maybe since Shane was able to repro in Outlook that maybe it was a cross-platform issue but I guess that was just a fluke.

**Comment by s-u** [comment]
- it seems to happen only in view-mode cells (not in ace edit mode) and in results
- drag&drop works in results
- the effect is that the text is off-screen on far right

**Comment by gordonwoodhull** [comment]
Browsers don't seem to accept that 
> `parentNode` itself is not part of the selection.

for [selectAllChildren](https://developer.mozilla.org/en-US/docs/Web/API/Selection/selectAllChildren)

Previously we had `<pre class="offscreen">` as the parent.

HTML fans will recognize the solution: make it `<div class="offscreen" />` and put the `<pre />` inside it.

**Comment by gordonwoodhull** [comment]
Results are weird, because it pulls some formatting from the notebook. But it works.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/1366709/70765722-980bdb80-1d29-11ea-9eef-e660b848b944.png">
