### ISSUE TITLE
'Generic' js-based plotting?

### ISSUE THREAD

**Issue by eddelbuettel** [att/rcloud#1765]
So I got @cscheid 's example from the screencast working -- `wtour()` on Iris is very nice.

How would I go about using Javascript-based plotting more generally?  In the sense of RStudio now having a 'Viewer' pane besides the 'Plot'?  Is that something that could happen here?

(Not sure where else to ask this.  Is there a better forum, or shall I just open tickets?)

**Comment by gordonwoodhull** [comment]
Hi @eddelbuettel, that's a pretty big question. There are all kinds of ways to use JavaScript with R.

What particular packages are you looking to use? Or are you thinking of writing the visualizations yourself?

**Comment by gordonwoodhull** [comment]
In general, we support two sorts of interactive JavaScript-R plots: ones in notebook cells, and ones via mini.html (with freeform, non-notebook layout).

We support (most of) Shiny through shiny.html, which is a variant of the mini.html approach. Here's an example:

http://rcloud.social/shiny.html?notebook=68d114c159e5c364ae7e

The flagship interactive plots-integrated-with-rcloud-cells is rcloud.dcplot a.k.a. wdcplot

http://rcloud.social/edit.html?notebook=af829ffb418ed0f054d1

**Comment by eddelbuettel** [comment]
I am no green with RCloud (and so bewildered by the documentation ...) that I didn't even kniw about `mini.html`.  I was assuming notebook cells.  My goto-example would be the [CRAN package dygraphs](https://cran.rstudio.com/web/packages/dygraphs/index.html), but I am really just scratching the surface.

(Your links to `rcloud.social` didn't resolve for me.)

**Comment by gordonwoodhull** [comment]
Yeah, we are very short on documentation. The best we've got is here: http://att.github.io/rcloud/

Everyone relies on the examples to get started, that's the good and the bad of a social coding platform. So I'm disappointed that the public site isn't loading for you. Do you see the site at all? It will require you to login through GitHub, etc.

**Comment by eddelbuettel** [comment]
`rcloud.shiny` by itself works. Links for documentation to github.io (and I had seen/used that).  

Might the fact that I am logged into _out_ local GHE be an issue?  Incognito mode does not work either for the quoted link.

[ And yes, working from examples is awesome and best ... ]

**Comment by gordonwoodhull** [comment]
So it's the edit.html links that don't work? 

Your login status for GHE shouldn't matter, that's independent from your public github login status (and obviously you're logged into public github). 

Maybe our login redirects aren't working; try http://rcloud.social/login.R and then the links?

**Comment by eddelbuettel** [comment]
Success!!   Going to `login.R` first was the key.  Having shiny is good (though we run a Shiny Server here).

**Comment by gordonwoodhull** [comment]
The really cool native RCloud vis packages use direct bindings between R and JavaScript functions across the Rserve protocol. However, it's brand new tech and we're a tiny team, so there are just a few libraries - rcloud.dcplot and a couple of leaflet things, rcleaflet and rcloud.dcmap. And the demos like wtour, wgeoplot, wplot.

General compatibility with the RStudio world of html widgets should be in the next version, although I don't know if it will the cell paradigm or the mini paradigm yet. (The latter is easier.) 

I have not looked at dygraphs, will check it out.

**Comment by eddelbuettel** [comment]
The related question, of course, is why shiny.html and mini.html do work on my local RCloud instance :/  

For mini.html I just get an empty screen with 20 lines of html viewable as source.

**Comment by holyguster** [comment]
I just opened #1766 on this topic.

**Comment by gordonwoodhull** [comment]
@eddelbuettel, you've installed rcloud.shiny? The next step would be to check the JavaScript browser console for any errors.

**Comment by eddelbuettel** [comment]
Ahh. If rcloud.shiny is an extra add-on then I have not (yet).

**Comment by gordonwoodhull** [comment]
Yeah, we try to do almost everything through extension packages (even parts of the UI). Only the basics are automatically installed; the rest are usually on rforge.net.

**Comment by gordonwoodhull** [comment]
We got htmlwidgets support in 1.7. Communication between R and JavaScript is [documented in the wiki](https://github.com/att/rcloud/wiki/R-JavaScript-binding). There's always more we can do, but I consider this question answered.
