### ISSUE TITLE
if not logged into GitHub and RCloud, unpublished notebook shiny and mini links show nothing

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1766]
For example, the first link below points at an unpublished notebook.  If user is NOT logged in to both GitHub and this specific RCloud instance, the browser will just be blank with no feedback to the user (though there is an error on the developer console if the user looks):

http://rcloud.social/edit.html?notebook=68d114c159e5c364ae7e

Whereas this notebook is *published*.  Works fine if logged out of GitHub and/or this RCloud instance:

http://rcloud.social/shiny.html?notebook=bd12ad56f869cd6198dc

For view.html notebook links, if not logged in and trying to look at an unpublished notebook, the user gets a message "Could not load notebook. You may need to login to see it."

For mini and shiny notebook links to unpublished notebooks, should RCloud inform the user that they may need to login to see it, or is this something RCloud will leave up to the developer of the mini/shiny notebook?

**Comment by gordonwoodhull** [comment]
Currently these view types have no UI in which to display such problems. 

I'm considering changing the categories of view types for RCloud 1.6, since there are various UI features people tend to use. We could consider the Aw Shucks dialog one of those features...

**Comment by gordonwoodhull** [comment]
Right now the workaround is to look at the JavaScript console. Errors should always be displayed there.

**Comment by gordonwoodhull** [comment]
We now show the error per #1995
