### ISSUE TITLE
ctrl-click in recents menu should open in new tab

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1777]
unfortunately we are special-casing control-clicks everywhere, to restore the browser's default behavior.

it would be helpful here.

**Comment by shaneporter** [comment]
Where's the recents menu? Thanks.

**Comment by gordonwoodhull** [comment]
It's the button/menu labeled Recent in the title of the notebook pane. I think it should have one of those inverse-caret things to make it clear a menu will appear.
