### ISSUE TITLE
load notebook tree more asynchronously

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1781]
This is another follow-up to #405, first load is slow. 

Previously we made building the tree UI lazy, but we're still loading all the data, and this is slow, both because it's a huge RCS query and because so much data must be crammed through the wire.

The more intelligent thing to do would be to model the tree on the back-end. Currently the server has no idea that there is a notebook tree, so this is is some work, but it might help with stuff like #1402 reflecting changes to the tree made in other sessions.

The easier thing to do would be to load each user's notebook tree on-demand. Since we currently don't have any features that organize the notebooks in any other structure, this would be fast and effective.

**Comment by gordonwoodhull** [comment]
Actually, we don't need to model the whole tree on the server. All we really need to do is load the notebooks for each user on demand. We estimate that the most active users of RCloud will have 500-1000 notebooks, which should be an acceptable amount of data to load. The problem arises with hundreds of users times hundreds of notebooks.

We only open one branch of the tree at once, so we only need to load one user's notebooks at a time. Then we can build that tree and display it.

The relevant API is `user.all.notebooks`, which is not currently exposed on the client. I'll expose that and then @shaneporter, you should be able to rework the editor_tab to load parts of the tree on demand. 

https://github.com/att/rcloud/blob/develop/rcloud.support/R/rcloud.support.R#L558

This fix is high priority for this release.

**Comment by gordonwoodhull** [comment]
Done - the JS API is `rcloud.config.all_user_notebooks(username)`

**Comment by gordonwoodhull** [comment]
Implemented in #1901

**Comment by gordonwoodhull** [comment]
Here are the improvements for me (couple hundred starred notebooks), on a fully-populated but underutilized develop server (rcloud-5).

### Without this optimization
Notebook infos loaded: **11483**
Average first load time: **16.92s**
Time spent initializing UI: ~**2.4s**

### With lazy loading
Notebook infos loaded: **316**
Average first load time: **4.88s**
Time spent initializing UI: ~**0.8s**

**Comment by shaneporter** [comment]
Pretty good. 🙂
