### ISSUE TITLE
"redo" on current version throws error and goes to last version

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1786]
@shaneporter, a little glitch here - when you hit the redo key on the current version, it looks like it's searching for `null` in the history, not finding it, and then not handling the `-1` correctly:

```
Uncaught TypeError: Cannot read property 'version' of undefined
```
https://github.com/att/rcloud/blob/develop/htdocs/editor_tab.js#L1098

Then it goes to the penultimate version as if "undo" were requested.

**Comment by shaneporter** [comment]
@gordonwoodhull a change to the get_current_notebook_history_index function should have resolved this.

**Comment by gordonwoodhull** [comment]
The redo to penultimate version turned out to be redo and undo being run concurrently due to the ambiguity of cmd-opt-Z and cmd-Z on Mac. (Same root cause as #1785.)
