### ISSUE TITLE
blurring edit mode on cells

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1791]
We will need to at least "blur" (unfocus) any cell or the command prompt when a cell selection event happens for #658, so that we take keyboard commands directly.

Currently we don't deactivate cells unless they are run or you click the edit button manually. The rationale is that we don't want to fully deactivate because it can cause cell height changes and disorientation. 

So I guess I've just convinced myself that we still don't to deactivate cells automatically, but we do need to blur them.

Anatoliy suggested that there should be a manual key to deactivate when you are editing a cell, probably ESC. I think this makes sense.

**Comment by gordonwoodhull** [comment]
@sanketd11, @Prateek032, @shaneporter, we discussed this today.. here's the issue I filed in January. (Makes you wonder what other gems might be buried in the tracker.)

Since the description above is kind of rambly, the two points are:
 - [ ] selecting or deselecting any cell should blur any active cell (or prompt or asset)
 - [ ] ESC key inside the active cell should blur it

Even though deactivation is now theoretically stable, I don't want to go that far yet. There doesn't seem to be any expense in keeping Ace active (but there is a big expense in activating the first time, which is why we do this).

**Comment by shaneporter** [comment]
If a cell is active, it is implied to be in the editable state.

You're just talking about blurring its focus on `ESC`, rather than setting it to read only (as if the user clicked the 'edit' button for that cell. Is that right? 

Is deactivation the same as setting it to read only?

Thanks.

**Comment by gordonwoodhull** [comment]
I'm just talking about the keyboard focus here. Probably my first description was too confusing and I should remove it.

"Read only" for me means that there is no way to edit it, like someone else's notebook. "Activated" means that the Ace editor is live, but not necessarily having the focus, whereas "deactivated" means that it is our html imitation of the Ace look (and a slightly lighter background).

**Comment by shaneporter** [comment]
thanks for the clarification.

**Comment by shaneporter** [comment]
A fix has been suggested with PR #1991.

**Comment by gordonwoodhull** [comment]
Clarified title.
