### ISSUE TITLE
Problems installing from Windows

### ISSUE THREAD

**Issue by cirocco** [att/rcloud#1799]
Clean installation via bootstrapR.sh fails.
Windows installation. R version 3.2.3. Tried to install through bash and also through Rstudio.

Notes below. Suggestions?

 /data/rcloud
* checking for file ‘rcloud.support/DESCRIPTION’ ... OK
* preparing ‘rcloud.support’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘rcloud.support_1.4-0.tar.gz’

Error in file(file.path(dir, "PACKAGES"), "wt") : 
    cannot open the connection
Calls: <Anonymous> -> file
In addition: Warning message:
In file(file.path(dir, "PACKAGES"), "wt") : 
   cannot open file '/data/rcloud/packages/src/contrib/PACKAGES': No such file or directory
Execution halted

**Comment by prateek05** [comment]
Hi @cirocco 
I dont think we have ever tested our distribution on windows. You could first establish if the latest Rserve installs first from www.rforge.net. 

If you have access to a linux machine I would suggest using that.
Prateek

**Comment by gordonwoodhull** [comment]
Yeah, @s-u can correct me if I'm wrong, but I don't think we ever intend to support Windows server-side. On the client side we support Chrome and Firefox on Windows.

**Comment by s-u** [comment]
Yes, correct, Windows lacks `fork` so you can't really use it as an R server.

**Comment by shaneporter** [comment]
The lack of Windows support isn't explicitly mentioned anywhere is it? Sounds as though it should be added to INSTALL.md.
