### ISSUE TITLE
run button keeps animating/blinking

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1812]
if you press it a lot of times fast, it will keep flashing for a while after you stop. It doesn't look like the notebook is continuing to run, more like the animation gets stacked up.

**Comment by shaneporter** [comment]
Running this from a JavaScript console will do the same sort of thing:

`_.times(20, function() { $('#run-notebook').click() });`

**Comment by gordonwoodhull** [comment]
Cool, thanks for the automated repro, @shaneporter.

I notice this also happens in view mode - when the notebook has a lot of cells, the play button will stay illuminated for a long time after the notebook has finished. If the notebook only has a few cells, it will stay illuminated just for a short time.

The animations should preempt and not queue up.
