### ISSUE TITLE
"freshness" notebook tree filter

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1817]
It would be nice to have a filter along the lines of "show only notebooks no older than 3 months in the notebook tree". The motivation is that as we are using RCloud for a while now, it accumulates notebooks and the tree becomes less manageable. However, in the vast majority of cases you're interested only in recent notebooks related to projects you're working on, so hiding older notebooks would reduce clutter. As a secondary use it would also work as a discovery tool "what are people up to these days".

**Comment by gordonwoodhull** [comment]
related: #1075 sort all notebooks by date, #522 sort user's notebooks by date

**Comment by gordonwoodhull** [comment]
Implemented in RCloud 1.9

**Comment by s-u** [comment]
cool, thanks!
