### ISSUE TITLE
Open in GitHub feature is not working for anonymous user

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1823]
Open any published notebook in view.html as anonymous user and try to open the notebook in GitHub using 'Open in GitHub' feature

**Comment by gordonwoodhull** [comment]
Wow. Did this ever work. The error is "Uncaught TypeError: rcloud.get_notebook_info is not a function"

**Comment by gordonwoodhull** [comment]
I think for safety we'll have to implement `rcloud.unauthenticated.get.notebook.info`, yuk.
