### ISSUE TITLE
remove the grabby handle

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1827]
I know @cscheid carefully designed the "grab affordance" icon, but I think it's time to retire it. 

Using the cell title & bar for rearranging cells is pretty clear, especially since the grabby hand appears.

It is also looking especially cluttered next to the new selection checkbox.

We should remove it. Optionally (not sure about this) the status icon could go first and selection checkbox second.

**Comment by cscheid** [comment]
"Carefully" is about five notches too kind.

**Comment by gordonwoodhull** [comment]
fixed in #1843
