### ISSUE TITLE
Replaced word still getting highlighted in Find/Replace

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1839]
Steps to replicate
1. Create a cell which contains word repeated 2-3 times
2. Invoke Find/replace for that word
3. Now replace any occurrence of that word with the new word
4. Search for previous word again
Still the replaced word also gets highlighted for the search

**Comment by gordonwoodhull** [comment]
Oo. Sounds bad. Thanks @Prateek032! 

This feature is a lot more complicated than it looks.
