### ISSUE TITLE
Import button is disabled while importing Notebook from file

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1840]
1. Open import notebook from file 
2. select any one of the file 
3. Now press <ENTER> key, and again select a file
Import button is disabled
![import1](https://cloud.githubusercontent.com/assets/10941328/13741927/35d51154-e996-11e5-8660-1cc7f44c198a.PNG)

**Comment by gordonwoodhull** [comment]
Thanks for reporting this, @Prateek032!

**Comment by shaneporter** [comment]
I can only reproduce this if I select the _same_ file.

**Comment by gordonwoodhull** [comment]
Ditto, I only see this for the same file. Presumably doesn't fire changed event if it's not changed. 😛 

Now testing the fix.

**Comment by gordonwoodhull** [comment]
Duh, as you said in the PR. Thanks again.
