### ISSUE TITLE
Cell overlaps with resized plots 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1841]
Steps:
- Add a plot to any cell in a notebook
- Resize the plot pulling it downwards 

![imgovrlp](https://cloud.githubusercontent.com/assets/9251570/13742040/fa2d70a0-e9af-11e5-8c11-ebce4e2d3c4f.PNG)

**Comment by gordonwoodhull** [comment]
Thanks for reporting this, @sanketd11!

**Comment by gordonwoodhull** [comment]
@sanketd11, are you still able to repro this? I have not repro'd it myself, but I seem to recall there were other conditions necessary. I am observing the cell resizing dynamically as I resize the plot, so there is no way for the plot to get bigger than the cell.

**Comment by sanketd11** [comment]
@gordonwoodhull, this issue is still reproducible.

**Comment by gordonwoodhull** [comment]
Looks like I introduced `max-height` and `max-width` `100%` in order to better fit large plots with scrolling while still showing the save menu, in cb04d752.

But the `max-height` doesn't help with that and I'll try removing it.

**Comment by gordonwoodhull** [comment]
BTW, this is hard to reproduce unless the window height is much less than the screen height. That's why I was unable to repro for so long.
