### ISSUE TITLE
<Del> key exhibits behavior of <Esc> key 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1847]
According to current behavior, 'Del' key works as expected for cell deletion, text deletion from cell and assets, etc. but for other operations such as renaming the notebook titles, asset rename, text deletion from comments, the 'Del' key exhibits the behavior of 'Esc' key (the selected field goes out of focus when the 'Del' key is pressed)

**Comment by gordonwoodhull** [comment]
The new delete cell behavior for <del> is stealing the keydown from the contenteditables (notebook title, asset name, comments).

**Comment by shaneporter** [comment]
Updated code with a commit #1842

**Comment by gordonwoodhull** [comment]
fixed by #1842
