### ISSUE TITLE
Cell selection color should be consistent

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1848]
Currently we have these two behaviors
 For editable cells selection looks like 

![cell_edit](https://cloud.githubusercontent.com/assets/10941328/13837053/9dade32a-ebc4-11e5-8c10-fb9163812e0d.PNG)

and for non-editable cells it look like
![cell_nonedit](https://cloud.githubusercontent.com/assets/10941328/13837065/b4cb8ce2-ebc4-11e5-8893-3caeeaab3784.PNG)

**Comment by gordonwoodhull** [comment]
Yeah, the gutter should be yellow when the cell is active, as well. Which I suppose means the "active line shadow" becomes a dark yellow.

**Comment by gordonwoodhull** [comment]
fixed by #1857
