### ISSUE TITLE
Save icon is getting enabled for language change

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1850]
Save icon is not getting enabled when we change the cell language. As of now it is enabled only when we make some changes in the cell

**Comment by shaneporter** [comment]
Hi @Prateek032 - please could you update the title to say that the Save icon is _not_ getting enabled?

**Comment by gordonwoodhull** [comment]
Changed title.

This is by design. The only action that does *not* save immediately is editing a cell or an asset, because that would produce too many commits. Changing the language is essentially a rename of the underlying asset, so it needs to commit, just like deleting or rearranging a cell.
