### ISSUE TITLE
Firefox: Notebook name is not getting wrapped in firefox browser

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1852]
If notebook has long name,  in chrome browser we see text is getting wrapped but in firefox  it is not 

![nb_ff](https://cloud.githubusercontent.com/assets/10941328/13837441/ad8420e4-ebc8-11e5-86b9-33967cc497b5.PNG)

**Comment by shaneporter** [comment]
This can be fixed by adding `display: inline-block;` to the item's CSS selector, which overrides the default (inline, since it's a span element) in `jqtree.css`. 

Is it a good idea to create a `jqtree-rcloud-tweaks.css` file and place it in there?

**Comment by gordonwoodhull** [comment]
I think it's fine to add it to bootstrap-rcloud-tweaks.css (since that should be named rcloud.css) or edit.css. Want to take this?

**Comment by shaneporter** [comment]
Yes please.

**Comment by gordonwoodhull** [comment]
Thanks!

**Comment by shaneporter** [comment]
Proposed a fix with #1856

**Comment by gordonwoodhull** [comment]
fixed by #1856
