### ISSUE TITLE
firefox: permissions and info popover text don't fit if a long word

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1860]
![image](https://cloud.githubusercontent.com/assets/1366709/13920041/3c14d6ce-ef47-11e5-92fe-bf7a390e9ad1.png)

![image](https://cloud.githubusercontent.com/assets/1366709/13920056/503f2eba-ef47-11e5-9a4d-58c46adc66be.png)

**Comment by shaneporter** [comment]
This should now hopefully be resolved following 8369124.

**Comment by gordonwoodhull** [comment]
fixed by #1866
