### ISSUE TITLE
only display shortcuts for current platform?

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1861]
Opening this for discussion, since I initially thought it was a bug but it's actually correct but confusing.

Seeing keyboard shortcuts for other platforms may overwhelm users. (Especially windows users going "what's the command key?!" ;) 

We generally map everything to both ctrl- and cmd- for simplicity of implementation. But maybe the shortcuts dialog should only show the shortcuts for the current platform?

**Comment by gordonwoodhull** [comment]
Re #1842 #300

**Comment by gordonwoodhull** [comment]
Alternately, maybe if we have real infrastructure for keys, maybe we shouldn't double-map all these keys. Are there Mac users who will miss the ctrl- versions of keys commands?

**Comment by gordonwoodhull** [comment]
Today I saw that the dialog looks different on Windows/Linux, so just for reference, here's what it looks like on OSX:

![image](https://cloud.githubusercontent.com/assets/1366709/13995955/f9ba14b2-f101-11e5-8997-1543a35acb33.png)

Since the ctrl-keys are just an accident of the way we implemented shortcuts in the first pass, I think we should eliminate them on Mac and only have the cmd- variants.

**Comment by shaneporter** [comment]
Hmm... I thought I'd implemented this behaviour for Mac. Will fix.

**Comment by shaneporter** [comment]
PR #1881.
