### ISSUE TITLE
implement find/replace keys through shortcut manager

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1862]
couple keys are still lingering undocumented. 

they're implemented at the end of `htdocs/js/ui/find_replace.js`

these are some of the ones where the shortcuts are very different on windows and mac.

**Comment by shaneporter** [comment]
updated code, but unable to test Mac.

Replace reverts to find in read-only mode. Adjusted call to shortcut manager init too.

**Comment by gordonwoodhull** [comment]
related (closed) issue: #1296

**Comment by gordonwoodhull** [comment]
confirmed keys are correct on mac.

**Comment by gordonwoodhull** [comment]
fixed by #1865
