### ISSUE TITLE
esc to close keyboard shortcuts dialog

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1863]
most of our dialogs close with `<esc>` - where they don't, it's a bug (#1831)

**Comment by shaneporter** [comment]
I've added a global handler for `<esc>`. I'm not sure if this is overkill, since you mention that

> most of our dialogs close with `<esc>`

If it's required that they do, this should fix that issue too. The selector '.modal' is used, which, I'm assuming is used for all bootstrap dialogs.

**Comment by gordonwoodhull** [comment]
hmm, that is kind of overkill, but it works. let's see if it causes problems heheh.

**Comment by gordonwoodhull** [comment]
fixed by #1865

**Comment by Prateek032** [comment]
This issue still persists on Local instance

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032, reopening.

**Comment by shaneporter** [comment]
This has been fixed.

**Comment by gordonwoodhull** [comment]
Fixed by #1896
