### ISSUE TITLE
Keyboard shortcut dialog should be consistent

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1864]
Currently we have different sizes of keyboard shortcut  dialog's in edit.html, view.html and Discover page.

**Comment by shaneporter** [comment]
Thanks for reporting. Some CSS isn't pulled through for view and discover, and discover looks particularly bad.

It seems that we should go further and filter shortcuts based on the page that they're on. There's not much cell management going on in view or discover, for example.

**Comment by gordonwoodhull** [comment]
Yes, we should filter shortcuts by page. We can do this the same way we do menus, and there is some basic functionality for sections and filtering in RCloud.extension.

Take a look at htdocs/js/ui/menus.js to see how to do this. The nice thing about this method is that that it allows shortcuts to belong to multiple pages.

**Comment by gordonwoodhull** [comment]
fixed by #1865
