### ISSUE TITLE
Cell get deleted in read only mode

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1874]
According to current behavior:
In a read only notebook, the cells get selected when we click on the title bar of the cell. After selecting the cells if we press < Del > key, the cells get deleted followed by  the error message in session div. 

- 
 ![c1](https://cloud.githubusercontent.com/assets/9251570/14011714/2c534a36-f177-11e5-80e4-1d8a4f9c85d5.PNG)

-  
![c3](https://cloud.githubusercontent.com/assets/9251570/14011723/39b535a4-f177-11e5-9400-47470e6f4de5.PNG)

- 
 ![c2](https://cloud.githubusercontent.com/assets/9251570/14011729/431c0d98-f177-11e5-9de7-8ddddc760ac9.PNG)

Reloading the page brings the content back to notebook.

**Comment by shaneporter** [comment]
In edit mode, selecting is the first step towards deleting a cell or cells.

I was going to prevent selection in read only mode, but perhaps it still makes some sense to select a cell or cells. Perhaps to highlight an interesting cell (particularly if the notebook has lots of cells.) @gordonwoodhull  - what do you think? Prevent selection in read only mode?

I will of course fix the delete issue :)

**Comment by gordonwoodhull** [comment]
@shaneporter, I had much the same thought - there currently aren't any operations which could be applied to a read-only notebook but there might be later, so let's just disable the delete operation (possibly through the same tag system I mentioned in #1864).

**Comment by gordonwoodhull** [comment]
.... but there might be operations that apply - will open another issue.

**Comment by gordonwoodhull** [comment]
fixed by #1878
