### ISSUE TITLE
Misaligned Notebooks in Discover page

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1875]
Alignment of notebooks gets distorted due to varying resolution of the thumb images in the discover page

![11](https://cloud.githubusercontent.com/assets/10941328/14012351/78f12d5a-f162-11e5-925b-e81c11348473.PNG)

**Comment by gordonwoodhull** [comment]
This is by design - we're using the layout popularized by Instagram. It's unfortunate that this can mean the end of the page is ragged, but hopefully there will be enough results in many queries so that users never get to the end.
