### ISSUE TITLE
undo/redo (Ctrl+Z / Y) operation fails for second attempt

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1876]
Steps to replicate:
- Load any notebook having several history versions 
- Press Ctrl+ Z ( This will load the history version of that notebook)
- Now press Ctrl +Z again ( This time nothing will happen )

For the next undo operation to work user needs to click on screen. Same is the behavior for 'redo' operation.

**Comment by gordonwoodhull** [comment]
I'm not able to verify this bug, except that if you press undo twice in quick succession (<1s on this machine) can invoke the "please wait from heck", pretty much identical to #1587

**Comment by gordonwoodhull** [comment]
@sanketd11, thanks for reporting this, is this the case where the "please wait" get stuck on the screen?

**Comment by gordonwoodhull** [comment]
Okay, I see this now. Clicking on the screen doesn't work for me. I do see the Edit menu flash (which it doesn't do when the command is handled by us) so I think this may be similar to #1889 / #1883?

On the other hand, the notebook becomes readonly once it's on a historical version so maybe I am seeing #1899

**Comment by gordonwoodhull** [comment]
Not at the computer atm but I'm going to bet this is reopened, same reason as #1899.

**Comment by gordonwoodhull** [comment]
This issue concerns the error message from concurrency problems, #1899 concerns the key not working at all.
