### ISSUE TITLE
Error: when empty shell cell is executed

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1882]
When we execute empty shell cell, the following errors are displayed in command prompt and in Session div

![shell_cmd](https://cloud.githubusercontent.com/assets/10941328/14102834/d25d1d16-f551-11e5-9a15-18694519634b.PNG)

-
![shell_session](https://cloud.githubusercontent.com/assets/10941328/14102851/e5b521a6-f551-11e5-9b99-0ff666f30259.PNG)

**Comment by gordonwoodhull** [comment]
Confirmed

**Comment by s-u** [comment]
we try hard to not allow empty cells (the prompt won't let you execute an empty cell), but it's a losing battle so I'll fix it in `rcloud.sh`.
