### ISSUE TITLE
Cell contents are not getting saved for imported Private notebook

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1885]
Steps to replicate:
1. Make any one of the existing notebook as **private** and export it
2. Import the exported private notebook and then open it
3.  Now make some changes  in the cell and execute it
still previous contents are displaying

**Comment by gordonwoodhull** [comment]
Choices:
 - don't allow exporting private notebooks
 - export as unencrypted
 - export unencrypted but warn first

I think we agree that an exported encrypted notebook makes no sense. (It couldn't be read on any other server.)

**Comment by gordonwoodhull** [comment]
For now, just banning exporting private notebooks. We should warn and then decrypt, but currently the APIs do not distinguish between binary assets and encryption.
