### ISSUE TITLE
Asset fails to display the pictures

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1886]
I am facing this issue on my **local instance**. When i upload any image files (.png/.jpeg) to the newly created notebook, files are getting uploaded but the asset fails to view the pictures. 
Following is the error displayed in browser console

![unabletouploadassetonlocalsystem](https://cloud.githubusercontent.com/assets/10941328/14172754/ae941508-f6ee-11e5-8334-6e1d6f7a45e4.PNG)

**Comment by gordonwoodhull** [comment]
I've confirmed this. Seems to affect instances using public github, but why?

The error returned is

Error fetching content:

```
 Error in doTryCatch(return(expr), name, parentenv, handler): Notebook `foo.jpeg' by user `b30ec28c028b143de7157cbd6b1b6cdb' not found
 ```

So why would notebook.R think that the hash is a user in this case?

**Comment by gordonwoodhull** [comment]
Actually, the other factor is that the failing instances are not proxified. That's probably more likely.

**Comment by s-u** [comment]
Because notebook hashes are defined to be 20-chars long -- and apparently GH has just changed that to 32-char on public GH which breaks.

**Comment by gordonwoodhull** [comment]
QA reported that they are still seeing this. In my experience the image sometimes does not display immediately, but the URL is good and the image will always display if the asset area is hidden and then displayed.

There is an obscure bug in one other place where we look at gist IDs, in "Load Notebook by ID" but it's not important and I'll file it for later.
