### ISSUE TITLE
Overlapping Modal windows

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1887]
Currently import external notebook and keyboard short cut modal windows are getting overlapped on each other
steps to replicate:
1. Open import external notebook dialogue box
2. Now press < shift + ? > keyboard shortcut dialog box is also invoking 

![dialog box overlap](https://cloud.githubusercontent.com/assets/10941328/14173371/83d4aa40-f70b-11e5-86e8-aff39be4223d.PNG)

**Comment by gordonwoodhull** [comment]
I don't think the shortcuts dialog should be accessible here.

**Comment by shaneporter** [comment]
Is it reasonable to say that the shortcuts help dialog shouldn't appear when there is already a visible dialog?

**Comment by gordonwoodhull** [comment]
I think that should do it, yes.
