### ISSUE TITLE
some github urls don't work for Load Notebook by ID

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1891]
Follow-up to #1886, there is another place we assume gist IDs are 20 characters but it's a pretty obscure place.

For convenience, we accept GitHub URLs in this dialog. Those can take two forms:

`https://gist.github.com/d90a67db7559554941f032a48b8febf8`

or

`https://gist.github.com/gordonwoodhull/d90a67db7559554941f032a48b8febf8`

We detect the second case by looking for a gist ID in the first part of the path, and if we don't find one we throw away the first part. So currently the first URL will cause an exception `shell_tab.js:282 Uncaught TypeError: Cannot read property 'replace' of undefined`.

Given that this is an unadvertised feature, and the first type of URL always redirects to the second type (so it would be hard to get one), I don't think it's important enough to fix in this point release.

**Comment by shaneporter** [comment]
Fixed with PR #2138.
