### ISSUE TITLE
Garbage value appears after clicking on the link from Asset div 

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1893]
For Chrome browser steps to replicate:
1. Make the existing Notebook as 'Private'
2. Upload any png file to the Notebook
3. Now click on *Link* from the asset div
New tab opens with garbage value

![garbagevalue](https://cloud.githubusercontent.com/assets/10941328/14418354/70f1911c-ffdb-11e5-900f-d082e0d83288.PNG)

For firefox browser:
1. Make existing Notebook as 'Private'
2. Upload any png files to the Notebook
the uploaded file in asset displayed as below

![garbagevalue_ff](https://cloud.githubusercontent.com/assets/10941328/14420277/d8184900-ffe8-11e5-89c5-7a83035d61b7.PNG)

**Comment by gordonwoodhull** [comment]
@s-u, here's one of those binary-encrypted interactions we talked about. Is it serving the wrong mime type for encrypted assets?
