### ISSUE TITLE
Complete code is not visible for the new cells

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1894]
When we write a code in new cell, the code content appears like below

![cell](https://cloud.githubusercontent.com/assets/10941328/14421203/e9a6f1ee-ffed-11e5-9c3e-85859e344b7f.PNG)

and its visible after executing cell or refreshing the tab

**Comment by shaneporter** [comment]
The behaviour I see is that a new cell is created with 2 lines, but the cell's height increases automatically when I add a new line.

**Comment by shaneporter** [comment]
This has been tackled by PR #1925.
