### ISSUE TITLE
Add 'Show keyboard shortcuts' link to Help pane.

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud#1908]
The only way to show the shortcuts dialog is to use a shortcut. 

We should add a 'Show keyboard shortcuts' link to the Help pane.

**Comment by shaneporter** [comment]
PR #1979

**Comment by Prateek032** [comment]
keyboard shortcut link is not working

**Comment by gordonwoodhull** [comment]
@Prateek032, I disagree. Maybe you have the focus on a cell or command prompt? It only works when the focus is not on a cell or command prompt.

**Comment by Prateek032** [comment]
I am just clicking on the 'Keyboard shortcut' link from the help pane

![image](https://cloud.githubusercontent.com/assets/10941328/15733820/71d74992-28a7-11e6-85db-cebd9ce6f173.png)

**Comment by gordonwoodhull** [comment]
It looks like you haven't built the javascript and html. (I think this explains another recent issue you were seeing that we weren't seeing.)

Please run `scripts/build.sh`

**Comment by gordonwoodhull** [comment]
Since I am in the middle of merging everything, I haven't been checking in the build artifacts.

**Comment by sanketd11** [comment]
I too faced this issue on commit 7f09c7e . But on the latest commit it seems to be working as expected.

**Comment by shaneporter** [comment]
Cool. Thanks @sanketd11!
