### ISSUE TITLE
Unable remove admin/member from group

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1910]
Steps to replicate:
- Open manage groups dialog box
- Press 'Delete' key
- Try to remove any Member or Admin from group

After pressing 'Delete' key the cursor will shift to command prompt which doesn't come back to current dialog box

**Comment by gordonwoodhull** [comment]
I am only seeing part of this issue (on Chrome/OSX). I am able to delete members and admins okay (except for deleting myself as an admin, which is not allowed). 

Pressing the delete key doesn't do anything in particular unless a member or admin is selected.

I also don't see the cursor moving to the command prompt (outside of the dialog?!) 

However: if a cell is selected and I press delete when none of the elements on the form are in focus, it deletes the cell. This shouldn't happen.

**Comment by sanketd11** [comment]
Now we are able to remove admin/members from group but the cursor shifting to prompt cell (outside the dialog box) can still be reproduced.
- Open group management dialog box
- Click anywhere except the admin/member fields on the dialog box
- Press 'Delete' key

**Comment by shaneporter** [comment]
This also happens on every other dialog. :disappointed:

**Comment by shaneporter** [comment]
PR #1962 should hopefully resolve this.
