### ISSUE TITLE
Unable to rename Notebook Title

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1918]
Old notebook title is retained after page reload.
Following is the session div error 

![rename](https://cloud.githubusercontent.com/assets/9251570/14629010/bd64910c-0620-11e6-9939-9b6b74e06b01.PNG)

**Comment by sanketd11** [comment]
This issue seems to be resolved on (develop/ ab60fca ). But still it waits longer than earlier commits to rename the notebook

**Comment by gordonwoodhull** [comment]
I reverted the change to a communication library (rserve.js) which was causing this.

I am not seeing any unusual slowness. If renames are radically slow (say >5s) then please file another issue.
