### ISSUE TITLE
Firefox: Cells getting selected while moving cells 

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1929]
While moving cells from top to bottom and bottom to top, the cell is getting selected in Firefox browser

**Comment by gordonwoodhull** [comment]
Apparently it registers a click after the event is done.

To continue the file browser analogy, this is like having some files selected and then starting a drag on another file that is not selected. It looks like the OSes disagree here: Windows and Linux will select just the dragged file and deselect the the old ones, while OSX will drag the other file while keeping the old selection.

I slightly prefer the Windows/Linux approach, in which case we should change the selection on mousedown. But this is open for debate - alternately we could ignore the click-after-drag on Firefox.

Somewhere I started some notes on what multisortable behavior would mean for notebook cells. Not something we should worry about for this release!

**Comment by gordonwoodhull** [comment]
Fixed in 956b801906df3e1e2f5f925bebdae9da494fc684 (merged in #1962)
