### ISSUE TITLE
Different behavior for 'Delete' key after cell selection

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1930]
Case 1:
- Select a cell by clicking on the check box 
- Press 'Delete' key 
- The selected cell will be deleted

Case 2:
- Select a cell by clicking on the cell header
- Press 'Delete' key 
- The selected cell will not be deleted this time

**Comment by gordonwoodhull** [comment]
If this is the issue we talked about yesterday, it's because the cell content hasn't lost focus in the header click case, #1791

**Comment by shaneporter** [comment]
@gordonwoodhull - so this will be resolved as a happy convenience when #1791 has been implemented. Hopefully I've understood things correctly.

**Comment by shaneporter** [comment]
Suggested fix submitted with PR #1977.
