### ISSUE TITLE
Ctrl/cmd + a does not select all in find/replace

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1932]
As we see in all the fields (ace editor, search, help and comments), we can select all the contents by pressing < ctrl + a >. But in find/replace it fails to select the contents.

**Comment by shaneporter** [comment]
Just so I'm 100%, you mean invoking select all whilst in the highlighted fields, shown below, should select all their text?

![image](https://cloud.githubusercontent.com/assets/2493614/15827656/ebf92c9a-2c03-11e6-8f26-caf10a0fc211.png)

So, select all in the replace field should look like this?

![image](https://cloud.githubusercontent.com/assets/2493614/15827606/b644744c-2c03-11e6-92ac-14c8d4aed2f5.png)

**Comment by shaneporter** [comment]
This issue has been tackled by PR #2045.
