### ISSUE TITLE
Empty cell content gets replaced using find/replace

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1940]
Steps to replicate
1. Create a new notebook and add some contents to it
2. Now invoke the 'Find/Replace'
3. Enter some text in 'find/replace' and click on replace
4. Now delete the cell contents and save the changes
5. Click again on replace

The text entered in replace filed will appear in cell div
and session div throws following error

![image](https://cloud.githubusercontent.com/assets/10941328/14876202/2ee0a0f8-0d30-11e6-98ca-eef0505895b0.png)

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032. Many similar issues with find/replace, missed this one. Should probably also be fixed by #2033.

**Comment by shaneporter** [comment]
Hi @gordonwoodhull - can this issue now be closed?

**Comment by gordonwoodhull** [comment]
Yes indeed

**Comment by shaneporter** [comment]
Thanks.
