### ISSUE TITLE
What is the expected behavior for < ctrl + s > in Discover and view.html pages

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1941]
In 'view.html' page if we press < ctrl + s > it invokes 'Save window', but in 'Discover page' when we do the same thing, nothing happens. So which one is the correct behavior

**Comment by shaneporter** [comment]
view.html doesn't have a shortcut assigned to `ctrl` `s`, so the browser default is invoked. Which makes sense.

It is therefore the 'discover page' that is at fault.  It too should invoke the 'save window' browser shortcuts.

PR #1946 should resolve this.
