### ISSUE TITLE
Groups dropdown list should be sorted according to group name

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1942]
In group management dialog, group selection drop down list is currently not sorted according to group name

![grp](https://cloud.githubusercontent.com/assets/9251570/14876822/a30ffc4e-0d35-11e6-8b9b-bb373d1420f3.PNG)

**Comment by shaneporter** [comment]
A suggested fix is in PR #1945.

**Comment by sanketd11** [comment]
The group drop-down list in the Notebook tab in 'Notebook Permissions/ Group Management' dialog is still unsorted.

**Comment by gordonwoodhull** [comment]
Fixed.
