### ISSUE TITLE
Different keyboard shortcut dialogs in view.html

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1955]
In 'view.html' the keyboard shortcut dialog appears with all the shortcuts as it appears in 'edit.html' for unpublished notebooks accessed by anonymous user. Same is the case for private/group notebooks accessed by non member user in 'view.html'. Normally in 'view.html' the keyboard shortcut dialog appears with limited shortcuts

**Comment by shaneporter** [comment]
@sanketd11 when I try to view one of my notebooks as an anonymous user, I see this:

![image](https://cloud.githubusercontent.com/assets/2493614/15046388/485b4888-12d7-11e6-9c1a-bc4c52c81064.png)

The notebook is visible and its group is 'public'. Is there something else I need to do to be able to view it?

Thanks.

**Comment by tejas1493** [comment]
@shaneporter you need to publish the notebook first. Then you can see the contents as anonymous user.
But for the published notebooks viewed as anonymous user, the above issue is not reproducible.

**Comment by sanketd11** [comment]
@shaneporter you need to publish the notebook first. Then you can see the contents as anonymous user.
But for the published notebooks viewed as anonymous user, the above issue is not reproducible

**Comment by gordonwoodhull** [comment]
@sanketd11, thanks for reporting this and sorry for the backlog.

Could you clarify what the issue is here, if it is still an issue?

**Comment by sanketd11** [comment]
In view.html mode for any unpublished notebook 
- If it is accessed by user (with RCloud login), we get following keyboard shortcuts dialog:

![c1](https://cloud.githubusercontent.com/assets/9251570/15855682/70984114-2cce-11e6-9629-3c98cb72108d.jpg)

- If the unpublished notebook accessed by anonymous user, we get following keyboard shortcuts dialog:

![c2](https://cloud.githubusercontent.com/assets/9251570/15855683/70c539d0-2cce-11e6-8eef-7c310933a3ef.jpg)

So on View.html page we get different keyboard shortcut dialogs

**Comment by gordonwoodhull** [comment]
Nowadays I see blank #2083 in either case.
