### ISSUE TITLE
Replace field appears in history version of the notebook

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1958]
steps to replicate:
1. Open any notebook
2. Invoke Find/Replace fields
3. Now click on History icon and open any History version of that notebook or simply press < ctrl + z >

![image](https://cloud.githubusercontent.com/assets/10941328/15036758/2476d5fc-12b1-11e6-8fba-4ea2a8113ff7.png)

**Comment by gordonwoodhull** [comment]
Confirmed. I think we enable the keyboard shortcuts based on the readonly mode but we don't similarly modify the find/replace dialog.

For better or worse, there's a whole source file dedicated to enabling/disabling things based on the readonly mode.

`htdocs/js/ui/configure_readonly.js`

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032.
