### ISSUE TITLE
Cell contents are replaced in another notebook

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1960]
Steps to replicate:
1. Open a notebook
2. Invoke Find/Replace and replace the contents with the existing content
3. After replacing switch to another notebook
4. Now again click on replace.
The cell contents are getting replaced

![replace](https://cloud.githubusercontent.com/assets/10941328/15039110/a6e76cd4-12c7-11e6-9ada-bb531424a33e.gif)

**Comment by gordonwoodhull** [comment]
As we discussed on the call, this is probably another aspect of #1849.

Thanks @Prateek032! BTW, this is helpful but there is no need to continue testing find&replace until we fix these issues - it is clear that it is not tracking any changes to the notebook (or indeed, the notebook being replaced entirely!)

**Comment by shaneporter** [comment]
...and #1839.
