### ISSUE TITLE
Undo/Redo shortcuts disappear in view.html

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1971]
Steps to reproduce:
- Load any notebook in view.html
- Invoke keyboard shortcuts (Undo/Redo shortcuts will be present in the dialog). Press Esc key
- Press Ctrl+Z 
- Again invoke the keyboard shortcuts. This time the Undo/Redo shortcuts will disappear from the dialog

**Comment by gordonwoodhull** [comment]
I don't think undo / redo should be available in view mode in the first place.

**Comment by shaneporter** [comment]
Shall I remove undo / redo from view mode?

**Comment by gordonwoodhull** [comment]
I think so. We probably don't have the data (since the history versions are held with the notebook tree), and it also doesn't make as much sense to walk versions if you can't see them.

**Comment by shaneporter** [comment]
I have removed undo/redo from view mode with PR #1976

**Comment by gordonwoodhull** [comment]
Confirmed that the first undo is throwing an error due to lack of data. No idea why that caused the shortcut to disappear, don't care. 😉
