### ISSUE TITLE
Cell language changes while moving cells

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1972]
While moving any cells, the cell language appears as Markdown.

![image](https://cloud.githubusercontent.com/assets/10941328/15238869/e8b81030-18fa-11e6-9597-971516b423b4.png)

**Comment by gordonwoodhull** [comment]
Probably due to the new clone for resolving #1929 Firefox select-on-drag?

**Comment by shaneporter** [comment]
That's definitely it. Looking at an alternative resolution to #1929 that doesn't cause this, or any other issue.

**Comment by shaneporter** [comment]
PR #1975 should fix this issue.
