### ISSUE TITLE
Trim Leading and trailing spaces for group names/asset names

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1973]
I case of naming groups, the same group name is not accepted. But it is accepted if it has leading or trailing spaces. 

![capture](https://cloud.githubusercontent.com/assets/9251570/15238933/a18bb8f0-18fb-11e6-915f-45b0735e4d97.PNG)

Similar is the case with Asset names. 

![capture](https://cloud.githubusercontent.com/assets/9251570/15238899/3b107188-18fb-11e6-9b9e-7c56707f45c3.PNG)

**Comment by gordonwoodhull** [comment]
As discussed, this also happens for notebook titles, but I don't think it is an issue there. It is an issue here for the possibility of misleading group names, and assets with bad extensions.

**Comment by shaneporter** [comment]
Fixed in PR #1974
