### ISSUE TITLE
'Export Notebook as R Source File' option should be disabled for Empty notebook

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1978]
Currently, for an empty notebook (without any cell), 'Export Notebook as R Source File' downloads blank R file.

**Comment by shaneporter** [comment]
I'd say it wasn't necessary to disable the export for an empty notebook. I wouldn't expect users to invoke the export in that scenario, but other applications allow saving when there is no content.

**Comment by gordonwoodhull** [comment]
I agree. It's [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out).
