### ISSUE TITLE
Error: after deleting cell contents

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1985]
Steps to replicate:
1. Open a notebook
2. Invoke Find/Replace
3. Replace the cell content with new keyword
4. now delete the cell contents

following error is displayed in session div

 
![f r_error](https://cloud.githubusercontent.com/assets/10941328/15417300/b935f878-1e71-11e6-8bbc-7f9500df0e47.PNG)

**Comment by gordonwoodhull** [comment]
We should see if this gets fixed by #1969

**Comment by gordonwoodhull** [comment]
I believe this is fixed now, because the find results go away when the find dialog loses focus.
