### ISSUE TITLE
Inappropriate selection order for Find/Replace options/fields using 'Tab' key

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1986]
Steps:
- Invoke Find/Replace dialog
- Press 'Tab' key to select the options and fields

The current order of selection is 
Find Text Field  -> Replace Text Field -> Find Next -> Find Previous -> Replace All

As discussed, the selection should be in sequential order

**Comment by gordonwoodhull** [comment]
Also, as reported in #1984, the Replace button doesn't ever receive the focus.

I wrote some custom code for all this but I guess it's succumbed to bitrot. There are arrays specifying the order.
