### ISSUE TITLE
Keyboard shortcut help content should be consistent across the browsers

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1987]
Currently when we invoke it in Firefox browser it looks like below

![image](https://cloud.githubusercontent.com/assets/10941328/15417470/dddff4d8-1e73-11e6-8edb-b11e8bafc3e1.png)

and in Chrome 

![image](https://cloud.githubusercontent.com/assets/10941328/15417493/2294ff7e-1e74-11e6-891b-268256d369c8.png)

**Comment by shaneporter** [comment]
Resolved in PR #1990.
