### ISSUE TITLE
Firefox: Notebook title field goes out of focus

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1988]
Steps 
- In Firefox browser, click on the notebook title to make it editable
- Press 'Right Arrow' key 

After pressing 'Right Arrow' key the cursor is expected at the end of notebook title but in firefox browser title field goes out of focus making the title uneditable

Also pressing 'End' end key should bring the cursor at the end of title but in this case it remains at the start of title

**Comment by gordonwoodhull** [comment]
Confirmed. Odd, this should be entirely within the browser, wonder if we are accidentally capturing these keys or something.

**Comment by shaneporter** [comment]
Hmm...

![image](https://cloud.githubusercontent.com/assets/2493614/15510522/a1f965da-21cf-11e6-827a-970eb659d41c.png)

That title? Arrow keys work for me, but not `End`.

**Comment by gordonwoodhull** [comment]
Yes. What I see is

 * Once I click on the title, all the text gets selected. Now the arrow keys don't work and all that happens is that the title loses focus. Home and End have no effect.
 * If I start typing, then the cursor appears and I can arrow around. But Home and End still don't work, and if I arrow off the end, it loses focus and gets deactivated again.

All of this seems to work in Chrome.

**Comment by shaneporter** [comment]
Non-working _home_ and _end_ keys don't seem to work for Firefox contenteditables, as can be seen in this [fiddle I created](https://jsfiddle.net/a3hfhv2u/).

But, the cursor does appear, and _left_/_right_ keys do work.

**Comment by gordonwoodhull** [comment]
@shaneporter, I take it you were not able to repro? It seems like you can't use the cursor at all unless you type something. 

In addition, clicking on the title a second time seems to blur it rather than showing a cursor. This happens whether or not you've started typing.

**Comment by shaneporter** [comment]
I can try again in about 12 hours' time.

**Comment by gordonwoodhull** [comment]
Oddly, left-arrow and ctrl-A work, but not right-arrow.

**Comment by shaneporter** [comment]
PR #2298.
