### ISSUE TITLE
discover recent notebooks

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1993]
We need a view in the discover page that shows recent notebooks across all users.

It's unclear whether recently created notebooks, recently modified, or recently opened notebooks will be more helpful. Let's start with recently modified.

**Comment by shaneporter** [comment]
Applying to #1994 too, the current toggle buttons for this don't currently do anything on the discover page. Perhaps it was unfinished.

**Comment by gordonwoodhull** [comment]
@paulinshek, thanks for looking at this!

**Comment by gordonwoodhull** [comment]
Implemented in #2014
