### ISSUE TITLE
prevent scrolling away in Session pane

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1996]
When the session pane is continuously updated by new output it will scroll away, making it impossible to read anything or perform a selection. Probably the most common solution to this problem in other software is to only auto-scroll if the last line is visible. If the user scrolls upwards such that the last line is no longer visible, the pane should update but not scroll such that select/copy/paste etc. still work.

**Comment by gordonwoodhull** [comment]
I assume the same behavior will also be helpful for the notebook pane.

@shaneporter, I'm creating a "follow up" point release for these last minute requests. If you can fit any in this week, that's awesome.

**Comment by gordonwoodhull** [comment]
wow i really want this in the notebook pane right now.

**Comment by gordonwoodhull** [comment]
Okay, I'm implementing this by checking whether how far we are from the bottom before adding output. If we were within 10 of the bottom before output, we scroll afterward.

There's a little bit of ugly jerkiness if you scroll while it's appending stuff, but the important part is that you win and it stops scrolling. So, good enough for now, I think.

I'll add a separate issue for autoscrolling the notebook pane, which should have the same behavior.
