### ISSUE TITLE
can't close dialogs with ESC (yet again!)

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1999]
I think this is the third time we've seen this, and each time a different reason. (Twice in #1863, once in #1928).

This time, it seems to be caused by 2a32bd2041b4b3df5b309bed3c6e97581b94cc5d "minor change to shortcut text" for cell deactivation.

Maybe a shortcut conflict? Do we need a global shortcut for cell blurring, considering that the cell should pick up ESC directly, considering it has the focus? The long, boring saga continues...

**Comment by shaneporter** [comment]
Sorry! I'll take a look.

**Comment by gordonwoodhull** [comment]
np, it's just kind of humorous. 

i am actually not surprised that the keyboard shortcuts have proven so difficult, considering they had no structure at all before.

**Comment by shaneporter** [comment]
This happened because #1991 involved adding a shortcut (esc) that was already used by a previous shortcut (close dialog) at the time of registration.

In reality, there wasn't a clash since they worked with different elements. I have removed the anti-clash code.
