### ISSUE TITLE
file download API

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2005]
what dashboard does not want Export to CSV?

pretty serious oversight here.

**Comment by gordonwoodhull** [comment]
The only thing that's complicated about this is it needs to declare and use the FileSaver.js dependency in requireJs, since we currently only load it in edit.html. (We could load it everywhere but that seems excessive.)

**Comment by Chuck-Field** [comment]
I seriously need functionality from Shiny as well. Apps in shiny are not very useful without a way to push data to the common app users desktop. Hoping the Shiny  "download button" functionality will be fixed in the RCloud version of Shiny too... Scratching my head, wondering why we reinvented the wheel on all this stuff which only half works. VERY FRUSTRATED... This is NOT embracing open source, when we have to fix things that work fine in the open source world...

**Comment by gordonwoodhull** [comment]
Hi @Chuck-Field, sorry for the inconvenience. 

Unfortunately open source is not some magic which automatically makes all software compatible. It is still work to integrate it. 

In this case, RCloud has its own session mechanism and websocket which has to be used instead of Shiny's. Shiny also provides its own web server and clearly if we are delivering the content through RCloud we have to use our web server instead.

You can always use Shiny's web server if it works in your environment. Integrating Shiny into RCloud is non-trivial and we are doing the best we can here.

**Comment by Chuck-Field** [comment]
I'm well aware, it's not magic. I appreciate all the talent and skill toward this effort. Please don't get me wrong... Next time I'll leave my "why are we doing this in the first place" thoughts out of it. It was not appropriate for this topic. 
As for using Shiny's web server, that's quite impossible if we are not allowed to develop "R" related products outside of RCloud, is it not? At least six months ago, TSS exceptions stopped getting approved for R and RStudio... anyway apologies for venting. The work is appreciated.

**Comment by gordonwoodhull** [comment]
Thanks for understanding. 

(And yeah... there can be those sorts of compatibility problems, can't there. Those are not coming from us, and not in the spirit of open source IMHO, but enough said about that I guess.)

**Comment by gordonwoodhull** [comment]
`rcloud.download.file` will be available in RCloud 1.6.1 - for now the workaround using a JS asset is the best way to go.

https://rcloud.social/edit.html?notebook=2b2bcfe5bfb5fa9e98d2274604a1f3df

It's exactly the same functionality, but it will be built in (and I'll have a notebook demonstrating binary downloads as well).
