### ISSUE TITLE
renaming asset to thumb.png doesn't index the thumbnail

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2011]
Although adding an asset named thumb.png does `rcloud.set.thumb` the thumbnail in the database, renaming an existing asset to thumb.png does not. 

This is strange because we implement rename as fetch-old, create-new, delete-old, so it should work the same.

I think a common workflow for adding thumbnails will be: take a snapshot, drag it to the assets, rename it to thumb.png, and that currently doesn't work.

**Comment by gordonwoodhull** [comment]
(A little background: [GitHub Gist does have a rename mechanism](https://developer.github.com/v3/gists/#edit-a-gist), but [we aren't using it](https://github.com/att/rcloud/blob/develop/htdocs/js/notebook/asset_view.js#L18-L43). So I don't think this should be a special case, although I'm obviously missing something here.)

**Comment by paulinshek** [comment]
thanks, will have a look!

**Comment by paulinshek** [comment]
Hmm, it looks like renaming is not working properly, for me.

If I upload oldfile.png and then try to rename it to thumb.png, I get the following behaviour:
- Two new assets appear, both called thumbnail.png
- The content on one points to oldfile.png
- and the other points to thumb.png (but the gist is not modified, so I get a GET error)

I think there must be something missing from notebook.controller.append asset, or something else needs to also be called. I will keep digging.

**Comment by gordonwoodhull** [comment]
Sounds like you're getting an error somewhere. The feature is well tested and should work. 

Temporarily displaying two assets is normal because of the silly way the feature is implemented, as described above. However, the old one should get removed after a moment.

**Comment by gordonwoodhull** [comment]
Implemented in #2047. 

It's a really easy workflow on the Mac because you just hit cmd-shift-4, select the area on the screen, and then find the png on the desktop, drag it in and rename it. So it's great to see this working.

(Of course, typing all that out, it doesn't sound simple and we should really have pasting from clipboard to a new thumb.png asset, but I'm not sure how to do that.)
