### ISSUE TITLE
< shift + alt + enter >  keyboard shortcut Running all the cells

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2013]
As per the keyboard shortcuts help  < shift + alt + enter > should execute/ run within a cell, but it is executing all the cells from the notebook. To Run all the cells we have < ctrl + u >

**Comment by gordonwoodhull** [comment]
Oh. Haha. The documentation is ambiguous here. It means that the command will be active within a cell, not that it acts within the cell. 

Perhaps it should say "Run from this cell on" instead of "Run from here (within a cell)"
