### ISSUE TITLE
Abbreviate key commands 

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2015]
It's a minor style point but I think the usual way to display key combinations is ctrl-cmd-alt-opt-shift-key. 

It will save a tiny bit of space too.

![image](https://cloud.githubusercontent.com/assets/1366709/15785362/db1ff3e4-2984-11e6-8ffd-208b4cd8c2f4.png)
looks too verbose to me.

**Comment by shaneporter** [comment]
I was inspired by Github's help:

![image](https://cloud.githubusercontent.com/assets/2493614/15785635/37604372-29b0-11e6-87d6-0d521c877d75.png)

But I have no issue changing it.

**Comment by shaneporter** [comment]
I've started looking at this, and I've abbreviated the mac keys. However, I don't believe using `-` over the current space will save any space.

I also think combining the keys in a single group conveys 'together' more effectively than using a `-`.

If you disagree, let me know, but I thought I'd let you know my opinion on it :smile:

**Comment by gordonwoodhull** [comment]
Yes github is good precedent for sure. Thanks!

**Comment by gordonwoodhull** [comment]
fixed by #2063
