### ISSUE TITLE
must lose focus on all text areas when selecting cell

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2018]
I thought that #1991 explicitly blurring cells on selection was better than #1977 setting the focus to the checkbox, at least in terms of code clarity. Since they seemed redundant I reverted #1977.

But I guess I was wrong about the robustness of the two approaches, since we also need to lose focus on any other text editor when we select a cell.

@shaneporter, looking for your opinion on this. We could reinstate #1977 and gut most of #1991 since there's no need for a MVC event just to blur the cell which currently has the focus on ESC. Or... ?

However we do it, everything text-oriented must be blurred when we select a cell, for Delete to work. It's confusing that it sometimes doesn't work, and I think it's expected that "notebook management" would get the focus when changing its selection.

**Comment by shaneporter** [comment]
Maybe a bit brute force, but 

```
$('*').blur();
```

would do it.

**Comment by gordonwoodhull** [comment]
That's a bit much. I think I prefer putting the focus on the checkbox like in #1977. I probably just chose the wrong one out of two possibilities. 

I can revert #1991 and re-apply #1977 if you like.

**Comment by shaneporter** [comment]
Hopefully PR #2064 is both sensible and suitable. Thanks.

**Comment by gordonwoodhull** [comment]
Fixed by #2064
