### ISSUE TITLE
notebook tree sometimes wraps too eagerly when highlighted

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2019]
Probably due to #1856 - not sure why it thinks it needs to wrap about 12 characters to the left of the notebook commands

![image](https://cloud.githubusercontent.com/assets/1366709/15806740/b1d25a8c-2b18-11e6-936c-ce35de86b898.png)

**Comment by gordonwoodhull** [comment]
note that the very next entry, which is longer, does not wrap:
![image](https://cloud.githubusercontent.com/assets/1366709/15806758/0221ba28-2b19-11e6-835c-7d76b7f0fe55.png)

**Comment by shaneporter** [comment]
I'm not able to reproduce on Ubuntu 14.04 with either Firefox or Chrome. I get the word break visual appearance, but only at very narrow left column widths. 

On my environment, as I reduce the width of the viewport, the notebook date gets closer to the notebook title, then goes onto a new line, as shown below:

![image](https://cloud.githubusercontent.com/assets/2493614/15934250/d1ad9b9c-2e5a-11e6-9855-35334882a11e.png)

(different part of the tree, but the principle's the same.)

**Comment by gordonwoodhull** [comment]
That notebook has been renamed with a capital 'A' and I don't see this anymore. Must be a very specific edge case. (I just had that notebook open a lot, I guess.)

Note that it wasn't putting the date on the line with the end of the title, as it would usually do, so maybe a browser glitch?
