### ISSUE TITLE
almost all keyboard commands marked as write-only

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2021]
The keyboard shortcuts dialog is pretty much empty for someone else's notebook:
![image](https://cloud.githubusercontent.com/assets/1366709/15808218/fb6cc8c2-2b3f-11e6-8d6a-c757df9d96ab.png)

I guess it makes sense that the code editor commands would be missing, but we need to go through and make sure that all the commands that should be available in readonly mode, are.

In particular, I miss cmd-U Run!

**Comment by shaneporter** [comment]
A suggested fix has been made with PR #2041.

**Comment by gordonwoodhull** [comment]
I was being dumb and tired here, it makes sense that the rest of the commands are gone when in readonly mode. Fixed in #2041
