### ISSUE TITLE
discover page hard coded at 20 results

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2026]
It pretty much fills a page and then stops short.

[Apparently Masonry does work with infinite scrolling](http://stackoverflow.com/questions/15630049/how-do-i-add-infinite-scroll-with-jquery-masonry), but we might have to wait on that.

I don't know what the best solution is in the near term. Cap at 100 instead? This is a problem both on the client and server side - currently we don't have a lot of results populated but when we do, it's going to be too much to return efficiently.

**Comment by shaneporter** [comment]
Am I right in saying that the R code simply returns a list, but that there is currently no restriction (on the server side) in terms of what's being returned?

If we adopt an infinite scroll implementation, it not make sense to extend the R side to use parameters such as 'page size', 'page number' and so on. Currently, everything's being returned, and slicing's happening on the client side.

Please let me know if it's ok to use 100 as the cap. (Then we can open a 'discover page hard coded at 100 results' issue in future :smile:)

**Comment by gordonwoodhull** [comment]
For infinite scrolling, I think it might be efficient to return the entire list but the client would only pull notebook info and thumbnails on demand. That way you get that cool effect where you can scroll as fast as you want but the page you are currently looking at gets filled in afterward.

But that's some work. For 1.6, yes, probably capping at 100 is fine. And then we can see with experience whether just retrieving that original list of notebooks plus sort keys is too slow.
