### ISSUE TITLE
discover page should read metric from query string

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2029]
Someday, it should reflect the current view state (metric radio button) in the query string, so that when you reload you get the same thing.

**Comment by gordonwoodhull** [comment]
I'm going to go ahead and put this on 1.6, because it's weird for the page to reload and show a different metric. For lack of a better term, the query parameter can be `?metric=` and then the same string we use in `rcloud.config.get.notebooks.discover` and the radio buttons. The query string should set the radio button and the radio button should set the string (through `window.history.replaceState` [as used in editor_tab](https://github.com/att/rcloud/blob/develop/htdocs/editor_tab.js#L909-L913)).

**Comment by shaneporter** [comment]
Easy to implement. I'll pick this up tomorrow.
