### ISSUE TITLE
Error while forking other users notebook

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2038]
Following error is displayed while forking another users Notebook or folder

![image](https://cloud.githubusercontent.com/assets/10941328/15818459/12f22558-2bfb-11e6-9f41-7f4a99601936.png)

**Comment by gordonwoodhull** [comment]
Yes, you'll need to upgrade the `rgithub` package. Until we get it updated on rforge.net, the easiest way to upgrade is

```r
install.packages('devtools')
devtools:::install_github('cscheid/rgithub')
```
