### ISSUE TITLE
Shortcut code is run multiple times

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud#2043]
I ran into this whilst fixing #2042; the first time a shortcut is used, its code is invoked once. The second time it's used, it's run twice. The third time it's used it's run three times. And so on.

This was causing an issue with #2042, and no doubt is causing some other issues too.

**Comment by gordonwoodhull** [comment]
Whoah! That's crazy! 

Again, I think this was probably due to a bad merge because this code was worked over by multiple PRs (esp that longstanding ace keys PR and all the other shortcut stuff going on). Sorry about that, glad you found it quickly!
