### ISSUE TITLE
adapt discover splash progress to new bottleneck

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2048]
right now progress is based on loading the thumbnails, but that's not the slow part anymore. so it waits, waits, and then swiftly animates to complete.

we should find the new bottleneck (which may be load_everything #2027) and plot that progress instead.

**Comment by shaneporter** [comment]
That waiting was probably down to it loading all the notebooks. I'm yet to submit a PR for those efficiency improvements, but now a progress bar doesn't seem like the best visual indicator.

Would you agree that a spinner of some kind is better? I'm hopeful that it won't be shown for very long :smile:
