### ISSUE TITLE
replace doesn't work unless you replace the first one

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2052]
create a cell or notebook with a repeated word
 1. invoke replace for that word
 2. hit next till the second or later occurrence is has the current (orange) highlight
 3. hit replace (not replace all)

find appears to "reset": nothing is replaced and the current highlight goes back to the first occurrence.

the feature works if you replace the first occurrence.

**Comment by gordonwoodhull** [comment]
what appears to be happening is that focusout is not for the entire form, it's just bubbling up from the individual controls. so it will also happen when you click any button which is not the current one.

**Comment by gordonwoodhull** [comment]
It's annoying but I guess on focusout we have to check if the new focus is on any of the find/replace elements.

**Comment by shaneporter** [comment]
When I used `focusin` and `focusout`, I was wondering when I last used them. I suspect I have used `blur` and `focus` a lot more, and that I'll find a cleaner solution if I use them for this solution.

Thanks for your investigative work!

**Comment by gordonwoodhull** [comment]
fixed by #2057

**Comment by amithrb** [comment]
This issue still persists on release-1.6/ e6707d7
