### ISSUE TITLE
Unable to access discover page as anonymous user

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#2061]
Following error message is displayed when discover page is accessed as anonymous user

![image](https://cloud.githubusercontent.com/assets/9251570/15960250/9cc20428-2f1c-11e6-94b7-6134a8a7701b.png)

As per our discussion, published notebooks should be displayed on discover page for anonymous user.

**Comment by gordonwoodhull** [comment]
This is really an instance of #2027 but an important test case. Thanks @sanketd11!

**Comment by shaneporter** [comment]
So, `rcloud.config` is null for unauthenticated users, and that's what's causing the issue here. Is the solution to move the ocaps out of the authenticated list? Or are there more complicated issues surrounding this?

**Comment by gordonwoodhull** [comment]
Ah okay, this is going to need some changes on the server side because we need to have APIs that return the same data but filtered for anonymous users.

**Comment by shaneporter** [comment]
Issue #1759 is dependent on this (the discover anonymous no filled in stars bit.)

**Comment by gordonwoodhull** [comment]
If we do this, no stars will be filled for anonymous users, since the filled-ness should indicate whether the current user starred them.

**Comment by gordonwoodhull** [comment]
Implemented - only published notebooks are displayed.
