### ISSUE TITLE
RCloud-5: Search feature is not working when 'All lakes' option selected 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#2066]
Following error is displayed in session div:

![searchalllake](https://cloud.githubusercontent.com/assets/9251570/15997429/bd7a25b0-3101-11e6-8c6a-07dd39a07e66.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11.

@prateek05, any ideas here? Could this have to do with running different versions of SOLR on research vs core lake?

**Comment by gordonwoodhull** [comment]
@s-u, @prateek05, we still have this issue. any ideas? solr is now 5.5 on rcloud-5

i don't know what an externalptr is.

**Comment by prateek05** [comment]
check for the below properties in rcloud.conf if they are missing get it from rcloud.research
should exists in external lake block they are running solr with security
solr.auth.user
solr.auth.pwd

**Comment by prateek05** [comment]
TODO: Better error handling we should have gotten a unauthorized in msg.

**Comment by gordonwoodhull** [comment]
This was a misconfigured server - thanks to @prateek05 for the fix!
