### ISSUE TITLE
Discover page fails to show thumbnail images

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2069]
Currently discover page show like below, when we add 'thumb.png' to the notebook asset

![image](https://cloud.githubusercontent.com/assets/10941328/16032432/54e69fce-3223-11e6-8a0f-b54f05308f12.png)

**Comment by gordonwoodhull** [comment]
You may need to recreate your thumbnails in your notebooks, because the format changed and the old cached images are invalid. Or rename them and rename them back. Does this help?

**Comment by Prateek032** [comment]
Tried with the new notebooks by adding thumb.png to the asset and i also tried renaming the assets but still it shows as "Responsive image"

**Comment by gordonwoodhull** [comment]
I haven't checked in any artifacts so I need to run build.sh in order for it to work. But I am pretty sure the code is there. Please check if build is failing, and also what errors are shown in the browser's debug console. Thanks @Prateek032!

**Comment by gordonwoodhull** [comment]
@Prateek032, are you still seeing this error? Does the console still show errors with those odd urls with two `data:` in them?

**Comment by Prateek032** [comment]
@gordonwoodhull, I am able to see the thumbnail images with no errors

**Comment by gordonwoodhull** [comment]
Great! I think the code must have been out of sync somehow.
