### ISSUE TITLE
Ctrl+Z highlights the text

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#2070]
Reproducible only in chrome browser
Steps to reproduce: 
- Load a notebook either in read only or in view.html mode
- Invoke Find/Replace and look for any keyword (The keyword will be highlighted)
- Close the Find/Replace dialog
- Press Ctrl+Z 

The previously highlighted text gets highlighted again.

**Comment by gordonwoodhull** [comment]
Confirmed. Bizarre.
Thanks @sanketd11!

**Comment by gordonwoodhull** [comment]
I am not able to repro as of a79f0561b.

**Comment by shaneporter** [comment]
FWIW, neither am I.

**Comment by sanketd11** [comment]
The issue is no longer reproducible hence closing it.
