### ISSUE TITLE
Firefox: Unable to invoke Replace text field

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2072]
In editable mode when we press < ctrl + h >, Replace text field doesn't invoke. But for non editable mode it invokes replace option

**Comment by gordonwoodhull** [comment]
Specifically, it doesn't work if a cell has the focus.

**Comment by shaneporter** [comment]
This was caused by the code for #1846. It is not an issue on Chrome.

These are the offending lines.

https://github.com/att/rcloud/blob/develop/htdocs/js/ui/find_replace.js#L177-L181

I've had a try fixing it, but have been unable so far. Any ideas @gordonwoodhull?

**Comment by gordonwoodhull** [comment]
It's probably that magic copy code. is it throwing an error? If a cell has the focus but no selection, then we don't need to go through all that.

**Comment by shaneporter** [comment]
No error, but it's definitely causing the issue. I comment it out, and the find/replace issues (this and #2073) work normally.
