### ISSUE TITLE
Forked notebooks disappear under 'All Notebooks' tree

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2075]
Steps to reproduce:
1. Create new notebook.
2. Fork the notebook (three or four times)
3. Now go to discover page.
4. Navigate back to main page.

Random forked notebooks disappear under 'People I Starred' and 'All Notebooks' tree. But doesn't disappear under 'Notebooks I Starred' tree.

**Comment by gordonwoodhull** [comment]
Likely the same as #2119

**Comment by gordonwoodhull** [comment]
@amithrb reported this was no longer reproducible. I think this may have had to do with other concurrency issues in the notebook tree, fixed in #2158.
