### ISSUE TITLE
paste or drop thumbnail

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2078]
It's actually not very hard and it should excite people to populate the discovery page with their cool work.

But it's too late to be adding features to RCloud 1.6 right now

We should have a button in the asset panel (next to tabs) to the effect of ":heavy_plus_sign::camera:"

It brings up a small dialog where you can paste an image from the clipboard or drop a png onto the dialog. It previews the image, and if you press "Add Thumb" it adds/replaces the thumb.png asset.

Like what gmail and stackoverflow allow you to do. We already work with Blobs and data url PNGs and the clipboard and drag-and-drop and so on, so this is proven.

http://stackoverflow.com/questions/490908/paste-an-image-from-clipboard-using-javascript

**Comment by gordonwoodhull** [comment]
The dialog is because
- we don't want paste normally to do this, so it's good to have an explicit target
- likewise drag and drop usually means "drop this asset with its current name" and there are other reasons why you might want image assets
- a preview is helpful because it often takes several tries to get a good screenshot, and that's a fair amount of data to write to the notebook.

**Comment by shaneporter** [comment]
This duplicates the 'File Upload' functionality, but specifically for the thumb.

I imagine the next (much larger) iteration in this area is to have an integrated upload/assets panel. 

When 'Arrange panels by size' is checked, the 'File Upload' and 'Assets' panels are conspicuously separate.

**Comment by shaneporter** [comment]
@gordonwoodhull I guess the file extension for this asset _must_ be .png? In which case, it should give UI feedback if it's not the correct file extension. (But I will show instructions on the dialog where necessary.)

**Comment by gordonwoodhull** [comment]
Implemented in #2175
