### ISSUE TITLE
no keyboard shortcuts shown in view mode

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2083]
there should be at least esc, cmd-U right?

**Comment by gordonwoodhull** [comment]
![image](https://cloud.githubusercontent.com/assets/1366709/16109401/90d364e6-3376-11e6-9bc2-48411318f8e5.png)

**Comment by shaneporter** [comment]
That the dialog was shown with a shortcut, but none were listed, was a bit fishy. Turns out the jQuery selector was incorrect.

**Comment by gordonwoodhull** [comment]
Snagged @shaneporter's fix for this. Thanks!
