### ISSUE TITLE
aw shucks is displayed without formatting in shiny mode

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2084]
I feel like I looked into this and it may not be trivial, but please take a look @shaneporter. 

For an easy repro, it will display with any unpublished notebook in anonymous mode for shiny.html

![image](https://cloud.githubusercontent.com/assets/1366709/16109730/53da46ca-3378-11e6-88e3-a275b210ae4d.png)

Shiny always loads bootstrap so there is no issue using it.

**Comment by shaneporter** [comment]
I have opened a PR, 2106, for this.
