### ISSUE TITLE
Should deleted notebooks appear in discover page?

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2087]
- According to current behaviour, deleted notebooks are appearing in discover page.
- On clicking deleted notebooks, it appears under 'All notebooks' tree.
- On reloading, it appears under 'People I Starred' tree.

**Comment by gordonwoodhull** [comment]
No. They should not.

**Comment by gordonwoodhull** [comment]
Thanks @amithrb!

**Comment by shaneporter** [comment]
I assume this is a server-side fix @gordonwoodhull?

**Comment by gordonwoodhull** [comment]
Yup, I'm taking this.
