### ISSUE TITLE
Help panel remains closed when invoked

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#2088]
Steps to reproduce:
- Select the option to arrange panels by size and reload (Help panel will be on right side of page)
- Invoke help using '?' from command prompt or any cell e.g. '?help', '?table', etc.

The help panel remains closed even after invoking help in above case. When the help panel is on left side of the page, it automatically gets opened when help is invoked from cell or command prompt

**Comment by gordonwoodhull** [comment]
Fixed by #2097
