### ISSUE TITLE
'Import notebook from file' imports notebook with empty title

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2089]
**Scenario 1:**
1. Click on Import notebook from file.
2. Browse a file.
3. Clear Notebook description.
4. Click on import. 
5. Blank notebook without title is displayed under 'Notebooks I Starred' and 'People I Starred' tree. 

Following error is displayed.
![capture](https://cloud.githubusercontent.com/assets/19602717/16112497/315c1c06-33d5-11e6-908b-1712ccf8a809.PNG)

On reloading, the notebook disappears.

**Scenario 2:**
1. Click on Import notebook from file.
2. Browse a file.
3. Clear Notebook description.
4. Click on import. 
5. Blank notebook without title is displayed under 'Notebooks I Starred' and 'People I Starred' tree. 
6. Click near notebook options of notebook without title, then notebook will be displayed with title as 'untitled'.

![capture](https://cloud.githubusercontent.com/assets/19602717/16112805/b76d582c-33d6-11e6-8ba2-a1fc9d5f6012.PNG)

**Comment by gordonwoodhull** [comment]
The dialog should not allow you to close it if the title is blank.

Thanks @amithrb!
