### ISSUE TITLE
discover fork/star icons are taking up vertical space

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2099]
It's annoying that the date/author line has to wrap in cases like this:

![image](https://cloud.githubusercontent.com/assets/1366709/16159297/f8749466-348f-11e6-8f51-94b4aedb4f62.png)

Seems like the icons should impinge only on the title and perhaps the folder.

**Comment by shaneporter** [comment]
The icons are positioned absolutely, and after #2079, only the title needs to account for the space.

I'll make the necessary adjustments.
