### ISSUE TITLE
Notebook tree fails to display history versions of the Notebook

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2104]
steps to reproduce:
1. Create a new notebook with (user1) and add some contents to it
2. Load the notebook with another user (user2)
3. Open any of the history version of that notebook and refresh the tab
Notebook tree fails to display History versions of the notebook

**Comment by gordonwoodhull** [comment]
Step 1 isn't necessary (as long as it's a notebook owned by someone else, with history).

History loads okay if the notebook is starred (so this is another lazy load concurrency problem).

**Comment by gordonwoodhull** [comment]
This was fixed by eae6d7f98b7, loading the tree of any user before updating it with new info
