### ISSUE TITLE
scss error in htdocs/sass/rcloud-discover.scss

### ISSUE THREAD

**Issue by gaborcsardi** [att/rcloud#2111]
This is a new install, Ubuntu 14.04 (via vagrant), release/1.6 branch. Building gives me:

```
Running "sass:all" (sass) task
>> Invalid CSS after "...#{$item-width}%": expected expression (e.g. 1px, bold), was ";"
>>   Line 5  Column 38  htdocs/sass/rcloud-discover.scss
Warning:  Used --force, continuing.
Warning: Invalid CSS after "...#{$item-width}%": expected expression (e.g. 1px, bold), was ";" Used --force, continuing.
```

`--force` helps, and I don't anything majorly wrong in the Discover page, although I am not sure how it is supposed to look exactly.

**Comment by gaborcsardi** [comment]
I guess this is not very important. As soon as you'll put the generated CSS files in the repo, all will be fine.

Anyway, tell me if you need more info, here are some basics:
```
root@vagrant-ubuntu-trusty-64:/data/rcloud# ./node_modules/.bin/grunt --version
grunt-cli v1.2.0
grunt v1.0.1
```

```
root@vagrant-ubuntu-trusty-64:/data/rcloud# node --version
v4.4.4
```

**Comment by gordonwoodhull** [comment]
Thanks @gaborcsardi, probably the sass tool has evolved and is not accepting code it was okay with before.

**Comment by shaneporter** [comment]
Running `npm list grunt-sass` results in 1.1.0 for both @gaborcsardi and me.

I get no errors. :confused:

**Comment by gordonwoodhull** [comment]
We want to stop checking in our build artifacts #1728 and have a deep separate build / package step but it's too late to do that for this release.

**Comment by gordonwoodhull** [comment]
@shaneporter, you could still try deleting your `node_modules` and reinstalling because often it's a transitive dependency problem. Anyway, it sounds like it's complaining about an empty rule or something trivial like that.

**Comment by gaborcsardi** [comment]
It's probably the different `node-sass` version. It is 3.7.0 for me and 3.4.2 for @shaneporter

**Comment by gaborcsardi** [comment]
So I guess we can fix it at `^3.4.x` ?

**Comment by gordonwoodhull** [comment]
Fix the sass syntax. It's probably something that was already illegal but the old node-sass was lax about it.

**Comment by gordonwoodhull** [comment]
It's hard to fix the version of a transitive dependency, unfortunately.

**Comment by shaneporter** [comment]
I see it now. Working on a fix.

**Comment by shaneporter** [comment]
Fixing the first issue (with the SASS syntax) then gave me this (at a later stage of the grunt process):

```
Warning: grunt.util._.include is not a function
```

Working on that.
