### ISSUE TITLE
parallel folders error on fresh install

### ISSUE THREAD

**Issue by gaborcsardi** [att/rcloud#2112]
I got an `Error: uh oh, parallel folders` JS error on a fresh install of release/1.6 (tip is 888f4a998b074e3751f502b904de25b5bd7ce38a).

Here is a quick and dirty workaround:
```diff
--- a/htdocs/editor_tab.js
+++ b/htdocs/editor_tab.js
@@ -149,7 +149,7 @@ var editor = function () {
             if(lc === 0) {
                 // put a folder with the same name as a notebook first
                 if(a.children) {
-                    if(b.children)
+                    if(b.children && b.children[0].label != "loading...")
                         throw new Error("uh oh, parallel folders");
                     return -1;
                 }
```

Then everythings seems to work fine, except that I get a lot of fake notebooks, so this is probably not a proper fix:

```
All Notebooks
►My Notebooks
▼a's Notebooks
loading...
►a's Notebooks
►b's Notebooks
►c's Notebooks
►d's Notebooks
►g's Notebooks
►i's Notebooks
►o's Notebooks
►r's Notebooks
►r's Notebooks
►s's Notebooks
```

**Comment by gordonwoodhull** [comment]
Thanks @gaborcsardi. 

I can take this if @shaneporter doesn't recognize what's going wrong here.

**Comment by shaneporter** [comment]
If that's ok?

**Comment by gordonwoodhull** [comment]
No problem.

**Comment by gordonwoodhull** [comment]
Good news. I am able to reproduce this without destroying my setup by adding the following setting in rcloud.conf:

```
rcs.redis.db: 1
```

This switches the redis database to a fresh one (the default is 0).

Testing with a blank db should become part of our regimen.

**Comment by gordonwoodhull** [comment]
Notice how it's creating a folder for each letter in your user name. Clearly user error to have a name with repeated letters. :-p

**Comment by gaborcsardi** [comment]
@gordonwoodhull LOL :D

We haven't actually noticed that it was my user name. (!)

I see, so a string is treated as a list somewhere.

**Comment by gordonwoodhull** [comment]
Yeah, unfortunately rserve.js does some "smart" mapping of R types to JavaScript types and a vector of size one becomes a scalar. We have special cases for this all over the place.

I'm just adding 
```js
        if(_.isString(all_the_users))
            all_the_users = [all_the_users];
```
and that fixes it.

**Comment by shaneporter** [comment]
So this issue may have been around for a while?

**Comment by gordonwoodhull** [comment]
Looks like it probably came from the lazy notebook tree loading. Just goes to show we have to test all the edge cases because rserve.js will make them edgier. 

Good thing @gaborcsardi has been working from a blank slate.
