### ISSUE TITLE
Discover page fails to load default thumbnail image after deleting thumb.png

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2117]
Steps to replicate:
1. Add any png file to the notebook and rename it as 'thumb.png'
2. Open discover page, respective thumbnail appears
3. now navigate to the notebook and delete/rename the thumb.png asset 
4. Open the discover page and notebook appears like below

![image](https://cloud.githubusercontent.com/assets/10941328/16292162/678274e0-392c-11e6-9846-020e5ab10582.png)

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032!
