### ISSUE TITLE
Newly created notebooks disappear from notebook tree

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#2119]
Steps to reproduce:
- Create 5 to 6 new notebooks 
- Reload the page

Some of the notebooks will disappear from the notebooks tree. The 'Recent' panel will show         'null something went wrong' for the disappeared notebooks. 

Sometimes, the currently loaded notebook won't be present in 'Notebooks I Stared' or 'People I Stared' but will load from 'All Notebooks' tree without highlighting notebook name and with empty star icon & count as 1
refer notebook 6 in below screen shot

![1](https://cloud.githubusercontent.com/assets/9251570/16295579/63f8f34e-3945-11e6-86ed-8c661329300b.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @sanketd11, great write-up.

I wasn't able to repro this. I am guessing it is another concurrency issue aggravated by Github latency.

Are you able to repro this on rcloud-5?

**Comment by gordonwoodhull** [comment]
@sanketd11 reported this was no longer reproducible. I think this may have had to do with other concurrency issues in the notebook tree, fixed in #2158.
