### ISSUE TITLE
Unable to create a new notebook in RCloud-5

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2125]
Steps to replicate:
- add Notebook prefix (settings div) like "folder_name/Notebook_name"
- click on create new notebook icon

following error is displayed in session div

![image](https://cloud.githubusercontent.com/assets/10941328/16330994/0d60b7c6-39bb-11e6-87e2-475ce2d4f4d6.png)

**Comment by shaneporter** [comment]
Is this happening for you locally?

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032. Unfortunately I am doing some last minute fixes in this area, so it's been unstable.

Should be fixed now!
