### ISSUE TITLE
can't see the current find highlight if it's the cell selection

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2130]
if you get the find text from the cell selection, it seems that ace's selection highlighting overrides our find-result highlighting, so you can't see that it's a match or the current match.

**Comment by shaneporter** [comment]
Do you mean as below, where the current match is actually on that first `dnorm`, but the background color is neither yellow (match), nor orange (current match)?

![image](https://cloud.githubusercontent.com/assets/2493614/18124149/e7faa1d4-6f68-11e6-96fb-55a061d0fe4d.png)

**Comment by shaneporter** [comment]
PR #2252.
