### ISSUE TITLE
Notebook doesn't get highlighted

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2147]
Load any other users notebook in to your account (read only mode), the notebook gets loaded but it is not highlighted in the notebook tree

![image](https://cloud.githubusercontent.com/assets/10941328/16441093/052df66c-3de5-11e6-9697-322886c843d9.png)

**Comment by gordonwoodhull** [comment]
Grey should mean that the notebook is private, so it should look like this e.g. if the notebook was deleted or hidden by its owner. But I guess that is not what you mean.

I need more info to repro. I see notebooks of other users highlighted as usual:
![image](https://cloud.githubusercontent.com/assets/1366709/16451336/62926960-3dd0-11e6-8c5e-74fe566a7609.png)

**Comment by gordonwoodhull** [comment]
I missed some detail on the call today. Is this particularly when opening a notebook by URL? 

I am still not able to repro (unless the notebook is deleted by its owner).

**Comment by Prateek032** [comment]
It happens only when other user's notebook is accessed through URL

**Comment by gordonwoodhull** [comment]
Okay, I must have picked the wrong user somehow, was able to repro looking at a random user on rcloud.social. 

We needed to load a user's tree before updating the model (`notebook_info_`).
