### ISSUE TITLE
Renamed image file shows cached content of previous image

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2148]
Steps to replicate:
- Upload any png file to the asset (eg: image.png)
-  rename the uploaded image with another name (eg: image1.png)
- Now upload another png file and rename it with the previously uploaded image file name (eg: image.png)

The newly renamed file shows the contents (cached) of the previously uploaded file

**Comment by gordonwoodhull** [comment]
Confirmed. 

I know that Chrome is very aggressive about caching. I guess one solution is to link to the specific version for the image, e.g. `http://192.168.1.151:8080/notebook.R/d90a67db7559554941f032a48b8febf8/8434bfb41a0133b76e4484da0a087c9f97bf3173/thumb0.png`

We intentionally don't do that for the link in the lower-left but there should be no harm for the image.

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032!
