### ISSUE TITLE
discover page show times

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2150]
While the spelled-out dates that we have are kind of nice, like Wed Jun 29 2016, it would be helpful to show the time, at least for recent notebooks. 

Maybe time-only for today, time and date without year for the past week, and date and year beyond that?

**Comment by shaneporter** [comment]
Perhaps a nicer alternative would be something like:

'5 minutes ago'
'12 hours ago'
'3 days ago'

**Comment by shaneporter** [comment]
That kind of thing...and so on.

**Comment by gordonwoodhull** [comment]
Sure why not? That's sort of the github flavor.

I guess we could use [timeago](http://timeago.yarp.com/). Apparently [stackexchange does, or did](http://stackoverflow.com/a/3177900/676195).

**Comment by shaneporter** [comment]
If the cool kids are using it...

**Comment by gordonwoodhull** [comment]
There's this one too, using custom tags: https://github.com/github/time-elements

Judging by the tags, this might be what Github is using.

**Comment by shaneporter** [comment]
Cool. And it looks like it works on Edge. 
So that's a relief.

**Comment by shaneporter** [comment]
PR #2170.

**Comment by Prateek032** [comment]
After editing Notebook, discover page fails to display the time in **Firefox**  browser.

Discover page before editing Notebook

![image](https://cloud.githubusercontent.com/assets/10941328/19031897/5b8ca410-8974-11e6-888f-fa37429af3d8.png)


and Discover page after renaming the Notebook

![image](https://cloud.githubusercontent.com/assets/10941328/19031930/a1d05c6e-8974-11e6-8b59-3d35bd16064b.png)

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032, please open a new issue for this.
