### ISSUE TITLE
Notebooks are not getting deleted

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2153]
After deleting the Notebook it should disappear from all the trees, but deleted Notebook still appears in 'All Notebooks' tree wit star count 0

**Comment by gordonwoodhull** [comment]
I saw this on rcloud.social but not rcloud-5 or my local. So I grabbed the latest release/1.6 commit and that seems to have fixed it.

I am guessing that be80cf0690649 lazy-loading earlier solved it somehow, but I'm not sure why.

**Comment by gordonwoodhull** [comment]
@Prateek032, thanks for the report - please retry.

**Comment by Prateek032** [comment]
@gordonwoodhull , I am not able to replicate this issue with the latest commit 7e31525

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032! Closing.
