### ISSUE TITLE
htmlwidgets are growing

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2162]
Some htmlwidgets, in particular networkD3 and dygraphs, grow about 1cm taller every 5 seconds.

**Comment by gaborcsardi** [comment]
Actually, there is still a problem. The problematic widgets still grow whenever you resize the window. Even if you make it smaller. :(

I am pretty sure that the resizing code for these widgets is wrong. They resize themselves to a larger size than the containing iframe. I'll see if I can come up with sg to fix this today.

**Comment by gordonwoodhull** [comment]
Argh. Well I guess that is consistent. 

Margins or something?

**Comment by gordonwoodhull** [comment]
Fixed by #2164
