### ISSUE TITLE
replace the cell delete button

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2176]
Overwhelming feedback is that it's too difficult to click the tiny checkbox and then the tiny trashcan at the top of the screen.

I just click the header and then press the delete key, and find that easier than the old way, but let's replace the old button too.

I believe in having lots of ways to do things.

**Comment by shaneporter** [comment]
Sorry, I don't quite follow. You mean replace the 'trash' button at the top of the notebook?

**Comment by gordonwoodhull** [comment]
Yes, but now it's two clicks very far away from each other. And the easier way is less visible, so people probably think you have to click the little checkbox and then the little trashcan.

I am not sure if people are just used to the old way of doing things but the perception is that we've actually made it harder to delete cells, when the intention was the opposite!

Maybe in time they'll learn the easier ways, but for now let's ease their adjustment.

**Comment by shaneporter** [comment]
Sure - will do. You can't please everyone I guess. :confused: but let's try :smile:

**Comment by shaneporter** [comment]
PR #2182.
