### ISSUE TITLE
Cell language changes from 'Markdown' to 'GCC Machine Description'

### ISSUE THREAD

**Issue by NaikPrateek** [att/rcloud#2178]
Steps to replicate
- Create a new cell with the Markdown 
- add some contents to it using 'Blockquotes' (for eg:  > RCLOUD)
- Execute the cell and refresh the page

cell language changes to "GCC Machine Description"

![image](https://cloud.githubusercontent.com/assets/10941328/16866891/47e546fa-4a8c-11e6-800f-cbe4cc3d8932.png)

**Comment by gordonwoodhull** [comment]
This confuses me because for more than a year (since 83fcb400e) we have "coerced" the language field of notebooks as we are reading them [in rcloud.augment.notebook](https://github.com/att/rcloud/blob/306ba3d38fd99f5c760ac56595bcac584f7bf98a/rcloud.support/R/rcloud.support.R#L64-L70):

```r
    if(length(res$content$files))
      res$content$files <- lapply(res$content$files, function(o) {
        file.ext <- if (is.null(o$filename)) "" else tail(strsplit(o$filename, '\\.')[[1]], n=1)
        if (file.ext %in% names(.session$file.extensions))
          o$language <- .session$file.extensions[[file.ext]]
        o
      })
```

We should only fall back on GitHub language detection if we don't recognize the extension. And that detection was always problematic because they seem to look at the content as well as the extension.

**Comment by gordonwoodhull** [comment]
(And although Markdown is unique in that it's built-in and doesn't use a language extension, it still [registers the .md extension](https://github.com/att/rcloud/blob/306ba3d38fd99f5c760ac56595bcac584f7bf98a/rcloud.support/R/languages.R#L3).)

So I think we have this covered but there must be a subtle bug.

**Comment by Prateek032** [comment]
Once the cell becomes `GCC Machine description` we can't delete that particular cell. If we try to delete, we get following error

![image](https://cloud.githubusercontent.com/assets/10941328/19151695/c4c535c2-8beb-11e6-83c1-97efef845863.png)

**Comment by gordonwoodhull** [comment]
We do add Markdown to the languages we return in the OCAP, as linked above. We don't add it to `.session$file.extensions` so the override doesn't work. I don't remember if there's a reason for this.

**Comment by rclouddocs** [comment]
This also happens with tabs in Markdown cells.
Steps to replicate

Create a new cell with the Markdown
add some contents prefaced by a tab
Execute the cell and refresh the page
cell language changes to "GCC Machine Description"
![screen shot 2016-12-09 at 3 53 39 pm](https://cloud.githubusercontent.com/assets/9993565/21064220/b005658a-be27-11e6-836f-3d2e2766f43d.png)
