### ISSUE TITLE
Update solrsetup.sh and rcloud-solr for version 5.5.1

### ISSUE THREAD

**Issue by benz0li** [att/rcloud#2179]
The following changes neet to be applied in order to get solr-5.5.1 working with the current $ROOT/services/ubuntu/init.d/rcloud-solr:

**$ROOT/conf/solr/solrsetup.sh**
change every occurence of `example` to `server` in the paths.

**$ROOT/services/rcloud-solr**

```
#!/bin/sh

cd /data/rcloud/services
solr/bin/solr start >> solr.out
```

**Comment by prateek05** [comment]
Hi @benz0li . We might not want to use init.d script for solr 5.5 since they package the service scripts themselves in the build up. 
Thanks I ll take a look at the current init and perhaps replace it with readme of how to use the the ones supplied with 5.5 itself

**Comment by gordonwoodhull** [comment]
Compatibility with latest SOLR should be obviated by our replacing the implementation with **rcloud.solr** in 1.9.

**Comment by dougmet** [comment]
In the **rcloud.solr** work I've not changed the solr version (but can do). I have, however, changed all instances of the word `example`. So the schema name is now `rcloud` and the core is called `rcloudnotebooks`.

**Comment by gordonwoodhull** [comment]
The search implementation in RCloud 1.9, [rcloud.solr](https://github.com/att/rcloud.solr), supports SOLR version 7.
