### ISSUE TITLE
Update Install.md to match $ROOT/conf/solr/README.md

### ISSUE THREAD

**Issue by benz0li** [att/rcloud#2180]
**Search**
[...] and run

```
cd $ROOT/conf/solr
sh solrsetup.sh $ROOT/services
```

assuming `$ROOT` is set to your RCloud root directory. [...]

**Comment by gordonwoodhull** [comment]
Sorry for missing this one. I am guessing this is a documentation issue. @benz0li, if you're still around, could you please clarify?

**Comment by gordonwoodhull** [comment]
We will have a big SOLR overhaul in 1.9 so I think if we update the documentation appropriately this can be fixed.

@dougmet, at some point, please review the install docs and mark the old instructions as old, and include any required new instructions.

**Comment by benz0li** [comment]
Hi @gordonwoodhull,

This is a documentation issue, which has been solved with merging pull request #1489 on Jan 27, 2016.

**Comment by gordonwoodhull** [comment]
Thanks @benz0li!
