### ISSUE TITLE
button to return to edit mode from discover

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2186]
It feels awkward to have to click on a notebook I may not care about in order to get from discover mode to edit mode.

We should add a button - which means enabling the navbar extension mechanism and making sure that we have the appropriate modes or flags. There may be other buttons wanted here.

It can just be the same edit icon we use in view mode, but the title should read Edit Mode instead of Edit Notebook. There's no active notebook, so it will bring you to edit.html with no parameters, loading the last notebook.

![image](https://cloud.githubusercontent.com/assets/1366709/16877864/2c39de3e-4a78-11e6-8c1a-4f9d9e60c6a9.png)

**Comment by gordonwoodhull** [comment]
It will also have the same asymmetry as view mode where clicking View opens a new tab, but clicking Edit navigates within the tab. This is weird but expected.

**Comment by shaneporter** [comment]
Why not use the existing RCloud link on the left of the nav bar?

**Comment by gordonwoodhull** [comment]
Hmm, that's not currently a link, but it could work, I guess. 

Is edit.html the main page? I guess it is.

You may have to modify [rcloud.logo](https://github.com/att/rcloud.logo) as well to get this working in all cases. If you haven't seen this, it's an extension that adds the official logo, and a swatch indicating what instance you're on.

![image](https://cloud.githubusercontent.com/assets/1366709/17064199/58ed8958-5009-11e6-892d-b9f91142ca5d.png)

**Comment by gordonwoodhull** [comment]
Ah, I see that it's a link when the extension is not enabled.

**Comment by shaneporter** [comment]
Yeah I'll take a look!

**Comment by shaneporter** [comment]
PR #2200 addresses this, together with att/rcloud.logo#2.
