### ISSUE TITLE
Indicate how many cells are selected

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2189]
With notebooks with lots of cells, it can be nerve-wracking to use the multiple-selection feature, because it isn't possible to see all the cells that are selected.

If we display the number of cells selected, one can at least know if it's just the ones on the screen, before pressing Delete.

Since the selection bar is mostly empty, we could easily add the text "N cells selected".

**Comment by shaneporter** [comment]
Good idea, but think it would be better if we used "N of T cells selected".
