### ISSUE TITLE
search again hotkey

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2192]
Cmd/ctrl-G (and F3 on Windows/Linux) goes to the next occurrence of the search term (or previous, with shift-cmd/ctrl-G / shift-F3). 

If the find dialog is not open, opens it.

**Comment by shaneporter** [comment]
Currently, if 'next' is clicked, the match index advances. If the find dialog is closed, and reopened, that match index resets to the first match.

So for this:

> If the find dialog is not open, opens it.

Should 'go to next' start at the first item (or the second?) and
Should 'go to last' go to the first, or the last?

My feeling is that go to next should start at the beginning, and go to last should go to the last one.

**Comment by gordonwoodhull** [comment]
That was my thought initially, but at least in Chrome, the find command opens continues where it left off. 

Arguably that's different because their Find control closes when you click on anything. 

It looks like the standard behavior (looking at TextEdit and LibreOffice) is to *continue from the cursor position*. That's pretty smart. Not simple in our case, but we've already done part of that for populating Find from the current selection.

**Comment by gordonwoodhull** [comment]
That's also nice because it can be the same behavior for the case where the Find dialog has lost focus (and thus we've lost the results) as for when the Find dialog has been closed.

**Comment by shaneporter** [comment]
Hmm... I'm more used to shift + f3 being used for 'go to previous' than 'go to last match' (Windows/Linux.)

**Comment by gordonwoodhull** [comment]
Think I wasn't careful with my words there, that's what I meant. Editing now.

**Comment by shaneporter** [comment]
PR #2205.
