### ISSUE TITLE
Uploaded image is overlapping on other divs

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2201]
Browser: Firefox
Upload any images to the asset div, the uploaded image overlaps on work space, session, data frame and file upload div

![image](https://cloud.githubusercontent.com/assets/10941328/17136417/d1e98932-5352-11e6-8617-219fa9829bcd.png)

**Comment by shaneporter** [comment]
Firefox specific @Prateek032? I wasn't seeing this on Chrome. But will take a look.
Thanks for reporting.

**Comment by shaneporter** [comment]
Fix proposed with PR #2207.
