### ISSUE TITLE
cursor should select current find result when find closed

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2204]
It's useful to use Find to place the cursor where you want to edit. At least when the notebook is editable, we should probably activate the cell of the current result and select the current result.

This is particularly useful in combination with Find Again #2192, because often you want to do something more complicated at each site, editing each result.

Find is a marvelously complicated little feature! It's remarkable how few applications get every feature right.

**Comment by shaneporter** [comment]
Suggested resolution in #2254.
