### ISSUE TITLE
changing language should leave focus on that cell's content 

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2206]
if it's active

**Comment by shaneporter** [comment]
When I change the cell's language using the dropdown located above right of the cell content, focus stays on that dropdown.

**Comment by gordonwoodhull** [comment]
Right, I've retitled: it seems to me the focus should land on the content. 

I think it's unlikely that after selecting a new language, one would want to arrow around in the other languages. Editing the text is far more likely.

**Comment by shaneporter** [comment]
Thanks.
