### ISSUE TITLE
Find/Replace: Unable to find content using next or previous button

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2210]
Unable to navigate to next or previous content, using next or previous button

Steps to Reproduce:
- Create new notebook
- Add new cell
- Add contents to newly created cell
- Reload the URL
- Invoke find/replace feature option
- Click next or previous button

**Comment by gordonwoodhull** [comment]
Thanks @amithrb! I can't remember this on Firefox or Chrome or both?

I'm not able to repro on OSX Chrome or Firefox. Will test on Linux another day.

On the call, this looked very much like a recurrence of #2052, where clicking "find next" resets the search because it loses focus.

**Comment by amithrb** [comment]
@gordonwoodhull , this issue is on both the browsers.
