### ISSUE TITLE
Firefox: Match count is not getting displayed for find/replace

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2213]
For editable cell, the match count is not getting displayed for find/replace

Steps to Reproduce:
- Create new notebook
- Add new cell
- Add content to newly created cell
- Save it
- Invoke find/replace option
- Search for content
- Close find/replace option using ESC or Close option.
- Once again invoke find/replace option

Below is the screenshot
![capture](https://cloud.githubusercontent.com/assets/19602717/17244604/5d22f8cc-55a0-11e6-80b5-5e9ef28fab5f.PNG)

**Comment by gordonwoodhull** [comment]
This is related to #2214.

For me, a recently-used menu is left behind when the dialog closes. If I click away, it invokes #2214, highlighting the results. If I invoke find while the recently-used menu is shown, then find appears with no match count shown.

@amithrb, is this what you see as well?

**Comment by gordonwoodhull** [comment]
menu left behind floating in space
![image](https://cloud.githubusercontent.com/assets/1366709/17365481/5c940402-5954-11e6-836d-c0308e975a59.png)

**Comment by shaneporter** [comment]
Suggested fix in #2249.

**Comment by gordonwoodhull** [comment]
fixed by #2251
