### ISSUE TITLE
access to htmlwidgets renderValue

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2216]
For RCAP and other RCloud-native dashboards, it will be nice to be able to update the data and have the chart update dynamically (incrementally with transitions).

I don't know if htmlwidgets currently has an R API for this or if this is done in an ad-hoc way for Shiny. It's easy enough to expose an ocap from JavaScript back to R to send new data - the R integration is the unknown part.

There is probably more information in this thread: https://github.com/ramnathv/htmlwidgets/issues/86

And [rstudio/crosstalk](https://github.com/rstudio/crosstalk) may also help.

I'd like to put the solution at the RCloud level rather than the RCAP level, so that it's available for bare mini.html dashboards as well as RCAP dashboards.

**Comment by gaborcsardi** [comment]
You mean `renderValue`? Probably. This is only called once for static (=non-Shiny) widgets. But maybe we can call it multiple times. There is no real public API unfortunately.

> There is probably more information in this thread: ramnathv/htmlwidgets#86
> And rstudio/crosstalk may also help.

Not really, unfortunately. This is a completely different mechanism, fully client-side. There are a lot of reasons why we cannot use this, or even anything from its implementation, really.

But, assuming that we can use `renderValue`, how would this work? How do we decide when to update the data, and when to replace the cell completely?

One possibility is that we implement this in rcloud, provide an `update` method for widgets, and then 
1. the user can manually use this in the notebook to update the data in an existing html widget, and 
2. we will use it in RCAP to change the data.

But I'll need some time to decide if this is possible at all, and we can get to `renderValue`.

**Comment by gordonwoodhull** [comment]
Fixed title, thanks! Yes, the idea is to imitate Shiny's behavior here. If the function is exposed on the client side, then we can wrap in an ocap, so the implementation should be simple.

I think it would be an explicit `update` method on the R side, as you say. In general, if Shiny is declarative, then RCloud is imperative. I take it RCAP has more of a declarative reactive model, though, so maybe it could be fit into that.

**Comment by gaborcsardi** [comment]
So, after looking around, it seems that no htmlwidgets make use of the "updating data" feature. The closest I got was `timevis`, which keeps the display, but clears the old markers and then adds the new ones. 

There are some toy ones that make use of `renderValue`: 
https://github.com/jcheng5/bubbles
https://github.com/jcheng5/d3scatter

I can't run the example app for the first one, it needs server support. The second one requires crosstalk it seems.

Anyway, I don't it is worth adding support for updates via `renderValue` currently. Maybe later.

**Comment by gordonwoodhull** [comment]
we could reopen this on [rcloud.htmlwidgets](https://github.com/att/rcloud.htmlwidgets) if still interested.
