### ISSUE TITLE
htmlwidgets are slow

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2219]
Moving discussion from att/rcloud.rcap#98

@gaborcsardi wrote:

> @gordonwoodhull OK, here is a plan. We'll only send scripts (and data?) over once. On the client side, we store them in a dictionary. We use hashing to see if we need to send a script over or not.
> 
> For this we need to parse the HTML to find the tags that I want to extract and hash. Can I depend on the xml2 package for the HTML parsing? Or does rcloud have a standard way to parse HTML on the server side?
> 
> Btw. it would be even better if I could serve the scripts from the server, over standard HTTP. Is there a standard rcloud way to do this?
> 

@gaborcsardi, htmlwidgets uses htmltools. So I think you can use the htmltools API to read/write the dependencies, and you won't need to parse HTML. In an experimental version of rcloud.shiny, I used this to rewrite the URLs.

Serving over HTTP is possible, but it's a little bit more complicated than you might guess. For Shiny, the session **is** the server, so it can use the URL namespace however it wants, including creating a bunch of temporary directories. 

We can't do that, since there are many sessions running at the same base URL. It's a namespace issue. Each session could stomp on the URL namespace of all the others, and the session may not be running on the server you're connected to (because of load balancing). 

So we offer the following two mechanisms instead.

 * If the asset is in the `inst/www/` directory of a package, it can be fetched with `shared.R/package/<asset>`

 * Or you can use `proxy.R` to serve the scripts over HTTP from your session, but you'll need to run your own HTTP server from R.

`proxy.R/<user>/<session>[:<port>]/[<path>]`
https://github.com/att/rcloud/blob/develop/htdocs/proxy.R

Yes that is `:port` inside the path portion of the URL. Usage example using `rcloud.session.info()` to get the session id: https://github.com/att/rcloud.shiny/blob/feature/call-serviceApp/R/rcloud.shiny.R#L45-L48

The (untested) direction I think rcloud.shiny is going is: 
 1. allow Shiny to spawn its own server, but don't block on it
 2. poll that server via a timeout from the client
 3. create an iframe and point to the proxy.R URL to allow Shiny to serve its own `/`
 4. now the Shiny server owns its own URL namespace and can do whatever it wants

That's a possible approach for htmlwidgets as well. In the non-viewer mode, it launches an HTTP server and enjoys its own URL namespace to serve assets.

**Comment by gordonwoodhull** [comment]
Oops, scratch that last thought - it's just using file:// URLs. But it could use HTTP like Shiny does.

**Comment by gaborcsardi** [comment]
OK, let's forget the serving via http approach, too difficult.

> @gaborcsardi, htmlwidgets uses htmltools. So I think you can use the htmltools API to read/write the dependencies, and you won't need to parse HTML.

Good idea. I could probably extract a state between the widget and the final HTML, e.g. a list of tags as R objects, and then manipulate that with htmltools. 

Btw. if this is the case, I can *almost* just link to the JS files in the R package of the htmlwidget, except that they are in `inst/htmlwidget`. So how about somehow allowing this, in addition to `inst/www`?

> In an experimental version of rcloud.shiny, I used this to rewrite the URLs.

Do you have a link for this?

**Comment by gordonwoodhull** [comment]
Same link, that one file holds all my of my experiments for a new rcloud.shiny. Specifically I'm changing processDependencies in renderPage, but you could do other things before the page is rendered.

https://github.com/att/rcloud.shiny/blob/feature/call-serviceApp/R/rcloud.shiny.R#L34

Huh, I didn't realize that packages had a special `inst/` dir for htmlwidgets. I wonder why, maybe the versioning. Everything else htmltools uses `inst/www` right?

Anyway, sure, you could look at modifying shared.R, if that helps. It's very simple:

https://github.com/att/rcloud/blob/develop/htdocs/shared.R

**Comment by gaborcsardi** [comment]
The problem with the `htmltools` approach is that the `print` method only gives me the formatted HTML code. :( No way to get to the `htmltools` object.

**Comment by gordonwoodhull** [comment]
Could you intercept `print` itself instead of the viewer? I don't know how the print magics work.

**Comment by gaborcsardi** [comment]
@gordonwoodhull Yes, that's what I am thinking about. Let me try. It can be done, the only question is how much hacking and `htmlwidgets` internals we need to use.....

**Comment by gaborcsardi** [comment]
@gordonwoodhull It seems that if I define and export a `print.htmlwidget` S3 method from `rcloud.support`, then that will be used by default. This is pretty good!

**Comment by gordonwoodhull** [comment]
@gaborcsardi, that's great! We should get a lot more control this way.

**Comment by gaborcsardi** [comment]
@gordonwoodhull `shared.R` is interesting. First tries to interpret `url[1]` as an installed package name, and searches its `www` directory.

Then it tries to interpret `url[1]` as a user name, and searches the rcloud user library. This mechanism makes the user library search references slightly unreliable. The installation of a package might break them. I think it is better to signal the user library with some special string that cannot be an R package. There are plenty of strings like this, e.g. `_user` would be fine, or even just `_`.

Anyway, for the current purpose, I suppose I can just use `_htmlwidgets` to refer to `inst/htmlwidgets`. This hopefully does not introduce more ambiguity.

**Comment by gordonwoodhull** [comment]
Weird! Yeah that makes sense. Go for it!

Going forward we could optionally allow `_user` and `_www` to disambiguate. (But then I guess we also end up with `_user/_htmlwidgets` so meh.)

**Comment by gordonwoodhull** [comment]
Fixed by #2231
