### ISSUE TITLE
Modifier-click shortcut help 

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2223]
There are a bunch of alt-click shortcuts which we should document in a section of the online help.

I think it all consists of "<modifier>-click <button>". I'll write up the current ones, and create more of these shortcuts, if you design the structure for them @shaneporter.

**Comment by shaneporter** [comment]
Couldn't find "-click", but perhaps I'm not understanding correctly.

**Comment by gordonwoodhull** [comment]
Thanks @shaneporter. Meaning, all of the shortcuts are modifier keys plus a click on something, rather than some other action such as a drag or swipe or right click or something.

**Comment by shaneporter** [comment]
So, in terms of a general shortcut definition, we just need to add a 'usesClick' boolean or something similar?

**Comment by gordonwoodhull** [comment]
Okay, if this isn't clear, we can talk about it when I get back next week. Thanks.

**Comment by shaneporter** [comment]
OK, thanks @gordonwoodhull.
