### ISSUE TITLE
Multiple instances of RCloud

### ISSUE THREAD

**Issue by tonijung** [att/rcloud#2228]
Is it possible to have multiple instances of RCloud running on Chrome? Where there's a different notebook in each tab.

**Comment by gordonwoodhull** [comment]
Sure, just try it e.g. on rcloud.social. It's one instance of the server but a separate R session (process) for each tab.

**Comment by gordonwoodhull** [comment]
There are also shortcuts like ctrl/cmd-clicking on notebooks to open in a separate tab.

Hope this answers your question. I'll close this but please comment if you have any further questions!
