### ISSUE TITLE
Master version reads devel

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#2238]
https://github.com/att/rcloud/blob/master/VERSION 
reads 1.6.2-devel

**Comment by gordonwoodhull** [comment]
Thanks @prateek05, fixed in 559b022

**Comment by gordonwoodhull** [comment]
BTW, master is a couple of commits ahead of the 1.6.1 tag but it's only changes to NEWS.md

**Comment by gordonwoodhull** [comment]
Er, rather, 95f253351... sheesh
