### ISSUE TITLE
htmlwidgets fail on cluster

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2239]
I'm seeing all htmlwidgets currently fail on rcloud.social, after I updated to 1.6.1

The error reads (where "dygraphs" is replaced with whatever package).

```
Error in htmltools::renderDependencies(deps, "href") : 
  Dependency dygraphs-binding 0.9 does not have a usable source
In addition: Warning message:
In FUN(X[[i]], ...) :
  Cannot find htmlwidgets dependency: /tmp/Rtmp5A4K0e-gordonwoodhull/widgetbinding7f860601f3a
trace:
stop("Dependency ", dep$name, " ", dep$version, " does not have a usable source")
htmltools::renderDependencies(deps, "href")
as.character.htmlwidget(x, ..., ocaps = FALSE)
as.character(x, ..., ocaps = FALSE)
print.htmlwidget(x)
function (x, ...) 
UseMethod("print")(x)
```
https://rcloud.social/edit.html?notebook=2db9a7e5847dfa2c078d206d612dd3fa

Tried reinstalling some, didn't help. I'm not sure why it would be using more than one process which might have been distributed to different VMs, but that kind of looks like the problem.

**Comment by gaborcsardi** [comment]
Maybe you just need to update `htmltools` to the latest version (0.3.5). Maybe also `htmlwidgets`.

E.g. sticking `install.packages("htmltools")` to the beginning of the `dygraphs` notebook solves the problem. 

I hope this works, to be honest, I never tested it with older package versions.

**Comment by gaborcsardi** [comment]
@gordonwoodhull Can you update `htmltools` and `htmlwidgets` on rcloud.social?

I believe that the update will fix the problem, or at least this problem. 

If you cannot update for some reason, then I need to come up with a workaround.

**Comment by gordonwoodhull** [comment]
Thanks @gaborcsardi! I had updated htmlwidgets but not htmltools. 

Have not had a chance to test this but I'll try it this morning.

**Comment by gordonwoodhull** [comment]
After some wrestling, this was resolved by updating both packages. Thank @gaborcsardi!
