### ISSUE TITLE
Upgrade to the new release - do other functions need updating?

### ISSUE THREAD

**Issue by ra-mac** [att/rcloud#2242]
When upgrading to the new RCloud release, do I need to do a refresh / setup / ??? to other components such as solr, session server, ... ? (Upgrade instructions, in addition to the Install instructions, would be helpful.)

**Comment by gordonwoodhull** [comment]
Hi @ra-mac, for this release, there shouldn't be any special upgrade instructions, except for the usual churn of R packages.

Are you running into problems after the upgrade?

**Comment by ra-mac** [comment]
No problems yet. I did a git pull origin master and scripts/fresh_start.sh. This is my first upgrade, so I am just checking that I did it right. It seemed too easy! :)


________________________________
