### ISSUE TITLE
Require recent versions of 'htmlwidgets' and 'htmltools' for 'rcloud.support'

### ISSUE THREAD

**Issue by gaborcsardi** [att/rcloud#2243]
To eliminate cryptic error messages that you get with older versions.

**Comment by gordonwoodhull** [comment]
@gaborcsardi, could we split our htmlwidgets support into an rcloud.htmlwidgets extension package and version it separately? 

It seems like the coupling is very light. It would just have to get put in the `rcloud.alluser.addons` list in [rcloud.conf](https://github.com/att/rcloud/wiki/rcloud.conf)

I'll go ahead and create the repo - please transfer the code if possible, or argue against this if you don't think it'll work.

https://github.com/att/rcloud.htmlwidgets

**Comment by gordonwoodhull** [comment]
Of course we'll also have to remove it from rcloud.support in 1.6.2 in order for the extension to work. This ticket can track that.

**Comment by gaborcsardi** [comment]
Make sense. 

The one drawback I see is that people would have to load the new package explicitly, whereas for now everything just works.

**Comment by gordonwoodhull** [comment]
It would usually be configured to load automatically like we do for some of the side panels and all of the languages

https://github.com/att/rcloud/blob/develop/conf/rcloud.conf.samp#L15-L16

**Comment by gaborcsardi** [comment]
OK, that makes sense.

**Comment by gaborcsardi** [comment]
Done in #2282.

**Comment by gordonwoodhull** [comment]
Fixed by att/rcloud.htmlwidgets@e30d4745 - the dependencies can be (and are) specified as needed in `rcloud.htmlwidgets/DESCRIPTION`
