### ISSUE TITLE
Search: clicking previous/next for not found content results in NaN being displayed

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud#2248]
Steps to reproduce:

1. Open find or find/replace.
2. Enter text that will not be found, verify that `0 of 0` is shown in the search field.

![image](https://cloud.githubusercontent.com/assets/2493614/18089807/9ac5eaa4-6eb9-11e6-90c3-a450f2ee60b4.png)

3. Click the previous or next button and observe the 'NaN of 0' that is shown:

![image](https://cloud.githubusercontent.com/assets/2493614/18089826/b8e4b9ac-6eb9-11e6-8aca-f6989ee0d3c3.png)

**Comment by shaneporter** [comment]
Fixed in PR #2250.

**Comment by Prateek032** [comment]
NaN is still displayed. Steps to reproduce:
1. Invoke Find and Replace
2. Provide inputs to the both the fields 
3. Click on 'Replace All'
4. Now click on 'Find previous' button

![image](https://cloud.githubusercontent.com/assets/10941328/18338116/0a254362-75b4-11e6-9029-6c16691329b5.png)

**Comment by shaneporter** [comment]
Thanks @Prateek032. I'll take a look.

**Comment by shaneporter** [comment]
A fix has been proposed with PR #2260.
