### ISSUE TITLE
Error when forking

### ISSUE THREAD

**Issue by ra-mac** [att/rcloud#2253]
On my RCloud instance (RCloud 1.6.1 (master/95f2533)), I am getting the errors below when I try to fork a notebook. (I restarted RCloud. I am using redis, which seems to be still running, and solr.)

I am not sure what is missing. Is there something else that I need to restart?

-Forking my own notebook gets this error, though it seems t do the fork.

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server
× 
Error: set_notebook_visibility: Error in curl::curl_fetch_memory(url, handle = handle) :
Couldn't connect to server

-Forking another user's notebook gets this error and does not do the fork.

Error in rcloud.get.notebook.forks(id) : 
  could not find function "get.gist.forks"
× 
Error: fork_notebook: Error in rcloud.get.notebook.forks(id) :
could not find function "get.gist.forks"
R trace:
rcloud.get.notebook.forks(id)
rcloud.update.fork.count(id)
fun(...)

**Comment by gordonwoodhull** [comment]
Hi @ra-mac. 

The second error definitely looks like your rcloud.support package is still on 1.5.*

When you asked if there were special upgrade instructions in #2242, I assumed that you had run the regular build instructions. This, plus a server restart, should fix this error. 

(It may be enough to run `scripts/fresh_start.sh`)

I think the curl error may also be a package version mismatch.

**Comment by ra-mac** [comment]
I have run scripts/fresh_start.sh


I tried restarting redis. but it didn't help. (lost my notebook index)


Now something has used up memory and RCloud won't re-start.

( system call failed: Cannot allocate memory)

________________________________

**Comment by ra-mac** [comment]
I just re-ran scripts/fresh_start.sh  but it failed due to no memory. I killed all the rcloud jobs.

Now when I run scripts/fresh_start.sh    I get:

***** RCloud is not properly installed, attempting to install ... *****

Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
Error in loadNamespace(name) :
  there is no package called 'rcloud.support'



________________________________

**Comment by gordonwoodhull** [comment]
Yuk!

Trouble shooting this stuff via Github issues is too low bandwidth. And unfortunately installing rcloud requires some serious R sysadmin chops.

I'm afraid I'm going to have to suggest using [the Docker image](https://hub.docker.com/r/rcl0ud/rcloud/). Your notebooks are still on github and can be loaded by id. (Find them via the Github Gist interface.)

Sorry!

**Comment by NattyE** [comment]
@gordonwoodhull I can also confirm that I receive the curl errors in my RCloud session. I have had these issues since I first installed RCloud but it doesn't seem to cause any issues. My current installed package versions are:

```
installed.packages()[, c("Package", "Version")][grep("rcloud", installed.packages()[, "Package"]), ]
                     Package                Version
rcloud.client        "rcloud.client"        "0.2"  
rcloud.enviewer      "rcloud.enviewer"      "0.1"  
rcloud.iip           "rcloud.iip"           "0.0.3"
rcloud.logo          "rcloud.logo"          "0.1.1"
rcloud.lux           "rcloud.lux"           "0.1"  
rcloud.notebook.info "rcloud.notebook.info" "0.1"  
rcloud.python        "rcloud.python"        "0.0.1"
rcloud.r             "rcloud.r"             "0.0.1"
rcloud.rcap          "rcloud.rcap"          "0.3.8"
rcloud.rmarkdown     "rcloud.rmarkdown"     "0.0.1"
rcloud.sh            "rcloud.sh"            "0.1-1"
rcloud.support       "rcloud.support"       "1.6-0"
rcloud.viewer        "rcloud.viewer"        "0.1"  
rcloud.web           "rcloud.web"           "1.0-1"

```

**Comment by gordonwoodhull** [comment]
As this stuff slowly pages back into memory, I think the curl error is just because you have search enabled in rcloud.conf but SOLR is not running.

You can either remove the `solr.url` line from your rcloud.conf, or [follow the directions in `services/README.md`](https://github.com/att/rcloud/blob/develop/services/README.md#solr) to install SOLR.

**Comment by ra-mac** [comment]
I re-loaded solr and now I can fork my own notebook without the curl error. However, I still get the error when trying to fork someone else's notebook:


Error in rcloud.get.notebook.forks(id) :
  could not find function "get.gist.forks"

Note that your solr start command has the rcloud location (/data/rcloud) hard coded so I had to modify it to adjust the dir. And the correct example dir  was services/solr/solr-4.5.1/example.

________________________________

**Comment by gordonwoodhull** [comment]
Thanks for the corrections.

Again, your rcloud.support is out of sync and it is almost impossible to debug installation through github issues, so I'm sorry, but I'm closing this. We can only afford to support the Docker image because R sysadmin is just way too tricky.

Contact me through other media if you want to pursue this.

**Comment by gordonwoodhull** [comment]
Correction: it's the github ("rgithub") package that's out of date. It should be 0.9.8.

I'm no expert on R packages but it seems to me that the githubgist package should have failed to build in the `scripts/build.sh` step, which is part of `fresh_start`. [It specifies this version.](https://github.com/att/rcloud/blob/develop/packages/githubgist/DESCRIPTION#L7)

**Comment by gordonwoodhull** [comment]
I've changed `services/rcloud-solr` to allow setting `ROOT`. I think the examples directory `services/solr/examples` is correct because `solrsetup.sh` creates a symlink for `solr`.

**Comment by NattyE** [comment]
FYI, I had the latest version of the rgithub package installed (0.9.8). I instead commented out the line

    solr.url: http://127.0.0.1:8983/solr/rcloudnotebooks

in the `rcloud.conf` file and these _seems_ to have stopped the issues I was having with the error message. It just means I can't search now.

**Comment by gordonwoodhull** [comment]
Thanks @NattyE. Yeah, the two errors are completely unrelated. The curl message has to do with solr, and the `get.gist.forks` error has to do with rgithub. I'm surprised that you were able to search even while receiving the curl errors.

**Comment by ra-mac** [comment]
Okay, I found the message about the wrong github version from the githubgist build. Unfortunately, the build does not automatically update it. I finally found github on rforge (rgithub) and did the update manually. Now it works.

________________________________

**Comment by gordonwoodhull** [comment]
Thanks @ra-mac & glad you got it working. 

My understanding is that the `bootstrapR.sh` step should have picked up this transitive dependency.
