### ISSUE TITLE
edit mode does not get activated when changing cell to a markdown

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2259]
Toggle edit mode gets activated, only if we are changing cell language to R, Python, Shell.
Doesn't gets activated, if we are changing cell language to Markdown and RMarkdown.

**Comment by gordonwoodhull** [comment]
Expected behavior is to activate edit mode whenever the language is changed, per #2206.

But that was implemented after this was filed, so I'm confused.

I'm not able to repro this - @amithrb, please confirm?

**Comment by amithrb** [comment]
@gordonwoodhull ,it's working now. I am not able to reproduce this issue.
