### ISSUE TITLE
PDF display is small

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2265]
PDFs in the asset pane are shown in a small box, with scrolling or very small depending on the browser.

![image](https://cloud.githubusercontent.com/assets/1366709/18437806/9d2d9d7e-78cc-11e6-8dc5-4af3495626ec.png)

![image](https://cloud.githubusercontent.com/assets/1366709/18438236/73d55456-78ce-11e6-9244-6f7984a22383.png)

**Comment by shaneporter** [comment]
PR #2268
