### ISSUE TITLE
arrow up/down/left/right should also work with command prompt

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2274]
e.g. arrow down from last cell to command prompt, etc.

**Comment by shaneporter** [comment]
think we talked about this before, but presuming here that when you are in the command prompt, the only way to get to the last cell will be with a left at the start of its content. Since up is used for command history.

**Comment by gordonwoodhull** [comment]
Ah right of course. Closing this as invalid.

That's a definite inconsistency. All the more reason to implement #1950 the extra cell for no command prompt, although I don't think we've completely figured that out.
