### ISSUE TITLE
Context Output fails to display plots

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2278]
Output displays only text related content and fails to display the plot content

![image](https://cloud.githubusercontent.com/assets/10941328/18606671/0e880102-7cd4-11e6-8fe3-0f48b7b0164b.png)

**Comment by gordonwoodhull** [comment]
Looks like it might be one of those weird closure problems

```
Uncaught ReferenceError: shell is not defined
 image_manager.js:120
```

**Comment by gordonwoodhull** [comment]
Nope: mini.html does not have a shell. Looks like I broke this in 4461f67029caa9c23daf47035c49b23520ac2004 in 1.6.1 - I suppose not too many people are using output context plots with controls showing.
