### ISSUE TITLE
pull changes from other notebook

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2285]
It's a common request to be able to pull the changes from another fork of a notebook
 - when collaborating and each person owns their own version of the notebook, it's common to pass control back and forth. right now that means lots of wasteful and confusing forking back and forth.
 - cheap support for "develop and release branches" - not really branches, but at least a public copy of the notebook, and another copy which gets worked on.

Version merging #127 would be even better but that's difficult especially in the UI. So let's do pull & replace, because it's simple.

@shaneporter, please take a look at how `notebook_controller.revert_notebook` works. Since it computes a diff from an arbitrary notebook in `find_changes_from`, we should be able to generalize this to take any notebook data. `notebook_controller.replace_notebook`?

Then we can add Advanced command(s) "Pull Changes from Notebook" - from file, URL, or notebook ID.

**Comment by shaneporter** [comment]
This is nitpicking, really it is, but shouldn't the command be "Pull and replace from notebook"?

"Pull changes from notebook" may infer a (user-driven) merge rather than a _brute force_ overwrite.

I think we should go for a single Advanced command which shows a dialog with an option to import from file, URL or ID.

**Comment by shaneporter** [comment]
As an aside, the default advanced menu has these command verbs, in order:

Open
Load
Import
Export
Import
Export

Would this be an opportunity to group the imports/exports? (And add the new 'Pull...' command after the imports?)

**Comment by gordonwoodhull** [comment]
"Pull and replace" is perfect. I've been searching for the right words for a long time.

I think we still want to keep the same sources/destinations together under the Advanced menu, specifically the File operations, but you could swap Import / Export File and put this new command before all of those.

**Comment by gordonwoodhull** [comment]
Pull is something people will do repeatedly (think dev version / release version) so if we can think of a quicker, more direct way to do this, it would reduce user frustration.. 

Verbs involving two items in the tree would be hard, but perhaps we can just remember the last source pulled for each notebook (using `rcloud.set_notebook_property`). That will go a long way.

**Comment by shaneporter** [comment]
Thanks. Yeah - I was thinking about remembering the last source. I think it's a reasonable assumption to believe that the source will stay the same, so the suggested source will help reduce thought and clicks, but there will still be an option to change if needed.

**Comment by shaneporter** [comment]
`find_changes_from` uses `current_gist_` because it's used as a revert operation where you want to go _back_ from latest to previous version.

I've added a parameter, `to_notebook`, which is used as the `cf` variable within the `find_changes_from` function. I get back a list of changes that are what I expect.

However, when I attempt to apply these, I get the following error in the session pane;

```
Error: update_notebook: Error in .gist.binary.process.outgoing(id, content) :
attempt to remove non-existing cell/asset: part1.R, part2.R
R trace:
```

The new notebook doesn't have these two cells, but I'm not sure why I'm seeing the error. I'm using this code (which at the moment works only with the ID of course):

```javascript
rcloud.get_notebook(id).then(function(notebook) {
  var changes = find_changes_from(current_gist_, notebook); // (this passes in the notebook I want to go to)
  apply_changes_and_load(changes, shell.gistname);
});
```

Haven't pushed this up yet, because I'm experimenting in this area of the code. Please can you let me know if I've gone completely off the rails here. Thanks.

**Comment by gordonwoodhull** [comment]
Hmm, definitely sounds like it might be some subject/object confusion there. 

As a child I always had trouble with expressions like "the tide is going out" - from its perspective or ours? From my comment there, it looks like I haven't changed much!

```js
    // calculate the changes needed to get back from the newest version in notebook
    // back to what we are presently displaying (current_gist_)
```

What?

It would be nice if we could clarify the code while we're doing this. `find_changes_from` is a horrible function name. `find_changes(from,to)` is better, so I think you're on the right track.

I'd simply put a breakpoint in there and see if the changes are what you expect. Doubt you are off the rails, but maybe something is still reversed.

**Comment by gordonwoodhull** [comment]
Hmm, missed you saying the changes are what you expect. Hard to say what could be going wrong - I checked the server side and it's not like get_notebook affects the state (load_notebook does replace the current notebook).

**Comment by gordonwoodhull** [comment]
If you get stuck on this, just work out the UI aspects and we can talk about it on the call.

**Comment by shaneporter** [comment]
Oh dear oh dear. `shell.gistname()` not `shell.gistname`!

I did have to take a look at `find_changes_from` more than once - it had a bit of 'back to the future' about it.  I will rename it.

So, I'm back on track. The UI is pretty much there.

I must remember to call functions. :wink:

**Comment by shaneporter** [comment]
@gordonwoodhull - for the URL (not including #2291), what would the expected format be?

Would it be: http(s)://{domain}/{user}/{notebookid}

Or something else? Thanks.
