### ISSUE TITLE
Not all of the find field accepts focus by clicking

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud#2286]
When text is entered in the find field, {current match} of {total matches} is shown within it.

![image](https://cloud.githubusercontent.com/assets/2493614/18985925/4c2e7676-86f2-11e6-9653-247aa0b82ce6.png)

When this is hidden, its extents do not accept focus, so the user cannot set focus on the input field (when the user clicks where the {current} of {total} would be shown.)

![image](https://cloud.githubusercontent.com/assets/2493614/18985871/fae9188e-86f1-11e6-88cf-23d551d707e5.png)

**Comment by gordonwoodhull** [comment]
Thanks @shaneporter - hadn't noticed this. I guess we can just let all mouse events fall through, since there's nothing to interact with there, shown or not.
