### ISSUE TITLE
rcloud.social website dashboard link error

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud#2294]
On the [rcloud social tryit page](http://rcloud.social/tryit/index.html), clicking on the 'Public Access' > 'Intelligent Dashboards' link results in this error:

```
Error fetching content:

 Error in doTryCatch(return(expr), name, parentenv, handler): Notebook `Dashboarding/RCloud notebook.R/Weather/main' by user `rclouddocs' not found
```

**Comment by gordonwoodhull** [comment]
The notebook was missing, but it's back.
