### ISSUE TITLE
Code execution with older version after update

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#2303]
Not very often updating the code in the frontend followed by execution leads to execution of the older code without the change though the frontend  reflects the change in code and the backend confirms the commit was made before execution took place. 
Prateek

**Comment by gordonwoodhull** [comment]
This is possible because of compute separation: one process is writing to GitHub and another process is reading independently. 

My theory is that this is a race condition in GitHub as described in #32 and #329. But I haven't seen this behavior so I can't confirm it. In those cases, the result of the write showed the correct result but a read immediately after did not reflect the changes.

Their advice was to wait at least a second after writing before reading. It would be unfortunate to add a delay or confirm the read but perhaps we have to.

**Comment by s-u** [comment]
Compute goes through control, so in principle we could use the state in control, i.e., compute asking control to perform on its behalf with the option to cache. The additional benefit would be that compute doesn't need any credentials - for better or worse. It would require a modification of Rserve to allow control to expose its own OCAPs to compute (right now it just passes them through to the client).

**Comment by gordonwoodhull** [comment]
Yeah, we've discussed doing that anyway, because it's more efficient. I don't believe we have any caching right now, after the first write.

We just don't know if that's the actual problem here. Must devise a way to test this.

**Comment by gordonwoodhull** [comment]
I am seeing something very similar to this on chusuk right now, simply because the solr configuration is broken. So the updated notebook never "takes". Wonder if it could be something as simple as this, with errors either ignored by the front-end or ignored by the user.

**Comment by gordonwoodhull** [comment]
I added a check for the above condition, in the above commit. 

Basically it nulls out the version while the commit is in transit - so if the promise chain is interrupted, or if it takes a long time and the user runs some cells simultaneously, they'll get a warning in the session pane:

```
Warning: executing unknown version, may be stale
```

It [looks like](https://github.com/att/rcloud/blob/73a7b6eaaff8442fcc3dedd44be9569071266bcc/rcloud.support/R/session.R#L21-L22) `null` means it will always use the cached copy of the notebook - may be better to use some signal value which forces loading of the most recent version.

**Comment by gordonwoodhull** [comment]
Results of testing this for ~6mos: we do not see the bug all that often but there are occasional complaints. We occasionally see the above error but the bug can occur without the error being printed.

**Comment by gordonwoodhull** [comment]
#2513 ties each execution to a particular promised version, so it should no longer be possible that a cell is run at the wrong version.

Consequently there is no longer any "stale notebook" warning.

This issue does not describe modifying/running more than one cell, but I am optimistically going to guess that was the cause and close this. 

Let's keep an eye out for any further concurrency issues.
