### ISSUE TITLE
Firefox: Unable to close find-dialog box

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2304]
Steps to reproduce:
- Create a new cell and add some contents to it
- Invoke `find` form and enter desired text in it
- Now delete the cell and click on `close` icon

![unable_to_close](https://cloud.githubusercontent.com/assets/10941328/19340053/93dbccba-9144-11e6-9503-3870672681a3.gif)

**Comment by shaneporter** [comment]
Thanks for reporting. It's Firefox only, will take a look.

**Comment by shaneporter** [comment]
in this scenario (where the only matches are in a cell or cells that are then deleted), the error
```
TypeError: shell.notebook.model.cells[match.index] is undefined
```
also happens when previous or next is clicked.

**Comment by shaneporter** [comment]
PR #2305.

**Comment by gordonwoodhull** [comment]
Took me a moment to repro this. Seems to only happen when the last cell is deleted and the notebook is empty.
