### ISSUE TITLE
Web Filter Redirect for Secure Sign in of Notebooks

### ISSUE THREAD

**Issue by LanceJensen-General** [att/rcloud#2306]
Many groups have a need for secure notebooks.  Currently we can secure a notebooks content by managing the access groups.  When a user creates a shiny app and supples a url that has been secured by group access and the user is not logged in to RCloud the user gets a empty page.

The preferred solution would be a web filter on the platform level that redirects the url call from the shiny web app to the Rcloud login if the user is not logged in.  Once logged in the system should then redirect back to the requested shiny url.

If that can not be done then the next best solution would be to create a page that showed that access to the page is prohibited due to lack of authentication and then provide the rcloud login url.

Blank pages mean broken to end users.

**Comment by gordonwoodhull** [comment]
Thanks @LanceJensen-General, I agree, there should be a popup that prompts the user to log in. We have this in some cases, but it's a matter of verifying this also works for shiny apps.

**Comment by LanceJensen-General** [comment]
Gordon,

Will the groups fix be in 1.7 for shiny apps?  This may affect our release process.

**Comment by gordonwoodhull** [comment]
Yes, we do display the "Aw shucks" for some errors and it's just a matter of verifying that it works in this case. I understand there will be an internal beta server for you to test prior to the release as well.

**Comment by gordonwoodhull** [comment]
I've verified that we do get an Aw Shucks with a login button that redirects correctly.

The message isn't very friendly (way too much detail) but it's effective.

Notebook not published:
![image](https://cloud.githubusercontent.com/assets/1366709/20019024/c27d411c-a2a0-11e6-92e9-a4f19ef47b50.png)

Notebook published but encrypted:
![image](https://cloud.githubusercontent.com/assets/1366709/20019065/ea02cdce-a2a0-11e6-9f7f-1d193b8b5f33.png)

RCloud 1.7 goes into beta on Tuesday the 8th. There will be an internal beta test server.
