### ISSUE TITLE
"export only selected cells" defaults falsy

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2313]
Similar problem as happened with `panel-layout-by-size` where fetching the option `export-only-selected-cells` when it hasn't been set, returns undefined.

I just reminded myself how these are supposed to work. The idea is to specify the `set` callback for the option, that will get called when all of these options are loaded at startup, as well as when the option has changed.

So for example `show-command-prompt` just calls the setter for a flag on the command prompt object:
```js
         set: function(val) {
             RCloud.UI.command_prompt.show_prompt(val);
         }
```
https://github.com/att/rcloud/blob/b74827014f2ceca05fce2fd0478a98c98f02e96b/htdocs/js/ui/settings_frame.js#L151-L153

This keeps the default in one place and avoids having to read the option an extra time.

**Comment by gordonwoodhull** [comment]
Loose end from #2311

**Comment by gordonwoodhull** [comment]
BTW, you can test the default state by calling `rcloud.config.set.user.option('export-only-selected-cells', NULL)` from your notebook, to delete the option.

**Comment by shaneporter** [comment]
PR #2315 resolves this, and it's nice because `rcloud.config.get_user_option(...)` is no longer required.

Did look at applying this for `panel-layout-by-size`, but found that the value was read before the set.

**Comment by gordonwoodhull** [comment]
It is a bit nicer, isn't it. I figured I must have dealt with this somehow. 

Kind of dumb that the options manager is actually part of the panel. I guess that's why we end up needing the `panel-layout-by-size` option before it's initialized.
