### ISSUE TITLE
All the available options are displayed in Pull and Replace from notebook's modal window

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2319]
when we open the `Pull and Replace from notebook` option for the first time, it displays all the available options

![image](https://cloud.githubusercontent.com/assets/10941328/19798598/aef032ee-9d0f-11e6-8214-1aaa279f82ea.png)

after closing and reopening the same it displays respective option

![image](https://cloud.githubusercontent.com/assets/10941328/19798658/042d51d8-9d10-11e6-9a37-ea2a92820a08.png)

And also the **`Pull`** option is enabled for the first time

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032, I can repro this and I'm fixing it now, because it's the first thing people will see when trying out the new feature.

**Comment by shaneporter** [comment]
Thanks @gordonwoodhull!
