### ISSUE TITLE
Unable to revert notebook after pull and replace notebook

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2322]
Unable to revert notebook, after performing pull and replace notebook by gist file

Steps to Reproduce:
- Create new notebook
- Make notebook private or add to the group
- Perform 'Export notebook to file'
- Create another notebook
- Perform pull and replace notebook by using encrypted gist file
- Click on history and try to revert. Following error is displayed

![capture](https://cloud.githubusercontent.com/assets/19602717/19804716/ad9f0e9c-9d2d-11e6-99b9-a08aeb745308.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @amithrb, looks like this is really a consequence of #1885 - we should not allow exporting a notebook as encrypted, as the notebook can only be decrypted on the same instance of RCloud.

**Comment by luxadm** [comment]
i'm new in it, how to `pull and replace notebook`?
