### ISSUE TITLE
Google Chrome: For invalid notebook format, error message is not displayed for pull and replace notebook

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2339]
For invalid notebook format, error message is not displayed for pull and replace notebook. This issue is observed in google chrome. Below is the screenshot.
![capture](https://cloud.githubusercontent.com/assets/19602717/19996405/4d48f6d6-a285-11e6-87d4-cac3b49d80a0.PNG)

**Comment by gordonwoodhull** [comment]
I'm seeing the message (usually "couldn't parse JSON"), once the file is processed, which may take a few seconds for a large file. So I think this is working. Please clarify?

**Comment by amithrb** [comment]
@gordonwoodhull ,On firefox browser after adding invalid notebook format the message "couldn't parse JSON" is displayed and doesn't allow user to pull. Pull button will be de-activated.

But in chrome browser it doesn't display any message after adding invalid notebook format or on pressing pull button. Pull button gets activated after adding invalid notebook format.

**Comment by shaneporter** [comment]
Hi @amithrb - please could you try this again? I changed the behaviour of the 'pull' button, so that it is never disabled. So this issue should now be fixed too.

**Comment by amithrb** [comment]
@shaneporter ,it's working now. I am not able to reproduce this issue.

**Comment by shaneporter** [comment]
Thanks @amithrb; @gordonwoodhull - please can you close this now? Thanks.
