### ISSUE TITLE
On pressing Enter key, error message is not visible for invalid URL

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2340]
On pressing Enter key, error message is not visible for invalid URL for pull and replace notebook. But on pressing pull button the error message is visible. Below is the screenshot.
![capture](https://cloud.githubusercontent.com/assets/19602717/19996803/2b7917b8-a288-11e6-92bc-fdfd3422282b.PNG)

**Comment by gordonwoodhull** [comment]
I'm seeing the error message flash very quickly on pressing enter.
