### ISSUE TITLE
Pull and Replace: pull from file with no file doesn't raise an error

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud#2341]
Steps to reproduce:

1. Advanced Menu -> Pull and Replace Notebook
2. Ensure 'Notebook source' is set to 'File'. 
3. Click 'Pull button'.

Expected:

Error message should be shown (since you can't pull from a file if you haven't chosen a file)

Actual:

'Pull' button changes to 'Pulling' and dialog disappears.

**Comment by gordonwoodhull** [comment]
Hmm, I'm seeing the Pull button disabled until a file is chosen, and I don't seem to be able to fool it. Seems like it works as expected.
