### ISSUE TITLE
Unable to import gist file using Pull and replace option 

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2343]
This issue is reproducible only after,when we try to import encrypted gist file

Steps to reproduce:
- Create a new notebook
- import encrypted gist using `Pull and replace notebook` option and it displays following error

![image](https://cloud.githubusercontent.com/assets/10941328/20092666/5b32ac58-a567-11e6-9699-f88677ed84ab.png)

- Now try to import some other gist file  
Then also it displays the same error

![image](https://cloud.githubusercontent.com/assets/10941328/20092725/93bd08b6-a567-11e6-81da-0c093f44035a.png)

Once the error is displayed, we weren't able to perform the `Pull and replace notebook` option until we refresh the tab

**Comment by gordonwoodhull** [comment]
The notebook becomes corrupted after the first attempt - the pull & replace actually succeeds, but then the cryptgroup doesn't agree with the contents, so the notebook is unreadable.

I'm not sure what we can do about this except ban exporting encrypted notebooks #1885 and/or ban pull & replace from an encrypted notebook file. Well okay, I'll do both.
