### ISSUE TITLE
Inconsistent error message is displayed while pulling current notebook

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2344]
While performing Pull and replace notebook option using current loaded notebook URL it shows the following error.

![capture](https://cloud.githubusercontent.com/assets/19602717/20098114/29e304ba-a5d8-11e6-9c0f-92338c48d11a.PNG)

But for the Notebook ID it doesn’t show any error message after clicking on pull button.

![screenshot from 2016-11-08 17 17 09](https://cloud.githubusercontent.com/assets/19602717/20097985/64c1f29a-a5d7-11e6-859d-f979ceee9a26.png)

**Comment by shaneporter** [comment]
PR #2345 adds an `if` statement.
