### ISSUE TITLE
R Cloud Shiny curl to github issue

### ISSUE THREAD

**Issue by LanceJensen-General** [att/rcloud#2347]
Intermittently we are getting a Github access failure.  The error message says, "Unhanded rejection Error: call_notebook: Error in curl::  ... Couldn't resolve hostname".  Later on in the stack trace it shows this occurred when calling a method fiction trying to access Github.

This intermittent error results in a blank page.  It would be preferable if something link this occurs to provide a platform level "Oops, page" or something that lets the user know they need to refresh their browser.

**Comment by gordonwoodhull** [comment]
This is probably a configuration problem on the instance of RCloud you are using, or intermittent network problems.

I agree with the request to improve error handling. It's difficult because there are a lot of moving pieces, but it can certainly be improved.

However, I don't think a browser refresh would help for this particular issue.

**Comment by LanceJensen-General** [comment]
I have found that sometimes a refresh changes the server that had the issue.  That in turn resolves the problem due to the change of server that is servicing the request...  I agree a refresh does not always solve this problem.

**Comment by gordonwoodhull** [comment]
Yeah, that's an intermittent solution at best - really you need to open a support ticket with IT if some servers do not have full network connectivity. I wouldn't add anything to the RCloud UI suggesting a refresh.

**Comment by prateek05** [comment]
curl:: ... Couldn't resolve hostname is definitely from the DNS. I would recommend you open a ticket with IT. 
Prateek

**Comment by LanceJensen-General** [comment]
I am happy to do so if that is your guys professional opinion of the root cause.  My concern is that I only experience this when R Cloud is running slow...  Then again, because the dns call is likely a blocking call it would make sense that if that service was dropping calls that R Cloud would slow.  I can not really diagnosis that it is a DNS issue.  Prateek, could you look at the log files to substantiate this assessment?  Otherwise I am afraid they may just point back to R Cloud.

**Comment by prateek05** [comment]
"slow" is little subjective. is it network or the server computation. I just went through the server usage graph there are very few peaks in cpu utilization. For the logs we will have the same message the system curl raised an exception with the message "Couldn't resolve hostname". 
If you can continue this coversation in the internal forums and provide me with an IT ticket I can help you with the supporting arguments required.

**Comment by gordonwoodhull** [comment]
I'm going to close this, because I don't think RCloud could cause DNS failures.
