### ISSUE TITLE
Unable to pull notebook using Notebook ID

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2349]
Steps to reproduce:
- Open Pull and replace option 
- In Notebook ID field, enter invalid notebook id and click on pull, `Invalid notebook ID.` error is displayed
- Now enter valid Notebook ID in notebook Id field and click on Pull. Pull button doesn't work

![pull](https://cloud.githubusercontent.com/assets/10941328/20162826/a260f9ce-a71d-11e6-8287-c57eea1056cc.gif)

**Comment by Prateek032** [comment]
For the URL also it is not working, with the above steps.

**Comment by gordonwoodhull** [comment]
Looks like there's a little bit of leftover code from when the dialog was early-validated, that refuses to try a pull if there's any current error. We just need to check everything every time we pull.
