### ISSUE TITLE
On pressing Enter key, previously searched character gets highlighted

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2360]
On pressing Enter key, previously searched character is getting highlighted using find/replace option.

Steps to Reproduce:
- Add contents to the cell
- Find character by invoking find/replace
- Press ESC key
- Invoke find/replace and enter second character 
- Press Enter key

The first searched character gets highlighted instead of second character
![capture](https://cloud.githubusercontent.com/assets/19602717/20377889/9c62c7a0-acb8-11e6-9792-6809889cd317.PNG)

**Comment by gordonwoodhull** [comment]
Like #1846, it looks like this was also broken by 9f5e769.

**Comment by gordonwoodhull** [comment]
The commit added an additional check to see if `change_interval_` was initialized, calling `setInterval` only if the variable was undefined. But `hide_dialog` calls `clearInterval` without resetting `change_interval_`.

So `setInterval` was never called on the second or subsequent times the find dialog was opened.

Resetting  `change_interval_` on `hide_dialog` fixes this.
