### ISSUE TITLE
Unable to import Rmarkdown file

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2364]
Steps to reproduce:
- Using **import notebook from file** option, import any notebook to RCloud
- after importing gist/Notebook, now open **import Rmarkdown file** option and select any valid `.Rmd` file, it shows below error

![image](https://cloud.githubusercontent.com/assets/10941328/20658132/b83860ec-b560-11e6-9a4c-7e7725571178.png)

**Comment by gordonwoodhull** [comment]
Confirmed. This is an rcloud.rmd bug - moving to that repo.

**Comment by gordonwoodhull** [comment]
This issue was moved to att/rcloud.rmd#17
