### ISSUE TITLE
for anonymous user, flexdashboard.html doesn't display any error message

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2365]
If the notebook is unpublished and anonymous user tries to open it using shreable links(`shiny`, `mini`, `view`) it throws the following  error message. 

![image](https://cloud.githubusercontent.com/assets/10941328/20663832/efa6e526-b57e-11e6-8811-c442b09f68cd.png)

But for the flexdashboard, it doesn't display any error.

**Comment by gordonwoodhull** [comment]
Another good one, thanks @Prateek032!

Moving to att/rcloud.flexdashboard.

**Comment by gordonwoodhull** [comment]
This issue was moved to att/rcloud.flexdashboard#13
