### ISSUE TITLE
Can't view published flexdashboard as anonymous user

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2366]
When anonymous user opens the published notebook in `flexdashboard.html`, it fails to display the contents.

Flexdashboard notebook contents are visible only when the user is **logged in**

**Comment by gordonwoodhull** [comment]
Good work as always, @Prateek032! Too bad we didn't get you properly set up before the release, as this is a pretty bad bug. But since this is an independent package, we should be able to fix it without patching RCloud core.

Moving to att/rcloud.flexdashboard.

**Comment by gordonwoodhull** [comment]
This issue was moved to att/rcloud.flexdashboard#12
