### ISSUE TITLE
proxy turns 302 into 200?

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2374]
Hi @s-u - I noticed that rcloud.rmd's Export to RCloud feature does not work because a redirect fails. att/rcloud.rmd#19

Looks like the 302 response gets changed into 200 so although the notebook has been created, the page hangs on `/api.R/create`

Could this be the fault of the proxy? It works locally but not on rcloud.social or the internal lakes.

You can test this by running the latest RStudio on a machine with rcloud.rmd installed - select Addins/Export to RCloud. Choose rcloud.social and Export on the page that opens. It gets stuck on a blank page - but examining the page shows that the response has a Location parameter with the correct URL for the new notebook.

**Comment by s-u** [comment]
I cannot reproduce what is reported here
``run <- function(...) return(list("", "", "Location: xxx", 302L))``
will correctly return `302` both by `forward` as well as by `nginx`.

```
$ curl -v https://rcloud.research.att.com/ex.R 2>&1| grep HTTP
> GET /ex.R HTTP/1.1
< HTTP/1.1 302 Code 302
tupile:$ curl -v http://127.0.0.1:8080/ex.R 2>&1| grep HTTP
> GET /ex.R HTTP/1.1
< HTTP/1.1 302 Code 302
```

I suspect the this is rather bug in `api.R` - the HTTP status code has to be an integer, so I suspect it should read
`return(list("", "", headers, 302L))`
I don't know if that fixes the issues or if there is something more, though.

**Comment by gaborcsardi** [comment]
@s-u Maybe so, but then why does it work locally?
@gordonwoodhull Can we change this on `rcloud.social` just to try it out? Or is there a test deployment that we can change?

I still don't understand how it can work on some hosts, and not on others, though.

**Comment by s-u** [comment]
Changing `rcloud.social` is mildly annoying, because it has several compute VMs, so you have to change it on all of them, but done - so please check. I'd use `rcloud-5` (aka `chusuk`) for testing inside if that's an option.

**Comment by s-u** [comment]
PS: we could add another VM on RedCloud that's used for testing - probably not a bad idea...

**Comment by gordonwoodhull** [comment]
Yep, that seems to have fixed it! I understand not at all.

**Comment by gordonwoodhull** [comment]
I'll try it on chusuk now.

**Comment by gordonwoodhull** [comment]
Great, it works, I'll close both issues with a commit.

**Comment by gordonwoodhull** [comment]
I'll release 1.7.1 once we see if any other fixes are needed to RCloud core.
