### ISSUE TITLE
Pull and replace: Text field retaining the previously entered values

### ISSUE THREAD

**Issue by prateek032** [att/rcloud#2377]
Steps to reproduce:
- Copy any URL
- Open `Pull and replace` option and paste the copied URL in the text field
- click on **cancel** button or press `<Esc>` key
- create a new notebook and open `Pull and replace` option 

previously pasted content doesn't disappear.

**Comment by gordonwoodhull** [comment]
It seems to clear when an old notebook is loaded from the tree, but not when a new notebook is created. Minor glitch, but might as well fix it.
