### ISSUE TITLE
incremental search for notebook titles

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2391]
The notebook tree is growing out of control and incremental search is a fast way to prune it, at least when you know the title. 

(If you don't know the title, we could do SOLR-based pruning of the tree, but that's slower and not appropriate for incremental search. Likewise the tree could also be filtered using notebook recommendations. I mention these features to motivate the design; they won't be part of this release.)

IMO the ideal way to add incremental search is without introducing another mode.

It should apply to both

1. the current notebook tree interface
2. the chronologically sorted notebook tree(s) of #2387

I'm open to discussion about the right interface. I am sure I am missing some subtleties here.

My first thought is for search not to affect which trees are open. Matching is against the path as well as notebook name; thus if you search for a folder name and it shows up, you can click the folder to open it, and all of its notebooks are shown because they meet the filter.

But it may be that we want to open trees in order to show matches. I'm not sure about this.

Search can be started with a shortcut (e.g. <kbd>ctrl s</kbd>) or by clicking a button in the notebook pane header. It inserts a small text-entry control above the tree. The filtering will stop when either the search string is empty, or the incremental search is closed with <kbd>esc</kbd> or clicking a close-x.

**Comment by s-u** [comment]
+1 cool idea

**Comment by shaneporter** [comment]
I think that the incremental search should not modify the structure of the tree (by hiding items), nor highlight or scroll to the current matching folder or notebook.

It should focus entirely on the matches, showing information about whether the match is based on the notebook name or the path.  

The user should be able to scroll through each match using the up/down cursor keys, and select a match with either enter or a mouse click. When a match is selected, the incremental search should be closed and the appropriate notebook or folder should be opened.

**Comment by gordonwoodhull** [comment]
@shaneporter, I guess you are proposing some sort of overlay that's separate from the tree? 

That's also valid, but what's wrong with hiding parts of the tree? Is this to make the implementation simpler?

It's been a while but I think the reason I thought it should happen in the same tree is partly so that it could combine with the chronologically sorted "tree". Also it is still a tree, at least in non-chronological mode, so it might not be that much simpler to display it separately.

**Comment by shaneporter** [comment]
Yes, that's exactly it. My inspiration came from my current editor of choice, Visual Studio Code, which like Sublime Text and no doubt lots of other editors has an incremental search much like this:

![image](https://user-images.githubusercontent.com/2493614/30280935-ec496e32-9708-11e7-94f5-53ef1706881a.png)

The matches are shown in the overlay, completely separate from the tree on the left. If there's enough info in that overlay to distinguish each match, it's easier to interact with than an ever-changing tree, which I think would be a bit distracting. 

To show the match in the tree, you may find yourself wondering the context of that match if the match is deeply nested and some of the parents are hidden. You could be interacting a lot with the tree during the search process, whereas you should be focusing on the matches.

The screenshot is a standard UI pattern for incremental search that matches our tree structure. I also think it will be easier to implement, but that isn't my primary concern in this instance.

**Comment by gordonwoodhull** [comment]
Okay, that makes sense to me. I agree that opening and closing folders while doing an incremental search would be confusing.

The one thing that is missing from the original proposal, is the concept of searching the currently open folders. 

The issue being that we have thousands of users, each with potentially hundreds of notebooks. So I am imagining, say, first typing the user name until the right user is highlighted. Then press enter to open that folder. Then start searching on the folder name (if needed, and then press enter), then on the notebook names.

Searching over the space of all notebooks would be a mess, especially because some notebooks have been forked by many, many users.

**Comment by shaneporter** [comment]
So - the user is searching for a folder or a notebook, but because of the likely duplication (across users) of folder and notebook names, the user is likely to be frustrated, and will likely need to use additional filters of username and 'parent folder'. 

For convenience, it makes sense to have a flag for 'my notebooks' and or 'other user's notebooks'.

You describe a 'then...' series of actions, but would it not be more fluid to allow the user to specify as much or as little information as possible and update the results? Confident that you have an 'unusual' notebook name, but can't remember where it is? Just use the name. More results than you thought? Output a message with the results suggesting that selecting a user and/or folder will help reduce the number of results.

The screenshot I added is listing the matched filename and path, but in our case, we'd show the notebook or folder name, alongside the user and the full path. Therefore, our UI will have additional fields, but as the user modifies a field, others will be filtered based on the current results.

**Comment by gordonwoodhull** [comment]
Multiple fields, or perhaps multiple search terms separated by space or slash. Sounds reasonable to me.

The reason I was thinking of using the tree in conjunction with search is that's the current way of exploring: browse for a user, then poke around for the right notebook. When we're looking for a specific notebook we almost always know the user, and we're likely to want to look at multiple notebooks by that user.

So I was thinking of ways to speed the current process up. But inventing a new process is also good. :)

**Comment by shaneporter** [comment]
Apologies if I've misunderstood here - you mentioned on the call that scrolling through a long list of usernames is annoying - so do we want a method to find and jump to a particular user, both from the tree itself, and from the incremental search as a basis from which to filter notebooks?

Are we also limiting this to 'My notebooks' and 'People I starred' notebooks? Because the 'all notebooks' are now lazily loaded, so that would require a server-side solution.

**Comment by gordonwoodhull** [comment]
Let's start with the easiest thing, which is your your proposal above, with incremental search on two fields: username and notebook folder/name. We can use any loaded tree data we have, which is to say, any user's trees we have opened in the current session. 

And we can also load any users we match in the username search - say if the pattern matches <= 3 users.

We can think about filtering after this and chronological sort.

**Comment by shaneporter** [comment]
Hi @gordonwoodhull - here's a screenshot of Visual Studio Code, searching for `pac`:

Note that matches include the following:

<pre>
<b>pac</b>kage.json
<b>p</b>opul<b>a</b>tion.<b>c</b>sv
</pre>

![image](https://user-images.githubusercontent.com/2493614/30647350-1b6a3fe6-9e13-11e7-9251-0c62a49e295e.png)

The `package.json` match is obvious, but would you be looking for the other type of match too? @dougmet is going to investigate the Lucene syntax.

**Comment by gordonwoodhull** [comment]
I wouldn't expect it to skip over characters when matching, no. (I think ace's code completion does something like this, too - not sure if @useless5771's patches stop this surprising behavior.)

However, it would be helpful to have a specific delimiter which allows skipping, maybe space, so that you could search for bits of the path and bits of the name without having to deal with multiple fields. The semantics would be, find all matches that have this substring and later this substring (and later this other substring).

**Comment by gordonwoodhull** [comment]
Implemented in 1.9 as a slick modal dialog which drops down from the top.

Good work, @shaneporter!
