### ISSUE TITLE
better error reporting for invalid characters

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2396]
We had a user report that unicode tilde `∼` will bomb the interpreter - yes, it looks exactly the same as ASCII tilde `~` in many fonts.

In the ace editor the false tilde shows up a little darker:
![shades of tilde](https://cloud.githubusercontent.com/assets/1366709/24324157/8422454a-1157-11e7-8776-f44ceecbed3e.png)

The error just says `URI malformed` but we can do better than that - I suspect we are not telling the interpreter that this is Unicode input, and it already has a better way of dealing with this.

E.g. on the command line it does

```
> 2∼3
Error: unexpected input in "2?"
```
which is better because it shows the position.

Could be an error encoding the json for github, which happens before execution.

**Comment by gordonwoodhull** [comment]
@s-u, is this a one liner? Can we just assign the correct character encoding at some spot, and let R handle the rest?

**Comment by s-u** [comment]
No idea - it doesn't even get to R, right? I have absolutely no idea what's the path on the JS side that this comes from...

**Comment by gordonwoodhull** [comment]
No, it's definitely on the R side - we don't actually send code to R to execute, remember, we just commit changes and then execute cells by notebook+cellid. 

Nonetheless I can do more troubleshooting and hone in on it. Thanks.

**Comment by s-u** [comment]
It's very odd - if you do

    x="2∼3" 

then it works just fine, so it's not an encoding issue. Also when you run it using `rcloud.r` it works as expected:

```
rcloud.r:::rcloud.language.support()$run.cell("2∼3", FALSE, rcloud.support:::.session) 

$error
[1] "<text>:1:1: unexpected input\n1: 2\xe2\n    ^"

attr(,"class")
[1] "parse-error"
```

so I really don't know where the "URI malformed" comes from .. the gist piece?

**Comment by gordonwoodhull** [comment]
Methinks all we need is a stack trace and this will be clear as day. 

The run queue is doing some ad-hoc error handling in order to deal with SIGINT. Let me see if it can handle this better.

**Comment by gordonwoodhull** [comment]
Nothing new in this world. Indeed, the error is on the JS side but it's due to R encoding the strings wrong. We've discussed this ad nauseam but haven't done anything about it.

https://github.com/att/rcloud/issues/1653
https://github.com/att/rserve-js/issues/2

**Comment by gordonwoodhull** [comment]
In this case, I guess the error reporting does not have the encoding declared properly.

It's trying to report

```
<text>:1:1: unexpected input↵1: 2â↵    ^
```

**Comment by s-u** [comment]
Aaaah - now I got it - it's the error that gets passed through that bombs. So it's actually trivial to replicate in a cell:

```
parse(text="2∼3")
```


 Ok, two pieces here

1) can we fix rserve-js to not report "URI malformed" but instead either report "string XX is not valid UTF-8 string"? That way you don't have to remind me every time we hit this where it comes from ;)

2) I have to look and see why `parse()` outputs the resulting string in an invalid encoding - it looks like a parser bug to me - I think it just outputs one byte instead of one character. I think I can detect that using `base64enc::checkUTF8` so I could special-case the cell evaluation piece.

**Comment by gordonwoodhull** [comment]
Good idea - definitely agree we should report errors instead of exploding when we see them. I'll take the rserve-js part.

**Comment by gordonwoodhull** [comment]
Okay, adding a simple try-catch to rserve-js I get meaningful error messages. Still reported to the session pane, as it should be:

![image](https://user-images.githubusercontent.com/1366709/31567948-e9f4486e-b03f-11e7-8b7e-ab2abf33059e.png)

**Comment by s-u** [comment]
It's a bug in R, so we can close it here. I have filed it [here](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17356)

**Comment by gordonwoodhull** [comment]
Thanks @s-u!
