### ISSUE TITLE
view mode for recent notebooks

### ISSUE THREAD

**Issue by s-u** [att/rcloud#2424]
It would be nice to be able to open a notebook form the recent notebooks list in view mode

**Comment by gordonwoodhull** [comment]
Since <kbd>ctrl</kbd> or <kbd>cmd</kbd>-clicking generally means open in a new tab (and <kbd>shift</kbd> in a new window, not sure if we implement it anywhere), we could <kbd>alt</kbd>-click an item in the recent notebooks to open in a new tab in view mode.

**Comment by s-u** [comment]
Nice, but does this respect mini/view/shiny/notebook settings? Just from the diff it looks like it may be hardcoded to `view.html` which is not what we want - but I may be wrong.

**Comment by gordonwoodhull** [comment]
Yep, that slipped by me. I'll open another issue since I accidentally merged the PR.

**Comment by useless5771** [comment]
Yes, it is hardcoded to view.html. How can the backend tell which view to open? Are users able to bind notebooks to specific views? Where that information is stored?

**Comment by gordonwoodhull** [comment]
Yes - it is stored with the notebook metadata.

Have a look at 

https://github.com/att/rcloud/blob/develop/htdocs/js/ui/share_button.js

And if anything needs to be exposed better, please improve where needed.

**Comment by useless5771** [comment]
ok, thanks
