### ISSUE TITLE
tree filtering based on time

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2448]
@s-u mentioned the idea of seeing only the past week's notebooks, past month's, etc.

I think we should do #2387 chronological sort of the tree first, but after that let's look at applying time-based filtering of the tree.

**Comment by shaneporter** [comment]
I assume that the filtering options should be derived from the `last_commit`s of available tree items, and update when new items are loaded (or saved).

(and also show the number of items that will be shown?)

e.g:

Previous 7 days (107 of 208)

**Comment by shaneporter** [comment]
I'm assuming that the current notebook should always be shown in the tree, regardless of whether it matches the date filter.

However, what happens if a user opens a notebook that doesn't match the filter, and then opens another. Should that previous notebook then be hidden?

I'm just wondering whether hiding the nodes is the best approach, and that some other approach isn't preferable.

**Comment by gordonwoodhull** [comment]
I am assuming we should keep the current behavior of just continuing to open folders, and leave closing of folders to the user. Suppose the user is looking for all notebooks on a certain topic, for example, and then they intend to do some comparison.

**Comment by shaneporter** [comment]
Following a discussion with you @gordonwoodhull, I'll look to implement a 'if it's in, it's shown'. (Future filter changes will update the tree, but the current notebook is *always* shown).

**Comment by gordonwoodhull** [comment]
(deleted my confused comment above)

Yes - certainly the current notebook should always be shown. 

We're undecided whether this means that things should be shown that don't match the filter, or the filter should be switched off if the user opens a notebook which doesn't match. Go with whichever is easiest and we'll iterate.

**Comment by gordonwoodhull** [comment]
This is complete - we're just working out the bugs now.
