### ISSUE TITLE
after successfully setup getting below error

### ISSUE THREAD

**Issue by dipenpatel235** [att/rcloud#2451]
Error in fun(...) : 
  Please do a hard reload with ctrl-F5 (Windows/Linux) or cmd-shift-R (macOS)
Server version 1.9-devel does not match client version 1.8
R trace:
stop(paste("Please do a hard reload with ctrl-F5 (Windows/Linux) or cmd-shift-R (macOS)\nServer version", 
    .info$rcloud.info$version.string, "does not match client version", 
    client.version))
fun(...)

**Comment by gordonwoodhull** [comment]
This means that the javascript bundles have not been built.

The build scripts don't fail if npm tools aren't present to build javascript. I'd recommend using a tagged version of rcloud or the master branch, but if you really want to use the bleeding edge develop branch, please follow the instructions here:

https://github.com/att/rcloud/blob/develop/doc/INSTALL.md#will-you-be-hacking-on-the-code-read-on

And please comment here if anything is missing.
