### ISSUE TITLE
RCloud should fail to start if solr.url is unavailable

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2467]
Right now you'll get a lot of errors during runtime if solr.url is unavailable/invalid. RCloud should ping the server and disable the option on startup instead.

Assigning to @s-u since @dougmet is on leave.

**Comment by s-u** [comment]
This is not quite what we talked about - SOLR failures may be transient so I don't want to fail on SOLR unavailability. However, we should fail if search is configured but rcloud.solr is not available as that is not a transient problem.

**Comment by s-u** [comment]
Closing as "won't fix" (in case anyone wants to discuss the original issue as-is) and will open a separate new issue on `rcloud.solr` availability.

**Comment by gordonwoodhull** [comment]
Ah, I misunderstood. Makes sense, thanks!
