### ISSUE TITLE
importing external notebooks should open folders

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2508]
If the folder(s) where the notebooks are imported are not open, they should be opened before highlighting them. (Otherwise there is no feedback.)

I checked 1.8 and this is not a regression, just something apparently never implemented.

**Comment by shaneporter** [comment]
![image](https://user-images.githubusercontent.com/2493614/33596833-1ff8eafe-d995-11e7-99ef-48c643f84a93.png)

I assume you're not referring to this method of importing, because I cannot reproduce on 1.9.

**Comment by gordonwoodhull** [comment]
Works for me!
