### ISSUE TITLE
incremental search by username does not seem to have any effect

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2517]
As soon as I start typing in the username field, I get a lot of notebooks, but they don't seem to match the username pattern.

If the notebook name pattern is filled in, then typing in the username field has no effect on filtering.

**Comment by shaneporter** [comment]
I assume the username should match in the same way as the notebook description,
 and be subject to the same conditions as (https://github.com/att/rcloud/issues/2518#issuecomment-353416445)

**Comment by gordonwoodhull** [comment]
Yeah, although I doubt anyone would use multiple terms for username, since usernames are short. It should have the effect of `AND user:foo*~` (if I understand rcloud.solr's search.R correctly).

Looks like maybe it's just ` user:` missing [here in rcloud.solr](https://github.com/att/rcloud.solr/blob/60c7fd762e2fd8a669fe9423d265edc276c3d345/R/search.R#L71), but I only took a very quick look and may be missing something.

**Comment by gordonwoodhull** [comment]
Thanks @bashlee! This is fixed for 1.9.1.
