### ISSUE TITLE
"all components of body must be named" when hiding notebook or making it private

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2533]
When search is enabled, hiding a notebook results in the above error being displayed in the session pane.

It is supposed to remove the content from the SOLR but it does not (because the solr update is apparently failing). (Showing a notebook should restore the content to SOLR.)

Not surprisingly, the same thing happens when taking a notebook from public to private using the notebook permissions dialog.

**Comment by gordonwoodhull** [comment]
@bashlee, I'll assign this to you since it's good to have someone else who understands rcloud.solr.

There are still some rough edges to the integration of rcloud.solr into RCloud. I think @dougmet tested the package thoroughly using mocking, however RCloud is difficult to mock and we didn't do enough end-to-end testing.

**Comment by bashlee** [comment]
thanks @gordonwoodhull. Fix for this one will be in rcloud.solr again

**Comment by gordonwoodhull** [comment]
Hurray! No annoying messages. Hidden notebooks and encrypted notebooks are not searchable.

Thanks @bashlee!
