### ISSUE TITLE
simplify rcloud.upload.asset / rcloud.delete.asset

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2555]
As @s-u pointed out in his review of #2544, trying to handle deletion of assets in `rcloud.upload.asset` just makes the implementation confusing.

Instead, please implement `rcloud.delete.asset` directly in terms of `rcloud.update.asset` - since deleting an asset doesn't need a file or content, it should just be a few lines (or five if you include the `is.list(notebook)` stuff).

**Comment by bashlee** [comment]
thanks @gordonwoodhull & @s-u - makes much more sense this way around

**Comment by gordonwoodhull** [comment]
fixed by #2556
