### ISSUE TITLE
multiple languages in a single extension package

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2565]
Currently each language extension (`rcloud.r`, `rcloud.python`, ...) implements exactly one language.

Rather than having to create a dummy package for each language supported by Jupyter, why don't we allow each package to return multiple languages when `rcloud.language.support()` is called?

<strike>I think the idiomatic R way of doing this is to return vectors for each field (`language`, `run.cell`, `ace.mode`, etc.) instead of a single value. [setup.R](https://github.com/att/rcloud/blob/e46ab0a4db66779f60390b43ce153a5db08c31b7/rcloud.support/R/setup.R#L355) will have to do more complicated validation/unpacking of the data, but it can be backward compatible. ("Scalar" fields will have the same type, since scalars are length-1 vectors in R; function fields will require a type test, since a vector of function references is different from a function reference.)</strike>

What's really nice about this is that `rcloud.jupyter` can detect at startup time which languages are available, and return that set dynamically.

**Comment by gordonwoodhull** [comment]
Per @s-u, the entry point should return either one (S3) object or a list of them. The class tag is mostly to identify if you got a single object or a list back.

**Comment by dkey-pugh** [comment]
@gordonwoodhull what's the scope on testing this? Execution, std in read, code completion and syntax highlighting for python2, python3 and julia? Java/Javascript? R/Scala/Python Spark - can we test this with a 'dummy' kernal or will we need an Apache Spark instance? There's a lot of functionality being added in one issue and I'd like to be sure we're on the same wavelength over testing it.

**Comment by gordonwoodhull** [comment]
Thanks @dkey-pugh. Yes, that is about the scope of it - those four features across 7-8 languages.

This is *the* major feature in RCloud 2.0 so yes, the fact that it's one issue is deceptive.

A dummy kernel for Spark will be fine, as long as you can test the language features. It's not an exercise in cluster management, although you'll probably get some more practice in system administration!
