### ISSUE TITLE
Integrating IDE (RStudio) to RCloud Notebooks for Development 

### ISSUE THREAD

**Issue by danielra0091** [att/rcloud#2580]
Would there be a way to build in Rstudio functionality to RCloud to be able to develop and version control from Rstudio much like a Git system. 

![rstudio](https://user-images.githubusercontent.com/28115584/41609064-90dc1bce-73af-11e8-9f81-c73458aa29f4.png)

**Comment by gordonwoodhull** [comment]
I think you're really talking about implementing RCloud-like features in RStudio - maybe you could bring it up with them? 

I don't really see how we could bring in the whole RStudio IDE as a feature in RCloud.

We did implement a feature to export RMarkdown notebooks from RStudio to RCloud, but that's about as much power as we have to implement features in RStudio.
