### ISSUE TITLE
notebook run: don't reset a clean session 

### ISSUE THREAD

**Issue by s-u** [att/rcloud#2589]
The "Run" button at the top will always create a new session. However, when the first notebook is loaded and the session is clean (first load of the RCloud page), there is no need to reset it. It would be nice if we could detect that case and not discard the clean session. This is fairly common occurrence so may warrant the extra handling.

**Comment by gordonwoodhull** [comment]
Also when a notebook is loaded, presumably.

This is probably easier to implement on the client side, although there are arguments either way.
