### ISSUE TITLE
merge into current notebook button

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2597]
As suggested by @s-u: even easier than getting the notebook id with #2594, why not add a button to each notebook in the tree that starts the merge process with that notebook?

We have been using the "branch" icon to mean "fork" because it looks similar, and Font Awesome doesn't have the real "fork" icon e.g. seen above in the GitHub interface. It doesn't look like a true merge icon is available in the free version of Font Awesome, but we might be able to flip the branch icon vertically.

**Comment by JABedford** [comment]
Happy to take this one on as well Gordon. 

Just for clarity, is #2594 still going to be implemented as well because I could work on both.

**Comment by gordonwoodhull** [comment]
Implemented in #2622
