### ISSUE TITLE
enter doesn't work everywhere in merge and apply dialogs

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2601]
The default action, either proceeding to the next dialog or applying the changes, should be invoked when pressing <kbd>enter</kbd> anywhere in the dialog (except the dropdowns).

However, when the Notebook ID input has the focus, or the Monaco editor has the focus, <kbd>enter</kbd> has no effect.

**Comment by JABedford** [comment]
I would be more than happy to have a look at this issue Gordon. It will give me a good chance to get familiar with the merge dialogue.

**Comment by JABedford** [comment]
I will be more than happy to look at this Gordon. It gives me a good chance to get familiar with the merge dialogue code.

**Comment by gordonwoodhull** [comment]
Thanks @JABedford, this is a great place to start. Filing a PR on this will be a good practice run.

I've invited you to the repo so I can assign issues to you, but until I do that, please feel free to take any open 2.1 issues.
