### ISSUE TITLE
Incorrect behaviour of "Remove Folder" dialogue.

### ISSUE THREAD

**Issue by JABedford** [att/rcloud#2612]
When a user tries to remove a folder, and then cancels the dialogue, it is remembered if they then try at any point to remove the same folder.

![screenshot 2018-11-01 at 14 12 20](https://user-images.githubusercontent.com/32302360/47856901-37009d00-dde0-11e8-8ab5-9970f80e0c08.png)

**Comment by gordonwoodhull** [comment]
Thanks @JABedford!

I see - looks like it keeps on appending notebooks to the same list every time you cancel and then try again. Weirdly, if you alternate between two folders, clicking remove and then cancel for each one, each one separately appends to its own list, so it's somehow associated with the folder and not the dialog.
