### ISSUE TITLE
Lint the JS

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2624]
@JABedford mentioned in #2623 that ESLint is the latest and greatest JS linter.

I want to detect accidental globals and other really dangerous stuff.

But I want to be extremely conservative about this in the first pass - no stylistic conventions, no brace rules.

We can start out with a minimal configuration and then add other features as we run into problems.

**Comment by JABedford** [comment]
I'll get to work on setting up a suitable config.

**Comment by gordonwoodhull** [comment]
Implemented in #2625
