### ISSUE TITLE
keep/ignore buttons shouldn't fade into Apply Changes dialog

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2626]
Ideally all of the UI in the Apply Changes dialog should be shown immediately when the dialog opens.

It looks like right now the UI displays, then space gets added in order to display the "Keep deleted content" / "Ignore added content" buttons, and then finally the buttons fade in.

These animations don't really add anything and I find them confusing. I understand that maybe the space needs to get added after the fact, but the buttons shouldn't fade in.

It's not like we are transitioning from a state where it makes sense not to have the buttons there.

**Comment by JABedford** [comment]
I agree the UX of these is misleading. 

Seemingly we are not alone in thinking this @gordonwoodhull :
https://github.com/Microsoft/vscode/issues/19917

Currently they are not able to be configured. I'll keep an eye on this though, surely with so many people crying out for this feature it will be implemented?
