### ISSUE TITLE
Merge Notebook from File tree triggers ReferenceError?

### ISSUE THREAD

**Issue by dkey-pugh** [att/rcloud#2634]
When usig the Merge Here feature from the file tree instead of the Advanced menu, when the diff is displayed, the cell contents hang and the console shows "Uncaught ReferenceError: monaco is not defined at init".
This blocks merger via this workflow.

**Comment by gordonwoodhull** [comment]
It's also possible to hit this by opening Advanced / Merge Notebook and pressing <kbd>enter</kbd> really quickly... basically monico is being loaded asynchronously by the Merge Changes dialog, instead of synchronously by the Apply Changes as one would expect.
