### ISSUE TITLE
Chrome warning regarding R comment symbol

### ISSUE THREAD

**Issue by dkey-pugh** [att/rcloud#2636]
Opening a commented R file in a notebook in Chrome produced the following message in the console:

[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

Is this anything to be worried about post release under Chrome?

**Comment by gordonwoodhull** [comment]
Thanks @dkey-pugh. I get this even when I open a notebook without any comments.

It looks like we are at risk of losing the up-down icon in our cell language `<select>`, because `#` is not a valid character in a data URL.
