### ISSUE TITLE
build should fail immediately when rcloud.support fails to build

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2651]
This is the package which is most likely to fail due to missing prerequisites.

There is no point in continuing if `rcloud.support` fails to build, and if the build continues it just buries an important message. 

Noobs unfamiliar with build systems don't know to search for the first error rather than trying to read the log backward, so they just see that something else failed due to no `rcloud.support`.

**Comment by s-u** [comment]
`build.sh` should check error codes of things it does
