### ISSUE TITLE
autoscroll in session pane can "lock" the scroll

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2690]
If there is a lot of output, the pane seems to think it needs to keep scrolling, and will fight the user trying to scroll back to see earlier messages.

**Comment by s-u** [comment]
I saw odd behavior in `dc.cube` example where it got "stuck" in the front part of the output

**Comment by gordonwoodhull** [comment]
Issue was that the scroll was animated. Lots of animations scheduled at once can pile up.

We still have lots of problems with too much input coming in too fast, see #1997
