### ISSUE TITLE
What would be the right version of OS and R for Rcloud Installation

### ISSUE THREAD

**Issue by sunny143code** [att/rcloud#2692]
Thanks in advance.

**Comment by gordonwoodhull** [comment]
Hi @sunny143code, sorry I missed this issue earlier.

To be sure it’s not easy to install RCloud. It is easiest on a Linux box following [INSTALL.md](https://github.com/att/rcloud/blob/develop/doc/INSTALL.md) - we’ve got scripts that follow this process automatically.

It’s also possible on macOS but you have to futz with OpenSSL and other dependencies.

Windows is not supported for the server. Of course the client can run on any OS you want as it’s just a web app.

**Comment by gordonwoodhull** [comment]
As for R versions, anything except for 3.4 should work.

Unfortunately the “could not connect to server” error you originally quoted can have a lot of different causes. If you are still at that step, I can show you how to turn on logging which helps sometimes.

**Comment by sunny143code** [comment]
Thanks for the reply.
I am still seeing the "could not connect to server" issue, here I am pasting my config file info.
Please let me know what I am missing.

**etc/hosts:**

13.82.230.185

#The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

**/data/rcloud/conf/rcloud.conf:**

##------RCloud Configuration: copy into rcloud.conf and edit! ------
##: GitHub info below must be modified in order for RCloud to work!
## Only set Host: if it doesn't match the canonical name of your machine
Host: 13.82.230.185
#--: gist back-end, pick either githubgist (default) or gitgist
github.client.id: 822164ea0d99b7983b0a
github.client.secret: db467114d780ddc41f6f0bfc149dacbe95a6e89b
github.base.url: https://github.com/
github.api.url: https://api.github.com/
github.gist.url: https://gist.github.com/
#gist.backend: gitgist
#gist.git.root: ${ROOT}/data/gists
rcs.engine: redis
#solr.url: http://127.0.0.1:8983/solr/rcloudnotebooks
rcloud.alluser.addons: rcloud.viewer, rcloud.enviewer, rcloud.notebook.info, rcloud.htmlwidgets, rcloud.rmd, rcloud.flexdashboard, rcloud.jupyter.notebooks, rcloud.shiny
rcloud.languages: rcloud.r, rcloud.jupyter, rcloud.rmarkdown, rcloud.sh
compute.separation.modes: IDE
#--: if using rcloud-gist-service
#rational.githubgist: true

I get below messages when I run the fresh_start.sh:

WARNING: running as root, skipping build step!

 - shutdown RCloud server 36076

Caught break signal, shutting down Rserve.
 - starting RCloud...
[1] TRUE
Starting Rserve:
 /opt/R/3.5.2/lib/R/bin/R CMD /opt/R/3.5.2/lib/R/library/Rserve/libs//Rserve '--RS-conf' '/data/rcloud/conf/rserve.conf' '--vanilla' '--no-save'


R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Loading required package: rcloud.support
Loading required package: base64enc
Loading required package: rjson
Loading required package: parallel
Starting Rserve on att-rcloud.fjs5egcx0noebjkupavagt2jkf.bx.internal.cloudapp.net
Loading RCloud configuration file...
Loading required package: rediscc
Rserv started in daemon mode.

And I also seeing this in the browser console:

![image](https://user-images.githubusercontent.com/58238845/70285103-2f49bf80-177b-11ea-8c37-4279d759c73d.png)

**Comment by gordonwoodhull** [comment]
Thanks for the screenshot. Please use the master branch, or do `npm install` at the root level in order to install the required JS dependencies.

Of course if you just want to try out RCloud, it is going to be a lot easier to go to http://rcloud.social and use the public instance, or use the Docker image.

**Comment by sunny143code** [comment]
I have tried it with master branch this time and ended up with below error:

Aw, shucks
Error: compute_init: Error in mapply(function(from, to) paste(lines[from:to], collapse = "\n"),  : 
  zero-length inputs cannot be mixed with those of non-zero length
collapse
R trace:
suppressWarnings(d(.session))
withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
suppressMessages(suppressWarnings(d(.session)))
start.rcloud.common(...)
start.rcloud.gist(username = username, token = token, ...)
start.rcloud(...)
fun(...)
    at success (http://3.80.187.200:8080/js/rcloud_bundle.js:32:23)
From previous event:
    at Object.compute_initAsync (http://3.80.187.200:8080/js/rcloud_bundle.js:38:54)
    at Object.rcloud.compute_init (http://3.80.187.200:8080/js/rcloud_bundle.js:459:33)
    at on_connect_anonymous_disallowed (http://3.80.187.200:8080/js/rcloud_bundle.js:5200:24)
    at http://3.80.187.200:8080/js/rcloud_bundle.js:5243:13
From previous event:
    at rclient_promise (http://3.80.187.200:8080/js/rcloud_bundle.js:5240:8)
    at Object.init (http://3.80.187.200:8080/js/rcloud_bundle.js:5295:16)
    at main (http://3.80.187.200:8080/edit.js:16:20)
    at http://3.80.187.200:8080/lib/js/require-common.js:80:17
    at Object.execCb (http://3.80.187.200:8080/lib/js/require.js:1650:33)
    at Module.check (http://3.80.187.200:8080/lib/js/require.js:861:55)
    at Module.<anonymous> (http://3.80.187.200:8080/lib/js/require.js:1113:34)
    at http://3.80.187.200:8080/lib/js/require.js:132:23
    at http://3.80.187.200:8080/lib/js/require.js:1156:21
    at each (http://3.80.187.200:8080/lib/js/require.js:57:31)
    at Module.emit (http://3.80.187.200:8080/lib/js/require.js:1155:17)
    at Module.check (http://3.80.187.200:8080/lib/js/require.js:917:30)
    at Module.enable (http://3.80.187.200:8080/lib/js/require.js:1143:22)
    at Module.init (http://3.80.187.200:8080/lib/js/require.js:774:26)
    at callGetModule (http://3.80.187.200:8080/lib/js/require.js:1170:63)
    at Object.completeLoad (http://3.80.187.200:8080/lib/js/require.js:1564:25)
    at HTMLScriptElement.onScriptLoad (http://3.80.187.200:8080/lib/js/require.js:1671:29)

**Comment by gordonwoodhull** [comment]
Getting closer! Looks like `rcloud.jupyter` failed to load - probably failed to load. 

We have an open issue #2689 to improve the error message when this happens.

Please remove this item from the list of languages in `rcloud.conf`. If you gets RCloud to start, you can always fix the build and restore this later.

**Comment by sunny143code** [comment]
Now, Rcloud is running without any issues but the buttons for running R scripts have disappeared, but most of the other functionality appears to be there.
Thank you Sir for the support.

**Comment by gordonwoodhull** [comment]
Thanks for following up, @sunny143code!

I’m not sure what you mean. Do you mean the buttons in the navbar? Could you post a screenshot?

The buttons are probably still clickable if you know where they are. :)

**Comment by gordonwoodhull** [comment]
Glad I could help you get started with RCloud! Please reach out if you have other questions.

I will guess that the buttons issue is #2386. I think there may be issues where other fontawesome buttons disappear. Maybe upgrading fontawesome #2673 and/or using SVG buttons would help.

**Comment by sunny143code** [comment]
Thanks for the info.

I was trying to create a Docker image which uses Github gist storage with master branch rcloud code but facing issues with redis connection so just wanted to check if you have any Dockerfile.

**Comment by gordonwoodhull** [comment]
You could try this one

https://github.com/s-u/docker-rcloud-aas

**Comment by sunny143code** [comment]
I have tried that but it runs using rcloud user but I want to have Github login user.

**Comment by gordonwoodhull** [comment]
I see - yes, that image is intended for running services and does not have Github login.

It would be nice to provide Docker images for other purposes but I am not sure when we will get to it.

Redis is not usually hard to set up - anything we can help you with?

**Comment by sunny143code** [comment]
Thanks for asking and all your help.
I did set up and was able to create a docker image for our needs.

**Comment by gordonwoodhull** [comment]
Awesome! Thanks for following up. 

Feel free to ask any questions here, or on SO with the [rcloud] tag.

**Comment by sunny143code** [comment]
hey, Cloud you please guide me or send me the link for how to integrate Rcloud app with Active Directory authentication?

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @sunny143code)

**Comment by gordonwoodhull** [comment]
Thanks @joeleonjr!

Yes, I see that @sunny143code posted the secret in a comment, and I obfuscated it, but it is still visible in the history.

@sunny143code, it’s been a few years. I agree you should probably assume bad guys have your secret by now, check for any damage, and revoke the API key.
