### ISSUE TITLE
clarify/change "merge from" icon wording

### ISSUE THREAD

**Issue by s-u** [att/rcloud#2704]
The words "merge from" in the tooltip for the "merge into current notebook" feature are misleading. I wanted to merge changes from the current notebook into its parent so assumed clicking "merge from" on the current notebook is how to tell you want to do that (assuming that it will default the target notebook to be the parent - see #2703). However, "merge from" really means "merge into current" so the proper way is to switch the notebook and use "merge into current" - which is not obvious. Hence I'd suggest changing the tooltip to say "merge into current notebook" so it's obvious what it does - it was the original name of the feature after all ;).

**Comment by gordonwoodhull** [comment]
Wow. We sure have struggled with this one. 

I guess you are right: there is no way to abbreviate the tooltip and we just need to spell it out.

**Comment by s-u** [comment]
The feature is very powerful, but non-trivial (merging never is trivial) - so we may need to spell it out.

(BTW: I'm starting to love this mindset of using notebooks as branches... don't get me too excited or I'll start thinking about branch networks ;))

**Comment by gordonwoodhull** [comment]
@jsseidel and I settled on [verbose language](https://rcloud.social/documentation/doc/2.1/guidoc/doc.html#merging-notebooks) when working on the docs. It was too confusing otherwise.

It would be really neat to have tools to deal with the tree of forks. These ideas go way back to #170. Technically with merging, it becomes a DAG, but we don't record merges in any special way, so we don't have the data.

**Comment by gordonwoodhull** [comment]
Here's a mockup of icon pointing from the notebook tree into current notebook for "merge into current notebook"

<img width="480" alt="image" src="https://user-images.githubusercontent.com/1366709/73495785-3bba5500-4385-11ea-99ff-b04f9722032a.png">

I couldn't figure out how to both rotate and flip the icon (this is `icon-code-fork icon-rotate-270`)
