### ISSUE TITLE
active directory

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#2705]
Could you please guide me or send me the link for how to integrate RCloud with Active Directory authentication?

_Originally posted by @sunny143code in https://github.com/att/rcloud/issues/2692#issuecomment-577373068_

**Comment by gordonwoodhull** [comment]
currently we don't have any examples but it is certainly possible!

**Comment by sunny143code** [comment]
Thank you for the quick response. Could you elaborate on how to set up it?

**Comment by gordonwoodhull** [comment]
Hi @sunny143code, this is not something we have ever tried, but for the authentication part you could probably use SessionKeyServer (SKS)

https://github.com/s-u/SessionKeyServer

It allows you to configure the JAAS configuration, which you could set to use LDAP.

You would set `Session.Server` in rcloud.conf to enable SKS.
https://github.com/att/rcloud/wiki/rcloud.conf

The other part of the puzzle is if you want user switching, but I'll leave that for @s-u to elaborate when he has time. You would need a Unix account for each user on the RCloud server for that part.

**Comment by sunny143code** [comment]
Hi @gordonwoodhull, Thanks for sharing the useful info. I am having some issues with the app installation when I run the command "sh scripts/bootstarpR.sh" so here is the logs of it:

**Comment by gordonwoodhull** [comment]
Doesn't look like the log pasted correctly. Also, please open another issue for this - we prefer to discuss one issue at a time, and we were discussing LDAP/active directory here.

**Comment by gordonwoodhull** [comment]
I'm going to close this because it's not really an RCloud issue.

It should be possible using SKS, as mentioned above. If not, please open an issue over on that repo. Thanks!
