### ISSUE TITLE
Installation issues with Rcloud app

### ISSUE THREAD

**Issue by sunny143code** [att/rcloud#2709]
Hi @gordonwoodhull, I was created a docker image and it built without any issues but now I am seeing below build errors when it executes the "sh scripts/bootstarpR.sh" command:
ERROR: dependencies ‘markdown’, ‘stringr’, ‘yaml’ are not available for package ‘knitr’

removing ‘/opt/R/3.6.1/lib/R/library/knitr’
ERROR: dependencies ‘Rcpp’, ‘guitar’ are not available for package ‘gitgist’
removing ‘/opt/R/3.6.1/lib/R/library/gitgist’
ERROR: dependencies ‘github’, ‘httr’ are not available for package ‘githubgist’
removing ‘/opt/R/3.6.1/lib/R/library/githubgist’
ERROR: dependencies ‘knitr’, ‘markdown’, ‘reticulate’, ‘jsonlite’ are not availa ble for package ‘rcloud.jupyter’
removing ‘/opt/R/3.6.1/lib/R/library/rcloud.jupyter’
ERROR: dependencies ‘knitr’, ‘markdown’ are not available for package ‘rcloud.py thon’
removing ‘/opt/R/3.6.1/lib/R/library/rcloud.python’
ERROR: dependencies ‘knitr’, ‘markdown’ are not available for package ‘rcloud.r’
removing ‘/opt/R/3.6.1/lib/R/library/rcloud.r’
ERROR: dependencies ‘knitr’, ‘rmarkdown’ are not available for package ‘rcloud.r markdown’
removing ‘/opt/R/3.6.1/lib/R/library/rcloud.rmarkdown’
ERROR: dependencies ‘rjson’, ‘RCurl’, ‘jsonlite’, ‘knitr’, ‘markdown’, ‘httr’, ‘ sendmailR’ are not available for package ‘rcloud.support’
removing ‘/opt/R/3.6.1/lib/R/library/rcloud.support’
ERROR: dependency ‘rcloud.support’ is not available for package ‘rcloud.enviewer ’
removing ‘/opt/R/3.6.1/lib/R/library/rcloud.enviewer’
ERROR: dependency ‘rcloud.support’ is not available for package ‘rcloud.lux’
removing ‘/opt/R/3.6.1/lib/R/library/rcloud.lux’
ERROR: dependency ‘rcloud.support’ is not available for package ‘rcloud.notebook .info’
removing ‘/opt/R/3.6.1/lib/R/library/rcloud.notebook.info’
ERROR: dependency ‘rcloud.support’ is not available for package ‘rcloud.viewer’
removing ‘/opt/R/3.6.1/lib/R/library/rcloud.viewer’
The downloaded source packages are in
‘/tmp/Rtmp4ZpN8d/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
There were 15 warnings (use warnings() to see them)
Error in library(rcloud.support) :
there is no package called ‘rcloud.support’
Execution halted

ERROR: one or more packages could not be installed.
Please check that you have all necessary dependencies installed

Please do let me know if you know/find anything about it. Thanks.

**Comment by gordonwoodhull** [comment]
Looks like you are missing some dependencies for building some of the packages that RCloud needs.

For most Linux variants, the prerequisites listed at the top of

https://github.com/att/rcloud/blob/develop/doc/INSTALL.md

will be enough, but sometimes it takes some iteration. 

In my experience, it is pretty hard to automate the process and I always need to search for the **first** error in the log, install whatever is missing, try again, watch it fail, search for the first error, install more, etc and so on.

**Comment by sunny143code** [comment]
Thanks @gordonwoodhull for the comment. I will look into it.

**Comment by gordonwoodhull** [comment]
I'm going to close this, since this is general purpose advice for this kind of error.

If you're still having trouble, please comment or open another issue.
