### ISSUE TITLE
document keyboard shortcuts

### ISSUE THREAD

**Issue by smschauhan** [att/rcloud#300]
There are a bunch of useful ace editor shortcuts which users aren't aware of. It would be helpful to have a list of useful shortcut help available. There are a bunch of them available [here](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts)

**Comment by gordonwoodhull** [comment]
Taking this for 1.6 as I don't have time for the current release. If anyone else wants to compile it earlier, obviously that great. IMO it should go on http://att.github.io/rcloud/ and we should link to it from the internal about page.

**Comment by martymcwizard** [comment]
As a future enhancement, I thought that we could rename the help in the bottom left to be R help and add a new selection UI help and have some information there.  Just a thought.

**Comment by gordonwoodhull** [comment]
Yeah, instead of the hint ".. Get help on" it could say "R help", and have a link to the right for _UI Shortcuts_. Much like we have a link for _Lucene search syntax_ up in Search, which perhaps should also show in the help pane instead of another tab.

**Comment by shaneporter** [comment]
Correct me if I'm wrong, but as I understand it, the current (non-Ace editor) shortcuts are assigned in init.js. With the number of these set to grow, it makes sense to split this shortcut management into a separate object/file,`shortcut_manager.js`.

A shortcut could be defined with the following properties:

1. Shortcut code (note this would be undefined for something already handled, such as something within the Ace editor)
2. Category of the shortcut, such as 'Cell Editor', 'Cell management', 'Notebook Management')
3. Shortcut description, such as 'Deletes the selected cells'.
4. Function to invoke when the shortcut is performed (undefined when the shortcut code is also undefined)
5. Text representation of the shortcode. (`del`)

We could even define variations for Mac/Windows/Linux and present these shortcuts based on the client.

The `shortcut_manager` would set up the shortcuts (by code) where appropriate and a view would use the collection of shortcuts to produce the documentation for use within RCloud.

**Comment by gordonwoodhull** [comment]
Yes - it looks like the only other relevant `keydown`s are in `ui/find_replace.js`

A global manager sounds like a good idea. Please use the (simple but effective) `RCloud.extension` framework for the basis - in particular the init/load distinction allows add-on packages like IIP and RCAP to manipulate the lists before they are realized in the browser. I guess the framework's sort order would be used for the documentation.

There's a conflict between putting the implementation code into the keyboard manager itself or keeping it close to what it manipulates. I think the most powerful thing is to improve the APIs on the things we add shortcuts for, and then just have the simple call without any logic in the shortcut definition.

Some of the shortcuts we install into Ace are also relevant; these can be found by grepping for `addCommands` - I'm not sure if these should be part of the manager or not, but they need to be documented and probably expanded. (One that comes to mind that will need to be added is "goto next cell" and we've also gotten requests for "delete last cell".)

**Comment by shaneporter** [comment]
I'm wondering how to handle possible shortcut clashes between core RCloud and an extension, or where it is not desirable for a core RCloud shortcut to be active during the running of an extension.

It would be useful to disable/enable all or some RCloud shortcuts whilst extensions are being used.

The `shortcut_manager` should keep track of any core shortcuts that have been disabled and allow them all to be re-enabled.

Should there be a flag to overwrite, add, or warn when an extension adds a shortcut that already exists?

Please let me know your thoughts; I'm not sure whether I'm overthinking things.

**Comment by gordonwoodhull** [comment]
I have always punted on this by saying that extensions should be aware of the RCloud bindings and either avoid them or intentionally override them.

Since extensions are usually installed per-instance and less often per-user, I don't think that disabling all core RCloud shortcuts is an option. I think it would be sufficient to overwrite and print a warning unless some flag is set. That's a big improvement over the current situation, where you could end up with two actions bound to the same key.

**Comment by shaneporter** [comment]
OK, thanks for your input.

**Comment by gordonwoodhull** [comment]
This is implemented in RCloud 1.6
