### ISSUE TITLE
protection of secret material

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#363]
We could use something like what travis has for protection of secret material: http://docs.travis-ci.com/user/encryption-keys/

The idea is: rcloud generates an RSA key pair for each user, and stores the private key securely in a place only visible by the RCloud process.

We then allow people to set an asset to be "encrypted", which means that it is always stored at the notebook encrypted with the public key (so the gist never actually stores plaintext). RCloud would then provide a `rcloud.decrypt.asset()` entry point that is *not* exposed for anonymous executions. Notebooks that wish to provide access to encrypted assets would use this entry point without worrying that the private material is accessible everywhere else.

Of course, the notebook author still needs to worry that no make sure that the notebook caller doesn't see the result of the call to `rcloud.decrypt.asset()`, but I think something like this is actually feasible.

This would enable us to do things like securely storing oauth tokens in the notebook. I'd like to create a public notebook that plots the data from my jawbone up, but I can't really do that without exposing secret material to a gist right now.

The biggest disadvantage is that this would tie a notebook to a particular RCloud deployment and specific user (although we could export/import keys to mitigate this somewhat)

**Comment by gordonwoodhull** [comment]
We have basic support in 1.3, where you can encrypt manually from R code. Encryption of assets/cells will follow later.

**Comment by gordonwoodhull** [comment]
This is merged into #1444
