### ISSUE TITLE
two back-to-back modal calls confuse RCloud

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#371]
run this cell:

    password("Give me!")
    password("No, seriously, give me!")

RCloud freezes after the first prompt.

Run these two lines as two separate cells in a row (by running all cells in a notebook) and you get to the second cell, but something along the way gets confused and the animation gets stuck in the fading-out part.

**Comment by gordonwoodhull** [comment]
Argh, I am probably still not going to get to this, but putting it on this release just in case.

**Comment by gordonwoodhull** [comment]
I don't like crashes.

**Comment by prateek05** [comment]
Can we upvote issues to push them in priority ? :+1: Just replied to another user today explaining its a known issue and he should practice splitting cells.

**Comment by gordonwoodhull** [comment]
Okay, I've been asking for feedback for weeks, so it would have been nice to hear this was a priority earlier than the day before feature freeze. Adding to 1.4

**Comment by gordonwoodhull** [comment]
well, it was easy.
