### ISSUE TITLE
keep assets in alphabetical order

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#388]
they jump around when reloading.

**Comment by bashlee** [comment]
@gordonwoodhull  I can't seem to replicate this ? When adding a new asset and refreshing the session, all assets appear alphabetized

**Comment by gordonwoodhull** [comment]
Right, the idea is to also add a new asset in the correct position, so that the order is always consistent and doesn't change on reload.

It isn't a big deal, but it's disorienting to have the order change on reload.

I think it should follow that rename also moves the asset to the correct position, since we implement rename as add + remove.

I don't think step 1 is necessary because we get the assets in alphabetical order from github / gist-services but please test that this is correct.

**Comment by bashlee** [comment]
Makes sense, thanks for clarifying !

**Comment by gordonwoodhull** [comment]
Fixed by #2550
