### ISSUE TITLE
easier access to lucene documentation

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#521]
Opening this issue to chat about search.

Some examples of potentially confusing functionality:

 1. searching for rcloud.get returns nothing because no tokens match that exactly, and partial matches are not explored automatically.   searching for rcloud.get* returns notebooks that include terms like rcloud.get.asset, rcloud.get.notebook, rcloud.get.notebook.file, etc.  having to include the * to look for partial matches might be confusing; maybe we should add * to the start/end of the search term automatically?  what side effects might that have?

 2. searching for "file=" returns everything that includes the word file, as the equals sign is stripped from the search term.  same goes for most special characters.  right now, the SOLR schema is not including special characters when indexing.  should search provide be a way to specify a special character in a search term?

 3. i am not sure how to search for two tokens separated by whitespace.  hi?mom returns nothing.  hi*mom returns only himom (no space between).  "hi mom" will be tokenized into the search "hi" OR "mom", and I do find my desired result in that list, but it is intermingled with results that either include only "hi" or only "mom".

**Comment by gordonwoodhull** [comment]
keeping this open to have an easier way to get at help syntax, along with the link in the main documentation, which itself will be easier to find with #1313 having docs links in the navbar.

**Comment by gordonwoodhull** [comment]
add question mark button to the right of search box

**Comment by gordonwoodhull** [comment]
I am hard-coding the link for now. It could be read from rcloud.conf 

@prateek05, what is the lucene version we should point to?

**Comment by gordonwoodhull** [comment]
Note: we already had a link to the lucene documentation on syntax error.

**Comment by prateek05** [comment]
solr-spec
4.10.3
solr-impl
4.10.3
lucene-spec
4.10.3

**Comment by gordonwoodhull** [comment]
thanks @prateek05, updated the links
