### ISSUE TITLE
sort user's notebooks by date

### ISSUE THREAD

**Issue by s-u** [att/rcloud#522]
It would be useful to be able to sort notebooks by the commit date instead of name.

**Comment by gordonwoodhull** [comment]
Implemented in RCloud 1.9

**Comment by s-u** [comment]
Great! It actually works very well by sorting the folders by the most recent date of their content.

Minor complaint: it takes ~10s to update on my notebooks - both ways (date->name and name->data)

**Comment by gordonwoodhull** [comment]
Odd, it only takes 5s on my machine when your notebook tree is open. We can continue to optimize though.
