### ISSUE TITLE
Interactive prompt should match the R prompt conventions

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#620]
We already use the `>` chevron mark, but if you press ctrl+enter to get a new line, the gutter should show `+` like the R prompt does.

**Comment by s-u** [comment]
Idea: add a parse-only ocap (and callback in lang) such that the UI can determine independently the validity of the code.

**Comment by gordonwoodhull** [comment]
To spell that out: not only should ctrl-enter do the "extended prompt", but incomplete expressions should as well. Although there are two separate work items here.
