### ISSUE TITLE
Too much mousing

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#664]
One of our users wishes they could navigate around the RCloud interface more effectively with a keyboard. I tend to agree, but which conventions are we going to follow?

At the very least, we should be able to navigate the list of notebook cells without touching the mouse, and possibly enter and leave edit mode for each specific cell.

**Comment by gordonwoodhull** [comment]
no, not tab, tab is completion.

**Comment by gordonwoodhull** [comment]
We have a lot of keyboard shortcuts per #300. If we want more, we have a good mechanism for it, and we should open individual issues for them.
