### ISSUE TITLE
Not all interactions should go to the notebook

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#665]
(tl;dr: Despite my best efforts, users won't do what I want! :))

I have now accepted the fact that the notebook model is too far from what users expect when they have previous experience with an interactive prompt interface.

The main complaint is that most of the commands typed into an interactive prompt are to be thrown away, and should not be stored in the notebook to be executed by default with everything else next time someone clicks on the notebook.

I still hold my belief that the decision of *which* parts of a session are important sometimes comes only in hindsight, so I would still like to capture everything that the user does and save it somewhere.

But if users get overwhelmed by the notebook interface and don't clean up their notebooks after a session, then we have a problem *in rcloud*, because the cluttered notebooks are not nice to reexecute (and so they hurt sharing), and they also hurt discoverability by polluting the indices with junk.

Perhaps we need two separate "modes", or "contexts". One is the *session* which is always captured, but not in the notebook. Then, the middle column can be (say) split into two rows, where the top row is the notebook, and the bottom row is the session. Everything that is executed in the prompt by default goes to the session, and from the session an executed cell can go to a notebook.

Features of this point in design space:

- The log of a session is recorded, but is read-only. Results of the interaction are cells that can be deleted and never make it to a notebook.
- The log of a session can be promoted to a notebook by a single click.
- User sessions can be searchable and visible in a separate pane, but perhaps they should deletable by users. Incidentally, this would solve the problem of typing usernames and passwords interactively.
- The notebook editing UX doesn't change at all to where we are right now. Split cells, edit, change type, etc. all happen and change the notebook as they do currently.
- Perhaps sessions should be preserved when clicking around to find a new notebook which has the desired snippet of code. This would reduce the chance of losing state by accident when browsing the page. It will increase the chance that interactions with the current state of the environment will make notebooks execute unexpectedly, but in this current mode we have already given up the notion of a notebook capturing the entire session anyway.

**Comment by gordonwoodhull** [comment]
My impression is that people were less concerned with having their work saved in a notebook, than they were annoyed by the clutter and inefficiency of so many cells.

Now that cells are streamlined both visually and in terms of resources used, we will see if people still complain about working in a notebook.  I expect that they will now want #658 cull cells and forget that all this stuff is getting saved to a notebook.

As @cscheid mentions, there is a risk of losing work whenever you have a session that is not getting saved, and this solution would require saving it separately.  It is far simpler just to save it to the notebook, and we get a very rich history this way.

**Comment by gordonwoodhull** [comment]
Hrrm, I think this is a Big Problem. The interface changes have helped a little bit, but have not really solved anything.

**Comment by gordonwoodhull** [comment]
I am closing this - see my rationale here: https://github.com/att/rcloud/issues/622#issuecomment-202456581

We can always reopen these if we find a better compromise.
