### ISSUE TITLE
support binary assets

### ISSUE THREAD

**Issue by s-u** [att/rcloud#683]
We're half-there with the `.b64` support but it's incomplete. This is to remind me to complete it.

**Comment by s-u** [comment]
Now supported.

Remaining issues on the JS side:

- [ ] the UI doesn't know what to do with binary assets. We could be smart and, e.g., for images show it (`notebook.R` works so they can be turned into links)
- [ ] binary upload into notebook doesn't work because `upload_utils.js` uses `readAsText` (note that `readAsArrayBuffer` does work). There are two ways to fix: a) add "binary" checkbox to use `readAsArrayBuffer` when checked; b) use `notebook_upload` (which supports automatic content detection) instead of `update_notebook` (which is too low-level so it expects caller to make the decision and choose content type accordingly).
- [ ] deleting a binary asset from the UI fails, because `update_notebook` doesn't necessarily know that the asset to be deleted is binary (this could also be addressed by making `update_notebook` more smart)

**Comment by gordonwoodhull** [comment]
For the second item, I think the client could probably read as binary and then convert to a string if it finds the content is text-only. I don't think a checkbox is an option because we support dragging and dropping of multiple assets.

Why does `update_notebook` need to know if an asset is binary? Can't it just send null content?

**Comment by gordonwoodhull** [comment]
Or is it that the server won't know whether the asset is binary if the client just sends null?

**Comment by s-u** [comment]
yes, exactly

for the second item - `upload_notebook` already does that so client shouldn't need to hence the second way forward

**Comment by gordonwoodhull** [comment]
Do you mean `rcloud.upload.asset`? It looks like it detects whether the parameter is raw or string, so the client still needs to detect whether the content is binary and send the correct type.

**Comment by s-u** [comment]
No I mean `notebook_upload` which is an ocap to `rcloud.upload.to.notebook`

**Comment by gordonwoodhull** [comment]
It turns out that it is fine to always read the data as `ArrayBuffer` and update the notebook using `update_notebook`. Then the server decides whether it's binary or not and the client honors that decision.

**Comment by gordonwoodhull** [comment]
@s-u, I put a very ugly hack on the client side to deal with the third point. Sheer laziness. It didn't sound like the hack on the server side would be much less ugly, and probably less efficient. But if you feel like cleaning up the interface, the guilty commit is the change to asset_model.js in 1f6c39aac64e4deaa3bbc553e54f1d93fc1bdfbf

**Comment by gordonwoodhull** [comment]
Nope, this didn't work. Now text assets are being uploaded as binary. :frowning:

**Comment by gordonwoodhull** [comment]
I would be much happier with a single way to update notebooks - `rcloud.upload.to.notebook` is okay but it doesn't support string content and it forces a second roundtrip and extra commit if there were already changes to the notebook when asset was added/updated.

I attempted to modify `.gist.binary.process.outgoing` in the following way:

```{r}
        for (i in seq.int(length(bin.f))) {
            name <- names(bin.f)[i]
            if(checkUTF8(bin.f[[i]]$content, quiet=TRUE, min.char=7L)) {
                txt.f[[name]] <- rawToChar(bin.f[[i]]$content)
            }
            else {
                if (!length(grep("\\.b64$", name))) name <- paste0(name, ".b64")
                txt.f[[name]] <- list(content=.binary.to.b64(bin.f[[i]]$content))
            }
        }
```

This does not handle the binary-to-text and text-to-binary transitions, which are broken in `rcloud.upload.to.notebook` anyway (as I've noted in #1323). 

We shouldn't have three entry points for modifying assets, and if we do, they should reuse all the binary detection/conversion code.
