### ISSUE TITLE
"aw shucks" is white in view mode

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#782]
![image](https://cloud.githubusercontent.com/assets/1366709/3519434/a16f5fb4-0716-11e4-9dce-da918fc36909.png)

**Comment by Prateek032** [comment]
This issue seems to be fixed.

**Comment by gordonwoodhull** [comment]
Yes, I moved this rule to the common css file as of 1.5.3. 

Thanks! One down, 402 to go!
