### ISSUE TITLE
Fresh install woes on Mac

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#852]
Both `bootstrapR.sh` and `fresh_start.sh` seem to want to install source versions of every package, which is not a great idea when some source packages are, um, finicky to build.

Can we only force source installs on the packages that truly require it? Or can we force binary builds on Cairo?

**Comment by Rutishauser** [comment]
I am installing RCloud on Ubuntu 12.04. It seems that  there are 3 ways to install the necessary packages. Some can be installed as
> install.packages("Rook") 
they go from CRAN. Some can be installed as
> install.packages("github",,'http://rforge.net/',type='source')
And the rest needs to be installed from the linux command prompt.
> R CMD INSTALL /opt/rcloud/packages/githubgist

**Comment by Rutishauser** [comment]
I am installing RCloud on Ubuntu 12.04. It seems that there are 3 ways to install the necessary packages. Some can be installed as
`    install.packages("Rook")`
They go from CRAN. Some can be installed as
`    install.packages("github",,"http://rforge.net/",type="source")`
And the rest needs to be installed from the linux command prompt.
`    R CMD INSTALL /opt/rcloud/packages/githubgist`

**Comment by gordonwoodhull** [comment]
@Rutishauser, what is the question here? Yes, there are multiple ways to install packages. The ones that are built into rcloud are best installed from the command prompt. Some are not available try through CRAN and should be installed from rforge. If you use `scripts/bootstrapR.sh` you shouldn't have to worry about it. 

BTW, I think the issue described in this ticket is fixed: bootstrapR prefers binaries on OSX. Closing.

**Comment by Rutishauser** [comment]
It wasn't a question.  I just came across the same issue that the package 'githubgist' hadn't been installed. And my workaround was to install it from the command prompt.

But still, when I follow the RCloud installation instructions, at step 7, I am getting the following error.

`* installing to library ‘/usr/local/lib/R/site-library’`
`ERROR: dependency ‘rcloud.support’ is not available for package ‘rcloud.enviewer’`

Has anything gone wrong, or is it a recommended way to install it manually?

**Comment by Rutishauser** [comment]
I have found the issue.  The instructions read "... just do
`$ ./scripts/fresh_start.sh`
which is incorrect. The correct command is (as you write here:)
`scripts/bootstrapR.sh`

**Comment by gordonwoodhull** [comment]
Hmm, which instructions are you following? We have been plagued with obsolete, duplicated instructions.

The current ones are here;
https://github.com/att/rcloud/blob/develop/doc/INSTALL.md

I think bootstrapR.sh should take care of installing dependencies in the right order. If it is failing to install rcloud.support, the main library, that is surely a bug.

**Comment by gordonwoodhull** [comment]
Ah, thanks for pointing out that wiki page. Although we put a warning at the top of that page, we should probably delete it, because it continues to confuse people. The INSTALL.md that I linked to is the correct, up-to-date instructions.
