### ISSUE TITLE
run rcloud.web in a notebook cell?

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#853]
Since we generate HTML from Markdown, can we also run rcloud.web (e.g. rcloud-shiny) in a cell and generate HTML inline?

**Comment by gordonwoodhull** [comment]
This works right @s-u ?

**Comment by s-u** [comment]
Yes, it works, but requires shady knowledge of internals. For a minimal hello world:

    r <- rcw.result(
       run=function() rcw.append("#test", "<p>Hello from R!"),
       body="<div id=test>This is my nice HTML...</div>") 

You need this to display the result in a cell:

    self.oobSend(list("html.out",r$content$body))
    Rserve::resolve.ocap(r$content$run)(list())

and you won't have `window.notebook_result` populated unless you do that, so it may be worthwhile to create something like a `display.rcw()` wrapped (but then we would acknowledge that this is official ;)).

**Comment by s-u** [comment]
I have added `rcw.inline()` that does both, so you can use

```r
rcw.inline(rcw.result(
   run=function() rcw.append("#test", "<p>Hello from R!"),
   body="<div id=test>This is my nice HTML...</div>"))
```

Any additional arguments will be passed to `run`.
