### ISSUE TITLE
Unified Logout Page from all systems

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#868]
Currently the user has to logout of github by clicking the "Logout of Github" on the goodbye.R page. 
Since the intention is to logout it would be more appropriate to logout from github as well by redirecting to github logout. Thoughts ?

**Comment by s-u** [comment]
@prateek05, can we just change the language and include the user name here?

**Comment by prateek05** [comment]
The mitigation report wanted a visual cue to make the message standout that you're not logged out of RCloud and would need to click here too.

**Comment by s-u** [comment]
Well, you *are* already logged out of RCloud so that doesn't make any sense. The proposal here was to make it more obvious that you're still logged in as a particular user on GitHub.

**Comment by prateek05** [comment]
Isn't the notion of rcloud user the signed in github user ?

Nexus 7 @ Vodafone IN

**Comment by prateek05** [comment]
Anywho this is the original discussion. If the above proposed fix helps the general users. I guess we should be fine with it. 
VOLINSKY, CHRISTOPHER T (CHRIS) wrote:

When I log into RCloud..it thinks I am byers.   I think Simon once logged into my github on  my machine, but I don’t know how to make it think I am not him. 

Prateek wrote: 
Need to click the hyperlink on the logout page "GitHub Logout"
However, you may still be logged into GitHub, use GitHub Logout to log out of there as well.

VOLINSKY, CHRISTOPHER T (CHRIS) <volinsky@research.att.com> wrote:
This is a confusing distinction to a casual user.  Not sure there is a way around it though.

**Comment by s-u** [comment]
@prateek05 no, because GitHub login is independent - you can login into GitHub without having anything to do with RCloud. You have to login to RCloud to get an RCloud token and the logout page simply invalidates all RCloud credentials (both execution and notebook access) - there is nothing more we can do on our. The discussion with CTV was different - it was about switching users that's why I was suggesting adding the name so that you knowhow you are logged in on GitHub.

**Comment by prateek05** [comment]
@s-u Do I need to do something or would you put in what you think is the right approach to close this out ? We do have an internal API in this release of rcloud. `rcloud.get.git.user`.

**Comment by s-u** [comment]
It's not that trivial - `goodbye.R` is already cookie-less, so it has no credentials anymore, so it has no way of knowing what GitHub user is logged in since all RCloud tokens are already revoked, so only GitHub knows the user name.
