### ISSUE TITLE
"content-type" as a search field throws error 

### ISSUE THREAD

**Issue by sujitbehera27** [att/rcloud#883]
Below error comes in the session pane.

Error: search: Error in strsplit(parts.content[[j]]$content, "\n") : non-character argument
at success (https://rcloud-2.research.att.com/js/rcloud_bundle.js:118:23)
From previous event:
at Object.search (https://rcloud-2.research.att.com/js/rcloud_bundle.js:124:31)
at https://rcloud-2.research.att.com/js/rcloud_bundle.js:4617:27

@gordonwoodhull you can allocate to appropriate milestone.

**Comment by s-u** [comment]
investigate better json libraries

**Comment by gordonwoodhull** [comment]
can't reproduce with rcloud.solr
