### ISSUE TITLE
wdcplot  reduce  - percentage?

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#901]
Is there a way to get a percentage out of wdcplot?    We are starting do deal with samples of large data but wdcplot seems to favor having all the data.    Can the reduce "any" function be used?   I couldn't find examples.   I learned from Dave Kapilow that dc.js also does not have the logic to do a percent calculation - is that right?

**Comment by gordonwoodhull** [comment]
This issue was moved to att/rcloud.dcplot#8
