### ISSUE TITLE
wdcplot problems with large data

### ISSUE THREAD

**Issue by rhknag** [att/rcloud#902]
If you push wdcplot to near the memory limit on Chrome 32 bits it often will fail to print an error message.   There's also an string that appears while it is calculating ...
Here's an example:
## [1] "c920436e-b1aa-429f-b0b3-986882d3f047|772EJtyFjVcaBV2QkDZj_d3n0aLH

**Comment by gordonwoodhull** [comment]
Is this the same as #904? Is it fixed now on rcloud.research?

**Comment by rhknag** [comment]
This is an old one – when I put in even larger datasets it would fail with an odd error
I don’t have an example at the moment.

Ralph

**Comment by s-u** [comment]
please comment if you see this again. closing
