### ISSUE TITLE
MOTD-like feature

### ISSUE THREAD

**Issue by s-u** [att/rcloud#91]
It would be very useful to have something like MOTD on login so we can optionally post announcements etc.

**Comment by gordonwoodhull** [comment]
Request is for a dialog you have to acknowledge. I figure it will be like Aw Shucks only not pink. (Blue?)

@s-u wrote
> where we can post content that gets shown on first login (=until acknowledged)

I'm unclear if this is sort of a "welcome to RCloud now close this dialog that's in your way", but I'm happy to create an OCAP and it will get used however it gets used. (Disclaimer? Shrinkwrap?)

**Comment by s-u** [comment]
For the record this is the `rcloud.profile` entry for serving MOTD messages from `motd.d` under config:

```r
## MOTD handling
local({
  motd <- Sys.glob(rcloud.support:::pathConf("configuration.root", "motd.d", "*.html"))
  if (length(motd)) {
    ## NOTE: we only show the first one for now!
    motd <- motd[1L]
    if (is.null(rcs.get(key <- usr.key(user=rcloud.support:::.session$username, notebook="system", "motd", basename(motd))))) {
      ## user has not seen this one yet
      rcloud.message.dialog("MOTD", paste(readLines(motd), sep="\n"))
      rcs.set(key, Sys.time())
    }
  }
})
```

**Comment by gordonwoodhull** [comment]
Unfortunately, with this scheme, if the page fails to load after displaying the MOTD, there is no way to recall the message. In #2135 I want to provide a way to display the last MOTD but that assumes the page can load.

@s-u, if I figure out an event for the page to successfully loading (edit.js all initialized), could we delay setting the key until that point?

**Comment by gordonwoodhull** [comment]
I also have two feature requests on the above script:
 1. Title should be something descriptive - I doubt many of our users will know what "MOTD" means, and in the future I'd like to be able to display a menu of recent messages by title. Alternately, we could skip/null the title and parse the `<h3>` where you're sending the "real" title.
 2. Mildly prefer that the script check the file timestamp and display the message again if it's been updated.

**Comment by shaneporter** [comment]
I thought it was [this](https://en.wikipedia.org/wiki/Match_of_the_Day). :soccer: :blush:

**Comment by gordonwoodhull** [comment]
Caveat: this will only show the message with a particular filename once. If you need to display the same message a second time, give it a new filename (or remove the RCS entries for all users).
