### ISSUE TITLE
File upload example from shiny gallery is currently not working in RCloud

### ISSUE THREAD

**Issue by GanapatiBhat** [att/rcloud#957]
Whenever user loads a file using shiny API a POST request is made to the session which looks something like below, which tries to write the file to tempdir()

Remote Address:127.0.0.1:8080
Request URL:http://127.0.0.1:8080/session/b248c49e4d4632e19db135cc58af6d8c/upload/1100eae0eefe31cb46d74cdc?w=
Request Method:POST
Status Code:404 Code 404

Shiny handleRequest function is not able to handle the above request in RCloud.

We can use RCloud file upload as an alternative but we cannot connect them back to shiny callback/render functions

![screenshot from 2014-10-20 20 29 53](https://cloud.githubusercontent.com/assets/5503452/4711692/e22510ea-58be-11e4-8657-8757c3fb301e.png)

**Comment by gordonwoodhull** [comment]
This issue was moved to att/rcloud.shiny#2
