### ISSUE TITLE
invalidateLater function is not working

### ISSUE THREAD

**Issue by GanapatiBhat** [att/rcloud#959]
Below is one example, where inavlidateLater function is supposed to invalidate the context after 1 second, but it is not doing so.

shinyApp(
ui = fluidPage(
  textOutput("currentTime")
),
server = function(input, output) {
  output$currentTime <- renderText({
    invalidateLater(1000, NULL)
    paste("The current time is", Sys.time(), input$action)
  })
  }
)

**Comment by gordonwoodhull** [comment]
This issue was moved to att/rcloud.shiny#1
