### ISSUE TITLE
self-referencing notebook shortcut

### ISSUE THREAD

**Issue by spenceatt** [att/rcloud#977]
Currently, when you fork a notebook, all the references to the original notebook remain in the code. This is as it should be.

However, it would be easier for forkers, especially when forking a notebook with lots of assets, if notebook creators could include self references that use an alias that references the current notebook, regardless of its ID. This would allow writers to reference external notebooks in absolute fashion as well as self reference in relative fashion.

E.g. RMarkdown:

This is an RCloudWeb notebook - to run use &lt;a href=/mini.html?notebook=$this.notebook&gt;/mini.html?notebook=$this.notebook&lt;/a&gt;

When executed, the cell would contain the ID of the notebook in place of $this.notebook.

**Comment by s-u** [comment]
You can use markdown to generate the link by querying the current ID -- not the most pretty, but:

````
```{r results="asis", echo=FALSE}
cat(paste0("<a href=/view.html?notebook=", rcloud.session.notebook.id(), ">view here</a>"))
```
````

**Comment by spenceatt** [comment]
I will document this as well as change rclouddocs notebooks where appropriate.

Spence
