### ISSUE TITLE
file upload failures

### ISSUE THREAD

**Issue by kshirley** [att/rcloud#984]
We use the following functionalities in our app:

— Multiple file controls on a single page
— Anonymous file upload

On rcloud we get the following errors:

Uncaught TypeError: undefined is not a function upload_funcs.js:7
setup_upload_ocaps upload_funcs.js:7
socket.onmessage rserve.js:922

Could rcloud be set up to support this upload functionality?

**Comment by gordonwoodhull** [comment]
we have a workaround to limit the message size, which has fixed this.  there is still an underlying problem in rserve, and it would be more efficient to use larger messages, but the functionality works now.

**Comment by gordonwoodhull** [comment]
seems the limited message size did not help after all

**Comment by gordonwoodhull** [comment]
Using d3.js 3.5.5, 313K, as the test file, I get the following results:

OSX - Firefox OK. Chrome, Opera OK locally but hang remotely.  Safari upload panel doesn't work #1128 
Windows - Chrome, Opera consistently fail - hang or disconnect. Firefox OK.
Ubuntu - Local: Chrome, Firefox OK. Opera hangs. Remote: Chrome, Opera hang. Firefox OK.

**Comment by s-u** [comment]
This should be fixed in latest Rserve - please check.

**Comment by gordonwoodhull** [comment]
I'll try to test this thoroughly. Does this mean we can also restore the block size to 1MB? 

Or from your research, do you think large blocks are a bad idea in terms of performance? Can you share a link?

**Comment by s-u** [comment]
https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/QuiTHBbMM6M

For performance reasons it's good to keep frames under 64k if practicable - as you get close/over 128kB things get worse exponentially (from dozens of kb to few bytes per packet).

**Comment by gordonwoodhull** [comment]
Okay, that's not the right link and I can't seem to find the reference myself, but I believe you. Seems like a very odd design choice from the Chrome folks.

**Comment by s-u** [comment]
I didn't hear anything and it works for me so I assume this is now fixed.

**Comment by gordonwoodhull** [comment]
I haven't had a chance to test it but I will ask QA. Thanks

**Comment by kshirley** [comment]
I just tested a bit and it worked great. thanks!
